function str=addUVMGeneratedBy(FileName,prefix)
    persistent vm;
    persistent vh;
    r=datestr(now,31);
    str=sprintf('%s\n',[prefix,'File: ',FileName]);
    str=sprintf('%s%s\n',str,[prefix,'Created: ',r]);
    if isempty(vm)
        t=ver('matlab');
        vm=t.Version;
    end
    if isempty(vh)
        t=ver('hdlverifier');
        if isempty(t)




            vh='';
        else
            vh=t.Version;
        end
    end
    str=sprintf('%s%s\n',str,[prefix,sprintf('Generated by MATLAB %s and HDL Verifier %s',vm,vh)]);
end