function out=getDeclaration(obj)




    prototype=obj.getFunctionPrototype('void',...
    obj.getFunctionName(obj.Entry.FunctionNamingRuleForValue),{'DATATYPE','data'});
    out=[
    obj.getDeclarationHeader...
    ,' imported through file: "',obj.getServiceHeaderFileName,'"'...
    ,obj.getPreviewCodeDiv([prototype,';'])...
    ];
