function dlgStruct=getDialogSchema(this,name)






    if(isempty(this.Actions)...
        ||~isfield(this.Actions,'New')...
        ||~isa(this.Actions.New,'DAStudio.Action'))

        pActions={};

    else

        newButton=dlgButton(this.Actions.New,...
        'ColSpan',[1,1],...
        'RowSpan',[1,1],...
        'Tag','newButton');
        newLink=dlgHyperlink(this,this.Actions.New,...
        'ColSpan',[2,2],...
        'RowSpan',[1,1],...
        'Tag','newLink');

        newFormButton=dlgButton(this.Actions.NewForm,...
        'ColSpan',[1,1],...
        'RowSpan',[2,2],...
        'Tag','newFormButton');
        newFormLink=dlgHyperlink(this,this.Actions.NewForm,...
        'ColSpan',[2,2],...
        'RowSpan',[2,2],...
        'Tag','newFormLink');

        openButton=dlgButton(this.Actions.Open,...
        'ColSpan',[1,1],...
        'RowSpan',[3,3],...
        'Tag','openButton');
        openLink=dlgHyperlink(this,this.Actions.Open,...
        'ColSpan',[2,2],...
        'RowSpan',[3,3],...
        'Tag','openLink');

        convertFileButton=dlgButton(this.Actions.ConvertFile,...
        'ColSpan',[1,1],...
        'RowSpan',[4,4],...
        'Tag','convertFileButton');
        convertFileLink=dlgHyperlink(this,this.Actions.ConvertFile,...
        'ColSpan',[2,2],...
        'RowSpan',[4,4],...
        'Tag','convertFileLink');

        createCompButton=dlgButton(this.Actions.CreateComponent,...
        'ColSpan',[1,1],...
        'RowSpan',[5,5],...
        'Tag','createCompButton');
        createCompLink=dlgHyperlink(this,this.Actions.CreateComponent,...
        'ColSpan',[2,2],...
        'RowSpan',[5,5],...
        'Tag','createCompLink');

        editStyleButton=dlgButton(this.Actions.EditStylesheet,...
        'ColSpan',[1,1],...
        'RowSpan',[6,6],...
        'Tag','editStyleButton');
        editStyleLink=dlgHyperlink(this,this.Actions.EditStylesheet,...
        'ColSpan',[2,2],...
        'RowSpan',[6,6],...
        'Tag','editStyleLink');

        pActions=this.dlgContainer({
newButton
newLink
openButton
openLink
convertFileButton
convertFileLink
createCompButton
createCompLink
editStyleButton
editStyleLink
newFormButton
newFormLink
        },getString(message('rptgen:RptgenML_Root:actionsLabel')),...
        'LayoutGrid',[6,3],...
        'RowStretch',[0,0,0,0,0,0],...
        'ColStretch',[0,0,1],...
        'Tag','pActions');


        pActions={pActions};
    end


    tGettingStarted=this.dlgText([...
    getString(message('rptgen:RptgenML_Root:guiDescriptionLabelPartI')),...
    ' ',...
    getString(message('rptgen:RptgenML_Root:guiDescriptionLabelPartII'))],...
    'RowSpan',[1,1],...
    'ColSpan',[1,1],...
...
    'WordWrap',true,...
    'Tag','tGettingStarted');

    tEmptyLine=this.dlgText('',...
    'ColSpan',[1,1],...
    'RowSpan',[2,2],...
    'Tag','tEmptyLine');

    pGettingStarted=this.dlgContainer({
tGettingStarted
tEmptyLine
    },...
    getString(message('rptgen:RptgenML_Root:gettingStartedLabel')),...
    'LayoutGrid',[2,1],...
    'RowStretch',[0,1],...
    'Tag','pGettingStarted');


    dlgStruct=this.dlgMain(name,{
    pActions{:}
pGettingStarted
    });


    function w=dlgButton(action,varargin)



        if~isa(action,'DAStudio.Action')
            idProp='Name';
            idVal='';
            tipText='';
            cbk='';
            vis=true;
        else
            if isempty(action.Icon)
                idProp='Name';
                idVal=action.Text;
                tipText=action.StatusTip;
            else
                idProp='FilePath';
                idVal=action.Icon;


                tipText=regexprep(action.Text,'\(&.\)','');

                tipText=strrep(tipText,'&','');
            end
            cbk=action.Callback;
            vis=strcmpi(action.Visible,'on');
        end

        w=struct(...
        'Type','pushbutton',...
        idProp,idVal,...
        'MatlabMethod',cbk,...
        'Visible',vis,...
        'ToolTip',tipText,...
        varargin{:});


        function w=dlgHyperlink(this,action,varargin)

            if~isa(action,'DAStudio.Action')
                w=this.dlgText('',varargin{:});
            else
                vis=strcmpi(action.Visible,'on');
                w=struct(...
                'Type','hyperlink',...
                'Name',action.StatusTip,...
                'MatlabMethod',action.Callback,...
                'Visible',vis,...
                varargin{:});
            end

