classdef DoseParameters<matlab.mixin.SetGet

    properties(Access=public)
        type;

        targetName;
        durationParameterName;
        lagParameterName;

        amount;
        amountUnits;

        rate;
        rateUnits;

        timeUnits;


        time=[];


        startTime=[];
        interval=[];
        repeatCount=[];

    end


    methods(Access=public)
        function obj=DoseParameters(values)
            if nargin>0
                numObj=numel(values);
                if numObj==0
                    obj=SimBiology.internal.plotting.categorization.binvalue.DoseParameters.empty;
                    return;
                end

                obj=arrayfun(@(~)SimBiology.internal.plotting.categorization.binvalue.DoseParameters(),transpose(1:numObj));

                if isa(values,'SimBiology.RepeatDose')
                    arrayfun(@(dp,dose)dp.setValuesFromRepeatDose(dose),obj,values);
                elseif isa(values,'SimBiology.ScheduleDose')
                    arrayfun(@(dp,dose)dp.setValuesFromScheduleDose(dose),obj,values);
                else
                    arrayfun(@(dp,dose)dp.setValuesFromDoseStruct(dose),obj,values);
                end
            end
        end

        function doseParameters=getStruct(obj)
            doseParameters=arrayfun(@(dose)struct('type',dose.type,...
            'targetName',dose.targetName,...
            'durationParameterName',dose.durationParameterName,...
            'lagParameterName',dose.lagParameterName,...
            'amount',dose.amount,...
            'amountUnits',dose.amountUnits,...
            'rate',dose.rate,...
            'rateUnits',dose.rateUnits,...
            'timeUnits',dose.timeUnits,...
            'startTime',dose.startTime,...
            'interval',dose.interval,...
            'repeatCount',dose.repeatCount,...
            'time',dose.time),...
            obj);
        end
    end

    methods(Access=private)
        function setValuesFromRepeatDose(obj,repeatdose)
            obj.setValuesFromDose(repeatdose);
            set(obj,'startTime',repeatdose.StartTime,...
            'interval',repeatdose.Interval,...
            'repeatCount',repeatdose.RepeatCount);
        end

        function setValuesFromScheduleDose(obj,scheduledose)
            obj.setValuesFromDose(scheduledose);
            set(obj,'time',scheduledose.Time);
        end

        function setValuesFromDose(obj,dose)
            set(obj,'type',dose.Type,...
            'targetName',dose.TargetName,...
            'durationParameterName',dose.DurationParameterName,...
            'lagParameterName',dose.LagParameterName,...
            'amount',dose.Amount,...
            'amountunits',dose.AmountUnits,...
            'rate',dose.Rate,...
            'rateUnits',dose.RateUnits,...
            'timeUnits',dose.TimeUnits);
        end

        function setValuesFromDoseStruct(obj,doseStruct)
            set(obj,'type',doseStruct.type,...
            'targetName',doseStruct.targetName,...
            'durationParameterName',doseStruct.durationParameterName,...
            'lagParameterName',doseStruct.lagParameterName,...
            'amount',doseStruct.amount,...
            'amountunits',doseStruct.amountUnits,...
            'rate',doseStruct.rate,...
            'rateUnits',doseStruct.rateUnits,...
            'timeUnits',doseStruct.timeUnits,...
            'startTime',doseStruct.startTime,...
            'interval',doseStruct.interval,...
            'repeatCount',doseStruct.repeatCount,...
            'time',doseStruct.time);
        end
    end
end