function resultJSON=getPreference()
    mp=ModelAdvisor.Preferences;

    pref=struct('ShowSourceTab',mp.ShowSourceTab,...
    'ShowExclusionTab',mp.ShowExclusionTab,...
    'ShowAccordion',mp.ShowAccordion,...
    'ShowExclusionsInRpt',mp.ShowExclusionsInRpt,...
    'RunInBackground',mp.RunInBackground);

    result=struct('success',true,'message',jsonencode(struct('title','','content','')),'warning',false,'filepath','','value',jsonencode(pref));
    resultJSON=jsonencode(result);
end
