function hC=getBUFGComp(hN,hInSignals,hOutSignals,compName)




    if(nargin<4)
        compName='BUFG';
    end

    hC=pirelab.getInstantiationComp(...
    'Network',hN,...
    'Name',compName,...
    'EntityName','BUFG',...
    'InportNames',{'I'},...
    'OutportNames',{'O'},...
    'InportSignals',hInSignals,...
    'OutportSignals',hOutSignals,...
    'AddClockPort','off',...
    'AddClockEnablePort','off',...
    'AddResetPort','off',...
    'InlineConfigurations','off'...
    );
