function hC=getIBUFDSComp(hN,hInSignals,hOutSignals)




    hC=pirelab.getInstantiationComp(...
    'Network',hN,...
    'Name','IBUFDS',...
    'Entity','IBUFDS',...
    'InportNames',{'I','IB'},...
    'OutportNames',{'O'},...
    'InportSignals',hInSignals,...
    'OutportSignals',hOutSignals,...
    'AddClockPort','off',...
    'AddClockEnablePort','off',...
    'AddResetPort','off',...
    'InlineConfigurations','off',...
    'GenericList','{{''DIFF_TERM'', ''TRUE'', ''boolean''}}'...
    );
