function hC=getIBUFGDSComp(hN,hInSignals,hOutSignals)




    hC=pirelab.getInstantiationComp(...
    'Network',hN,...
    'Name','IBUFGDS',...
    'InportNames',{'I','IB'},...
    'OutportNames',{'O'},...
    'InportSignals',hInSignals,...
    'OutportSignals',hOutSignals,...
    'AddClockPort','off',...
    'AddClockEnablePort','off',...
    'AddResetPort','off',...
    'InlineConfigurations','off',...
    'GenericList',['{{''DIFF_TERM'', ''FALSE'', ''boolean''}, ',...
    '{''IBUF_LOW_PWR'', ''TRUE'', ''boolean''}, ',...
    '{''IOSTANDARD'', ''"DEFAULT"'', ''string''}}']...
    );















