function lines=getCEFIncludeLines()




    lines=[...
    "<script type=""text/javascript"" src=""/toolbox/shared/comparisons/web/mw-diff/release/mw-diff/dojoConfig-release-global.js""></script>",...
    "<script type=""text/javascript"" src=""/toolbox/shared/comparisons/web/mw-diff/release/bundle.index.js""></script>",...
    "<script type=""text/javascript"" src=""/toolbox/shared/comparisons/web/templates/shared/js/printablereport.js""></script>",...
    "<script type=""text/javascript"" src=""/toolbox/shared/comparisons/web/templates/shared/js/events.js""></script>",...
    ];
    lines=lines.cellstr();
end
