function bool=isSignalBuilderChannels(aVar)







    if nargin>0
        if isstring(aVar)
            aVar=cellstr(aVar);
        end
    end

    bool=false;

    if isstruct(aVar)


        sigBldrFieldNames={
        'stepX',...
        'stepY',...
        'yMin',...
        'yMax',...
        'color',...
        'lineStyle',...
        'lineWidth',...
        'label',...
        'lineH',...
        'leftDisp',...
        'rightDisp',...
        'outIndex',...
        'axesInd',...
        'xData',...
'yData'
        };


        if all(isfield(aVar,sigBldrFieldNames))&&...
            iscellstr({aVar(:).label})&&...
            all(cellfun(@isnumeric,{aVar(:).xData}))&&all(cellfun(@isnumeric,{aVar(:).yData}))
            bool=true;
        end

    end