function setupEMLPaths(~)






    gp=pir;
    emlPathList={...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/arithmeticops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/bitops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/counters',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/delays',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/fftops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/fifo',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/logicalops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/lookup',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/minmax',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/newton',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/nativefloatingpoint',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/relops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/shared',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/target',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/treearch',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/wireops',...
    '$matlabroot$/toolbox/shared/algorithmlowering/emlauthoring/intrinsic',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/stringops',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/cordic',...
    '$matlabroot$/toolbox/hdlcoder/hdlcommon/emlauthoring/nonRestoreDivide',...
    };

    for ii=1:length(emlPathList)
        gp.addEMLPath(emlPathList{ii});
    end



