



Simulink.defineIntEnumType('Std_ReturnType',...
{'E_OK','E_NOT_OK'},...
[0,1],...
'DefaultValue','E_OK',...
'StorageType','uint8',...
'HeaderFile','Rte_Type.h',...
'AddClassNameToEnumNames',false);
