function dlgStruct=getDialogSchema(this,name)




    if~builtin('license','checkout','SIMULINK_Report_Gen')
        dlgStruct=this.buildErrorMessage(name,true);
        return;
    end


    wIsFunctionTable=this.dlgWidget('IsFunctionTable',...
    'DialogRefresh',1,...
    'ColSpan',[1,2],...
    'RowSpan',[1,1]);

    wFunctionTableTitleType=this.dlgWidget('FunctionTableTitleType',...
    'Enabled',this.isFunctionTable,...
    'ColSpan',[1,1],...
    'RowSpan',[2,2],...
    'DialogRefresh',1);

    wFunctionTableTitle=this.dlgWidget('FunctionTableTitle',...
    'ColSpan',[2,2],...
    'RowSpan',[2,2],...
    'Enabled',this.isFunctionTable&&strcmp(this.FunctionTableTitleType,'manual'));

    wFunctionTableParentBlock=this.dlgWidget('FunctionTableParentBlock',...
    'Enabled',this.isFunctionTable,...
    'ColSpan',[1,2],...
    'RowSpan',[3,3]);

    wFunctionTableCallingString=this.dlgWidget('FunctionTableCallingString',...
    'Enabled',this.isFunctionTable,...
    'ColSpan',[1,2],...
    'RowSpan',[4,4]);

    wFunctionsPanel=this.dlgContainer({
wIsFunctionTable
wFunctionTableTitleType
wFunctionTableTitle
wFunctionTableParentBlock
wFunctionTableCallingString
    },getString(message('RptgenSL:rsl_csl_obj_fun_var:functionsLabel')),...
    'RowSpan',[1,1],...
    'ColSpan',[1,1],...
    'RowStretch',[0,0,0,0],...
    'ColStretch',[0,1],...
    'LayoutGrid',[4,2]);


    wIsVariableTable=this.dlgWidget('IsVariableTable',...
    'ColSpan',[1,2],...
    'RowSpan',[1,1]);

    wVariableTableTitleType=this.dlgWidget('VariableTableTitleType',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,1],...
    'RowSpan',[2,2],...
    'DialogRefresh',1);

    wVariableTableTitle=this.dlgWidget('VariableTableTitle',...
    'ColSpan',[2,2],...
    'RowSpan',[2,2],...
    'Enabled',this.isVariableTable&&strcmp(this.VariableTableTitleType,'manual'));

    wIsWorkspaceIO=this.dlgWidget('isWorkspaceIO',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,2],...
    'RowSpan',[3,3]);

    wVariableTableParentBlock=this.dlgWidget('VariableTableParentBlock',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,1],...
    'RowSpan',[4,4]);

    wVariableTableCallingString=this.dlgWidget('VariableTableCallingString',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[2,2],...
    'RowSpan',[4,4]);

    wIsShowVariableSize=this.dlgWidget('isShowVariableSize',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,1],...
    'RowSpan',[5,5]);

    wIsShowVariableMemory=this.dlgWidget('isShowVariableMemory',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[2,2],...
    'RowSpan',[5,5]);

    wIsShowVariableClass=this.dlgWidget('isShowVariableClass',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,1],...
    'RowSpan',[6,6]);

    wIsShowVariableValue=this.dlgWidget('isShowVariableValue',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[2,2],...
    'RowSpan',[6,6]);

    wIsShowTunableProps=this.dlgWidget('isShowTunableProps',...
    'Enabled',this.isVariableTable,...
    'ColSpan',[1,1],...
    'RowSpan',[7,7]);

    wParameterProps=this.dlgWidgetStringVector('ParameterProps');
    wParameterProps.Enabled=this.isVariableTable;
    wParameterProps.ColSpan=[1,2];
    wParameterProps.RowSpan=[8,8];

    wVariablesPanel=this.dlgContainer({
wIsVariableTable
wVariableTableTitleType
wVariableTableTitle
wIsWorkspaceIO
wVariableTableParentBlock
wVariableTableCallingString
wIsShowVariableSize
wIsShowVariableMemory
wIsShowVariableClass
wIsShowVariableValue
wIsShowTunableProps
wParameterProps
    },getString(message('RptgenSL:rsl_csl_obj_fun_var:variablesLabel')),...
    'RowSpan',[2,2],...
    'ColSpan',[1,1],...
    'LayoutGrid',[8,2],...
    'ColStretch',[0,1],...
    'RowStretch',[0,0,0,0,0,0,0,1]);


    dlgStruct=this.dlgMain(name,{
wFunctionsPanel
wVariablesPanel
    },...
    'LayoutGrid',[2,1],...
    'RowStretch',[0,1]);
