classdef ShortcutsDialog<images.internal.app.utilities.CloseDialog




    properties(GetAccess=public,SetAccess=protected)

Table

    end

    methods




        function self=ShortcutsDialog(loc,dlgTitle)

            self=self@images.internal.app.utilities.CloseDialog(loc,dlgTitle);

            self.Size=[500,360];

            create(self);

            addTable(self);
            set(self.Table,'Visible','on');

        end




        function create(self)

            create@images.internal.app.utilities.CloseDialog(self);
            self.FigureHandle.WindowStyle="normal";

        end

    end

    methods(Access=protected)


        function addTable(self)

            data={getString(message('images:segmenter:upTask')),getString(message('images:segmenter:upAction'));...
            getString(message('images:segmenter:downTask')),getString(message('images:segmenter:downAction'));...
            getString(message('images:segmenter:leftTask')),getString(message('images:segmenter:leftAction'));...
            getString(message('images:segmenter:rightTask')),getString(message('images:segmenter:rightAction'));...
            getString(message('images:segmenter:CtrlZTask')),getString(message('images:segmenter:CtrlZAction'));...
            getString(message('images:segmenter:CtrlYTask')),getString(message('images:segmenter:CtrlYAction'));...
            getString(message('images:segmenter:CtrlClickTask')),getString(message('images:segmenter:CtrlClickAction'));...
            getString(message('images:segmenter:CtrlCTask')),getString(message('images:segmenter:CtrlCAction'));...
            getString(message('images:segmenter:CtrlXTask')),getString(message('images:segmenter:CtrlXAction'));...
            getString(message('images:segmenter:CtrlATask')),getString(message('images:segmenter:CtrlAAction'));...
            getString(message('images:segmenter:CtrlVTask')),getString(message('images:segmenter:CtrlVAction'));...
            getString(message('images:segmenter:DeleteTask')),getString(message('images:segmenter:DeleteAction'));...
            getString(message('images:segmenter:CtrlSTask')),getString(message('images:segmenter:CtrlSAction'));...
            getString(message('images:segmenter:CtrlZoomInTask')),getString(message('images:segmenter:CtrlZoomInAction'));...
            getString(message('images:segmenter:CtrlZoomOutTask')),getString(message('images:segmenter:CtrlZoomOutAction'));...
            getString(message('images:segmenter:ShiftPanUpTask')),getString(message('images:segmenter:ShiftPanUpAction'));...
            getString(message('images:segmenter:ShiftPanDownTask')),getString(message('images:segmenter:ShiftPanDownAction'));...
            getString(message('images:segmenter:ShiftPanLeftTask')),getString(message('images:segmenter:ShiftPanLeftAction'));...
            getString(message('images:segmenter:ShiftPanRightTask')),getString(message('images:segmenter:ShiftPanRightAction'));...
            getString(message('images:segmenter:ShiftAltPanUpTask')),getString(message('images:segmenter:ShiftAltPanUpAction'));...
            getString(message('images:segmenter:ShiftAltPanDownTask')),getString(message('images:segmenter:ShiftAltPanDownAction'));...
            getString(message('images:segmenter:ShiftAltPanLeftTask')),getString(message('images:segmenter:ShiftAltPanLeftAction'));...
            getString(message('images:segmenter:ShiftAltPanRightTask')),getString(message('images:segmenter:ShiftAltPanRightAction'));...
            getString(message('images:segmenter:EnterTask')),getString(message('images:segmenter:EnterAction'));...
            getString(message('images:segmenter:EscapeTask')),getString(message('images:segmenter:EscapeAction'));...
            getString(message('images:segmenter:BackspaceTask')),getString(message('images:segmenter:BackspaceAction'));...
            getString(message('images:segmenter:EscapeROITask')),getString(message('images:segmenter:EscapeROIAction'));...
            getString(message('images:segmenter:EnterROITask')),getString(message('images:segmenter:EnterROIAction'));...
            getString(message('images:segmenter:DoubleClickROITask')),getString(message('images:segmenter:DoubleClickROIAction'));...
            getString(message('images:segmenter:RightClickROITask')),getString(message('images:segmenter:RightClickROIAction'));...
            getString(message('images:segmenter:DoubleClickROIEdgeTask')),getString(message('images:segmenter:DoubleClickROIEdgeAction'))};

            self.Table=uitable(...
            'Parent',self.FigureHandle,...
            'Position',[self.ButtonSpace,self.ButtonSize(2)+(2*self.ButtonSpace),self.Size(1)-(2*self.ButtonSpace),self.Size(2)-(3*self.ButtonSpace)-self.ButtonSize(2)],...
            'FontSize',12,...
            'Enable','on',...
            'ColumnName',{getString(message('images:segmenter:action')),getString(message('images:segmenter:task'))},...
            'ColumnFormat',{'char','char'},...
            'RowName',{},...
            'Visible','off',...
            'SelectionType','row',...
            'Tag','ShortcutsTable',...
            'Data',data);

        end

    end

end
