function[refMdls,mdlBlks,mdlRefGraph]=getMdlRefs(modelName)



    if Simulink.internal.useFindSystemVariantsMatchFilter()
        [refMdls,mdlBlks,mdlRefGraph]=find_mdlrefs(modelName,...
        'AllLevels',true,...
        'IncludeProtectedModels',false,...
        'MatchFilter',@Simulink.match.activeVariants,...
        'IncludeCommented','off');
    else
        [refMdls,mdlBlks,mdlRefGraph]=find_mdlrefs(modelName,...
        'AllLevels',true,...
        'IncludeProtectedModels',false,...
        'Variants','ActiveVariants',...
        'IncludeCommented','off');
    end

end


