classdef Controller<handle
    properties(Hidden)
Model
View
Listeners
KeyPressList
Components
KeyPressListener
    end

    methods
        function self=Controller(model,view)
            self.Model=model;
            self.View=view;

            self.Listeners.SampleRate=addlistener(self.View.SampleRateEdit,'String',...
            'PostSet',@(h,e)SampleRateValueChanged(self.Model,self.View));

            self.Listeners.SystemParameterChanged=...
            addlistener(self.View.Parameters,'SystemParameterChanged',...
            @(h,data)systemParameterChanged(self.Model,data));
            self.Listeners.SystemParameterView=...
            addlistener(self.View.Parameters,'SystemParameterView',...
            @(h,data)waveformParameterChanged(self.Model,data));
            self.Listeners.SystemCompressionView=...
            addlistener(self.View.Parameters,'SystemCompressionView',...
            @(h,data)processTypeChanged(self.Model,data));

            self.Listeners.ElementParameterChanged=...
            addlistener(self.View.Parameters,'ElementParameterChanged',...
            @(h,data)setElementParameters(self.Model,self.View,data));
            self.Listeners.ElementParameter=...
            addlistener(self.View.Parameters,'ElementParameterView',...
            @(h,data)elementParameterChanged(self.Model,self.View,data));
            self.Listeners.ElementParameter=...
            addlistener(self.View.Parameters,'CompressParameterView',...
            @(h,data)compressParameterChanged(self.Model,self.View,data));

            self.Listeners.MultiSelectElementParameter=...
            addlistener(self.View.Parameters,'MultiSelectElementParameterView',...
            @(h,data)multielementParameterChanged(self.Model,self.View,data));
            self.Listeners.MultiSelectCompressParameter=...
            addlistener(self.View.Parameters,'MultiSelectCompressParameterView',...
            @(h,data)multicompressParameterChanged(self.Model,self.View,data));


            self.Listeners.InsertionRequested=...
            addlistener(self.View,'InsertionRequested',...
            @(h,data)insertionRequested(self.Model,data));
            self.Listeners.DuplicateInsertionRequested=...
            addlistener(self.View,'DuplicateInsertionRequested',...
            @(h,data)duplicateInsertionRequested(self.Model,data));
            self.Listeners.DeletionRequested=...
            addlistener(self.View,'DeletionRequested',...
            @(h,data)deletionRequested(self.Model,data));
            self.Listeners.PlotRequested=...
            addlistener(self.View,'PlotRequested',...
            @(h,data)plotRequested(self.Model,self.View,data));
            self.Listeners.CharacteristicsRequested=...
            addlistener(self.View,'CharacteristicsRequested',...
            @(h,data)characteristicsRequested(self.Model,data));

            self.Listeners.TitleSave=...
            addlistener(self.Model,'TitleSave',...
            @(h,data)titleSave(self.View.Canvas,data));

            self.Listeners.NewName=...
            addlistener(self.View,'NewName',...
            @(h,data)updateName(self.Model,data));

            self.Listeners.ElementSelected=...
            addlistener(self.View.Canvas,'ElementSelected',...
            @(h,data)elementSelected(self.Model,data));


            self.Listeners.MultiselectDisable=...
            addlistener(self.View.Canvas,'MultiselectDisable',...
            @(h,data)multiSelectDisable(self.Model,data));

            self.Listeners.UpdateName=...
            addlistener(self.View.Canvas,'UpdateName',...
            @(h,data)updateName(self.Model,data));

            self.Listeners.ElementParameterInvalid=...
            addlistener(self.Model,'ElementParameterInvalid',...
            @(h,data)elementParameterInvalid(self.View,data));

            self.Listeners.CompressParameterInvalid=...
            addlistener(self.Model,'CompressParameterInvalid',...
            @(h,data)compressParameterInvalid(self.View,data));

            self.Listeners.NewModel=...
            addlistener(self.Model,'NewModel',...
            @(h,data)newView(self.View.Canvas,data));
            self.Listeners.NewName=...
            addlistener(self.Model,'NewName',...
            @(h,data)newName(self.View,data.Name));
            self.Listeners.ItemSelected=...
            addlistener(self.View.Canvas,'ItemSelected',...
            @(h,data)itemSelected(self.Model,data));


            self.Listeners.ElementInserted=...
            addlistener(self.Model,'ElementInserted',...
            @(h,data)elementInserted(self.View,data));
            self.Listeners.ElementDeleted=...
            addlistener(self.Model,'ElementDeleted',...
            @(h,data)elementDeleted(self.View,data));
            self.Listeners.PlotAdded=...
            addlistener(self.Model,'PlotAdded',...
            @(h,data)plotAdded(self.View,data));
            self.Listeners.CharacteristicsAdded=...
            addlistener(self.Model,'CharacteristicsAdded',...
            @(h,data)characteristicsAdded(self.View,data));


            self.Listeners.SelectedElement=...
            addlistener(self.Model,'SelectedElement',...
            @(h,data)selectedElement(self.View.Canvas,data));
            self.Listeners.SelectedProcess=...
            addlistener(self.Model,'SelectedProcess',...
            @(h,data)selectedProcess(self.View.Canvas,data));
            self.Listeners.Componentsadd=...
            addlistener(self.View,'Componentsadd',...
            @(h,data)addComponents(self,data));



            addToolGroupKeyPress(self,'s',@self.controlSaveAction,{'control'});
            addToolGroupKeyPress(self,'n',@self.refresh,{'control'});
            addToolGroupKeyPress(self,'o',@self.openSessionAction,{'control'});
            self.Components=[self.View.ParametersFig,self.View.RealAndImaginaryFig...
            ,self.View.Library,self.View.Characteristics,self.View.SpectrumFig...
            ,self.View.SampleRateEdit,self.View.Parameters.RectangularDialog.PRFEdit...
            ,self.View.Parameters.RectangularDialog.NumPulsesEdit,self.View.Parameters.RectangularDialog.PulseWidthEdit...
            ,self.View.Parameters.RectangularDialog.PropagationSpeedEdit,self.View.Parameters.RectangularDialog.FrequencyOffsetEdit...
            ,self.View.Parameters.RectangularDialog.WaveformEdit,self.View.Parameters.WaveformCharacteristics.characteristicsTable];

            createComponentKeyPressListener(self);
        end

        function addToolGroupKeyPress(self,key,callback,modifier)

            self.KeyPressList{end+1}=struct(...
            'key',key,...
            'modifier',{modifier},...
            'callback',callback);
        end

        function createComponentKeyPressListener(self)
            if isempty(self.KeyPressList)
                return;
            end

            self.KeyPressListener=event.listener([self.Components],...
            'KeyPress',@self.onComponentKeyPress);
        end
        function onComponentKeyPress(self,~,event)

            keyPressList=self.KeyPressList;
            for indx=1:numel(keyPressList)
                key=keyPressList{indx};
                if isequal(sort(event.Modifier),sort(key.modifier))&&...
                    isequal(event.Key,key.key)
                    key.callback();
                    return;
                end
            end
        end
        function refresh(self)

            newActions(self.Model,self.View)
        end
        function controlSaveAction(self)

            saveAction(self.Model,self.View)
        end
        function openSessionAction(self)

            openAction(self.Model,self.View)
        end
    end
    methods(Access=private)

        function addComponents(self,data)

            self.Components(end+1)=data.figure;
            self.KeyPressListener=event.listener([self.Components],...
            'KeyPress',@self.onComponentKeyPress);
        end
    end
end
