function rstCtrl=elabRstCtrl(this,topNet,dataRate,...
    dinVld,syncReset,initReg)







    InportNames={dinVld.Name,syncReset.Name};
    InportTypes=[dinVld.Type,syncReset.Type];
    InportRates=[dataRate;dataRate];

    OutportNames={initReg.Name};
    OutportTypes=[initReg.Type];

    rstCtrl=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','rstCtrl',...
    'InportNames',InportNames,...
    'InportTypes',InportTypes,...
    'InportRates',InportRates,...
    'OutportNames',OutportNames,...
    'OutportTypes',OutportTypes...
    );

    inputPort=rstCtrl.PirInputSignals;
    outputPort=rstCtrl.PirOutputSignals;

    dinVld=inputPort(1);
    syncReset=inputPort(2);
    initReg=outputPort(1);

    fid=fopen(fullfile(matlabroot,'toolbox','dsphdl','dsphdlutilities',...
    '+dsphdlsupport','+internal','@AbstractFilterBank','cgireml','rstCtrl.m'),'r');
    fcnBody=fread(fid,Inf,'char=>char')';
    fclose(fid);

    desc='rstCtrl';

    rst=rstCtrl.addComponent2(...
    'kind','cgireml',...
    'Name','rstCtrl',...
    'InputSignals',dinVld,...
    'OutputSignals',initReg,...
    'EMLFileName','rstCtrl',...
    'EMLFileBody',fcnBody,...
    'EMLParams',{},...
    'ExternalSynchronousResetSignal',syncReset,...
    'EMLFlag_TreatInputIntsAsFixpt',true,...
    'EMLFlag_SaturateOnIntOverflow',false,...
    'EMLFlag_TreatInputBoolsAsUfix1',false,...
    'BlockComment',desc);

    rst.runConcurrencyMaximizer(0);
    rst.resetNone(false);
