function ret=getDefaultBusStruct()




    ret=struct(...
    'Description',"",...
    'DataScope',"Auto",...
    'HeaderFile',"",...
    'Alignment',-1,...
    'PreserveElementDimensions',0...
    );
end
