function breakpoint=createSourceBreakpoint(fileName,oneBasedLineNumber,expression,anonymousIndex,columnNumber,isEnabled)
    if nargin<6
        isEnabled=true;
    end

    breakpoint=struct(...
    'lineNumber',oneBasedLineNumber,...
    'fileName',fileName,...
    'expression',expression,...
    'isEnabled',isEnabled,...
    'anonymousIndex',anonymousIndex,...
    'columnNumber',1...
    );
end