function dlgStruct=getDialogSchema(this,name)




    if~builtin('license','checkout','SIMULINK_Report_Gen')
        dlgStruct=this.buildErrorMessage(name,true);
        return;

    end

    if strcmp(this.ListTitleMode,'auto')
        wTitle=this.dlgText(getString(message('RptgenSL:rsl_csl_blk_sort_list:sortedListForLabel',getString(message('RptgenSL:rsl_csl_blk_sort_list:systemNameLabel')))));
    else
        wTitle=this.dlgWidget('ListTitle');
    end

    dlgStruct=this.dlgMain(name,{
    this.dlgContainer({
    this.dlgWidget('ListTitleMode',...
    'DialogRefresh',true,...
    'ColSpan',[1,1],...
    'RowSpan',[1,1])
    this.dlgSet(wTitle,...
    'ColSpan',[2,2],...
    'RowSpan',[1,1])
    this.dlgWidget('isBlockType',...
    'ColSpan',[1,2],...
    'RowSpan',[2,2])
    this.dlgWidget('FollowNonVirtual',...
    'ColSpan',[1,2],...
    'RowSpan',[3,3])
    },getString(message('RptgenSL:rsl_csl_blk_sort_list:propertiesLabel')),...
    'LayoutGrid',[4,2],...
    'ColStretch',[0,1],...
    'RowStretch',[0,0,0,1])
    });
