function retValue = convertToLTLFormula(typedDependencies)
    retValue = Simulink.specminer.internal.convertToPredicateTree(length(typedDependencies.tokens), ...
                                                                  typedDependencies.tokens, ...
                                                                  length(typedDependencies.basicDependencies), ...
                                                                  typedDependencies.basicDependencies, ...
                                                                  typedDependencies.enhancedDependencies, ...
                                                                  typedDependencies.enhancedPlusPlusDependencies);
end
