function sysObjs=getSupportedSystemObjects()












    sysObjs={
    'hdlram',...
    'comm.BPSKModulator','comm.BPSKDemodulator',...
    'comm.PSKModulator','comm.PSKDemodulator',...
    'comm.QPSKModulator','comm.QPSKDemodulator',...
    'comm.RectangularQAMModulator','comm.RectangularQAMDemodulator',...
    'comm.ConvolutionalInterleaver','comm.ConvolutionalDeinterleaver',...
    'comm.ViterbiDecoder',...
    'dsp.Delay',...
    'dsp.BiquadFilter',...
    'hdlram',...
    'hdl.RAM',...
    'commcodegen.BPSKModulator','commcodegen.BPSKDemodulator',...
    'commcodegen.PSKModulator','comm.PSKDemodulator',...
    'commcodegen.QPSKModulator','comm.QPSKDemodulator',...
    'commcodegen.RectangularQAMModulator','comm.RectangularQAMDemodulator',...
    'commcodegen.ConvolutionalInterleaver','commcodegen.ConvolutionalDeinterleaver',...
    'commcodegen.ViterbiDecoder',...
    'dsp.Delay',...
    'dspcodegen.BiquadFilter',...
    };
end
