function time=dotnetdatetime2datetime(dotnetdatetime)



    if isa(dotnetdatetime,'System.DateTime[]')
        [years,months,days,hours,minutes,seconds,milliseconds]=...
        NETUtilities.Datetime.Export(dotnetdatetime);
        time=getDatetime(...
        int32(years),int32(months),int32(days),...
        int32(hours),int32(minutes),int32(seconds),...
        int32(milliseconds));
    else
        time=getDatetime(...
        dotnetdatetime.Year,...
        dotnetdatetime.Month,...
        dotnetdatetime.Day,...
        dotnetdatetime.Hour,...
        dotnetdatetime.Minute,...
        dotnetdatetime.Second,...
        dotnetdatetime.Millisecond);
    end
end

function time=getDatetime(year,month,day,hour,minute,second,millisecond)
    time=datetime(year,month,day,hour,minute,second,millisecond,...
    'TimeZone','UTC',...
    'Format',icomm.pi.internal.Locale.DatetimeFormat);
end