

function success=setParamWithUndo(editor,editorDomain,setParamFcn,fcnArgs)
    success=editorDomain.createParamChangesCommand(...
    editor,...
    '',...
    '',...
    setParamFcn,...
    fcnArgs,...
    false,...
    true,...
    false,...
    false,...
false...
    );
end

