function filtparams=filterImplParamNames(this)







    filtparams={'CoeffMultipliers',...
'DALUTPartition'...
    ,'DARadix',...
    'SerialPartition',...
    'ReuseAccum',...
    'AddPipelineRegisters',...
    'MultiplierInputPipeline',...
    'MultiplierOutputPipeline'};

