classdef Four_QuadrantSingle_Phas_class<ConvClass&handle



    properties

        OldParam=struct(...
        'Laf',[],...
        'Ra',[],...
        'La',[],...
        'Rf',[],...
        'Lf',[],...
        'J',[],...
        'Bm',[],...
        'Tfriction',[],...
        'w0',[],...
        'smoothingInductance',[],...
        'Vfield',[],...
        'Lcc',[],...
        'Ron_rec1',[],...
        'Vf_rec1',[],...
        'Rsnb_rec1',[],...
        'Csnb_rec1',[],...
        'Ron_rec2',[],...
        'Vf_rec2',[],...
        'Rsnb_rec2',[],...
        'Csnb_rec2',[],...
        'LineVoltage',[],...
        'LineFrequency',[],...
        'sourceInductance',[],...
        'PhaseAngle',[],...
        'Tc',[],...
        'wb',[],...
        'InitialSpeed',[],...
        'fc_sc',[],...
        'kp_sc',[],...
        'ki_sc',[],...
        'Acc',[],...
        'Dec',[],...
        'fc_ic',[],...
        'refLim',[],...
        'Pb',[],...
        'Vb',[],...
        'kp_ic',[],...
        'ki_ic',[],...
        'alphamin',[],...
        'alphamax',[],...
        'freqSynchro',[],...
        'pulseWitdth',[],...
        'baseSampleTime',[]...
        )


        OldDropdown=struct(...
        'regulationType',[],...
        'outputBusMode',[],...
        'MechanicalLoad',[],...
        'modelDetailLevel',[],...
        'driveType',[],...
        'busLabels',[],...
        'AverageValue',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='electricdrivelib/DC drives/Four-Quadrant Single-Phase Rectifier DC Drive'
        NewPath='elec_conv_Four_QuadrantSingle_Phas/Four_QuadrantSingle_Phas'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
