classdef Inverter_Three_Phase__class<ConvClass&handle



    properties

        OldParam=struct(...
        'Ts',[],...
        'SnubberResistance',[],...
        'SnubberCapacitance',[],...
        'Ron',[],...
        'ForwardVoltages',[],...
        'GTOparameters',[],...
        'IGBTparameters',[],...
        'SourceFrequency',[],...
        'dqInductances',[],...
        'Inductance',[],...
        'Ls',[],...
        'Resistance',[],...
        'Flux',[],...
        'Stator_sm',[],...
        'Stator_im',[],...
        'Rotor',[],...
        'Lm',[],...
        'p',[]...
        )


        OldDropdown=struct(...
        'detailLevel',[],...
        'driveType',[],...
        'Device',[],...
        'Measurements',[],...
        'converterType',[],...
        'ReferenceFrame',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='electricdrivelib/Fundamental Drive Blocks/Inverter (Three-Phase)'
        NewPath='elec_conv_Inverter_Three_Phase_/Inverter_Three_Phase_'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
