classdef Multi_WindingTransformer_class<ConvClass&handle



    properties

        OldParam=struct(...
        'LeftWindings',[],...
        'RightWindings',[],...
        'NumberOfTaps',[],...
        'DataFile',[],...
        'NominalPower',[],...
        'NominalVoltages',[],...
        'WindingResistances',[],...
        'WindingInductances',[],...
        'Rm',[],...
        'Lm',[],...
        'Saturation',[],...
        'InitialFlux',[],...
        'TransfoNumber',[]...
        )


        OldDropdown=struct(...
        'TappedWindings',[],...
        'Measurements',[],...
        'UNITS',[],...
        'SetSaturation',[],...
        'Hysteresis',[],...
        'MoreParameters',[],...
        'BreakLoop',[],...
        'DataType',[]...
        )


        NewParam=struct(...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='powerlib/Elements/Multi-Winding Transformer'
        NewPath='elec_conv_Multi_WindingTransformer/Multi_WindingTransformer'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
