classdef PVArray_class<ConvClass&handle



    properties

        OldParam=struct(...
        'Npar',[],...
        'Nser',[],...
        'S_vec',[],...
        'Temp_C_vec',[],...
        'Pm',[],...
        'Ncell',[],...
        'Voc',[],...
        'Isc',[],...
        'Vm',[],...
        'Im',[],...
        'beta_Voc_pc',[],...
        'alpha_Isc_pc',[],...
        'beta_Voc',[],...
        'alpha_Isc',[],...
        'IL',[],...
        'I0',[],...
        'nI',[],...
        'Rsh',[],...
        'Rs',[],...
        'Tc',[],...
        'Tfilter',[]...
        )


        OldDropdown=struct(...
        'PlotType',[],...
        'ModuleName',[],...
        'PlotWhenSelected',[],...
        'BAL',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='re_lib/Solar/PV Array'
        NewPath='elec_conv_PVArray/PVArray'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
