classdef ThyristorConverter_class<ConvClass&handle



    properties

        OldParam=struct(...
        'Ts',[],...
        'Ron',[],...
        'SnubberResistance',[],...
        'SnubberCapacitance',[],...
        'ForwardVoltage',[],...
        'LineVoltage',[],...
        'LineFrequency',[],...
        'initAngle',[],...
        'SourceInductance',[],...
        'CirculationInductance',[],...
        'NominalPower',[],...
        'Percentage',[]...
        )


        OldDropdown=struct(...
        'detailLevel',[],...
        'supplyType',[],...
        'numQuad',[],...
        'converterType',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='electricdrivelib/Fundamental Drive Blocks/Thyristor Converter'
        NewPath='elec_conv_ThyristorConverter/ThyristorConverter'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
