classdef UnifiedPowerFlowControll_class<ConvClass&handle



    properties

        OldParam=struct(...
        'SystemNominal',[],...
        'Pnom_SH',[],...
        'RL_SH',[],...
        'Iinit_SH',[],...
        'SeriesNominal',[],...
        'RL_SE',[],...
        'Iinit_SE',[],...
        'VnomDC',[],...
        'C_DC',[],...
        'Vref_SH',[],...
        'MaxRateChangeVref_SH',[],...
        'Droop_SH',[],...
        'Par_VacReg',[],...
        'Qref_SH',[],...
        'MaxRateChangeQref_SH',[],...
        'Par_VdcReg',[],...
        'Par_IReg_SH',[],...
        'PQref_SE',[],...
        'Rate_PQref',[],...
        'Par_PReg_SE',[],...
        'Vdqref_SE',[],...
        'Rate_Vdqref',[]...
        )


        OldDropdown=struct(...
        'OpMode_SH',[],...
        'ExternalByPass',[],...
        'OpMode_SE',[],...
        'ExternalVref',[],...
        'ExternalPQref',[],...
        'ExternalVdqref',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='factslib/Power-Electronics Based FACTS/Unified Power Flow Controller (Phasor Type)'
        NewPath='elec_conv_UnifiedPowerFlowControll/UnifiedPowerFlowControll'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
