classdef WindTurbineDoubly_FedInd_class<ConvClass&handle



    properties

        OldParam=struct(...
        'nom',[],...
        'sta',[],...
        'rot',[],...
        'Lm',[],...
        'mec',[],...
        'init',[],...
        'speed_power',[],...
        'Pmec',[],...
        'speed_ABCD',[],...
        'power_C',[],...
        'wind_point_C',[],...
        'pitch_gain',[],...
        'pitch_max',[],...
        'pitch_rate',[],...
        'Pmax',[],...
        'Lchoke',[],...
        'init_inductor',[],...
        'Vdc_nom',[],...
        'capacitor',[],...
        'Vref',[],...
        'Qref',[],...
        'Iq_ref',[],...
        'Kpi_volt_reg',[],...
        'Xs',[],...
        'Kpi_Q',[],...
        'Kpi_power_reg',[],...
        'Kpi_dc_reg',[],...
        'Kpi_grid_side_cur_reg',[],...
        'Kpi_rotor_side_cur_reg',[],...
        'V_slew_rate',[],...
        'Q_slew_rate',[],...
        'power_slew_rate',[],...
        'current_slew_rate',[]...
        )


        OldDropdown=struct(...
        'ControlVQ',[],...
        'ExternalTm',[],...
        'ExternalVref',[],...
        'ExternalQref',[],...
        'ExternalIqref',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }

        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='re_lib/Wind Generation/Wind Turbine Doubly-Fed Induction Generator (Phasor Type)'
        NewPath='elec_conv_WindTurbineDoubly_FedInd/WindTurbineDoubly_FedInd'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
