classdef WindTurbineInductionGene_class<ConvClass&handle



    properties

        OldParam=struct(...
        'nom',[],...
        'sta',[],...
        'rot',[],...
        'Lm',[],...
        'mec',[],...
        'init',[],...
        'pitch_angle',[],...
        'Pmec',[],...
        'wind_base',[],...
        'speed_nom',[],...
        'P_wind_base',[],...
        'K_pitch_gain',[],...
        'pitch_max',[],...
        'pitch_rate',[]...
        )


        OldDropdown=struct(...
        'ExternalTm',[]...
        )


        NewDirectParam=struct(...
        )


        NewDerivedParam=struct(...
        )


        NewDropdown=struct(...
        )


        BlockOption={...
        }
        OldBlockName=[];
        NewBlockPath=[];
        ConversionType=[];
    end

    properties(Constant)
        OldPath='re_lib/Wind Generation/Wind Turbine Induction Generator (Phasor Type)'
        NewPath='elec_conv_WindTurbineInductionGene/WindTurbineInductionGene'
    end
    methods
        function obj=objParamMappingDirect(obj)
        end

        function obj=objParamMappingDerived(obj)


        end

        function obj=objDropdownMapping(obj)
            logObj=ElecAssistantLog.getInstance();
            logObj.addMessage(obj,'BlockNotSupported');
        end
    end

end
