function[position,velocity]=propagate(tleStruct,time)%#codegen








    coder.allowpcode('plain');


    numSamples=numel(time);


    dragCoefficient=tleStruct.BStar;
    meanArgumentOfPeriapsisAtEpoch=tleStruct.ArgumentOfPeriapsis;
    meanMeanAnomalyAtEpoch=tleStruct.MeanAnomaly;
    meanRightAscensionOfAscendingNodeAtEpoch=...
    tleStruct.RightAscensionOfAscendingNode;
    epoch=tleStruct.Epoch;
    meanInclinationAtEpoch=tleStruct.Inclination;
    meanEccentricityAtEpoch=tleStruct.Eccentricity;

    if meanEccentricityAtEpoch==0
        meanEccentricityAtEpoch=eps;
    end
    meanMeanMotionAtEpoch=tleStruct.MeanMotion*60;


    timeSinceEpoch=minutes(time-epoch);


    standardGravitationalParameter=...
    matlabshared.orbit.internal.OrbitPropagationModel.StandardGravitationalParameter...
    /(1e9);
    earthRadius=matlabshared.orbit.internal.GeneralPerturbations.pEarthRadiusGP/1000;
    normalizedEarthRadius=1;
    J2=matlabshared.orbit.internal.GeneralPerturbations.pJ2;
    J3=matlabshared.orbit.internal.GeneralPerturbations.pJ3;
    J4=matlabshared.orbit.internal.GeneralPerturbations.pJ4;


    densityFunctionParameter1=...
    matlabshared.orbit.internal.GeneralPerturbations.pDensityFunctionParameter1;
    densityFunctionParameter2=...
    matlabshared.orbit.internal.GeneralPerturbations.pDensityFunctionParameter2;
    A30=-(J3*(normalizedEarthRadius^3));
    ke=matlabshared.orbit.internal.GeneralPerturbations.pNormalizedStandardGravitationalParameter;
    k2=(1/2)*J2*(normalizedEarthRadius^2);
    k4=-3/8*J4*normalizedEarthRadius^4;


    a1=(ke/meanMeanMotionAtEpoch)^(2/3);
    del1=(3/2)*(k2/(a1^2))*((3*(cos(meanInclinationAtEpoch)^2))-1)/...
    ((1-(meanEccentricityAtEpoch^2))^(3/2));
    a0=a1*(1-(del1/3)-(del1^2)-(134*(del1^3)/81));
    del0=(3/2)*(k2/(a0^2))*((3*(cos(meanInclinationAtEpoch)^2))-1)/...
    ((1-(meanEccentricityAtEpoch^2))^(3/2));
    meanMotionAtEpoch=meanMeanMotionAtEpoch/(1+del0);
    semiMajorAxisAtEpoch=a0/(1-del0);


    meanSemiMajorAxisAtEpoch=(standardGravitationalParameter/...
    ((meanMeanMotionAtEpoch/60)^2))^(1/3);
    meanPeriapsisAtEpoch=...
    meanSemiMajorAxisAtEpoch*(1-meanEccentricityAtEpoch);



    if meanPeriapsisAtEpoch>=(98+6378.135)&&...
        meanPeriapsisAtEpoch<(156+6378.135)
        densityFunctionParameter1Modified=...
        (semiMajorAxisAtEpoch*(1-meanEccentricityAtEpoch))-...
        densityFunctionParameter1+normalizedEarthRadius;
        densityFunctionParameter2=...
        ((densityFunctionParameter2^(1/4))+densityFunctionParameter1...
        -densityFunctionParameter1Modified)^4;
        densityFunctionParameter1=densityFunctionParameter1Modified;
    elseif meanPeriapsisAtEpoch<(98+6378.135)
        densityFunctionParameter1=(20/earthRadius)+normalizedEarthRadius;
        densityFunctionParameter1Modified=(20)+normalizedEarthRadius;
        densityFunctionParameter2=...
        ((densityFunctionParameter2^(1/4))+densityFunctionParameter1...
        -densityFunctionParameter1Modified)^4;
        densityFunctionParameter1=densityFunctionParameter1Modified;
    end


    theta=cos(meanInclinationAtEpoch);
    zeta=1/(semiMajorAxisAtEpoch-densityFunctionParameter1);
    beta0=(1-(meanEccentricityAtEpoch^2))^(1/2);
    eta=semiMajorAxisAtEpoch*meanEccentricityAtEpoch*zeta;

    C2=densityFunctionParameter2*(zeta^4)*meanMotionAtEpoch*((1-(eta^2))^...
    (-(7/2)))*((semiMajorAxisAtEpoch*(1+((3/2)*(eta^2))+...
    (4*meanEccentricityAtEpoch*eta)+...
    (meanEccentricityAtEpoch*(eta^3))))+((3/2)*(k2*zeta/(1-(eta^2))...
    )*(-(1/2)+((3/2)*(theta^2)))*(8+(24*(eta^2))+(3*(eta^4)))));
    C1=dragCoefficient*C2;
    C3=densityFunctionParameter2*(zeta^5)*A30*meanMotionAtEpoch*...
    normalizedEarthRadius*sin(meanInclinationAtEpoch)/...
    (k2*meanEccentricityAtEpoch);
    C4=(2*meanMotionAtEpoch*densityFunctionParameter2*(zeta^4)*...
    semiMajorAxisAtEpoch*(beta0^2)*((1-(eta^2))^(-(7/2))))*(((2*eta*(1+...
    (meanEccentricityAtEpoch*eta)))+((1/2)*meanEccentricityAtEpoch)+...
    ((1/2)*(eta^3)))-((2*k2*zeta/(semiMajorAxisAtEpoch*(1-(eta^2))))*...
    (3*(1-3*eta^2)*(1+3/2*eta^2-2*meanEccentricityAtEpoch*eta-1/2*...
    meanEccentricityAtEpoch*eta^3)+3/4*(1-theta^2)*(2*eta^2-...
    meanEccentricityAtEpoch*eta-meanEccentricityAtEpoch*eta^3)*...
    cos(2*meanArgumentOfPeriapsisAtEpoch))));
    C5=2*densityFunctionParameter2*zeta^4*semiMajorAxisAtEpoch*beta0^2*...
    (1-eta^2)^(-7/2)*(1+11/4*eta*(eta+meanEccentricityAtEpoch)+...
    meanEccentricityAtEpoch*eta^3);

    D2=4*semiMajorAxisAtEpoch*zeta*C1^2;
    D3=4/3*semiMajorAxisAtEpoch*zeta^2*(17*semiMajorAxisAtEpoch+...
    densityFunctionParameter1)*C1^3;
    D4=2/3*semiMajorAxisAtEpoch*zeta^3*(221*semiMajorAxisAtEpoch+31*...
    densityFunctionParameter1)*C1^4;


    meanAnomalyDF=meanMeanAnomalyAtEpoch+(1+3*k2*(-1+3*theta^2)/...
    (2*semiMajorAxisAtEpoch^2*beta0^3)+3*k2^2*(13-78*theta^2+137*...
    theta^4)/(16*semiMajorAxisAtEpoch^4*beta0^7))*meanMotionAtEpoch*...
    timeSinceEpoch;
    argumentOfPeriapsisDF=meanArgumentOfPeriapsisAtEpoch+(-3*k2*(1-5*...
    theta^2)/(2*semiMajorAxisAtEpoch^2*beta0^4)+3*k2^2*(7-114*theta^2...
    +395*theta^4)/(16*semiMajorAxisAtEpoch^4*beta0^8)...
    +5*k4*(3-36*theta^2+49*theta^4)/(4*semiMajorAxisAtEpoch^4*beta0^8)...
    )*meanMotionAtEpoch*timeSinceEpoch;
    rightAscensionOfAscendingNodeDF=...
    meanRightAscensionOfAscendingNodeAtEpoch+(-3*k2*theta/...
    (semiMajorAxisAtEpoch^2*beta0^4)+3*k2^2*(4*theta-19*theta^3)/...
    (2*semiMajorAxisAtEpoch^4*beta0^8)...
    +5*k4*theta*(3-7*theta^2)/(2*semiMajorAxisAtEpoch^4*beta0^8))*...
    meanMotionAtEpoch*timeSinceEpoch;
    argumentOfPeriapsisPerturbation=dragCoefficient*C3*...
    cos(meanArgumentOfPeriapsisAtEpoch)*timeSinceEpoch;
    meanAnomalyPerturbation=-2/3*densityFunctionParameter2*...
    dragCoefficient*zeta^4*normalizedEarthRadius/...
    (meanEccentricityAtEpoch*eta)*((1+eta*cos(meanAnomalyDF)).^3-...
    (1+eta*cos(meanMeanAnomalyAtEpoch))^3);
    meanAnomaly=meanAnomalyDF+argumentOfPeriapsisPerturbation+...
    meanAnomalyPerturbation;
    argumentOfPeriapsis=argumentOfPeriapsisDF-...
    argumentOfPeriapsisPerturbation-meanAnomalyPerturbation;
    rightAscensionOfAscendingNode=rightAscensionOfAscendingNodeDF-...
    21/2*meanMotionAtEpoch*k2*theta/(semiMajorAxisAtEpoch^2*beta0^2)*...
    C1*timeSinceEpoch.^2;
    eccentricity=meanEccentricityAtEpoch-...
    dragCoefficient*C4*timeSinceEpoch-dragCoefficient*C5*...
    (sin(meanAnomaly)-sin(meanMeanAnomalyAtEpoch));


    if meanPeriapsisAtEpoch<(220+6378.137)
        semiMajorAxis=semiMajorAxisAtEpoch*(1-C1*timeSinceEpoch).^2;
        L=meanAnomaly+argumentOfPeriapsis+...
        rightAscensionOfAscendingNode+meanMotionAtEpoch*...
        (3/2*C1*timeSinceEpoch.^2);
    else
        semiMajorAxis=semiMajorAxisAtEpoch*(1-C1*timeSinceEpoch-D2*...
        timeSinceEpoch.^2-D3*timeSinceEpoch.^3-D4*timeSinceEpoch.^4).^2;
        L=meanAnomaly+argumentOfPeriapsis+...
        rightAscensionOfAscendingNode+meanMotionAtEpoch*...
        (3/2*C1*timeSinceEpoch.^2+(D2+2*C1^2)*timeSinceEpoch.^3...
        +1/4*(3*D3+12*C1*D2+10*C1^3)*timeSinceEpoch.^4...
        +1/5*(3*D4+12*C1*D3+6*D2^2+30*C1^2*D2+15*C1^4)*timeSinceEpoch.^5);
    end


    beta=sqrt(1-eccentricity.^2);
    axN=eccentricity.*cos(argumentOfPeriapsis);
    LL=(A30*sin(meanInclinationAtEpoch)./(8*k2*semiMajorAxis.*beta.^2)).*...
    (eccentricity.*cos(argumentOfPeriapsis))*(3+5*theta)/(1+theta);
    ayNL=A30*sin(meanInclinationAtEpoch)./(4*k2*semiMajorAxis.*beta.^2);
    LT=L+LL;
    ayN=eccentricity.*sin(argumentOfPeriapsis)+ayNL;


    tol=1e-6;

    U=LT-rightAscensionOfAscendingNode;
    eccentricAnomalyPlusArgumentOfPeriapsis=U;

    for idx=1:numSamples
        eccentricAnomalyPlusArgumentOfPeriapsisDelta=1;

        while abs(eccentricAnomalyPlusArgumentOfPeriapsisDelta)>tol
            eccentricAnomalyPlusArgumentOfPeriapsisDelta=real((U(idx)-...
            ayN(idx)*cos(eccentricAnomalyPlusArgumentOfPeriapsis(idx))+...
            axN(idx)*sin(eccentricAnomalyPlusArgumentOfPeriapsis(idx))-...
            eccentricAnomalyPlusArgumentOfPeriapsis(idx))/...
            (-ayN(idx)*sin(eccentricAnomalyPlusArgumentOfPeriapsis(idx))-...
            axN(idx)*cos(eccentricAnomalyPlusArgumentOfPeriapsis(idx))+1));
            eccentricAnomalyPlusArgumentOfPeriapsis(idx)=...
            eccentricAnomalyPlusArgumentOfPeriapsis(idx)+...
            eccentricAnomalyPlusArgumentOfPeriapsisDelta;
        end
    end


    eccentricityTimesCosEccentricAnomaly=...
    axN.*cos(eccentricAnomalyPlusArgumentOfPeriapsis)+...
    ayN.*sin(eccentricAnomalyPlusArgumentOfPeriapsis);
    eccentricityTimesSinEccentricAnomaly=...
    axN.*sin(eccentricAnomalyPlusArgumentOfPeriapsis)-...
    ayN.*cos(eccentricAnomalyPlusArgumentOfPeriapsis);
    eccentricityIntermediate=sqrt(axN.^2+ayN.^2);
    semiLatusRectumIntermediate=...
    semiMajorAxis.*(1-eccentricityIntermediate.^2);
    radialDistanceIntermediate=...
    semiMajorAxis.*(1-eccentricityTimesCosEccentricAnomaly);

    radialVelocityIntermediate=ke*sqrt(semiMajorAxis).*...
    eccentricityTimesSinEccentricAnomaly./radialDistanceIntermediate;
    tangentialVelocityIntermediate=ke*sqrt(semiLatusRectumIntermediate)./...
    radialDistanceIntermediate;
    cosArgumentOfPeriapsisPlusTrueAnomalyIntermediate=...
    (semiMajorAxis./radialDistanceIntermediate).*...
    (cos(eccentricAnomalyPlusArgumentOfPeriapsis)-axN+...
    ayN.*eccentricityTimesSinEccentricAnomaly./...
    (1+sqrt(1-eccentricityIntermediate.^2)));
    sinArgumentOfPeriapsisPlusTrueAnomalyIntermediate=...
    (semiMajorAxis./radialDistanceIntermediate).*...
    (sin(eccentricAnomalyPlusArgumentOfPeriapsis)-ayN-...
    axN.*eccentricityTimesSinEccentricAnomaly./...
    (1+sqrt(1-eccentricityIntermediate.^2)));
    argumentOfPeriapsisPlusTrueAnomalyIntermediate=...
    matlabshared.orbit.internal.GeneralPerturbations.arctan(...
    sinArgumentOfPeriapsisPlusTrueAnomalyIntermediate,...
    cosArgumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaRadialDistance=(k2./(2*semiLatusRectumIntermediate))*...
    (1-theta^2).*cos(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaArgumentOfPeriapsisPlusTrueAnomaly=...
    -(k2./(4*semiLatusRectumIntermediate.^2))*(7*theta^2-1).*...
    sin(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaRightAscensionOfAscendingNode=...
    (3*k2*theta./(2*semiLatusRectumIntermediate.^2)).*...
    sin(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaInclination=(3*k2*theta./(2*semiLatusRectumIntermediate.^2))*...
    sin(meanInclinationAtEpoch).*...
    cos(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaRadialVelocity=-(k2*eta./semiLatusRectumIntermediate)*...
    (1-theta^2).*sin(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate);
    deltaTangentialVelocity=...
    (k2*eta./semiLatusRectumIntermediate).*((1-theta^2).*...
    cos(2*argumentOfPeriapsisPlusTrueAnomalyIntermediate)-...
    (3/2)*(1-3*theta^2));


    radialDistance=radialDistanceIntermediate.*(1-(3/2)*k2*...
    (sqrt(1-eccentricityIntermediate.^2)./...
    semiLatusRectumIntermediate.^2)*(3*theta^2-1))+deltaRadialDistance;
    argumentOfPeriapsisPlusTrueAnomaly=...
    argumentOfPeriapsisPlusTrueAnomalyIntermediate+...
    deltaArgumentOfPeriapsisPlusTrueAnomaly;

    rightAscensionOfAscendingNode=rightAscensionOfAscendingNode+...
    deltaRightAscensionOfAscendingNode;
    inclination=meanInclinationAtEpoch+deltaInclination;
    radialVelocity=radialVelocityIntermediate+deltaRadialVelocity;
    tangentialVelocity=tangentialVelocityIntermediate+...
    deltaTangentialVelocity;


    unitRadialVector=zeros(3,numSamples);
    unitTangentVector=unitRadialVector;


    for idx=1:numSamples




        directionCosineMatrix=...
        [-sin(rightAscensionOfAscendingNode(idx))*cos(inclination(idx)),...
        cos(rightAscensionOfAscendingNode(idx)),...
        sin(rightAscensionOfAscendingNode(idx))*sin(inclination(idx));...
        cos(rightAscensionOfAscendingNode(idx))*cos(inclination(idx)),...
        sin(rightAscensionOfAscendingNode(idx)),...
        cos(rightAscensionOfAscendingNode(idx))*sin(inclination(idx));...
        sin(inclination(idx)),...
        0,...
        cos(inclination(idx))]...
        *...
        [sin(argumentOfPeriapsisPlusTrueAnomaly(idx)),...
        cos(argumentOfPeriapsisPlusTrueAnomaly(idx)),...
        0;...
        cos(argumentOfPeriapsisPlusTrueAnomaly(idx)),...
        -sin(argumentOfPeriapsisPlusTrueAnomaly(idx)),...
        0;...
        0,...
        0,...
        1];


        unitRadialVector(:,idx)=directionCosineMatrix(:,1);
        unitTangentVector(:,idx)=directionCosineMatrix(:,2);
    end


    radialDistances=[radialDistance;radialDistance;radialDistance];
    radialVelocities=[radialVelocity;radialVelocity;radialVelocity];
    tangentialVelocities=[tangentialVelocity;tangentialVelocity;tangentialVelocity];

    position=...
    radialDistances.*unitRadialVector*...
    matlabshared.orbit.internal.GeneralPerturbations.pEarthRadiusGP;
    velocity=(radialVelocities.*unitRadialVector+...
    tangentialVelocities.*unitTangentVector)*...
    matlabshared.orbit.internal.GeneralPerturbations.pEarthRadiusGP/60;
end


