function cgirComp=getBitSliceComp(hN,hInSignals,hOutSignals,msbPos,lsbPos,compName)







    if(nargin<6)
        compName='slice';
    end

    cgirComp=hN.addComponent2(...
    'kind','cgireml',...
    'Name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'EMLFileName','hdleml_bitsliceget',...
    'EMLParams',{msbPos+1,lsbPos+1},...
    'EMLFlag_ParamsFollowInputs',false,...
    'EMLFlag_RunLoopUnrolling',false);
end


