function blComp=getBacklashComp(hN,hInSignals,hOutSignals,backlashWidth,initialOutput,name)



    narginchk(6,6);

    blComp=hN.addComponent2(...
    'kind','cgireml',...
    'Name',name,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'EMLFileName','hdleml_backlash',...
    'EMLParams',{backlashWidth,initialOutput});
end


