function cgirComp=getPreLookupComp(hN,hInSignals,hOutSignals,...
    bp_data,bpType,kType,fType,idxOnly,powerof2,compName)









    if(nargin<9)
        compName='PreLookup';
    end

    if hInSignals.Type.isArrayType
        numTables=hInSignals.Type.Dimensions;
        hInputDemux=pirelab.getDemuxCompOnInput(hN,hInSignals);
        hIndexOutSignals=hdlhandles(numTables,1);
        [~,outTypeIdx]=pirelab.getVectorTypeInfo(hOutSignals(1));
        if~idxOnly
            hFractionOutSignals=hdlhandles(numTables,1);
            [~,outTypeFrac]=pirelab.getVectorTypeInfo(hOutSignals(2));
        end
        for ii=1:numTables
            hIndexOutSignals(ii)=hN.addSignal(outTypeIdx,sprintf('%s_index%d',compName,ii));
            if idxOnly
                hOutSigs=hIndexOutSignals(ii);
            else
                hFractionOutSignals(ii)=hN.addSignal(outTypeFrac,sprintf('%s_fraction%d',compName,ii));
                hOutSigs=[hIndexOutSignals(ii);hFractionOutSignals(ii)];
            end
            cgirComp=hN.addComponent2(...
            'kind','cgireml',...
            'Name',compName,...
            'InputSignals',hInputDemux.PirOutputSignals(ii),...
            'OutputSignals',hOutSigs,...
            'EMLFileName','hdleml_prelookup',...
            'EMLParams',{bp_data,bpType,kType,fType,idxOnly,powerof2},...
            'EMLFlag_ParamsFollowInputs',false,...
            'EMLFlag_RunLoopUnrolling',false,...
            'EMLFlag_TreatInputIntsAsFixpt',true);
        end
        hMux=pirelab.getMuxComp(hN,hIndexOutSignals,hOutSignals(1),sprintf('%s_idxconcat',compName));
        if~idxOnly
            hMux=pirelab.getMuxComp(hN,hFractionOutSignals,hOutSignals(2),sprintf('%s_fracconcat',compName));
        end
    else
        cgirComp=hN.addComponent2(...
        'kind','cgireml',...
        'Name',compName,...
        'InputSignals',hInSignals,...
        'OutputSignals',hOutSignals,...
        'EMLFileName','hdleml_prelookup',...
        'EMLParams',{bp_data,bpType,kType,fType,idxOnly,powerof2},...
        'EMLFlag_ParamsFollowInputs',false,...
        'EMLFlag_RunLoopUnrolling',false,...
        'EMLFlag_TreatInputIntsAsFixpt',true);
    end
end


