function satComp=getSaturateDynamicComp(hN,hInSignals,hOutSignals,rndMode,satMode,compName)



    if(nargin<6)
        compName='saturateDynamic';
    end

    satComp=hN.addComponent2(...
    'kind','cgireml',...
    'Name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'EMLFileName','hdleml_saturate_dynamic',...
    'EMLParams',{},...
    'EMLFlag_RunLoopUnrolling',true);

end


