function schema






    pkg=findpackage('rptgen');
    pkgRG=findpackage('rptgen');

    h=schema.class(pkg,'cfr_section',pkgRG.findclass('rpt_section'));


    rptgen.prop(h,'SectionTitle',...
    'ustring',getString(message('rptgen:r_cfr_section:sectionTitleLabel')),getString(message('rptgen:r_cfr_section:titleLabel')));


    rptgen.prop(h,'isTitleFromSubComponent','bool',false,...
    getString(message('rptgen:r_cfr_section:takeFromFirstLabel')));

    styleMap=containers.Map(...
    {
    'book',...
    'chapter',...
    'simplesect',...
    'sect1',...
    'sect2',...
    'sect3',...
    'sect4',...
    'sect5',...
    'none',...
'ignore'
    },...
    {
    'rgTitlePageTitle',...
    'rgChapterTitle',...
    'rgSectTitle',...
    'rgSect1Title',...
    'rgSect2Title',...
    'rgSect3Title',...
    'rgSect4Title',...
    'rgSect5Title',...
    'none',...
'ignore'
    });

    p=rptgen.prop(h,'HeadingStyleMap','MATLAB array',styleMap);
    p.AccessFlags.Copy='off';
    p.AccessFlags.PublicSet='off';
    p.Visible='off';


    rptgen.makeProp(h,'StyleNameType',{
    'auto',getString(message('rptgen:r_cfr_section:autoLabel'))
    'custom',getString(message('rptgen:r_cfr_section:customLabel'))
    },'auto',getString(message('rptgen:r_cfr_section:styleNameLabel')));


    rptgen.prop(h,'StyleName','ustring');


    rptgen.prop(h,'NumberMode',{
    'auto',getString(message('rptgen:r_cfr_section:autoLabel'))
    'manual',[getString(message('rptgen:r_cfr_section:customLabel')),':']
    },'auto',...
    getString(message('rptgen:r_cfr_section:numberingLabel')));


    rptgen.prop(h,'Number','ustring','1');


    rptgen.makeStaticMethods(h,{},{});
