function data=getAutoGeneratedData(obj,cc,pid)





    data=[];
    cs=cc.getConfigSet;
    names=cc.getProp;
    n=length(names);
    params={};
    for i=1:n
        name=names{i};
        try
            if cs.getPropOwner(name)==cc
                params{end+1}=obj.getData(name);%#ok
            end
        catch
            continue;
        end
    end

    data.cid=obj.getCID(cc);
    data.pid=pid;
    data.params=params;
    data.name=cc.Name;


