function hNewC=lowerCompareToConstant(hN,hC)



    hNewC=pireml.getCompareToValueComp(hN,...
    hC.PirInputSignals,...
    hC.PirOutputSignals,...
    hC.getOpName,...
    hC.getConstant,...
    hC.Name);
end
