function hNewC=lowerLookup(hN,hC)



    hNewC=pireml.getLookupNDComp(...
    hN,...
    hC.PirInputSignals,...
    hC.PirOutputSignals,...
    hC.getTableData,...
    hC.getPowerOf2,...
    hC.getBpType,...
    hC.getOutType,...
    hC.getFractionType,...
    hC.getInterpVal,...
    hC.getBpData,...
    hC.Name);

end
