function hNewC=lowerDTCComp(hN,hC)




    hNewC=pireml.getDTCComp(...
    hN,...
    hC.PirInputSignals,...
    hC.PirOutputSignals,...
    hC.getRoundingMode,...
    hC.getOverflowMode,...
    hC.getConversionMode,...
    hC.Name);

end
