function hNewC=lowerUpSample(hN,hC)




    hNewC=pireml.getUpSampleComp(...
    hN,...
    hC.PirInputSignals,...
    hC.PirOutputSignals,...
    hC.getFactor,...
    hC.getOffset,...
    hC.getInitialValue,...
    hC.Name,...
    '',...
    hC.SimulinkHandle);

end
