function hNewC=lowerIntegerDelayEnabledResettable(hN,hC)



    resetSignals=hC.getInputSignals('external_sync_reset');
    enableSignals=hC.getInputSignals('external_enable');


    hNewC=pireml.getIntDelayEnabledResettableComp(...
    hN,...
    hC.PirInputSignals(1),...
    hC.PirOutputSignals,...
    hC.getNumDelays,...
    hC.Name,...
    hC.getInitialValue,...
    hC.getResetNone,...
    enableSignals,...
    resetSignals);
end

