function hNewC=lowerBitSlice(hN,hC)





    hInSignals=hC.PirInputSignals;
    inSignalType=hInSignals(1).Type.BaseType;
    if inSignalType.WordLength>128
        hNewC=pircore.getBitSliceComp(hN,...
        hC.PirInputSignals,...
        hC.PirOutputSignals,...
        hC.getLeftIndex,...
        hC.getRightIndex,...
        hC.Name);
    else
        hNewC=pireml.getBitSliceComp(hN,...
        hC.PirInputSignals,...
        hC.PirOutputSignals,...
        hC.getLeftIndex,...
        hC.getRightIndex,...
        hC.Name);
    end

end
