function v=validBlockMask(~,slbh)





    v=true;
    if slbh<0
        return;
    end
    blkFunction=get_param(slbh,'Function');
    invalidFunctions={...
    'tan',...
    'asin',...
    'acos',...
    'atan',...
    'sinh',...
    'cosh',...
    'tanh',...
    'asinh',...
    'acosh',...
    'atanh',...
    };

    validFunctions={...
    'sin',...
    'cos',...
    'sincos',...
    'cos + jsin',...
    'atan2',...
    };

    switch blkFunction
    case invalidFunctions
        v=false;

    case validFunctions
        approxMethod=get_param(slbh,'ApproximationMethod');
        if(strcmp(approxMethod,'None'))
            v=false;
        end
    end


