function blocks=getAllBlocks(system)



    blocks=find_system(system,...
    'FollowLinks','off',...
    'MatchFilter',@Simulink.match.internal.filterOutInactiveVariantSubsystemChoices,...
    'LookUnderMasks','all',...
    'Type','Block');
end
