function dlgStruct=getDialogSchema(this,name)




    listenPWD(this,true);

    legalFile=exist(this.SrcFileName,'file');

    if this.RuntimeConverting
        descMsg=getString(message('rptgen:RptgenML_FileConverter:convertingFile'));
    elseif~legalFile
        descMsg=getString(message('rptgen:RptgenML_FileConverter:selectSourceFile'));
    else
        try
            fid=fopen(this.SrcFileName,'r');
            descMsg=fread(fid,512,'char*1=>char')';
            fclose(fid);
        catch
            descMsg=getString(message('rptgen:RptgenML_FileConverter:cannotRead'));
        end
    end

    dbFormat=this.getFormat('db');
    oldDocbookVisibility=dbFormat.getVisible;
    try
        dbFormat.setVisible(false);
        wFormat=this.dlgFormatWidget(...
        'DialogRefresh',true,...
        'Enabled',~this.RuntimeConverting);
    end
    dbFormat.setVisible(oldDocbookVisibility);


    coItems={...
    this.dlgWidget('SrcFileName',...
    'ColSpan',[1,2],...
    'RowSpan',[1,1],...
    'DialogRefresh',true,...
    'Enabled',~this.RuntimeConverting)
    struct('Type','pushbutton',...
    'Name',getString(message('rptgen:RptgenML_FileConverter:browse')),...
    'ColSpan',[3,3],...
    'RowSpan',[1,1],...
    'ToolTip',getString(message('rptgen:RptgenML_FileConverter:selectDBXmlSource')),...
    'ObjectMethod','cbkSelectFile',...
    'Enabled',~this.RuntimeConverting)
    this.dlgSet(wFormat,...
    'ColSpan',[1,3],...
    'RowSpan',[2,2]);
    this.dlgStylesheetWidget(...
    'ColSpan',[1,2],...
    'RowSpan',[3,3],...
    'Name',getString(message('rptgen:RptgenML_FileConverter:stylesheet')),...
    'Enabled',~this.RuntimeConverting)
    struct('Type','pushbutton',...
    'Name',getString(message('rptgen:RptgenML_FileConverter:edit')),...
    'ColSpan',[3,3],...
    'RowSpan',[3,3],...
    'ToolTip',getString(message('rptgen:RptgenML_FileConverter:openInEditor')),...
    'MatlabMethod','rpteditstyle',...
    'MatlabArgs',{{this.getStylesheetID}},...
    'Enabled',~this.RuntimeConverting)
    this.dlgWidget('View',...
    'ColSpan',[1,3],...
    'RowSpan',[4,4],...
    'Enabled',~this.RuntimeConverting)
    struct('Type','pushbutton',...
    'Name',getString(message('rptgen:RptgenML_FileConverter:convertFile')),...
    'ColSpan',[1,1],...
    'RowSpan',[5,5],...
    'ToolTip',getString(message('rptgen:RptgenML_FileConverter:convertedSelected')),...
    'ObjectMethod','cbkConvert',...
    'FilePath','toolbox/rptgen/resources/Convert.png',...
    'Enabled',~this.RuntimeConverting&&legalFile)
    this.dlgWidget('RuntimeConverting',...
    'ColSpan',[1,1],...
    'RowSpan',[6,6],...
    'DialogRefresh',true,...
    'Visible',0)
    };



    grpPackageType=rpt_xml.getPackageTypeSchema();
    grpPackageType.ColSpan=[1,4];
    grpPackageType.RowSpan=[2,2];
    grpPackageType.Enabled=strcmp(this.Format,'dom-htmx');

    coItems=[coItems(1:2);...
    {grpPackageType};...
    coItems(3:end)];

    for i=4:length(coItems)
        coItems{i}.RowSpan(1)=coItems{i}.RowSpan(1)+1;
        coItems{i}.RowSpan(2)=coItems{i}.RowSpan(2)+1;
    end


    wConversionOptions=this.dlgContainer(coItems,...
    getString(message('rptgen:RptgenML_FileConverter:conversionOptions')),...
    'ColSpan',[1,1],...
    'RowSpan',[2,2],...
    'LayoutGrid',[6,3],'ColStretch',[0,1,0]);

    wConversionOptions.LayoutGrid(1)=wConversionOptions.LayoutGrid(1)+1;

    dlgStruct=this.dlgMain(name,{
    this.dlgText(getString(message('rptgen:RptgenML_FileConverter:description')),...
    'WordWrap',true,...
    'ColSpan',[1,1],...
    'RowSpan',[1,1])
wConversionOptions
    this.dlgContainer({
    this.dlgText(descMsg,'WordWrap',true)
    },getString(message('rptgen:RptgenML_FileConverter:filePreview')),...
    'ColSpan',[1,1],...
    'RowSpan',[3,3])
    },...
    'LayoutGrid',[3,1],...
    'RowStretch',[0,0,1],...
    'CloseCallback','listenPWD',...
    'CloseArgs',{this,false},...
    'DialogTitle',getString(message('rptgen:RptgenML_FileConverter:convertSourceFile')));