



function createMarkerFile(obj)
    import matlab.io.xml.dom.*

    xmlDoc=Document(obj.mMarkerNodeName_Root);
    xmlDoc.appendChild(xmlDoc.createComment('DO NOT EDIT THIS FILE'));
    writeToFile(DOMWriter,xmlDoc,obj.mMarkerFileNameFull);
end
