function[status,reason,buildStatusMgr]=buildTopRefModel(...
    iMdl,mdlRefNames,secTopLvlMdlRefNames,parMdlRefs,orderedMdlRefs,...
    iTopTflChecksum,...
    iBuildArgs,verbose,mdlrefUpdateCtrl,thisMdlUpdateCtrl,runningForExternalMode,targetType,...
    mdlRefSimModeMap,buildStatusMgr,libsToClose,updateMsg,...
    status,reason)





    updateTopMdlRefTargetInSerial=true;

    [status,reason,buildStatusMgr]=...
    coder.serial.hBuildModelRefs(...
    iMdl,mdlRefNames,secTopLvlMdlRefNames,parMdlRefs,orderedMdlRefs,...
    iTopTflChecksum,updateTopMdlRefTargetInSerial,...
    iBuildArgs,verbose,mdlrefUpdateCtrl,thisMdlUpdateCtrl,runningForExternalMode,targetType,...
    mdlRefSimModeMap,buildStatusMgr,libsToClose,updateMsg,...
    status,reason);
end
