function m=createAngleLimCursor(p,idx)



    detailDataFcn=@internal.polariAngleMarker.angleLimCursorDataStrFcn;
    detailTypeFcn=@internal.polariAngleMarker.angleLimCursorDataStrFcn;
    detailIndexFcn=@internal.polariAngleMarker.angleLimCursorDataStrFcn;


    localAng=p.pAngleLim(idx);

    if idx==1
        z=0.41;
    else
        z=0.415;
    end






    m=internal.polariAngleMarker(p,...
    'DataDot',false,...
    'DataDotLegend',false,...
    'Type','a',...
    'EdgeColor','w',...
    'FaceAlpha',1,...
    'FaceColor','k',...
    'Index',idx,...
    'Length',0.2,...
    'LocalAngle',localAng,...
    'Tip',0.125,...
    'TipOverlap',true,...
    'DetailWidth',.4,...
    'WidthMode','auto',...
    'Width',0.125,...
    'OriginLineColorMode','auto',...
    'DetailDataStr',detailDataFcn,...
    'DetailIndexStr',detailIndexFcn,...
    'DetailTypeStr',detailTypeFcn,...
    'StringDirection','width',...
    'ShowDetail',1,...
    'Z',z);


    m.ContextMenuFcn=@(h,~)updateAngleLimCursorContextMenu(p,h,m);
