



classdef Common<handle


    properties(Constant)

        DTNames={...
        'double','single',...
        'int8','uint8',...
        'int16','uint16',...
        'int32','uint32',...
        'boolean','void'...
        }


        Enums={...
        'SS_DOUBLE','SS_SINGLE',...
        'SS_INT8','SS_UINT8',...
        'SS_INT16','SS_UINT16',...
        'SS_INT32','SS_UINT32',...
        'SS_BOOLEAN','SS_POINTER'...
        }


        NativeTypes={...
        'real_T','real32_T',...
        'int8_T','uint8_T',...
        'int16_T','uint16_T',...
        'int32_T','uint32_T',...
        'boolean_T','void'...
        }

        WordLengths=[...
        64,32,...
        8,8,...
        16,16,...
        32,32,...
        8,-1...
        ]


        NumBuiltinDataTypes uint32=numel(legacycode.lct.types.Common.NativeTypes)


        NumSLBuiltInDataTypes uint32=legacycode.lct.types.Common.NumBuiltinDataTypes-1
    end

end
