classdef CabOverTractor




    properties(Constant=true)
        FrontBumper=struct(...
        'translation',single([5.24,0,0.69]),...
        'rotation',single([0,0,0]),...
        'scale',single([1,1,1]));
        RightMirror=struct(...
        'translation',single([4.55,1.60,1.98]),...
        'rotation',single([0,-pi/2,0]),...
        'scale',single([1,1,1]));
        LeftMirror=struct(...
        'translation',single([4.55,-1.60,1.98]),...
        'rotation',single([0,-pi/2,0]),...
        'scale',single([1,1,1]));
        RearviewMirror=struct(...
        'translation',single([4.80,0,2.73]),...
        'rotation',single([0,0,0]),...
        'scale',single([1,1,1]));
        RearCenter=struct(...
        'translation',single([2.56,0,3.72]),...
        'rotation',single([0,deg2rad(-40),pi]),...
        'scale',single([1,1,1]));
    end

end