function dnnfpgaSharedRenderDebugableRAM(gcb,pipelineLatency,debugFromTag,debugGotoTag)



    if(isempty(pipelineLatency))
        return;
    end
    if(strcmpi(get_param([gcb,'/DebugGoto'],'blocktype'),'goto'))
        set_param([gcb,'/DebugFrom'],'GotoTag',debugFromTag);
        set_param([gcb,'/DebugGoto'],'GotoTag',debugGotoTag);
    end

    pipelineDelays={...
    'Delay2',...
    'Delay3',...
    'Delay4',...
    'Delay5',...
    'Delay6',...
    'Delay7',...
    'Delay8',...
    'Delay9',...
    'Delay10',...
    'Delay11',...
    'Delay12',...
    'Delay13',...
    };
    switch pipelineLatency
    case{0}
        for i=1:length(pipelineDelays)
            set_param([gcb,'/',pipelineDelays{i}],'DelayLength','0');
        end
    case{4}
        for i=1:length(pipelineDelays)
            set_param([gcb,'/',pipelineDelays{i}],'DelayLength','1');
        end
    otherwise
        assert(false);
    end
end

