function dnnfpgaDatamemlibRenderDataMem(gcb,pipelineLatency)



    if(isempty(pipelineLatency))
        return;
    end

    pipelineDelays={...
    'Pipeline',...
    'Pipeline1',...
    'Pipeline2',...
    'Pipeline3',...
    'Pipeline4',...
    'Pipeline5',...
    'Pipeline6',...
    'Pipeline7',...
    'Pipeline8',...
    'Pipeline9',...
    'Pipeline10',...
    'Pipeline11',...
    'Pipeline12',...
    'Pipeline13',...
    'Pipeline14',...
    'Pipeline15',...
    'Pipeline16',...
    'Pipeline17',...
    'Pipeline18',...
    'Pipeline19',...
    'Pipeline20',...
    'Pipeline21',...
    'Pipeline22',...
    'Pipeline23',...
    'Pipeline24',...
    'Pipeline25',...
    };
    switch pipelineLatency
    case{0}
        for i=1:length(pipelineDelays)
            set_param([gcb,'/',pipelineDelays{i}],'DelayLength','0');
        end
    case{4}
        for i=1:length(pipelineDelays)
            set_param([gcb,'/',pipelineDelays{i}],'DelayLength','1');
        end
    otherwise
        assert(false);
    end
end

