function elabModViaCast(~,hN,inSignal,outSignal,blkInfo)





    fid=fopen(fullfile(matlabroot,'toolbox','fixedpoint','embeddedlibhdl',...
    '+emblibhdl','@ModByConstant','cgireml','ModViaCast.m'));
    h=onCleanup(@()fclose(fid));
    fcnBody=fread(fid,inf,'char=>char');
    mulRnd=hN.addComponent2(...
    'kind','cgireml',...
    'Name','modviacast',...
    'InputSignals',inSignal,...
    'OutputSignals',outSignal,...
    'EMLFileName','ModViaCast',...
    'EMLFileBody',fcnBody,...
    'EMLParams',{blkInfo.typesTable.outputPrototype},...
    'ExternalSynchronousResetSignal','',...
    'EMLFlag_TreatInputIntsAsFixpt',true,...
    'EMLFlag_SaturateOnIntOverflow',false,...
    'BlockComment','cgireml component');
    mulRnd.runConcurrencyMaximizer(0);
    mulRnd.resetNone(false);

end
