function makeSubNet(~,hN,inSignal,outSignal,blkInfo)














    typesTable=blkInfo.typesTable;
    fid=fopen(fullfile(matlabroot,'toolbox','fixedpoint','embeddedlibhdl',...
    '+emblibhdl','@ModByConstant','cgireml','Sub.m'));
    h=onCleanup(@()fclose(fid));
    fcnBody=fread(fid,inf,'char=>char');
    mulRnd=hN.addComponent2(...
    'kind','cgireml',...
    'Name','Sub',...
    'InputSignals',inSignal,...
    'OutputSignals',outSignal,...
    'EMLFileName','Sub',...
    'EMLFileBody',fcnBody,...
    'EMLParams',{typesTable.subtractionType,typesTable.outputPrototype},...
    'ExternalSynchronousResetSignal','',...
    'EMLFlag_TreatInputIntsAsFixpt',true,...
    'EMLFlag_SaturateOnIntOverflow',false,...
    'BlockComment','cgireml component');
    mulRnd.runConcurrencyMaximizer(0);
    mulRnd.resetNone(true);

end
