function inArgs = report( InfoObj, filePath, NV )

















































































R36
InfoObj;
filePath( 1, : )char;

NV.Author( 1, : )char = '';

NV.Title( 1, : )char = 'Report Generated by Design Evolutions';


NV.GenerateEvolutionTreeReport( 1, 1 )logical = true;
NV.GenerateEvolutionReport( 1, 1 )logical = true;
NV.GenerateArtifactFileReport( 1, 1 )logical = true;

NV.IncludeEvolutionTreeNameHeading( 1, 1 )logical = true;
NV.IncludeEvolutionTreeTopInfoTable( 1, 1 )logical = true;
NV.IncludeEvolutionTreePlot( 1, 1 )logical = true;
NV.IncludeEvolutionTreeEvolutionHyperlinks( 1, 1 )logical = true;
NV.IncludeEvolutionTreeDetailsTable( 1, 1 )logical = true;

NV.IncludeEvolutionNameHeading( 1, 1 )logical = true;
NV.IncludeEvolutionFileTable( 1, 1 )logical = true;
NV.IncludeEvolutionParent( 1, 1 )logical = true;
NV.IncludeEvolutionChildren( 1, 1 )logical = true;
NV.IncludeEvolutionDetailsTable( 1, 1 )logical = true;
NV.IncludeEvolutionArtifactHyperlinks( 1, 1 )logical = true;
NV.IncludeEvolutionBackToEvolutionTreeHyperlink( 1, 1 )logical = true;

NV.IncludeArtifactFileNameHeading( 1, 1 )logical = true;
NV.IncludeArtifactFileWebView( 1, 1 )logical = true;
NV.IncludeArtifactFileBackToEvolutionHyperlinks( 1, 1 )logical = true;
NV.IncludeArtifactFileBackToEvolutionTreeHyperlink( 1, 1 )logical = true;

NV.LaunchReport( 1, 1 )logical = true;

end 

inArgs.Content = InfoObj;
inArgs.OutputFile = filePath;

inArgs.AuthorName = NV.Author;
inArgs.ReportTitle = NV.Title;

inArgs.GenerateEvolutionTreeReport = NV.GenerateEvolutionTreeReport;
inArgs.GenerateEvolutionReport = NV.GenerateEvolutionReport;
inArgs.GenerateArtifactFileReport = NV.GenerateArtifactFileReport;

inArgs.IncludeEvolutionTreeNameHeading = NV.IncludeEvolutionTreeNameHeading;
inArgs.IncludeEvolutionTreeTopInfoTable = NV.IncludeEvolutionTreeTopInfoTable;
inArgs.IncludeEvolutionTreePlot = NV.IncludeEvolutionTreePlot;
inArgs.IncludeEvolutionTreeEvolutionHyperlinks = NV.IncludeEvolutionTreeEvolutionHyperlinks;
inArgs.IncludeEvolutionTreeDetailsTable = NV.IncludeEvolutionTreeDetailsTable;

inArgs.IncludeEvolutionNameHeading = NV.IncludeEvolutionNameHeading;
inArgs.IncludeEvolutionFileTable = NV.IncludeEvolutionFileTable;
inArgs.IncludeEvolutionParent = NV.IncludeEvolutionParent;
inArgs.IncludeEvolutionChildren = NV.IncludeEvolutionChildren;
inArgs.IncludeEvolutionDetailsTable = NV.IncludeEvolutionDetailsTable;
inArgs.IncludeEvolutionArtifactHyperlinks = NV.IncludeEvolutionArtifactHyperlinks;
inArgs.IncludeEvolutionBackToEvolutionTreeHyperlink = NV.IncludeEvolutionBackToEvolutionTreeHyperlink;

inArgs.IncludeArtifactFileNameHeading = NV.IncludeArtifactFileNameHeading;
inArgs.IncludeArtifactFileWebView = NV.IncludeArtifactFileWebView;
inArgs.IncludeArtifactFileBackToEvolutionHyperlinks = NV.IncludeArtifactFileBackToEvolutionHyperlinks;
inArgs.IncludeArtifactFileBackToEvolutionTreeHyperlink = NV.IncludeArtifactFileBackToEvolutionTreeHyperlink;

inArgs.LaunchReport = NV.LaunchReport;
evolutions.internal.report.createDesignEvolutionReport( inArgs );
end 



% Decoded using De-pcode utility v1.2 from file /tmp/tmpEfUNaf.p.
% Please follow local copyright laws when handling this file.

