function usprops=getunsupportedprops(this)






    usprops={'ClockEnableOutputPort',...
    'ClockInputs',...
    'CoefficientSource',...
    'DALUTPartition',...
    'DARadix',...
    'FracDelayPort',...
    'ReuseAccum',...
    'SerialPartition',...
    'AddPipelineRegisters',...
    'MultiplierInputPipeline',...
    'MultiplierOutputPipeline',...
    };


