classdef Rx_Decision_Time<serdes.internal.ibisami.ami.parameter.ReservedParameter

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=Rx_Decision_Time(varargin)
            param.NodeName="Rx_Decision_Time";
            param.Usage=serdes.internal.ibisami.ami.usage.Out;
            param.Type=serdes.internal.ibisami.ami.type.Float;
            param.Format=serdes.internal.ibisami.ami.format.Value({0.0});
            param.Description=...
            "This model outputs an Init sampling time in seconds to be used by the EDA tool.";
            param.AllowedUsages=["Out"];%#ok<*NBRAK>
            param.AllowedTypes=["Float","UI"];
            param.DirectionTx=false;
            param.AllowedFormats=["Value"];
            param.EarliestRequiredVersion=7.1;
            param.IncludeInInit=true;
            param.CreateMWSVariables=true;
            param.ShowInDlg=true;
        end
    end
end

