function countNet=elabCountBank(~,topNet,~,sigInfo,dataRate)







    booleanT=pir_boolean_t();
    accCountT=sigInfo.accCountT;

    inPortNames={'lineReset','frameStart','processPixel',...
    'lvlTwoEn','lvlThreeEn','lvlFourEn','endFlag'};

    inPortRates=[dataRate,dataRate,dataRate,dataRate...
    ,dataRate,dataRate,dataRate];

    inPortTypes=[booleanT,booleanT,booleanT,booleanT,booleanT,booleanT,booleanT];

    outPortNames={'lvlOneCount','lvlTwoCount','lvlThreeCount','lvlFourCount'};

    outPortTypes=[accCountT,accCountT,accCountT,accCountT];

    countNet=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','counterBank',...
    'InportNames',inPortNames,...
    'InportTypes',inPortTypes,...
    'InportRates',inPortRates,...
    'OutportNames',outPortNames,...
    'OutportTypes',outPortTypes...
    );

    countNet.addComment('Counter Bank - Store the lvlOne, lvlTwo, lvlThree, lvlFour Count');

    countBankIn=countNet.PirInputSignals;
    countBankOut=countNet.PirOutputSignals;

    lineReset=countBankIn(1);
    frameStart=countBankIn(2);
    processPixel=countBankIn(3);
    lvlTwoEn=countBankIn(4);
    lvlThreeEn=countBankIn(5);
    lvlFourEn=countBankIn(6);
    endFlag=countBankIn(7);

    lvlOneCountReset=countNet.addSignal2('Type',booleanT,'Name','lvlOneCountReset');
    rsC=pirelab.getBitwiseOpComp(countNet,[lineReset,endFlag],lvlOneCountReset,'OR');
    rsC.addComment('Reset On Multiple hStart OR at Frame End');



    C1=pirelab.getCounterComp(countNet,...
    [lvlOneCountReset,processPixel],...
    countBankOut(1),...
    'Free Running',...
    0,...
    1,...
    63,...
    true,...
    false,...
    true,...
    false,...
    'lvlOneCount');
    C1.addComment('lvlOne Count');


    C2=pirelab.getCounterComp(countNet,...
    [frameStart,lvlTwoEn],...
    countBankOut(2),...
    'Free Running',...
    0,...
    1,...
    63,...
    true,...
    false,...
    true,...
    false,...
    'lvlTwoCount');
    C2.addComment('lvlTwo Count');


    C3=pirelab.getCounterComp(countNet,...
    [frameStart,lvlThreeEn],...
    countBankOut(3),...
    'Free Running',...
    0,...
    1,...
    63,...
    true,...
    false,...
    true,...
    false,...
    'lvlThreeCount');
    C3.addComment('lvlThree Count');


    C3=pirelab.getCounterComp(countNet,...
    [frameStart,lvlFourEn],...
    countBankOut(4),...
    'Free Running',...
    0,...
    1,...
    63,...
    true,...
    false,...
    true,...
    false,...
    'lvlFourCount');
    C3.addComment('lvlFour Count');







