classdef(ConstructOnLoad)MWAJTAG<eda.internal.component.BlackBox
    properties
        CopyHDLFiles;
    end
    methods
        function this=MWAJTAG(varargin)
            this.setGenerics(varargin);
            props={
            'CLK125',...
            'TxEnable',...
            'TxData',...
            'TxDataValid',...
            'TxEOP',...
            'TxDataLength',...
            'TxReady',...
            'RxData',...
            'RxDataValid',...
            'RxEOP',...
            'RxCRCOK',...
            'RxCRCBad',...
            'TxReset',...
            'RxReset',...
            };
            for m=1:numel(props)
                addprop(this,props{m});
            end
            this.CLK125=eda.internal.component.ClockPort;
            this.TxData=eda.internal.component.Inport('FiType','std8');
            this.TxDataValid=eda.internal.component.Inport('FiType','boolean');
            this.TxEOP=eda.internal.component.Inport('FiType','boolean');
            this.TxDataLength=eda.internal.component.Inport('FiType','std13');
            this.TxReady=eda.internal.component.Outport('FiType','boolean');
            this.RxData=eda.internal.component.Outport('FiType','std8');
            this.RxDataValid=eda.internal.component.Outport('FiType','boolean');
            this.RxEOP=eda.internal.component.Outport('FiType','boolean');
            this.RxCRCOK=eda.internal.component.Outport('FiType','boolean');
            this.RxCRCBad=eda.internal.component.Outport('FiType','boolean');

            this.HDLFileDir={fullfile(matlabroot,'toolbox','shared','eda','fil',...
            '+eda','+internal','+component','@MWAJTAG')};
            this.HDLFiles={'MWAJTAG.vhd'};
        end

    end

end

