function type=getNFPBlockTypeBySlType(slOpType)





    typeMap=containers.Map({'Sum','Product','Abs','UnaryMinus',...
    'MinMax','sqrt','rSqrt','Recip','DataTypeConversion',...
    '==','~=','<','<=',...
    '>=','>','isInf','isNan','isFinite',...
    'log','reciprocal','exp','10^u'...
    ,'sin','cos','atan','atan2',...
    'acos','asin','div',...
    'fix','Reciprocal','log','log10','mod',...
    'rem','round','hypot'...
    ,'Signum','sincos','asin','acos','atan2','asinh','acosh','atanh','sin','cos','tan','sinh','cosh','tanh',...
    'PreLookup','LookupNDDirect','Lookup_n-D','GainPow2','pow'...
    },...
    {'AddSub','Mul','Abs','Uminus',...
    'MinMax','sqrt','Rsqrt','Reciprocal','Convert',...
    'Relop','Relop','Relop','Relop',...
    'Relop','Relop','Relop','Relop','Relop',...
    'Log','Recip','Exp','Pow10'...
    ,'Sin','Cos','ATan','ATan2',...
    'ACos','ASin','Div',...
    'Fix','HDLRecip','Log','Log10','Mod',...
    'Rem','Rounding','Hypot'...
    ,'Signum','SinCos','Asin','Acos','Atan2','Asinh','Acosh','Atanh','Sin','Cos','Tan','Sinh','Cosh','Tanh',...
    'PreLookup','LookupNDDirect','Lookup_n-D','GainPow2','Pow'...
    });

    try
        type=typeMap(slOpType);
    catch
        type='';
    end
end
