classdef DllID<serdes.internal.ibisami.ami.parameter.DataManagementReservedParameter

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=DllID()
            param.NodeName="DLL_ID";
            param.Usage=serdes.internal.ibisami.ami.usage.In;
            param.Type=serdes.internal.ibisami.ami.type.String;
            param.Format=serdes.internal.ibisami.ami.format.Value("To_be_set_by_EDA_Tool");
            param.Description=...
            "The EDA tool is responsible for recognizing this parameter name and replacing the value declared in the .ami file with a string that contains a unique alphanumeric identifier.";
        end
    end
end

