function displayError(~,me,varargin)

    msgStr=me.message;
    titleStr=getString(message('SDI:sdi:mgError'));
    okStr=getString(message('SDI:sdi:OKShortcut'));
    Simulink.sdi.internal.controllers.SessionSaveLoad.displayMsgBox(...
    'sdi',...
    titleStr,...
    msgStr,...
    {okStr},...
    0,...
    -1,...
    [],...
    varargin{:});
end