function html=insertCheckboxHtml(system,target,curr,idx,candidate,freeze)



    mdladvObj=Simulink.ModelAdvisor.getModelAdvisor(system);
    m2m_obj=mdladvObj.UserData;
    if curr
        checked='checked="true"';
    else
        checked='';
    end

    if strcmpi(target,'sysclone')
        callback_fcn='m2m_toggle_sysclone(';
    elseif strcmpi(target,'constant')
        callback_fcn='m2m_toggle_const(';
    elseif strcmpi(target,'dsm')
        callback_fcn='m2m_toggle_dsm(';
    else
        callback_fcn='m2m_toggle_operation(';
    end

    if strcmpi(target,'dsm')
        callback_fcn=[callback_fcn,'''',system,''', ''',num2str(candidate),''','];
    else
        callback_fcn=[callback_fcn,'''',system,''', ''',candidate,''','];
    end

    html=[
    '<html>',...
    '<body>',...
    '<style>',...
    '#HiddenLink',...
    '{display:none;}',...
    '</style>',...
    '<script>',...
    'function myCallbackFunction',...
    num2str(idx),...
    '(checkbox)',...
    '{',...
    'var hyperlink = document.getElementById("HiddenLink");',...
    'var href = hyperlink.getAttribute("href");',...
    'if (checkbox.checked)',...
    '{href = "matlab: ',...
    callback_fcn,...
    'true)" ; ',...
    '}',...
    'else',...
    '{href = "matlab: ',...
    callback_fcn,...
    'false)" ; ',...
    '}',...
    'hyperlink.setAttribute("href", href);',...
    'hyperlink.click();',...
    '}',...
    '</script>',...
    '<a id="HiddenLink" href=""></a>',...
    '<label>',...
'</label>'...
    ,'<input type="checkbox" id="',...
    '''',target,'''',num2str(idx),...
    ];
    if freeze
        html=[html,...
        '" onclick="return false" ',...
        checked,...
        '/><br/>',...
        '</body>',...
'</html>'
        ];
    else
        html=[html,...
        '" onclick="myCallbackFunction',...
        num2str(idx),...
        '(this)" ',...
        checked,...
        '/><br/>',...
        '</body>',...
'</html>'
        ];
    end
end
