function writeHDLFile(this)





    dir=this.HDLFileDir;
    if isempty(dir)

        dir='./rtl';
        hdlsetparameter('codegendir',dir)
    end

    rtlFile=this.openFile2W(dir,'HDL');
    HDL=this.HDL;

    fprintf(rtlFile,[HDL.entity_comment,...
    HDL.entity_library,...
    HDL.entity_package,...
    HDL.entity_decl,...
    HDL.entity_generic,...
    HDL.entity_ports,...
    HDL.entity_portdecls,...
    HDL.entity_end,...
    HDL.arch_comment,...
    HDL.arch_decl,...
    HDL.arch_component_decl,...
    HDL.arch_component_config,...
    HDL.arch_functions,...
    HDL.arch_typedefs,...
    HDL.arch_constants,...
    HDL.arch_signals,...
    HDL.arch_begin,...
    HDL.arch_body_component_instances,...
    HDL.arch_body_blocks,...
    HDL.arch_body_output_assignments,...
    HDL.arch_end]);


    if rtlFile>0
        fclose(rtlFile);
    end
end
