function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CxpDaUBhVPzNFuYquCYrmTClqRahd0tlcJlRea7X73Q9YZ/+i+Dx4+rVCq'...
        ,'XDHXjxIEvD6PqrtA7bgRzRqafy5kKONqPRiOsLt4/7PP5tc0yiVaCN1yg20f'...
        ,'S09OKVMeN5XGgI/215hzvaLPqyMM4tAe33sc5gpYFU7ZVhXinTiyHvoJfiSZ'...
        ,'uFkAERiCNoZuP8W8fCqxrt1+SnFdFCCMkdEc4Y1aBsLulvCI4kimXduibgo2'...
        ,'hzvxTsh3Hs0aHkxXw/hMCgR5LhTGjwfw/VKlFGdBk7agiwzoqJYptUYepvU='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end