function dlgStruct=loop_getDialogSchema(this,name)




    if~builtin('license','checkout','SIMULINK_Report_Gen')
        dlgStruct=this.buildErrorMessage('panel',true);
        return;

    end

    dlgStruct={
    this.dlgContainer({
    this.dlgWidget('legibleFontSize',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1])
    this.dlgWidget('SkipAutogenerated',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1])
    RptgenML.twoColumnTable(this,'SFFilterTerms','isSFFilterList',...
    'RowSpan',[3,3],...
    'ColSpan',[1,1])
    },getString(message('RptgenSL:rsf_csf_hier_loop:loopOptionsLabel')),...
    'LayoutGrid',[3,1],'RowStretch',[0,0,1]);
    };
