function currState=loop_saveState(h)




    adSF=rptgen_sf.appdata_sf;

    currState={'CurrentMachine',adSF.CurrentMachine,...
    'CurrentChart',adSF.CurrentChart,...
    'CurrentState',adSF.CurrentState,...
    'CurrentObject',adSF.CurrentObject,...
    'Context',adSF.Context};
