function schema






    pkg=findpackage('rptgen_sf');
    pkgRG=findpackage('rptgen');

    h=schema.class(pkg,'csf_hier_loop',pkgRG.findclass('rpt_looper'));


    p=rptgen.prop(h,'legibleFontSize','double',8,...
    getString(message('RptgenSL:rsf_csf_hier_loop:minLegibleFontSizeLabel')),'SIMULINK_Report_Gen');


    p=rptgen.prop(h,'SkipAutogenerated','bool',true,...
    getString(message('RptgenSL:rsf_csf_hier_loop:skipAutoGeneratedChartsLabel')),'SIMULINK_Report_Gen');


    p=rptgen.prop(h,'isSFFilterList','bool',false,...
    getString(message('RptgenSL:rsf_csf_hier_loop:searchStateflowLabel')),'SIMULINK_Report_Gen');


    p=rptgen.prop(h,'SFFilterTerms','MATLAB array',{'Tag','MyTag'},...
    '','SIMULINK_Report_Gen');
    p.Visible='off';




    rptgen.makeStaticMethods(h,{
    },{
'loop_getContextString'
'loop_getLoopObjects'
'loop_getObjectType'
'loop_getPropSrc'
'loop_restoreState'
'loop_saveState'
'loop_setState'
    });
