function props=getCommonJobPropsForJobRecreation()




    props={'AdditionalPaths',...
    'AttachedFiles',...
    'AutoAttachFiles',...
    'AutoAddClientPath',...
    'EnvironmentVariables',...
    'JobData',...
    'Name',...
    'Tag',...
    'UserData'};
end
