function [ callbacks, prompts, tags ] = getCallbacks( skipRuntimeCallbacks )




R36
skipRuntimeCallbacks( 1, 1 )logical = false
end 

callbacks = {  ...
'PreLoadFcn',  ...
'PostLoadFcn',  ...
'PreSaveFcn',  ...
'PostSaveFcn',  ...
'CloseFcn' };
prompts = {  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPreLoadFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPostLoadFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPreSaveFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPostSaveFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptCloseFcn' ) };
tags = {  ...
'Model pre-load function:',  ...
'Model post-load function:',  ...
'Model pre-save function:',  ...
'Model post-save function:',  ...
'Model close function:' };

if skipRuntimeCallbacks
return ;
end 

rtCallbacks = {  ...
'InitFcn',  ...
'PreStartFcn',  ...
'StartFcn',  ...
'PauseFcn',  ...
'ContinueFcn',  ...
'StopFcn' };
rtPrompts = {  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptInitFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPreStartFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptStartFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptPauseFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptContinueFcn' ),  ...
DAStudio.message( 'Simulink:dialog:ModelCallbackPromptStopFcn' ) };
rtTags = {  ...
'Model initialization function:',  ...
'Model Pre-Start function:',  ...
'Simulation start function:',  ...
'Simulation pause function:',  ...
'Simulation continue function:',  ...
'Simulation stop function:' };

if slfeature( 'PreStartCallback' ) < 1

rtCallbacks( 2 ) = [  ];
rtPrompts( 2 ) = [  ];
rtTags( 2 ) = [  ];
end 

callbacks = [ callbacks( 1:2 ), rtCallbacks, callbacks( 3:end  ) ];
prompts = [ prompts( 1:2 ), rtPrompts, prompts( 3:end  ) ];
tags = [ tags( 1:2 ), rtTags, tags( 3:end  ) ];

end 
% Decoded using De-pcode utility v1.2 from file /tmp/tmpL8shwi.p.
% Please follow local copyright laws when handling this file.

