function selectedBlocks=getSelectedBlocksInSystem(sys)
    selectedBlocks=setdiff(...
    find_system(sys,...
    'LookUnderMasks','all',...
    'FollowLinks','on',...
    'SearchDepth','1',...
    'Selected','on'),...
    sys);
end
