function this=FIRInterpolationDA(block)




    this=hdlfilterblks.FIRInterpolationDA;

    supportedBlocks={...
'dspmlti4/FIR Interpolation'...
    };

    if nargin==0
        block='';
    end

    desc=struct(...
    'ShortListing','FIR Interpolation Distributed Arithmetic Implementation',...
    'HelpText','FIR Interpolation code generation via direct HDL instantiation');

    this.init('SupportedBlocks',supportedBlocks,...
    'Block',block,...
    'ArchitectureNames',{'Distributed Arithmetic (DA)'},...
    'CodeGenMode','instantiation',...
    'Description',desc);
