function pathItems=getPortMapping(~,blkObj,~,outportIdx)








    pathItems={};
    if~isempty(outportIdx)>0
        originalPathItems={...
        'AreaOutput','Centroid output','Bounding box output','Equiv Diam^2 output','Extent output','Perimeter output','Count output','Label output'};
        isChecked=[...
        strcmp(blkObj.area,'on'),...
        strcmp(blkObj.centroid,'on'),...
        strcmp(blkObj.bBox,'on'),...
        strcmp(blkObj.equivDiameterSq,'on'),...
        strcmp(blkObj.extent,'on'),...
        strcmp(blkObj.perimeter,'on'),...
        strcmp(blkObj.isCount,'on'),...
        strcmp(blkObj.isLabel,'on')];
        checkedPathItems=originalPathItems(isChecked);
        pathItems=checkedPathItems(outportIdx);

    end
end