function[hC,num]=getTargetSpecificInstantiationCompsWithTwoInputs(targetCompInventory,hN,hInSignals,hOutSignals,coregenBlkName)




    [dimlen,~]=pirelab.getVectorTypeInfo(hInSignals(1));
    if dimlen>1
        hC=xilinxtarget.getVectorCoreGenComp(targetCompInventory,hN,hInSignals,hOutSignals,coregenBlkName,@getScalarTargetSpecificCoreGenCompWithTwoInputs);
    else
        hC=getScalarTargetSpecificCoreGenCompWithTwoInputs(targetCompInventory,hN,hInSignals,hOutSignals,coregenBlkName);
    end
    num=dimlen*hN.getNumOfInstances();

    function hC=getScalarTargetSpecificCoreGenCompWithTwoInputs(~,hN,hInSignals,hOutSignals,coregenBlkName)

        hC=pirelab.getInstantiationComp(...
        'Network',hN,...
        'Name',coregenBlkName,...
        'EntityName',coregenBlkName,...
        'InportNames',{'a','b'},...
        'OutportNames',{'result'},...
        'InportSignals',hInSignals,...
        'OutportSignals',hOutSignals,...
        'AddClockPort','on',...
        'ClockInputPort','clk',...
        'AddClockEnablePort','on',...
        'ClockEnableInputPort','ce',...
        'AddResetPort','on',...
        'ResetInputPort','sclr',...
        'InlineConfigurations','off'...
        );
        hC.setTargetIP(true);


