function symDemodPiBy2BPSK=elabPiBy2BPSKSymDemodNet(~,topNet,~,rate,inpWL,inpFL)





    pirTyp2=pir_boolean_t;
    pirTyp5=pir_sfixpt_t(16,-13);
    pirTyp1=pir_sfixpt_t(inpWL,inpFL);
    pirTyp3=pir_sfixpt_t(inpWL+3,inpFL);
    pirTyp8=pir_sfixpt_t(inpWL+16,inpFL-13);
    pirTyp4=pir_sfixpt_t(inpWL+16+1,inpFL-13);
    pirTyp6=pir_ufixpt_t(3,0);
    pirTyp7=pir_unsigned_t(8);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt5=numerictype(0,1,0);
    nt3=numerictype(0,3,0);
    nt4=numerictype(0,8,0);
    nt1=numerictype(1,16,13);
    nt6=numerictype(1,inpWL,-inpFL);
    nt2=numerictype(1,inpWL+3,-inpFL);
    nt7=numerictype(1,inpWL+16,-(inpFL-13));

    inportNamePiBy2BPSK={'dataIn','validIn','resetIn','endIn'};
    controlType=pir_ufixpt_t(1,0);
    inType=pir_complex_t(pir_sfixpt_t(inpWL,inpFL));
    inTypePiBy2BPSK=[inType,controlType,controlType,controlType];
    inDataRatePiBy2BPSK=[rate,rate,rate,rate];

    outportNamePiBy2BPSK={'dataOut','validOut','nonMul8FlagOut'};
    outTypePiBy2BPSK=[pirelab.createPirArrayType(pirTyp3,[8,0]),controlType,controlType];

    symDemodPiBy2BPSK=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','symDemodPiBy2BPSK',...
    'InportNames',inportNamePiBy2BPSK,...
    'InportTypes',inTypePiBy2BPSK,...
    'InportRates',inDataRatePiBy2BPSK,...
    'OutportNames',outportNamePiBy2BPSK,...
    'OutportTypes',outTypePiBy2BPSK...
    );



    dataIn_s0=symDemodPiBy2BPSK.PirInputSignals(1);
    validIn_s1=symDemodPiBy2BPSK.PirInputSignals(2);
    rstIn_s2=symDemodPiBy2BPSK.PirInputSignals(3);
    endIn_s3=symDemodPiBy2BPSK.PirInputSignals(4);

    dataOut=symDemodPiBy2BPSK.PirOutputSignals(1);
    validOut=symDemodPiBy2BPSK.PirOutputSignals(2);
    nonMul8FlagOut=symDemodPiBy2BPSK.PirOutputSignals(3);

    slRate1=rate;

    Delay11_out1_s45=addSignal(symDemodPiBy2BPSK,'Delay11_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    delayMatch19_out1_s133=addSignal(symDemodPiBy2BPSK,'delayMatch19_out1',pirTyp2,slRate1);
    delayMatch20_out1_s135=addSignal(symDemodPiBy2BPSK,'delayMatch20_out1',pirTyp2,slRate1);

    AND_out1_s4=addSignal(symDemodPiBy2BPSK,'AND_out1',pirTyp2,slRate1);
    AND1_out1_s5=addSignal(symDemodPiBy2BPSK,'AND1_out1',pirTyp2,slRate1);
    AND10_out1_s6=addSignal(symDemodPiBy2BPSK,'AND10_out1',pirTyp2,slRate1);
    AND11_out1_s7=addSignal(symDemodPiBy2BPSK,'AND11_out1',pirTyp2,slRate1);
    AND12_out1_s8=addSignal(symDemodPiBy2BPSK,'AND12_out1',pirTyp2,slRate1);
    AND2_out1_s9=addSignal(symDemodPiBy2BPSK,'AND2_out1',pirTyp2,slRate1);
    AND3_out1_s10=addSignal(symDemodPiBy2BPSK,'AND3_out1',pirTyp2,slRate1);
    AND4_out1_s11=addSignal(symDemodPiBy2BPSK,'AND4_out1',pirTyp2,slRate1);
    AND5_out1_s12=addSignal(symDemodPiBy2BPSK,'AND5_out1',pirTyp2,slRate1);
    AND6_out1_s13=addSignal(symDemodPiBy2BPSK,'AND6_out1',pirTyp2,slRate1);
    AND7_out1_s14=addSignal(symDemodPiBy2BPSK,'AND7_out1',pirTyp2,slRate1);
    AND8_out1_s15=addSignal(symDemodPiBy2BPSK,'AND8_out1',pirTyp2,slRate1);
    AND9_out1_s16=addSignal(symDemodPiBy2BPSK,'AND9_out1',pirTyp2,slRate1);
    Add_out1_s17=addSignal(symDemodPiBy2BPSK,'Add_out1',pirTyp4,slRate1);
    Add1_out1_s18=addSignal(symDemodPiBy2BPSK,'Add1_out1',pirTyp4,slRate1);
    CompareToConstant_out1_s19=addSignal(symDemodPiBy2BPSK,'Compare To Constant_out1',pirTyp2,slRate1);
    CompareToConstant1_out1_s20=addSignal(symDemodPiBy2BPSK,'Compare To Constant1_out1',pirTyp2,slRate1);
    CompareToConstant10_out1_s21=addSignal(symDemodPiBy2BPSK,'Compare To Constant10_out1',pirTyp2,slRate1);
    CompareToConstant2_out1_s22=addSignal(symDemodPiBy2BPSK,'Compare To Constant2_out1',pirTyp2,slRate1);
    CompareToConstant3_out1_s23=addSignal(symDemodPiBy2BPSK,'Compare To Constant3_out1',pirTyp2,slRate1);
    CompareToConstant4_out1_s24=addSignal(symDemodPiBy2BPSK,'Compare To Constant4_out1',pirTyp2,slRate1);
    CompareToConstant5_out1_s25=addSignal(symDemodPiBy2BPSK,'Compare To Constant5_out1',pirTyp2,slRate1);
    CompareToConstant6_out1_s26=addSignal(symDemodPiBy2BPSK,'Compare To Constant6_out1',pirTyp2,slRate1);
    CompareToConstant7_out1_s27=addSignal(symDemodPiBy2BPSK,'Compare To Constant7_out1',pirTyp2,slRate1);
    CompareToConstant8_out1_s28=addSignal(symDemodPiBy2BPSK,'Compare To Constant8_out1',pirTyp2,slRate1);
    CompareToConstant9_out1_s29=addSignal(symDemodPiBy2BPSK,'Compare To Constant9_out1',pirTyp2,slRate1);
    ComplexToReal_Imag_out1_s30=addSignal(symDemodPiBy2BPSK,'Complex to Real-Imag_out1',pirTyp1,slRate1);
    ComplexToReal_Imag_out2_s31=addSignal(symDemodPiBy2BPSK,'Complex to Real-Imag_out2',pirTyp1,slRate1);
    Constant_out1_s32=addSignal(symDemodPiBy2BPSK,'Constant_out1',pirTyp5,slRate1);
    Constant1_out1_s33=addSignal(symDemodPiBy2BPSK,'Constant1_out1',pirTyp5,slRate1);
    Constant10_out1_s34=addSignal(symDemodPiBy2BPSK,'Constant10_out1',pirTyp3,slRate1);
    Constant2_out1_s35=addSignal(symDemodPiBy2BPSK,'Constant2_out1',pirTyp3,slRate1);
    Constant3_out1_s36=addSignal(symDemodPiBy2BPSK,'Constant3_out1',pirTyp3,slRate1);
    Constant4_out1_s37=addSignal(symDemodPiBy2BPSK,'Constant4_out1',pirTyp3,slRate1);
    Constant5_out1_s38=addSignal(symDemodPiBy2BPSK,'Constant5_out1',pirTyp3,slRate1);
    Constant6_out1_s39=addSignal(symDemodPiBy2BPSK,'Constant6_out1',pirTyp3,slRate1);
    Constant7_out1_s40=addSignal(symDemodPiBy2BPSK,'Constant7_out1',pirTyp3,slRate1);
    Constant8_out1_s41=addSignal(symDemodPiBy2BPSK,'Constant8_out1',pirTyp3,slRate1);
    DataTypeConversion_out1_s42=addSignal(symDemodPiBy2BPSK,'Data Type Conversion_out1',pirTyp3,slRate1);
    Delay_out1_s43=addSignal(symDemodPiBy2BPSK,'Delay_out1',pirTyp6,slRate1);
    Delay10_out1_s44=addSignal(symDemodPiBy2BPSK,'Delay10_out1',pirTyp2,slRate1);
    Delay12_out1_s46=addSignal(symDemodPiBy2BPSK,'Delay12_out1',pirTyp2,slRate1);
    Delay13_out1_s47=addSignal(symDemodPiBy2BPSK,'Delay13_out1',pirTyp2,slRate1);
    Delay14_out1_s48=addSignal(symDemodPiBy2BPSK,'Delay14_out1',pirTyp2,slRate1);
    Delay15_out1_s49=addSignal(symDemodPiBy2BPSK,'Delay15_out1',pirTyp2,slRate1);
    Delay16_out1_s50=addSignal(symDemodPiBy2BPSK,'Delay16_out1',pirTyp2,slRate1);
    Delay17_out1_s51=addSignal(symDemodPiBy2BPSK,'Delay17_out1',pirTyp2,slRate1);
    Delay1_bypass_out1_s52=addSignal(symDemodPiBy2BPSK,'Delay1_bypass_out1',pirTyp3,slRate1);
    Delay1_lowered_out1_s53=addSignal(symDemodPiBy2BPSK,'Delay1_lowered_out1',pirTyp3,slRate1);
    Delay2_bypass_out1_s54=addSignal(symDemodPiBy2BPSK,'Delay2_bypass_out1',pirTyp3,slRate1);
    Delay2_lowered_out1_s55=addSignal(symDemodPiBy2BPSK,'Delay2_lowered_out1',pirTyp3,slRate1);
    Delay3_bypass_out1_s56=addSignal(symDemodPiBy2BPSK,'Delay3_bypass_out1',pirTyp3,slRate1);
    Delay3_lowered_out1_s57=addSignal(symDemodPiBy2BPSK,'Delay3_lowered_out1',pirTyp3,slRate1);
    Delay4_bypass_out1_s58=addSignal(symDemodPiBy2BPSK,'Delay4_bypass_out1',pirTyp3,slRate1);
    Delay4_lowered_out1_s59=addSignal(symDemodPiBy2BPSK,'Delay4_lowered_out1',pirTyp3,slRate1);
    Delay5_bypass_out1_s60=addSignal(symDemodPiBy2BPSK,'Delay5_bypass_out1',pirTyp3,slRate1);
    Delay5_lowered_out1_s61=addSignal(symDemodPiBy2BPSK,'Delay5_lowered_out1',pirTyp3,slRate1);
    Delay6_bypass_out1_s62=addSignal(symDemodPiBy2BPSK,'Delay6_bypass_out1',pirTyp3,slRate1);
    Delay6_lowered_out1_s63=addSignal(symDemodPiBy2BPSK,'Delay6_lowered_out1',pirTyp3,slRate1);
    Delay7_bypass_out1_s64=addSignal(symDemodPiBy2BPSK,'Delay7_bypass_out1',pirTyp3,slRate1);
    Delay7_lowered_out1_s65=addSignal(symDemodPiBy2BPSK,'Delay7_lowered_out1',pirTyp3,slRate1);
    Delay8_bypass_out1_s66=addSignal(symDemodPiBy2BPSK,'Delay8_bypass_out1',pirTyp3,slRate1);
    Delay8_lowered_out1_s67=addSignal(symDemodPiBy2BPSK,'Delay8_lowered_out1',pirTyp3,slRate1);
    Delay9_out1_s68=addSignal(symDemodPiBy2BPSK,'Delay9_out1',pirTyp2,slRate1);
    Delay_Switch_out1_s69=addSignal(symDemodPiBy2BPSK,'Delay_Switch_out1',pirTyp3,slRate1);
    Delay_Switch1_out1_s70=addSignal(symDemodPiBy2BPSK,'Delay_Switch1_out1',pirTyp3,slRate1);
    Delay_Switch2_out1_s71=addSignal(symDemodPiBy2BPSK,'Delay_Switch2_out1',pirTyp3,slRate1);
    Delay_Switch3_out1_s72=addSignal(symDemodPiBy2BPSK,'Delay_Switch3_out1',pirTyp3,slRate1);
    Delay_Switch4_out1_s73=addSignal(symDemodPiBy2BPSK,'Delay_Switch4_out1',pirTyp3,slRate1);
    Delay_Switch5_out1_s74=addSignal(symDemodPiBy2BPSK,'Delay_Switch5_out1',pirTyp3,slRate1);
    Delay_Switch6_out1_s75=addSignal(symDemodPiBy2BPSK,'Delay_Switch6_out1',pirTyp3,slRate1);
    Delay_Switch7_out1_s76=addSignal(symDemodPiBy2BPSK,'Delay_Switch7_out1',pirTyp3,slRate1);
    EvenSymCounter_out1_s77=addSignal(symDemodPiBy2BPSK,'Even sym counter_out1',pirTyp7,slRate1);
    EvenSymCounter_Initial_Val_out1_s78=addSignal(symDemodPiBy2BPSK,'Even sym counter_Initial_Val_out1',pirTyp7,slRate1);
    EvenSymCounter_ctrl_const_out1_s79=addSignal(symDemodPiBy2BPSK,'Even sym counter_ctrl_const_out1',pirTyp2,slRate1);
    EvenSymCounter_ctrl_delay_out1_s80=addSignal(symDemodPiBy2BPSK,'Even sym counter_ctrl_delay_out1',pirTyp2,slRate1);
    EvenSymCounter_switch_out1_s81=addSignal(symDemodPiBy2BPSK,'Even sym counter_switch_out1',pirTyp7,slRate1);
    HDLCounter_out1_s82=addSignal(symDemodPiBy2BPSK,'HDL Counter_out1',pirTyp6,slRate1);
    HDLCounter_out1_out1_s83=addSignal(symDemodPiBy2BPSK,'HDL Counter_out1_out1',pirTyp6,slRate1);
    HwModeRegister_out1_s84=addSignal(symDemodPiBy2BPSK,'HwModeRegister_out1',pirTyp5,slRate1);
    HwModeRegister1_out1_s85=addSignal(symDemodPiBy2BPSK,'HwModeRegister1_out1',pirTyp1,slRate1);
    HwModeRegister2_out1_s86=addSignal(symDemodPiBy2BPSK,'HwModeRegister2_out1',pirTyp1,slRate1);
    HwModeRegister3_out1_s87=addSignal(symDemodPiBy2BPSK,'HwModeRegister3_out1',pirTyp5,slRate1);
    LogicalOperator_out1_s88=addSignal(symDemodPiBy2BPSK,'Logical Operator_out1',pirTyp2,slRate1);
    LogicalOperator1_out1_s89=addSignal(symDemodPiBy2BPSK,'Logical Operator1_out1',pirTyp2,slRate1);
    LogicalOperator3_out1_s90=addSignal(symDemodPiBy2BPSK,'Logical Operator3_out1',pirTyp2,slRate1);
    LogicalOperator4_out1_s91=addSignal(symDemodPiBy2BPSK,'Logical Operator4_out1',pirTyp2,slRate1);
    OR_out1_s92=addSignal(symDemodPiBy2BPSK,'OR_out1',pirTyp2,slRate1);
    OR1_out1_s93=addSignal(symDemodPiBy2BPSK,'OR1_out1',pirTyp2,slRate1);
    OR2_out1_s94=addSignal(symDemodPiBy2BPSK,'OR2_out1',pirTyp2,slRate1);
    OR3_out1_s95=addSignal(symDemodPiBy2BPSK,'OR3_out1',pirTyp2,slRate1);
    OR4_out1_s96=addSignal(symDemodPiBy2BPSK,'OR4_out1',pirTyp2,slRate1);
    OR5_out1_s97=addSignal(symDemodPiBy2BPSK,'OR5_out1',pirTyp2,slRate1);
    OR6_out1_s98=addSignal(symDemodPiBy2BPSK,'OR6_out1',pirTyp2,slRate1);
    OR7_out1_s99=addSignal(symDemodPiBy2BPSK,'OR7_out1',pirTyp2,slRate1);
    PipelineRegister_out1_s100=addSignal(symDemodPiBy2BPSK,'PipelineRegister_out1',pirTyp8,slRate1);
    PipelineRegister1_out1_s101=addSignal(symDemodPiBy2BPSK,'PipelineRegister1_out1',pirTyp8,slRate1);
    Product_out1_s102=addSignal(symDemodPiBy2BPSK,'Product_out1',pirTyp8,slRate1);
    Product1_out1_s103=addSignal(symDemodPiBy2BPSK,'Product1_out1',pirTyp8,slRate1);
    Switch_out1_s104=addSignal(symDemodPiBy2BPSK,'Switch_out1',pirTyp4,slRate1);
    Switch1_out1_s105=addSignal(symDemodPiBy2BPSK,'Switch1_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    adder_out1_s106=addSignal(symDemodPiBy2BPSK,'adder_out1',pirTyp6,slRate1);
    adder1_out1_s107=addSignal(symDemodPiBy2BPSK,'adder1_out1',pirTyp7,slRate1);
    bypass_out_out1_s108=addSignal(symDemodPiBy2BPSK,'bypass_out_out1',pirTyp3,slRate1);
    bypass_out1_out1_s109=addSignal(symDemodPiBy2BPSK,'bypass_out1_out1',pirTyp3,slRate1);
    bypass_out2_out1_s110=addSignal(symDemodPiBy2BPSK,'bypass_out2_out1',pirTyp3,slRate1);
    bypass_out3_out1_s111=addSignal(symDemodPiBy2BPSK,'bypass_out3_out1',pirTyp3,slRate1);
    bypass_out4_out1_s112=addSignal(symDemodPiBy2BPSK,'bypass_out4_out1',pirTyp3,slRate1);
    bypass_out5_out1_s113=addSignal(symDemodPiBy2BPSK,'bypass_out5_out1',pirTyp3,slRate1);
    bypass_out6_out1_s114=addSignal(symDemodPiBy2BPSK,'bypass_out6_out1',pirTyp3,slRate1);
    bypass_out7_out1_s115=addSignal(symDemodPiBy2BPSK,'bypass_out7_out1',pirTyp3,slRate1);
    compare_out1_s116=addSignal(symDemodPiBy2BPSK,'compare_out1',pirTyp2,slRate1);
    compare1_out1_s117=addSignal(symDemodPiBy2BPSK,'compare1_out1',pirTyp2,slRate1);
    const_out1_s118=addSignal(symDemodPiBy2BPSK,'const_out1',pirTyp7,slRate1);
    const1_out1_s119=addSignal(symDemodPiBy2BPSK,'const1_out1',pirTyp6,slRate1);
    countFrom_out1_s120=addSignal(symDemodPiBy2BPSK,'countFrom_out1',pirTyp7,slRate1);
    countFrom1_out1_s121=addSignal(symDemodPiBy2BPSK,'countFrom1_out1',pirTyp6,slRate1);
    delayMatch_out1_s122=addSignal(symDemodPiBy2BPSK,'delayMatch_out1',pirTyp7,slRate1);
    delayMatch1_out1_s123=addSignal(symDemodPiBy2BPSK,'delayMatch1_out1',pirTyp2,slRate1);
    delayMatch10_out1_s124=addSignal(symDemodPiBy2BPSK,'delayMatch10_out1',pirTyp2,slRate1);
    delayMatch11_out1_s125=addSignal(symDemodPiBy2BPSK,'delayMatch11_out1',pirTyp2,slRate1);
    delayMatch12_out1_s126=addSignal(symDemodPiBy2BPSK,'delayMatch12_out1',pirTyp2,slRate1);
    delayMatch13_out1_s127=addSignal(symDemodPiBy2BPSK,'delayMatch13_out1',pirTyp2,slRate1);
    delayMatch14_out1_s128=addSignal(symDemodPiBy2BPSK,'delayMatch14_out1',pirTyp2,slRate1);
    delayMatch15_out1_s129=addSignal(symDemodPiBy2BPSK,'delayMatch15_out1',pirTyp2,slRate1);
    delayMatch16_out1_s130=addSignal(symDemodPiBy2BPSK,'delayMatch16_out1',pirTyp2,slRate1);
    delayMatch17_out1_s131=addSignal(symDemodPiBy2BPSK,'delayMatch17_out1',pirTyp2,slRate1);
    delayMatch18_out1_s132=addSignal(symDemodPiBy2BPSK,'delayMatch18_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    delayMatch2_out1_s134=addSignal(symDemodPiBy2BPSK,'delayMatch2_out1',pirTyp2,slRate1);
    delayMatch3_out1_s136=addSignal(symDemodPiBy2BPSK,'delayMatch3_out1',pirTyp2,slRate1);
    delayMatch4_out1_s137=addSignal(symDemodPiBy2BPSK,'delayMatch4_out1',pirTyp2,slRate1);
    delayMatch5_out1_s138=addSignal(symDemodPiBy2BPSK,'delayMatch5_out1',pirTyp2,slRate1);
    delayMatch6_out1_s139=addSignal(symDemodPiBy2BPSK,'delayMatch6_out1',pirTyp2,slRate1);
    delayMatch7_out1_s140=addSignal(symDemodPiBy2BPSK,'delayMatch7_out1',pirTyp2,slRate1);
    delayMatch8_out1_s141=addSignal(symDemodPiBy2BPSK,'delayMatch8_out1',pirTyp2,slRate1);
    delayMatch9_out1_s142=addSignal(symDemodPiBy2BPSK,'delayMatch9_out1',pirTyp2,slRate1);
    mux_out1_s143=addSignal(symDemodPiBy2BPSK,'mux_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    mux1_out1_s144=addSignal(symDemodPiBy2BPSK,'mux1_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    step_value_out1_s145=addSignal(symDemodPiBy2BPSK,'step_value_out1',pirTyp7,slRate1);
    step_value1_out1_s146=addSignal(symDemodPiBy2BPSK,'step_value1_out1',pirTyp6,slRate1);
    switch_out1_s147=addSignal(symDemodPiBy2BPSK,'switch_out1',pirTyp6,slRate1);
    switch1_out1_s148=addSignal(symDemodPiBy2BPSK,'switch1_out1',pirTyp7,slRate1);
    switchEnable_out1_s149=addSignal(symDemodPiBy2BPSK,'switchEnable_out1',pirTyp6,slRate1);
    switchEnable1_out1_s150=addSignal(symDemodPiBy2BPSK,'switchEnable1_out1',pirTyp7,slRate1);
    switchReset_out1_s151=addSignal(symDemodPiBy2BPSK,'switchReset_out1',pirTyp6,slRate1);
    switchReset1_out1_s152=addSignal(symDemodPiBy2BPSK,'switchReset1_out1',pirTyp7,slRate1);
    t_out1_s153=addSignal(symDemodPiBy2BPSK,'t_out1',pirelab.createPirArrayType(pirTyp3,[8,0]),slRate1);
    delayMatch19_iv_s156=addSignal(symDemodPiBy2BPSK,'delayMatch19_iv',pirTyp2,slRate1);
    delayMatch19_delOut_s157=addSignal(symDemodPiBy2BPSK,'delayMatch19_delOut',pirTyp2,slRate1);
    delayMatch19_toDel_s158=addSignal(symDemodPiBy2BPSK,'delayMatch19_toDel',pirTyp2,slRate1);
    delayMatch19_delOut_s159=addSignal(symDemodPiBy2BPSK,'delayMatch19_delOut',pirTyp2,slRate1);
    delayMatch19_toDel_s160=addSignal(symDemodPiBy2BPSK,'delayMatch19_toDel',pirTyp2,slRate1);
    t_out1_s161=addSignal(symDemodPiBy2BPSK,'t_out1',pirTyp3,slRate1);

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant_out1_s32,...
    fi(0,nt1,fiMath1,'hex','5a82'),...
    'Constant','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant1_out1_s33,...
    fi(0,nt1,fiMath1,'hex','5a82'),...
    'Constant1','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant10_out1_s34,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant10','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant2_out1_s35,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant2','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant3_out1_s36,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant3','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant4_out1_s37,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant4','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant5_out1_s38,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant5','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant6_out1_s39,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant6','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant7_out1_s40,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant7','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    Constant8_out1_s41,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant8','on',1,'','','');

    pirelab.getAnnotationComp(symDemodPiBy2BPSK,...
    'Data Type Duplicate');

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    Delay_out1_s43,...
    1,'Delay',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    AND8_out1_s15,...
    Delay10_out1_s44,...
    4,'Delay10',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Switch1_out1_s105,...
    Delay11_out1_s45,...
    4,'Delay11',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    LogicalOperator_out1_s88,...
    Delay12_out1_s46,...
    1,'Delay12',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    LogicalOperator_out1_s88,...
    Delay13_out1_s47,...
    1,'Delay13',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    LogicalOperator_out1_s88,...
    Delay14_out1_s48,...
    3,'Delay14',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    LogicalOperator_out1_s88,...
    Delay15_out1_s49,...
    2,'Delay15',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    LogicalOperator_out1_s88,...
    Delay16_out1_s50,...
    4,'Delay16',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    AND11_out1_s7,...
    Delay17_out1_s51,...
    5,'Delay17',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out_out1_s108,...
    Delay1_bypass_out1_s52,...
    1,'Delay1_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch_out1_s69,...
    Delay1_lowered_out1_s53,...
    1,'Delay1_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out1_out1_s109,...
    Delay2_bypass_out1_s54,...
    1,'Delay2_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch1_out1_s70,...
    Delay2_lowered_out1_s55,...
    1,'Delay2_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out2_out1_s110,...
    Delay3_bypass_out1_s56,...
    1,'Delay3_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch2_out1_s71,...
    Delay3_lowered_out1_s57,...
    1,'Delay3_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out3_out1_s111,...
    Delay4_bypass_out1_s58,...
    1,'Delay4_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch3_out1_s72,...
    Delay4_lowered_out1_s59,...
    1,'Delay4_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out4_out1_s112,...
    Delay5_bypass_out1_s60,...
    1,'Delay5_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch4_out1_s73,...
    Delay5_lowered_out1_s61,...
    1,'Delay5_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out5_out1_s113,...
    Delay6_bypass_out1_s62,...
    1,'Delay6_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch5_out1_s74,...
    Delay6_lowered_out1_s63,...
    1,'Delay6_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out6_out1_s114,...
    Delay7_bypass_out1_s64,...
    1,'Delay7_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch6_out1_s75,...
    Delay7_lowered_out1_s65,...
    1,'Delay7_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    bypass_out7_out1_s115,...
    Delay8_bypass_out1_s66,...
    1,'Delay8_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay_Switch7_out1_s76,...
    Delay8_lowered_out1_s67,...
    1,'Delay8_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    validIn_s1,...
    Delay9_out1_s68,...
    1,'Delay9',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    switchReset1_out1_s152,...
    EvenSymCounter_out1_s77,...
    1,'Even sym counter',...
    uint8(0),...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    EvenSymCounter_Initial_Val_out1_s78,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'Even sym counter_Initial_Val','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    EvenSymCounter_ctrl_const_out1_s79,...
    fi(0,nt5,fiMath1,'hex','1'),...
    'Even sym counter_ctrl_const','on',0,'','','');

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    EvenSymCounter_ctrl_const_out1_s79,...
    EvenSymCounter_ctrl_delay_out1_s80,...
    1,'Even sym counter_ctrl_delay',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    switchReset_out1_s151,...
    HDLCounter_out1_s82,...
    1,'HDL Counter',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Constant_out1_s32,...
    HwModeRegister_out1_s84,...
    1,'HwModeRegister',...
    fi(0,nt1,fiMath1,'hex','0000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    ComplexToReal_Imag_out1_s30,...
    HwModeRegister1_out1_s85,...
    1,'HwModeRegister1',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    ComplexToReal_Imag_out2_s31,...
    HwModeRegister2_out1_s86,...
    1,'HwModeRegister2',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Constant1_out1_s33,...
    HwModeRegister3_out1_s87,...
    1,'HwModeRegister3',...
    fi(0,nt1,fiMath1,'hex','0000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Product_out1_s102,...
    PipelineRegister_out1_s100,...
    1,'PipelineRegister',...
    fi(0,nt7,fiMath1,'hex','00000000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Product1_out1_s103,...
    PipelineRegister1_out1_s101,...
    1,'PipelineRegister1',...
    fi(0,nt7,fiMath1,'hex','00000000'),...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    const_out1_s118,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'const','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    const1_out1_s119,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'const1','off',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    countFrom_out1_s120,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'countFrom','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    countFrom1_out1_s121,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'countFrom1','off',1,'','','');

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    EvenSymCounter_switch_out1_s81,...
    delayMatch_out1_s122,...
    2,'delayMatch',...
    uint8(0),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR_out1_s92,...
    delayMatch1_out1_s123,...
    2,'delayMatch1',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR4_out1_s96,...
    delayMatch10_out1_s124,...
    2,'delayMatch10',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR5_out1_s97,...
    delayMatch11_out1_s125,...
    2,'delayMatch11',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR5_out1_s97,...
    delayMatch12_out1_s126,...
    2,'delayMatch12',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR6_out1_s98,...
    delayMatch13_out1_s127,...
    2,'delayMatch13',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR6_out1_s98,...
    delayMatch14_out1_s128,...
    2,'delayMatch14',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR7_out1_s99,...
    delayMatch15_out1_s129,...
    2,'delayMatch15',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR7_out1_s99,...
    delayMatch16_out1_s130,...
    2,'delayMatch16',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    AND8_out1_s15,...
    delayMatch17_out1_s131,...
    2,'delayMatch17',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    mux1_out1_s144,...
    delayMatch18_out1_s132,...
    2,'delayMatch18',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR_out1_s92,...
    delayMatch2_out1_s134,...
    2,'delayMatch2',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    Delay17_out1_s51,...
    delayMatch20_out1_s135,...
    2,'delayMatch20',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR1_out1_s93,...
    delayMatch3_out1_s136,...
    2,'delayMatch3',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR1_out1_s93,...
    delayMatch4_out1_s137,...
    2,'delayMatch4',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR2_out1_s94,...
    delayMatch5_out1_s138,...
    2,'delayMatch5',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR2_out1_s94,...
    delayMatch6_out1_s139,...
    2,'delayMatch6',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR3_out1_s95,...
    delayMatch7_out1_s140,...
    2,'delayMatch7',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR3_out1_s95,...
    delayMatch8_out1_s141,...
    2,'delayMatch8',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    OR4_out1_s96,...
    delayMatch9_out1_s142,...
    2,'delayMatch9',...
    false,...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    step_value_out1_s145,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'step_value','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    step_value1_out1_s146,...
    fi(0,nt3,fiMath1,'hex','1'),...
    'step_value1','off',0,'','','');

    pirelab.getWireComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_s82,...
    HDLCounter_out1_out1_s83,...
    'HDL Counter_out1_out1');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    delayMatch19_iv_s156,...
    false,...
    'Initial_Val','on',0,'','','');

    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [delayMatch19_iv_s156,AND10_out1_s6],...
    delayMatch19_toDel_s158,...
    rstIn_s2,'reset_in',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    delayMatch19_toDel_s158,...
    delayMatch19_delOut_s157,...
    1,'delayMatch19_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [delayMatch19_iv_s156,delayMatch19_delOut_s157],...
    delayMatch19_toDel_s160,...
    rstIn_s2,'reset_in',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(symDemodPiBy2BPSK,...
    delayMatch19_toDel_s160,...
    delayMatch19_delOut_s159,...
    1,'delayMatch19_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [delayMatch19_iv_s156,delayMatch19_delOut_s159],...
    delayMatch19_out1_s133,...
    rstIn_s2,'reset_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getMuxComp(symDemodPiBy2BPSK,...
    [t_out1_s161,t_out1_s161,t_out1_s161,t_out1_s161,t_out1_s161,t_out1_s161,...
    t_out1_s161,t_out1_s161],...
    t_out1_s153,...
    '');

    pirelab.getConstComp(symDemodPiBy2BPSK,...
    t_out1_s161,...
    double(0),...
    '','on',1,'','','');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [validIn_s1,CompareToConstant6_out1_s26],...
    AND_out1_s4,...
    'and','AND');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant5_out1_s25,validIn_s1],...
    AND1_out1_s5,...
    'and','AND1');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [Delay13_out1_s47,Delay15_out1_s49,Delay14_out1_s48,Delay16_out1_s50,Delay10_out1_s44],...
    AND10_out1_s6,...
    'and','AND10');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [endIn_s3,AND12_out1_s8],...
    AND11_out1_s7,...
    'and','AND11');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [validIn_s1,CompareToConstant10_out1_s21],...
    AND12_out1_s8,...
    'and','AND12');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant_out1_s19,validIn_s1],...
    AND2_out1_s9,...
    'and','AND2');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant1_out1_s20,validIn_s1],...
    AND3_out1_s10,...
    'and','AND3');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant2_out1_s22,validIn_s1],...
    AND4_out1_s11,...
    'and','AND4');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant3_out1_s23,validIn_s1],...
    AND5_out1_s12,...
    'and','AND5');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant4_out1_s24,validIn_s1],...
    AND6_out1_s13,...
    'and','AND6');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant7_out1_s27,validIn_s1],...
    AND7_out1_s14,...
    'and','AND7');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [CompareToConstant8_out1_s28,AND9_out1_s16],...
    AND8_out1_s15,...
    'and','AND8');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [Delay9_out1_s68,Delay12_out1_s46],...
    AND9_out1_s16,...
    'and','AND9');


    pirelab.getAddComp(symDemodPiBy2BPSK,...
    [PipelineRegister_out1_s100,PipelineRegister1_out1_s101],...
    Add_out1_s17,...
    'Floor','Wrap','Add',pirTyp4,'++');


    pirelab.getAddComp(symDemodPiBy2BPSK,...
    [PipelineRegister1_out1_s101,PipelineRegister_out1_s100],...
    Add1_out1_s18,...
    'Floor','Wrap','Add1',pirTyp4,'+-');


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant_out1_s19,...
    '==',fi(0,nt3,fiMath1,'hex','2'),...
    'Compare To Constant',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant1_out1_s20,...
    '==',fi(0,nt3,fiMath1,'hex','3'),...
    'Compare To Constant1',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant10_out1_s21,...
    '~=',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant10',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant2_out1_s22,...
    '==',fi(0,nt3,fiMath1,'hex','4'),...
    'Compare To Constant2',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant3_out1_s23,...
    '==',fi(0,nt3,fiMath1,'hex','5'),...
    'Compare To Constant3',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant4_out1_s24,...
    '==',fi(0,nt3,fiMath1,'hex','6'),...
    'Compare To Constant4',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant5_out1_s25,...
    '==',fi(0,nt3,fiMath1,'hex','1'),...
    'Compare To Constant5',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant6_out1_s26,...
    '==',fi(0,nt3,fiMath1,'hex','0'),...
    'Compare To Constant6',1);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant7_out1_s27,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant7',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    Delay_out1_s43,...
    CompareToConstant8_out1_s28,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant8',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_out1_s83,...
    CompareToConstant9_out1_s29,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant9',0);


    pirelab.getComplex2RealImag(symDemodPiBy2BPSK,...
    dataIn_s0,...
    [ComplexToReal_Imag_out1_s30,ComplexToReal_Imag_out2_s31],...
    'Real and imag',...
    'Complex to Real-Imag');


    pirelab.getDTCComp(symDemodPiBy2BPSK,...
    Switch_out1_s104,...
    DataTypeConversion_out1_s42,...
    'Floor','Wrap','RWV','Data Type Conversion');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay1_lowered_out1_s53],...
    Delay_Switch_out1_s69,...
    delayMatch1_out1_s123,'Delay_Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay2_lowered_out1_s55],...
    Delay_Switch1_out1_s70,...
    delayMatch3_out1_s136,'Delay_Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay3_lowered_out1_s57],...
    Delay_Switch2_out1_s71,...
    delayMatch5_out1_s138,'Delay_Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay4_lowered_out1_s59],...
    Delay_Switch3_out1_s72,...
    delayMatch7_out1_s140,'Delay_Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay5_lowered_out1_s61],...
    Delay_Switch4_out1_s73,...
    delayMatch9_out1_s142,'Delay_Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay6_lowered_out1_s63],...
    Delay_Switch5_out1_s74,...
    delayMatch11_out1_s125,'Delay_Switch5',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay7_lowered_out1_s65],...
    Delay_Switch6_out1_s75,...
    delayMatch13_out1_s127,'Delay_Switch6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [DataTypeConversion_out1_s42,Delay8_lowered_out1_s67],...
    Delay_Switch7_out1_s76,...
    delayMatch15_out1_s129,'Delay_Switch7',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [EvenSymCounter_out1_s77,EvenSymCounter_Initial_Val_out1_s78],...
    EvenSymCounter_switch_out1_s81,...
    EvenSymCounter_ctrl_delay_out1_s80,'Even sym counter_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    rstIn_s2,...
    LogicalOperator_out1_s88,...
    'not','Logical Operator');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [validIn_s1,CompareToConstant9_out1_s29],...
    LogicalOperator1_out1_s89,...
    'and','Logical Operator1');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [rstIn_s2,AND11_out1_s7],...
    LogicalOperator3_out1_s90,...
    'or','Logical Operator3');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [rstIn_s2,AND11_out1_s7,LogicalOperator1_out1_s89],...
    LogicalOperator4_out1_s91,...
    'or','Logical Operator4');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND_out1_s4],...
    OR_out1_s92,...
    'or','OR');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND1_out1_s5],...
    OR1_out1_s93,...
    'or','OR1');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND2_out1_s9],...
    OR2_out1_s94,...
    'or','OR2');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND3_out1_s10],...
    OR3_out1_s95,...
    'or','OR3');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND4_out1_s11],...
    OR4_out1_s96,...
    'or','OR4');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND5_out1_s12],...
    OR5_out1_s97,...
    'or','OR5');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND6_out1_s13],...
    OR6_out1_s98,...
    'or','OR6');


    pirelab.getLogicComp(symDemodPiBy2BPSK,...
    [AND8_out1_s15,AND7_out1_s14],...
    OR7_out1_s99,...
    'or','OR7');


    pirelab.getMulComp(symDemodPiBy2BPSK,...
    [HwModeRegister_out1_s84,HwModeRegister1_out1_s85],...
    Product_out1_s102,...
    'Floor','Wrap','Product','**','',-1,0);


    pirelab.getMulComp(symDemodPiBy2BPSK,...
    [HwModeRegister2_out1_s86,HwModeRegister3_out1_s87],...
    Product1_out1_s103,...
    'Floor','Wrap','Product1','**','',-1,0);


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Add_out1_s17,Add1_out1_s18],...
    Switch_out1_s104,...
    delayMatch_out1_s122,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [mux_out1_s143,delayMatch18_out1_s132],...
    Switch1_out1_s105,...
    delayMatch17_out1_s131,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getAddComp(symDemodPiBy2BPSK,...
    [HDLCounter_out1_s82,step_value1_out1_s146],...
    adder_out1_s106,...
    'Floor','Wrap','adder',pirTyp6,'++');


    pirelab.getAddComp(symDemodPiBy2BPSK,...
    [EvenSymCounter_switch_out1_s81,step_value_out1_s145],...
    adder1_out1_s107,...
    'Floor','Wrap','adder1',pirTyp7,'+-');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay1_lowered_out1_s53,Delay1_bypass_out1_s52],...
    bypass_out_out1_s108,...
    delayMatch2_out1_s134,'bypass_out',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay2_lowered_out1_s55,Delay2_bypass_out1_s54],...
    bypass_out1_out1_s109,...
    delayMatch4_out1_s137,'bypass_out1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay3_lowered_out1_s57,Delay3_bypass_out1_s56],...
    bypass_out2_out1_s110,...
    delayMatch6_out1_s139,'bypass_out2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay4_lowered_out1_s59,Delay4_bypass_out1_s58],...
    bypass_out3_out1_s111,...
    delayMatch8_out1_s141,'bypass_out3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay5_lowered_out1_s61,Delay5_bypass_out1_s60],...
    bypass_out4_out1_s112,...
    delayMatch10_out1_s124,'bypass_out4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay6_lowered_out1_s63,Delay6_bypass_out1_s62],...
    bypass_out5_out1_s113,...
    delayMatch12_out1_s126,'bypass_out5',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay7_lowered_out1_s65,Delay7_bypass_out1_s64],...
    bypass_out6_out1_s114,...
    delayMatch14_out1_s128,'bypass_out6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [Delay8_lowered_out1_s67,Delay8_bypass_out1_s66],...
    bypass_out7_out1_s115,...
    delayMatch16_out1_s130,'bypass_out7',...
    '~=',0,'Floor','Wrap');


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    HDLCounter_out1_s82,...
    compare_out1_s116,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'compare',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSK,...
    EvenSymCounter_switch_out1_s81,...
    compare1_out1_s117,...
    '==',fi(0,nt4,fiMath1,'hex','00'),...
    'compare1',1);


    pirelab.getMuxComp(symDemodPiBy2BPSK,...
    [bypass_out_out1_s108,bypass_out1_out1_s109,bypass_out2_out1_s110,bypass_out3_out1_s111,bypass_out4_out1_s112,bypass_out5_out1_s113,...
    bypass_out6_out1_s114,bypass_out7_out1_s115],...
    mux_out1_s143,...
    'mux');


    pirelab.getMuxComp(symDemodPiBy2BPSK,...
    [Constant10_out1_s34,Constant3_out1_s36,Constant2_out1_s35,Constant4_out1_s37,Constant5_out1_s38,Constant6_out1_s39,...
    Constant7_out1_s40,Constant8_out1_s41],...
    mux1_out1_s144,...
    'mux');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [countFrom1_out1_s121,adder_out1_s106],...
    switch_out1_s147,...
    compare_out1_s116,'switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [countFrom_out1_s120,adder1_out1_s107],...
    switch1_out1_s148,...
    compare1_out1_s117,'switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getMultiPortSwitchComp(symDemodPiBy2BPSK,...
    [validIn_s1,HDLCounter_out1_s82,switch_out1_s147],...
    switchEnable_out1_s149,...
    1,'Zero-based contiguous','Floor','Wrap','switchEnable',[]);


    pirelab.getMultiPortSwitchComp(symDemodPiBy2BPSK,...
    [validIn_s1,EvenSymCounter_switch_out1_s81,switch1_out1_s148],...
    switchEnable1_out1_s150,...
    1,'Zero-based contiguous','Floor','Wrap','switchEnable1',[]);


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [const1_out1_s119,switchEnable_out1_s149],...
    switchReset_out1_s151,...
    LogicalOperator4_out1_s91,'switchReset',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSK,...
    [const_out1_s118,switchEnable1_out1_s150],...
    switchReset1_out1_s152,...
    LogicalOperator3_out1_s90,'switchReset1',...
    '~=',0,'Floor','Wrap');



    pirelab.getWireComp(symDemodPiBy2BPSK,Delay11_out1_s45,dataOut);
    pirelab.getWireComp(symDemodPiBy2BPSK,delayMatch19_out1_s133,validOut);
    pirelab.getWireComp(symDemodPiBy2BPSK,delayMatch20_out1_s135,nonMul8FlagOut);
end

function hS=addSignal(symDemodPiBy2BPSK,sigName,pirTyp,simulinkRate)
    hS=symDemodPiBy2BPSK.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end