function readyControlNet=elabReadyCtrl(~,topNet,blockInfo,datarate)




    inDataRate(1)=datarate;
    inDataRate(2)=datarate;
    inDataRate(3)=datarate;

    inportNames={'scalarValidIn','inpRxFlag','modIndxSig'};
    outportNames={'readyOutput'};

    inTypes(1)=pir_ufixpt_t(1,0);
    inTypes(2)=pir_ufixpt_t(1,0);
    inTypes(3)=pir_ufixpt_t(3,0);

    outTypes(1)=pir_ufixpt_t(1,0);

    readyControlNet=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','readyControlNet',...
    'InportNames',inportNames,...
    'InportTypes',inTypes,...
    'InportRates',inDataRate,...
    'OutportNames',outportNames,...
    'OutportTypes',outTypes...
    );

    scalValidIn=readyControlNet.PirInputSignals(1);
    inpRxdFlag=readyControlNet.PirInputSignals(2);
    modIndex=readyControlNet.PirInputSignals(3);
    readyOp=readyControlNet.PirOutputSignals(1);

    desc='ready Ctrl - controller for scalar valid';

    fid=fopen(fullfile(matlabroot,'toolbox','whdl','whdlutilities',...
    '+satcomhdlsupport','+internal','@DVBS2SymbolDemodulator','cgireml',...
    'readyController.m'),'r');

    fcnBody=fread(fid,Inf,'char=>char');
    fclose(fid);

    inports=[scalValidIn,inpRxdFlag,modIndex];
    outports=[readyOp];

    sampleBusCtrl=readyControlNet.addComponent2(...
    'kind','cgireml',...
    'Name','readyController',...
    'InputSignals',inports,...
    'OutputSignals',outports,...
    'EMLFileName','readyController',...
    'EMLFileBody',fcnBody,...
    'BlockComment',desc...
    );
    sampleBusCtrl.runConcurrencyMaximizer(0);

end
