function symDemodQPSKSc=elabQPSKScSymDemodNet(~,topNet,~,rate,inpWL,inpFL)





    pirTyp2=pir_boolean_t;
    pirTyp4=pir_sfixpt_t(16,-13);
    pirTyp1=pir_sfixpt_t(inpWL,inpFL);
    pirTyp3=pir_sfixpt_t(inpWL+3,inpFL);
    pirTyp5=pir_sfixpt_t(inpWL+16,inpFL-13);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt1=numerictype(1,16,13);
    nt3=numerictype(1,inpWL,-inpFL);
    nt2=numerictype(1,inpWL+3,-inpFL);
    nt4=numerictype(1,inpWL+16,-(inpFL-13));

    inportNameQPSK={'dataIn','validIn'};
    controlType=pir_ufixpt_t(1,0);
    inType=pir_complex_t(pir_sfixpt_t(inpWL,inpFL));
    inTypeQPSK=[inType,controlType];
    inDataRateQPSK=[rate,rate];

    outportNameQPSK={'dataOut','validOut'};
    outTypeQPSK=[pirTyp3,controlType];

    symDemodQPSKSc=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','symDemodQPSKSc',...
    'InportNames',inportNameQPSK,...
    'InportTypes',inTypeQPSK,...
    'InportRates',inDataRateQPSK,...
    'OutportNames',outportNameQPSK,...
    'OutportTypes',outTypeQPSK...
    );



    dataIn_s0=symDemodQPSKSc.PirInputSignals(1);
    validIn_s1=symDemodQPSKSc.PirInputSignals(2);

    dataOut=symDemodQPSKSc.PirOutputSignals(1);
    validOut=symDemodQPSKSc.PirOutputSignals(2);

    slRate1=rate;

    Switch2_out1_s23=addSignal(symDemodQPSKSc,'Switch2_out1',pirTyp3,slRate1);
    delayMatch4_out1_s29=addSignal(symDemodQPSKSc,'delayMatch4_out1',pirTyp2,slRate1);


    ComplexToReal_Imag_out1_s2=addSignal(symDemodQPSKSc,'Complex to Real-Imag_out1',pirTyp1,slRate1);
    ComplexToReal_Imag_out2_s3=addSignal(symDemodQPSKSc,'Complex to Real-Imag_out2',pirTyp1,slRate1);
    Constant_out1_s4=addSignal(symDemodQPSKSc,'Constant_out1',pirTyp4,slRate1);
    Constant1_out1_s5=addSignal(symDemodQPSKSc,'Constant1_out1',pirTyp4,slRate1);
    Constant2_out1_s6=addSignal(symDemodQPSKSc,'Constant2_out1',pirTyp3,slRate1);
    DataTypeConversion_out1_s7=addSignal(symDemodQPSKSc,'Data Type Conversion_out1',pirTyp3,slRate1);
    DataTypeConversion1_out1_s8=addSignal(symDemodQPSKSc,'Data Type Conversion1_out1',pirTyp3,slRate1);
    Delay_out1_s9=addSignal(symDemodQPSKSc,'Delay_out1',pirTyp2,slRate1);
    Delay1_bypass_out1_s10=addSignal(symDemodQPSKSc,'Delay1_bypass_out1',pirTyp3,slRate1);
    Delay1_lowered_out1_s11=addSignal(symDemodQPSKSc,'Delay1_lowered_out1',pirTyp3,slRate1);
    Delay_Switch_out1_s12=addSignal(symDemodQPSKSc,'Delay_Switch_out1',pirTyp3,slRate1);
    HwModeRegister_out1_s13=addSignal(symDemodQPSKSc,'HwModeRegister_out1',pirTyp4,slRate1);
    HwModeRegister1_out1_s14=addSignal(symDemodQPSKSc,'HwModeRegister1_out1',pirTyp1,slRate1);
    HwModeRegister2_out1_s15=addSignal(symDemodQPSKSc,'HwModeRegister2_out1',pirTyp1,slRate1);
    HwModeRegister3_out1_s16=addSignal(symDemodQPSKSc,'HwModeRegister3_out1',pirTyp4,slRate1);
    LogicalOperator_out1_s17=addSignal(symDemodQPSKSc,'Logical Operator_out1',pirTyp2,slRate1);
    PipelineRegister_out1_s18=addSignal(symDemodQPSKSc,'PipelineRegister_out1',pirTyp5,slRate1);
    PipelineRegister1_out1_s19=addSignal(symDemodQPSKSc,'PipelineRegister1_out1',pirTyp5,slRate1);
    Product_out1_s20=addSignal(symDemodQPSKSc,'Product_out1',pirTyp5,slRate1);
    Product1_out1_s21=addSignal(symDemodQPSKSc,'Product1_out1',pirTyp5,slRate1);
    Switch_out1_s22=addSignal(symDemodQPSKSc,'Switch_out1',pirTyp3,slRate1);
    bypass_out_out1_s24=addSignal(symDemodQPSKSc,'bypass_out_out1',pirTyp3,slRate1);
    delayMatch_out1_s25=addSignal(symDemodQPSKSc,'delayMatch_out1',pirTyp2,slRate1);
    delayMatch1_out1_s26=addSignal(symDemodQPSKSc,'delayMatch1_out1',pirTyp2,slRate1);
    delayMatch2_out1_s27=addSignal(symDemodQPSKSc,'delayMatch2_out1',pirTyp2,slRate1);
    delayMatch3_out1_s28=addSignal(symDemodQPSKSc,'delayMatch3_out1',pirTyp2,slRate1);


    pirelab.getConstComp(symDemodQPSKSc,...
    Constant_out1_s4,...
    fi(0,nt1,fiMath1,'hex','5a82'),...
    'Constant','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKSc,...
    Constant1_out1_s5,...
    fi(0,nt1,fiMath1,'hex','5a82'),...
    'Constant1','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKSc,...
    Constant2_out1_s6,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant2','on',1,'','','');

    pirelab.getAnnotationComp(symDemodQPSKSc,...
    'Data Type Duplicate1');

    pirelab.getAnnotationComp(symDemodQPSKSc,...
    'Data Type Duplicate2');


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    validIn_s1,...
    Delay_out1_s9,...
    1,'Delay',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    bypass_out_out1_s24,...
    Delay1_bypass_out1_s10,...
    1,'Delay1_bypass',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Delay_Switch_out1_s12,...
    Delay1_lowered_out1_s11,...
    1,'Delay1_lowered',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Constant_out1_s4,...
    HwModeRegister_out1_s13,...
    1,'HwModeRegister',...
    fi(0,nt1,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    ComplexToReal_Imag_out1_s2,...
    HwModeRegister1_out1_s14,...
    1,'HwModeRegister1',...
    fi(0,nt3,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    ComplexToReal_Imag_out2_s3,...
    HwModeRegister2_out1_s15,...
    1,'HwModeRegister2',...
    fi(0,nt3,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Constant1_out1_s5,...
    HwModeRegister3_out1_s16,...
    1,'HwModeRegister3',...
    fi(0,nt1,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Product_out1_s20,...
    PipelineRegister_out1_s18,...
    1,'PipelineRegister',...
    fi(0,nt4,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Product1_out1_s21,...
    PipelineRegister1_out1_s19,...
    1,'PipelineRegister1',...
    fi(0,nt4,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    LogicalOperator_out1_s17,...
    delayMatch_out1_s25,...
    2,'delayMatch',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    LogicalOperator_out1_s17,...
    delayMatch1_out1_s26,...
    2,'delayMatch1',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    validIn_s1,...
    delayMatch2_out1_s27,...
    2,'delayMatch2',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    Delay_out1_s9,...
    delayMatch3_out1_s28,...
    2,'delayMatch3',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKSc,...
    LogicalOperator_out1_s17,...
    delayMatch4_out1_s29,...
    2,'delayMatch4',...
    false,...
    0,0,[],0,0);


    pirelab.getComplex2RealImag(symDemodQPSKSc,...
    dataIn_s0,...
    [ComplexToReal_Imag_out1_s2,ComplexToReal_Imag_out2_s3],...
    'Real and imag',...
    'Complex to Real-Imag');


    pirelab.getDTCComp(symDemodQPSKSc,...
    PipelineRegister_out1_s18,...
    DataTypeConversion_out1_s7,...
    'Floor','Wrap','RWV','Data Type Conversion');


    pirelab.getDTCComp(symDemodQPSKSc,...
    PipelineRegister1_out1_s19,...
    DataTypeConversion1_out1_s8,...
    'Floor','Wrap','RWV','Data Type Conversion1');


    pirelab.getSwitchComp(symDemodQPSKSc,...
    [DataTypeConversion1_out1_s8,Delay1_lowered_out1_s11],...
    Delay_Switch_out1_s12,...
    delayMatch_out1_s25,'Delay_Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getLogicComp(symDemodQPSKSc,...
    [validIn_s1,Delay_out1_s9],...
    LogicalOperator_out1_s17,...
    'or','Logical Operator');


    pirelab.getMulComp(symDemodQPSKSc,...
    [HwModeRegister_out1_s13,HwModeRegister1_out1_s14],...
    Product_out1_s20,...
    'Floor','Wrap','Product','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKSc,...
    [HwModeRegister2_out1_s15,HwModeRegister3_out1_s16],...
    Product1_out1_s21,...
    'Floor','Wrap','Product1','**','',-1,0);


    pirelab.getSwitchComp(symDemodQPSKSc,...
    [DataTypeConversion_out1_s7,Constant2_out1_s6],...
    Switch_out1_s22,...
    delayMatch2_out1_s27,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKSc,...
    [bypass_out_out1_s24,Switch_out1_s22],...
    Switch2_out1_s23,...
    delayMatch3_out1_s28,'Switch2',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKSc,...
    [Delay1_lowered_out1_s11,Delay1_bypass_out1_s10],...
    bypass_out_out1_s24,...
    delayMatch1_out1_s26,'bypass_out',...
    '~=',0,'Floor','Wrap');



    pirelab.getWireComp(symDemodQPSKSc,Switch2_out1_s23,dataOut);
    pirelab.getWireComp(symDemodQPSKSc,delayMatch4_out1_s29,validOut);
end

function hS=addSignal(symDemodQPSKSc,sigName,pirTyp,simulinkRate)
    hS=symDemodQPSKSc.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end