function symDemodPiBy2BPSKHD=elabPiBy2BPSKHDSymDemodNet(~,topNet,~,rate,inpWL)





    pirTyp2=pir_boolean_t;
    pirTyp1=pir_sfixpt_t(inpWL+3,-inpWL);
    pirTyp3=pir_sfixpt_t(35,-32);
    pirTyp4=pir_ufixpt_t(1,0);
    pirTyp5=pir_ufixpt_t(3,0);
    pirTyp6=pir_unsigned_t(8);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt2=numerictype(0,1,0);
    nt3=numerictype(0,3,0);
    nt4=numerictype(0,8,0);
    nt5=numerictype(1,inpWL+3,inpWL);
    nt1=numerictype(1,35,32);

    inportNamePiBy2BPSK={'dataIn','validIn','resetIn','endIn'};
    controlType=pir_ufixpt_t(1,0);
    inType=pir_sfixpt_t(inpWL+3,-inpWL);
    inTypePiBy2BPSK=[inType,controlType,controlType,controlType];
    inDataRatePiBy2BPSK=[rate,rate,rate,rate];

    outportNamePiBy2BPSK={'dataOut','validOut','nonMul8FlagOut'};
    outTypePiBy2BPSK=[pirelab.createPirArrayType(controlType,[8,0]),controlType,controlType];

    symDemodPiBy2BPSKHD=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','symDemodPiBy2BPSKHD',...
    'InportNames',inportNamePiBy2BPSK,...
    'InportTypes',inTypePiBy2BPSK,...
    'InportRates',inDataRatePiBy2BPSK,...
    'OutportNames',outportNamePiBy2BPSK,...
    'OutportTypes',outTypePiBy2BPSK...
    );



    dataIn_s0=symDemodPiBy2BPSKHD.PirInputSignals(1);
    validIn_s1=symDemodPiBy2BPSKHD.PirInputSignals(2);
    rstIn_s2=symDemodPiBy2BPSKHD.PirInputSignals(3);
    endIn_s3=symDemodPiBy2BPSKHD.PirInputSignals(4);

    dataOut=symDemodPiBy2BPSKHD.PirOutputSignals(1);
    validOut=symDemodPiBy2BPSKHD.PirOutputSignals(2);
    nonMul8FlagOut=symDemodPiBy2BPSKHD.PirOutputSignals(3);

    slRate1=rate;

    Delay11_out1_s47=addSignal(symDemodPiBy2BPSKHD,'Delay11_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    delayMatch22_out1_s143=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_out1',pirTyp2,slRate1);
    delayMatch23_out1_s144=addSignal(symDemodPiBy2BPSKHD,'delayMatch23_out1',pirTyp2,slRate1);

    AND_out1_s4=addSignal(symDemodPiBy2BPSKHD,'AND_out1',pirTyp2,slRate1);
    AND1_out1_s5=addSignal(symDemodPiBy2BPSKHD,'AND1_out1',pirTyp2,slRate1);
    AND10_out1_s6=addSignal(symDemodPiBy2BPSKHD,'AND10_out1',pirTyp2,slRate1);
    AND11_out1_s7=addSignal(symDemodPiBy2BPSKHD,'AND11_out1',pirTyp2,slRate1);
    AND12_out1_s8=addSignal(symDemodPiBy2BPSKHD,'AND12_out1',pirTyp2,slRate1);
    AND2_out1_s9=addSignal(symDemodPiBy2BPSKHD,'AND2_out1',pirTyp2,slRate1);
    AND3_out1_s10=addSignal(symDemodPiBy2BPSKHD,'AND3_out1',pirTyp2,slRate1);
    AND4_out1_s11=addSignal(symDemodPiBy2BPSKHD,'AND4_out1',pirTyp2,slRate1);
    AND5_out1_s12=addSignal(symDemodPiBy2BPSKHD,'AND5_out1',pirTyp2,slRate1);
    AND6_out1_s13=addSignal(symDemodPiBy2BPSKHD,'AND6_out1',pirTyp2,slRate1);
    AND7_out1_s14=addSignal(symDemodPiBy2BPSKHD,'AND7_out1',pirTyp2,slRate1);
    AND8_out1_s15=addSignal(symDemodPiBy2BPSKHD,'AND8_out1',pirTyp2,slRate1);
    AND9_out1_s16=addSignal(symDemodPiBy2BPSKHD,'AND9_out1',pirTyp2,slRate1);
    CompareToConstant_out1_s17=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant_out1',pirTyp2,slRate1);
    CompareToConstant1_out1_s18=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant1_out1',pirTyp2,slRate1);
    CompareToConstant10_out1_s19=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant10_out1',pirTyp2,slRate1);
    CompareToConstant2_out1_s20=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant2_out1',pirTyp2,slRate1);
    CompareToConstant3_out1_s21=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant3_out1',pirTyp2,slRate1);
    CompareToConstant4_out1_s22=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant4_out1',pirTyp2,slRate1);
    CompareToConstant5_out1_s23=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant5_out1',pirTyp2,slRate1);
    CompareToConstant6_out1_s24=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant6_out1',pirTyp2,slRate1);
    CompareToConstant7_out1_s25=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant7_out1',pirTyp2,slRate1);
    CompareToConstant8_out1_s26=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant8_out1',pirTyp2,slRate1);
    CompareToConstant9_out1_s27=addSignal(symDemodPiBy2BPSKHD,'Compare To Constant9_out1',pirTyp2,slRate1);
    Constant_out1_s28=addSignal(symDemodPiBy2BPSKHD,'Constant_out1',pirTyp3,slRate1);
    Constant1_out1_s29=addSignal(symDemodPiBy2BPSKHD,'Constant1_out1',pirTyp2,slRate1);
    Constant10_out1_s30=addSignal(symDemodPiBy2BPSKHD,'Constant10_out1',pirTyp2,slRate1);
    Constant11_out1_s31=addSignal(symDemodPiBy2BPSKHD,'Constant11_out1',pirTyp2,slRate1);
    Constant12_out1_s32=addSignal(symDemodPiBy2BPSKHD,'Constant12_out1',pirTyp2,slRate1);
    Constant13_out1_s33=addSignal(symDemodPiBy2BPSKHD,'Constant13_out1',pirTyp2,slRate1);
    Constant14_out1_s34=addSignal(symDemodPiBy2BPSKHD,'Constant14_out1',pirTyp3,slRate1);
    Constant15_out1_s35=addSignal(symDemodPiBy2BPSKHD,'Constant15_out1',pirTyp3,slRate1);
    Constant16_out1_s36=addSignal(symDemodPiBy2BPSKHD,'Constant16_out1',pirTyp4,slRate1);
    Constant2_out1_s37=addSignal(symDemodPiBy2BPSKHD,'Constant2_out1',pirTyp2,slRate1);
    Constant3_out1_s38=addSignal(symDemodPiBy2BPSKHD,'Constant3_out1',pirTyp2,slRate1);
    Constant4_out1_s39=addSignal(symDemodPiBy2BPSKHD,'Constant4_out1',pirTyp2,slRate1);
    Constant5_out1_s40=addSignal(symDemodPiBy2BPSKHD,'Constant5_out1',pirTyp2,slRate1);
    Constant6_out1_s41=addSignal(symDemodPiBy2BPSKHD,'Constant6_out1',pirTyp2,slRate1);
    Constant7_out1_s42=addSignal(symDemodPiBy2BPSKHD,'Constant7_out1',pirTyp2,slRate1);
    Constant8_out1_s43=addSignal(symDemodPiBy2BPSKHD,'Constant8_out1',pirTyp2,slRate1);
    Constant9_out1_s44=addSignal(symDemodPiBy2BPSKHD,'Constant9_out1',pirTyp3,slRate1);
    Delay_out1_s45=addSignal(symDemodPiBy2BPSKHD,'Delay_out1',pirTyp5,slRate1);
    Delay10_out1_s46=addSignal(symDemodPiBy2BPSKHD,'Delay10_out1',pirTyp2,slRate1);
    Delay12_out1_s48=addSignal(symDemodPiBy2BPSKHD,'Delay12_out1',pirTyp2,slRate1);
    Delay13_out1_s49=addSignal(symDemodPiBy2BPSKHD,'Delay13_out1',pirTyp2,slRate1);
    Delay14_out1_s50=addSignal(symDemodPiBy2BPSKHD,'Delay14_out1',pirTyp2,slRate1);
    Delay15_out1_s51=addSignal(symDemodPiBy2BPSKHD,'Delay15_out1',pirTyp2,slRate1);
    Delay16_out1_s52=addSignal(symDemodPiBy2BPSKHD,'Delay16_out1',pirTyp2,slRate1);
    Delay17_out1_s53=addSignal(symDemodPiBy2BPSKHD,'Delay17_out1',pirTyp2,slRate1);
    Delay1_bypass_out1_s54=addSignal(symDemodPiBy2BPSKHD,'Delay1_bypass_out1',pirTyp2,slRate1);
    Delay1_lowered_out1_s55=addSignal(symDemodPiBy2BPSKHD,'Delay1_lowered_out1',pirTyp2,slRate1);
    Delay2_bypass_out1_s56=addSignal(symDemodPiBy2BPSKHD,'Delay2_bypass_out1',pirTyp2,slRate1);
    Delay2_lowered_out1_s57=addSignal(symDemodPiBy2BPSKHD,'Delay2_lowered_out1',pirTyp2,slRate1);
    Delay3_bypass_out1_s58=addSignal(symDemodPiBy2BPSKHD,'Delay3_bypass_out1',pirTyp2,slRate1);
    Delay3_lowered_out1_s59=addSignal(symDemodPiBy2BPSKHD,'Delay3_lowered_out1',pirTyp2,slRate1);
    Delay4_bypass_out1_s60=addSignal(symDemodPiBy2BPSKHD,'Delay4_bypass_out1',pirTyp2,slRate1);
    Delay4_lowered_out1_s61=addSignal(symDemodPiBy2BPSKHD,'Delay4_lowered_out1',pirTyp2,slRate1);
    Delay5_bypass_out1_s62=addSignal(symDemodPiBy2BPSKHD,'Delay5_bypass_out1',pirTyp2,slRate1);
    Delay5_lowered_out1_s63=addSignal(symDemodPiBy2BPSKHD,'Delay5_lowered_out1',pirTyp2,slRate1);
    Delay6_bypass_out1_s64=addSignal(symDemodPiBy2BPSKHD,'Delay6_bypass_out1',pirTyp2,slRate1);
    Delay6_lowered_out1_s65=addSignal(symDemodPiBy2BPSKHD,'Delay6_lowered_out1',pirTyp2,slRate1);
    Delay7_bypass_out1_s66=addSignal(symDemodPiBy2BPSKHD,'Delay7_bypass_out1',pirTyp2,slRate1);
    Delay7_lowered_out1_s67=addSignal(symDemodPiBy2BPSKHD,'Delay7_lowered_out1',pirTyp2,slRate1);
    Delay8_bypass_out1_s68=addSignal(symDemodPiBy2BPSKHD,'Delay8_bypass_out1',pirTyp2,slRate1);
    Delay8_lowered_out1_s69=addSignal(symDemodPiBy2BPSKHD,'Delay8_lowered_out1',pirTyp2,slRate1);
    Delay9_out1_s70=addSignal(symDemodPiBy2BPSKHD,'Delay9_out1',pirTyp2,slRate1);
    Delay_Switch_out1_s71=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch_out1',pirTyp2,slRate1);
    Delay_Switch1_out1_s72=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch1_out1',pirTyp2,slRate1);
    Delay_Switch2_out1_s73=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch2_out1',pirTyp2,slRate1);
    Delay_Switch3_out1_s74=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch3_out1',pirTyp2,slRate1);
    Delay_Switch4_out1_s75=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch4_out1',pirTyp2,slRate1);
    Delay_Switch5_out1_s76=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch5_out1',pirTyp2,slRate1);
    Delay_Switch6_out1_s77=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch6_out1',pirTyp2,slRate1);
    Delay_Switch7_out1_s78=addSignal(symDemodPiBy2BPSKHD,'Delay_Switch7_out1',pirTyp2,slRate1);
    EvenSymCounter_out1_s79=addSignal(symDemodPiBy2BPSKHD,'Even sym counter_out1',pirTyp6,slRate1);
    EvenSymCounter_Initial_Val_out1_s80=addSignal(symDemodPiBy2BPSKHD,'Even sym counter_Initial_Val_out1',pirTyp6,slRate1);
    EvenSymCounter_ctrl_const_out1_s81=addSignal(symDemodPiBy2BPSKHD,'Even sym counter_ctrl_const_out1',pirTyp2,slRate1);
    EvenSymCounter_ctrl_delay_out1_s82=addSignal(symDemodPiBy2BPSKHD,'Even sym counter_ctrl_delay_out1',pirTyp2,slRate1);
    EvenSymCounter_switch_out1_s83=addSignal(symDemodPiBy2BPSKHD,'Even sym counter_switch_out1',pirTyp6,slRate1);
    HDLCounter_out1_s84=addSignal(symDemodPiBy2BPSKHD,'HDL Counter_out1',pirTyp5,slRate1);
    HDLCounter_out1_out1_s85=addSignal(symDemodPiBy2BPSKHD,'HDL Counter_out1_out1',pirTyp5,slRate1);
    HwModeRegister_out1_s86=addSignal(symDemodPiBy2BPSKHD,'HwModeRegister_out1',pirTyp4,slRate1);
    HwModeRegister1_out1_s87=addSignal(symDemodPiBy2BPSKHD,'HwModeRegister1_out1',pirTyp3,slRate1);
    LogicalOperator_out1_s88=addSignal(symDemodPiBy2BPSKHD,'Logical Operator_out1',pirTyp2,slRate1);
    LogicalOperator1_out1_s89=addSignal(symDemodPiBy2BPSKHD,'Logical Operator1_out1',pirTyp2,slRate1);
    LogicalOperator2_out1_s90=addSignal(symDemodPiBy2BPSKHD,'Logical Operator2_out1',pirTyp2,slRate1);
    LogicalOperator3_out1_s91=addSignal(symDemodPiBy2BPSKHD,'Logical Operator3_out1',pirTyp2,slRate1);
    LogicalOperator4_out1_s92=addSignal(symDemodPiBy2BPSKHD,'Logical Operator4_out1',pirTyp2,slRate1);
    LogicalOperator5_out1_s93=addSignal(symDemodPiBy2BPSKHD,'Logical Operator5_out1',pirTyp2,slRate1);
    OR_out1_s94=addSignal(symDemodPiBy2BPSKHD,'OR_out1',pirTyp2,slRate1);
    OR1_out1_s95=addSignal(symDemodPiBy2BPSKHD,'OR1_out1',pirTyp2,slRate1);
    OR2_out1_s96=addSignal(symDemodPiBy2BPSKHD,'OR2_out1',pirTyp2,slRate1);
    OR3_out1_s97=addSignal(symDemodPiBy2BPSKHD,'OR3_out1',pirTyp2,slRate1);
    OR4_out1_s98=addSignal(symDemodPiBy2BPSKHD,'OR4_out1',pirTyp2,slRate1);
    OR5_out1_s99=addSignal(symDemodPiBy2BPSKHD,'OR5_out1',pirTyp2,slRate1);
    OR6_out1_s100=addSignal(symDemodPiBy2BPSKHD,'OR6_out1',pirTyp2,slRate1);
    OR7_out1_s101=addSignal(symDemodPiBy2BPSKHD,'OR7_out1',pirTyp2,slRate1);
    PipelineRegister_out1_s102=addSignal(symDemodPiBy2BPSKHD,'PipelineRegister_out1',pirTyp3,slRate1);
    Product_out1_s103=addSignal(symDemodPiBy2BPSKHD,'Product_out1',pirTyp3,slRate1);
    RelationalOperator_out1_s104=addSignal(symDemodPiBy2BPSKHD,'Relational Operator_out1',pirTyp2,slRate1);
    RelationalOperator1_out1_s105=addSignal(symDemodPiBy2BPSKHD,'Relational Operator1_out1',pirTyp2,slRate1);
    RelationalOperator2_out1_s106=addSignal(symDemodPiBy2BPSKHD,'Relational Operator2_out1',pirTyp2,slRate1);
    RelationalOperator3_out1_s107=addSignal(symDemodPiBy2BPSKHD,'Relational Operator3_out1',pirTyp2,slRate1);
    Switch_out1_s108=addSignal(symDemodPiBy2BPSKHD,'Switch_out1',pirTyp2,slRate1);
    Switch1_out1_s109=addSignal(symDemodPiBy2BPSKHD,'Switch1_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    Switch2_out1_s110=addSignal(symDemodPiBy2BPSKHD,'Switch2_out1',pirTyp2,slRate1);
    Switch3_out1_s111=addSignal(symDemodPiBy2BPSKHD,'Switch3_out1',pirTyp2,slRate1);
    adder_out1_s112=addSignal(symDemodPiBy2BPSKHD,'adder_out1',pirTyp5,slRate1);
    adder1_out1_s113=addSignal(symDemodPiBy2BPSKHD,'adder1_out1',pirTyp6,slRate1);
    bypass_out_out1_s114=addSignal(symDemodPiBy2BPSKHD,'bypass_out_out1',pirTyp2,slRate1);
    bypass_out1_out1_s115=addSignal(symDemodPiBy2BPSKHD,'bypass_out1_out1',pirTyp2,slRate1);
    bypass_out2_out1_s116=addSignal(symDemodPiBy2BPSKHD,'bypass_out2_out1',pirTyp2,slRate1);
    bypass_out3_out1_s117=addSignal(symDemodPiBy2BPSKHD,'bypass_out3_out1',pirTyp2,slRate1);
    bypass_out4_out1_s118=addSignal(symDemodPiBy2BPSKHD,'bypass_out4_out1',pirTyp2,slRate1);
    bypass_out5_out1_s119=addSignal(symDemodPiBy2BPSKHD,'bypass_out5_out1',pirTyp2,slRate1);
    bypass_out6_out1_s120=addSignal(symDemodPiBy2BPSKHD,'bypass_out6_out1',pirTyp2,slRate1);
    bypass_out7_out1_s121=addSignal(symDemodPiBy2BPSKHD,'bypass_out7_out1',pirTyp2,slRate1);
    compare_out1_s122=addSignal(symDemodPiBy2BPSKHD,'compare_out1',pirTyp2,slRate1);
    compare1_out1_s123=addSignal(symDemodPiBy2BPSKHD,'compare1_out1',pirTyp2,slRate1);
    const_out1_s124=addSignal(symDemodPiBy2BPSKHD,'const_out1',pirTyp6,slRate1);
    const1_out1_s125=addSignal(symDemodPiBy2BPSKHD,'const1_out1',pirTyp5,slRate1);
    countFrom_out1_s126=addSignal(symDemodPiBy2BPSKHD,'countFrom_out1',pirTyp6,slRate1);
    countFrom1_out1_s127=addSignal(symDemodPiBy2BPSKHD,'countFrom1_out1',pirTyp5,slRate1);
    delayMatch_out1_s128=addSignal(symDemodPiBy2BPSKHD,'delayMatch_out1',pirTyp1,slRate1);
    delayMatch1_out1_s129=addSignal(symDemodPiBy2BPSKHD,'delayMatch1_out1',pirTyp2,slRate1);
    delayMatch10_out1_s130=addSignal(symDemodPiBy2BPSKHD,'delayMatch10_out1',pirTyp2,slRate1);
    delayMatch11_out1_s131=addSignal(symDemodPiBy2BPSKHD,'delayMatch11_out1',pirTyp2,slRate1);
    delayMatch12_out1_s132=addSignal(symDemodPiBy2BPSKHD,'delayMatch12_out1',pirTyp2,slRate1);
    delayMatch13_out1_s133=addSignal(symDemodPiBy2BPSKHD,'delayMatch13_out1',pirTyp2,slRate1);
    delayMatch14_out1_s134=addSignal(symDemodPiBy2BPSKHD,'delayMatch14_out1',pirTyp2,slRate1);
    delayMatch15_out1_s135=addSignal(symDemodPiBy2BPSKHD,'delayMatch15_out1',pirTyp2,slRate1);
    delayMatch16_out1_s136=addSignal(symDemodPiBy2BPSKHD,'delayMatch16_out1',pirTyp2,slRate1);
    delayMatch17_out1_s137=addSignal(symDemodPiBy2BPSKHD,'delayMatch17_out1',pirTyp2,slRate1);
    delayMatch18_out1_s138=addSignal(symDemodPiBy2BPSKHD,'delayMatch18_out1',pirTyp2,slRate1);
    delayMatch19_out1_s139=addSignal(symDemodPiBy2BPSKHD,'delayMatch19_out1',pirTyp2,slRate1);
    delayMatch2_out1_s140=addSignal(symDemodPiBy2BPSKHD,'delayMatch2_out1',pirTyp6,slRate1);
    delayMatch20_out1_s141=addSignal(symDemodPiBy2BPSKHD,'delayMatch20_out1',pirTyp2,slRate1);
    delayMatch21_out1_s142=addSignal(symDemodPiBy2BPSKHD,'delayMatch21_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    delayMatch3_out1_s145=addSignal(symDemodPiBy2BPSKHD,'delayMatch3_out1',pirTyp2,slRate1);
    delayMatch4_out1_s146=addSignal(symDemodPiBy2BPSKHD,'delayMatch4_out1',pirTyp2,slRate1);
    delayMatch5_out1_s147=addSignal(symDemodPiBy2BPSKHD,'delayMatch5_out1',pirTyp2,slRate1);
    delayMatch6_out1_s148=addSignal(symDemodPiBy2BPSKHD,'delayMatch6_out1',pirTyp2,slRate1);
    delayMatch7_out1_s149=addSignal(symDemodPiBy2BPSKHD,'delayMatch7_out1',pirTyp2,slRate1);
    delayMatch8_out1_s150=addSignal(symDemodPiBy2BPSKHD,'delayMatch8_out1',pirTyp2,slRate1);
    delayMatch9_out1_s151=addSignal(symDemodPiBy2BPSKHD,'delayMatch9_out1',pirTyp2,slRate1);
    mux_out1_s152=addSignal(symDemodPiBy2BPSKHD,'mux_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    mux1_out1_s153=addSignal(symDemodPiBy2BPSKHD,'mux1_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    step_value_out1_s154=addSignal(symDemodPiBy2BPSKHD,'step_value_out1',pirTyp6,slRate1);
    step_value1_out1_s155=addSignal(symDemodPiBy2BPSKHD,'step_value1_out1',pirTyp5,slRate1);
    switch_out1_s156=addSignal(symDemodPiBy2BPSKHD,'switch_out1',pirTyp5,slRate1);
    switch1_out1_s157=addSignal(symDemodPiBy2BPSKHD,'switch1_out1',pirTyp6,slRate1);
    switchEnable_out1_s158=addSignal(symDemodPiBy2BPSKHD,'switchEnable_out1',pirTyp5,slRate1);
    switchEnable1_out1_s159=addSignal(symDemodPiBy2BPSKHD,'switchEnable1_out1',pirTyp6,slRate1);
    switchReset_out1_s160=addSignal(symDemodPiBy2BPSKHD,'switchReset_out1',pirTyp5,slRate1);
    switchReset1_out1_s161=addSignal(symDemodPiBy2BPSKHD,'switchReset1_out1',pirTyp6,slRate1);
    t_out1_s162=addSignal(symDemodPiBy2BPSKHD,'t_out1',pirelab.createPirArrayType(pirTyp2,[8,0]),slRate1);
    delayMatch22_iv_s165=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_iv',pirTyp2,slRate1);
    delayMatch22_delOut_s166=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_delOut',pirTyp2,slRate1);
    delayMatch22_toDel_s167=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_toDel',pirTyp2,slRate1);
    delayMatch22_delOut_s168=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_delOut',pirTyp2,slRate1);
    delayMatch22_toDel_s169=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_toDel',pirTyp2,slRate1);
    delayMatch22_delOut_s170=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_delOut',pirTyp2,slRate1);
    delayMatch22_toDel_s171=addSignal(symDemodPiBy2BPSKHD,'delayMatch22_toDel',pirTyp2,slRate1);
    t_out1_s172=addSignal(symDemodPiBy2BPSKHD,'t_out1',pirTyp2,slRate1);

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant_out1_s28,...
    fi(0,nt1,fiMath1,'hex','736f0255e'),...
    'Constant','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant1_out1_s29,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant1','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant10_out1_s30,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant10','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant11_out1_s31,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'Constant11','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant12_out1_s32,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant12','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant13_out1_s33,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'Constant13','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant14_out1_s34,...
    fi(0,nt1,fiMath1,'hex','0c90fdaa2'),...
    'Constant14','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant15_out1_s35,...
    fi(0,nt1,fiMath1,'hex','5a4d0701a'),...
    'Constant15','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant16_out1_s36,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'Constant16','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant2_out1_s37,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant2','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant3_out1_s38,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant3','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant4_out1_s39,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant4','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant5_out1_s40,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant5','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant6_out1_s41,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant6','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant7_out1_s42,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant7','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant8_out1_s43,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant8','on',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    Constant9_out1_s44,...
    fi(0,nt1,fiMath1,'hex','25b2f8fe6'),...
    'Constant9','on',0,'','','');

    pirelab.getAnnotationComp(symDemodPiBy2BPSKHD,...
    'Data Type Duplicate');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    Delay_out1_s45,...
    1,'Delay',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    AND8_out1_s15,...
    Delay10_out1_s46,...
    4,'Delay10',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Switch1_out1_s109,...
    Delay11_out1_s47,...
    4,'Delay11',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    LogicalOperator_out1_s88,...
    Delay12_out1_s48,...
    1,'Delay12',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    LogicalOperator_out1_s88,...
    Delay13_out1_s49,...
    1,'Delay13',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    LogicalOperator_out1_s88,...
    Delay14_out1_s50,...
    3,'Delay14',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    LogicalOperator_out1_s88,...
    Delay15_out1_s51,...
    2,'Delay15',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    LogicalOperator_out1_s88,...
    Delay16_out1_s52,...
    4,'Delay16',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    AND11_out1_s7,...
    Delay17_out1_s53,...
    5,'Delay17',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out_out1_s114,...
    Delay1_bypass_out1_s54,...
    1,'Delay1_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch_out1_s71,...
    Delay1_lowered_out1_s55,...
    1,'Delay1_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out1_out1_s115,...
    Delay2_bypass_out1_s56,...
    1,'Delay2_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch1_out1_s72,...
    Delay2_lowered_out1_s57,...
    1,'Delay2_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out2_out1_s116,...
    Delay3_bypass_out1_s58,...
    1,'Delay3_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch2_out1_s73,...
    Delay3_lowered_out1_s59,...
    1,'Delay3_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out3_out1_s117,...
    Delay4_bypass_out1_s60,...
    1,'Delay4_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch3_out1_s74,...
    Delay4_lowered_out1_s61,...
    1,'Delay4_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out4_out1_s118,...
    Delay5_bypass_out1_s62,...
    1,'Delay5_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch4_out1_s75,...
    Delay5_lowered_out1_s63,...
    1,'Delay5_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out5_out1_s119,...
    Delay6_bypass_out1_s64,...
    1,'Delay6_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch5_out1_s76,...
    Delay6_lowered_out1_s65,...
    1,'Delay6_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out6_out1_s120,...
    Delay7_bypass_out1_s66,...
    1,'Delay7_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch6_out1_s77,...
    Delay7_lowered_out1_s67,...
    1,'Delay7_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    bypass_out7_out1_s121,...
    Delay8_bypass_out1_s68,...
    1,'Delay8_bypass',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay_Switch7_out1_s78,...
    Delay8_lowered_out1_s69,...
    1,'Delay8_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    validIn_s1,...
    Delay9_out1_s70,...
    1,'Delay9',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    switchReset1_out1_s161,...
    EvenSymCounter_out1_s79,...
    1,'Even sym counter',...
    uint8(0),...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    EvenSymCounter_Initial_Val_out1_s80,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'Even sym counter_Initial_Val','on',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    EvenSymCounter_ctrl_const_out1_s81,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'Even sym counter_ctrl_const','on',0,'','','');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    EvenSymCounter_ctrl_const_out1_s81,...
    EvenSymCounter_ctrl_delay_out1_s82,...
    1,'Even sym counter_ctrl_delay',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    switchReset_out1_s160,...
    HDLCounter_out1_s84,...
    1,'HDL Counter',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Constant16_out1_s36,...
    HwModeRegister_out1_s86,...
    1,'HwModeRegister',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Constant_out1_s28,...
    HwModeRegister1_out1_s87,...
    1,'HwModeRegister1',...
    fi(0,nt1,fiMath1,'hex','000000000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Product_out1_s103,...
    PipelineRegister_out1_s102,...
    2,'PipelineRegister',...
    fi(0,nt1,fiMath1,'hex','000000000'),...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    const_out1_s124,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'const','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    const1_out1_s125,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'const1','off',1,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    countFrom_out1_s126,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'countFrom','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    countFrom1_out1_s127,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'countFrom1','off',1,'','','');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    dataIn_s0,...
    delayMatch_out1_s128,...
    3,'delayMatch',...
    fi(0,nt5,fiMath1,'hex','0000000'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    RelationalOperator1_out1_s105,...
    delayMatch1_out1_s129,...
    3,'delayMatch1',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR3_out1_s97,...
    delayMatch10_out1_s130,...
    3,'delayMatch10',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR3_out1_s97,...
    delayMatch11_out1_s131,...
    3,'delayMatch11',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR4_out1_s98,...
    delayMatch12_out1_s132,...
    3,'delayMatch12',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR4_out1_s98,...
    delayMatch13_out1_s133,...
    3,'delayMatch13',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR5_out1_s99,...
    delayMatch14_out1_s134,...
    3,'delayMatch14',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR5_out1_s99,...
    delayMatch15_out1_s135,...
    3,'delayMatch15',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR6_out1_s100,...
    delayMatch16_out1_s136,...
    3,'delayMatch16',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR6_out1_s100,...
    delayMatch17_out1_s137,...
    3,'delayMatch17',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR7_out1_s101,...
    delayMatch18_out1_s138,...
    3,'delayMatch18',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR7_out1_s101,...
    delayMatch19_out1_s139,...
    3,'delayMatch19',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    EvenSymCounter_switch_out1_s83,...
    delayMatch2_out1_s140,...
    3,'delayMatch2',...
    uint8(0),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    AND8_out1_s15,...
    delayMatch20_out1_s141,...
    3,'delayMatch20',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    mux1_out1_s153,...
    delayMatch21_out1_s142,...
    3,'delayMatch21',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Delay17_out1_s53,...
    delayMatch23_out1_s144,...
    3,'delayMatch23',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    Switch3_out1_s111,...
    delayMatch3_out1_s145,...
    3,'delayMatch3',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR_out1_s94,...
    delayMatch4_out1_s146,...
    3,'delayMatch4',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR_out1_s94,...
    delayMatch5_out1_s147,...
    3,'delayMatch5',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR1_out1_s95,...
    delayMatch6_out1_s148,...
    3,'delayMatch6',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR1_out1_s95,...
    delayMatch7_out1_s149,...
    3,'delayMatch7',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR2_out1_s96,...
    delayMatch8_out1_s150,...
    3,'delayMatch8',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    OR2_out1_s96,...
    delayMatch9_out1_s151,...
    3,'delayMatch9',...
    false,...
    0,0,[],0,0);

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    step_value_out1_s154,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'step_value','off',0,'','','');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    step_value1_out1_s155,...
    fi(0,nt3,fiMath1,'hex','1'),...
    'step_value1','off',0,'','','');

    pirelab.getWireComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_s84,...
    HDLCounter_out1_out1_s85,...
    'HDL Counter_out1_out1');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    delayMatch22_iv_s165,...
    false,...
    'Initial_Val','on',0,'','','');

    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [delayMatch22_iv_s165,AND10_out1_s6],...
    delayMatch22_toDel_s167,...
    rstIn_s2,'reset_in',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    delayMatch22_toDel_s167,...
    delayMatch22_delOut_s166,...
    1,'delayMatch22_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [delayMatch22_iv_s165,delayMatch22_delOut_s166],...
    delayMatch22_toDel_s169,...
    rstIn_s2,'reset_in',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    delayMatch22_toDel_s169,...
    delayMatch22_delOut_s168,...
    1,'delayMatch22_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [delayMatch22_iv_s165,delayMatch22_delOut_s168],...
    delayMatch22_toDel_s171,...
    rstIn_s2,'reset_in',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(symDemodPiBy2BPSKHD,...
    delayMatch22_toDel_s171,...
    delayMatch22_delOut_s170,...
    1,'delayMatch22_lowered',...
    false,...
    0,0,[],0,0);

    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [delayMatch22_iv_s165,delayMatch22_delOut_s170],...
    delayMatch22_out1_s143,...
    rstIn_s2,'reset_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getMuxComp(symDemodPiBy2BPSKHD,...
    [t_out1_s172,t_out1_s172,t_out1_s172,t_out1_s172,t_out1_s172,t_out1_s172,...
    t_out1_s172,t_out1_s172],...
    t_out1_s162,...
    '');

    pirelab.getConstComp(symDemodPiBy2BPSKHD,...
    t_out1_s172,...
    double(0),...
    '','on',1,'','','');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [validIn_s1,CompareToConstant6_out1_s24],...
    AND_out1_s4,...
    'and','AND');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant5_out1_s23,validIn_s1],...
    AND1_out1_s5,...
    'and','AND1');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [Delay13_out1_s49,Delay15_out1_s51,Delay14_out1_s50,Delay16_out1_s52,Delay10_out1_s46],...
    AND10_out1_s6,...
    'and','AND10');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [endIn_s3,AND12_out1_s8],...
    AND11_out1_s7,...
    'and','AND11');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [validIn_s1,CompareToConstant10_out1_s19],...
    AND12_out1_s8,...
    'and','AND12');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant_out1_s17,validIn_s1],...
    AND2_out1_s9,...
    'and','AND2');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant1_out1_s18,validIn_s1],...
    AND3_out1_s10,...
    'and','AND3');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant2_out1_s20,validIn_s1],...
    AND4_out1_s11,...
    'and','AND4');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant3_out1_s21,validIn_s1],...
    AND5_out1_s12,...
    'and','AND5');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant4_out1_s22,validIn_s1],...
    AND6_out1_s13,...
    'and','AND6');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant7_out1_s25,validIn_s1],...
    AND7_out1_s14,...
    'and','AND7');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [CompareToConstant8_out1_s26,AND9_out1_s16],...
    AND8_out1_s15,...
    'and','AND8');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [Delay9_out1_s70,Delay12_out1_s48],...
    AND9_out1_s16,...
    'and','AND9');


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant_out1_s17,...
    '==',fi(0,nt3,fiMath1,'hex','2'),...
    'Compare To Constant',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant1_out1_s18,...
    '==',fi(0,nt3,fiMath1,'hex','3'),...
    'Compare To Constant1',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant10_out1_s19,...
    '~=',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant10',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant2_out1_s20,...
    '==',fi(0,nt3,fiMath1,'hex','4'),...
    'Compare To Constant2',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant3_out1_s21,...
    '==',fi(0,nt3,fiMath1,'hex','5'),...
    'Compare To Constant3',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant4_out1_s22,...
    '==',fi(0,nt3,fiMath1,'hex','6'),...
    'Compare To Constant4',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant5_out1_s23,...
    '==',fi(0,nt3,fiMath1,'hex','1'),...
    'Compare To Constant5',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant6_out1_s24,...
    '==',fi(0,nt3,fiMath1,'hex','0'),...
    'Compare To Constant6',1);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant7_out1_s25,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant7',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    Delay_out1_s45,...
    CompareToConstant8_out1_s26,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant8',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_out1_s85,...
    CompareToConstant9_out1_s27,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'Compare To Constant9',0);


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay1_lowered_out1_s55],...
    Delay_Switch_out1_s71,...
    delayMatch4_out1_s146,'Delay_Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay2_lowered_out1_s57],...
    Delay_Switch1_out1_s72,...
    delayMatch6_out1_s148,'Delay_Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay3_lowered_out1_s59],...
    Delay_Switch2_out1_s73,...
    delayMatch8_out1_s150,'Delay_Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay4_lowered_out1_s61],...
    Delay_Switch3_out1_s74,...
    delayMatch10_out1_s130,'Delay_Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay5_lowered_out1_s63],...
    Delay_Switch4_out1_s75,...
    delayMatch12_out1_s132,'Delay_Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay6_lowered_out1_s65],...
    Delay_Switch5_out1_s76,...
    delayMatch14_out1_s134,'Delay_Switch5',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay7_lowered_out1_s67],...
    Delay_Switch6_out1_s77,...
    delayMatch16_out1_s136,'Delay_Switch6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch_out1_s108,Delay8_lowered_out1_s69],...
    Delay_Switch7_out1_s78,...
    delayMatch18_out1_s138,'Delay_Switch7',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [EvenSymCounter_out1_s79,EvenSymCounter_Initial_Val_out1_s80],...
    EvenSymCounter_switch_out1_s83,...
    EvenSymCounter_ctrl_delay_out1_s82,'Even sym counter_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    rstIn_s2,...
    LogicalOperator_out1_s88,...
    'not','Logical Operator');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [validIn_s1,CompareToConstant9_out1_s27],...
    LogicalOperator1_out1_s89,...
    'and','Logical Operator1');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [RelationalOperator_out1_s104,delayMatch1_out1_s129],...
    LogicalOperator2_out1_s90,...
    'and','Logical Operator2');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [rstIn_s2,AND11_out1_s7],...
    LogicalOperator3_out1_s91,...
    'or','Logical Operator3');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [rstIn_s2,AND11_out1_s7,LogicalOperator1_out1_s89],...
    LogicalOperator4_out1_s92,...
    'or','Logical Operator4');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [RelationalOperator2_out1_s106,RelationalOperator3_out1_s107],...
    LogicalOperator5_out1_s93,...
    'or','Logical Operator5');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND_out1_s4],...
    OR_out1_s94,...
    'or','OR');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND1_out1_s5],...
    OR1_out1_s95,...
    'or','OR1');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND2_out1_s9],...
    OR2_out1_s96,...
    'or','OR2');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND3_out1_s10],...
    OR3_out1_s97,...
    'or','OR3');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND4_out1_s11],...
    OR4_out1_s98,...
    'or','OR4');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND5_out1_s12],...
    OR5_out1_s99,...
    'or','OR5');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND6_out1_s13],...
    OR6_out1_s100,...
    'or','OR6');


    pirelab.getLogicComp(symDemodPiBy2BPSKHD,...
    [AND8_out1_s15,AND7_out1_s14],...
    OR7_out1_s101,...
    'or','OR7');


    pirelab.getMulComp(symDemodPiBy2BPSKHD,...
    [HwModeRegister_out1_s86,HwModeRegister1_out1_s87],...
    Product_out1_s103,...
    'Floor','Wrap','Product','**','',-1,0);


    pirelab.getRelOpComp(symDemodPiBy2BPSKHD,...
    [delayMatch_out1_s128,PipelineRegister_out1_s102],...
    RelationalOperator_out1_s104,...
    '>=',0,'Relational Operator');


    pirelab.getRelOpComp(symDemodPiBy2BPSKHD,...
    [dataIn_s0,Constant9_out1_s44],...
    RelationalOperator1_out1_s105,...
    '<',0,'Relational Operator1');


    pirelab.getRelOpComp(symDemodPiBy2BPSKHD,...
    [dataIn_s0,Constant14_out1_s34],...
    RelationalOperator2_out1_s106,...
    '>=',0,'Relational Operator2');


    pirelab.getRelOpComp(symDemodPiBy2BPSKHD,...
    [dataIn_s0,Constant15_out1_s35],...
    RelationalOperator3_out1_s107,...
    '<',0,'Relational Operator3');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Switch2_out1_s110,delayMatch3_out1_s145],...
    Switch_out1_s108,...
    delayMatch2_out1_s140,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [mux_out1_s152,delayMatch21_out1_s142],...
    Switch1_out1_s109,...
    delayMatch20_out1_s141,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Constant1_out1_s29,Constant11_out1_s31],...
    Switch2_out1_s110,...
    LogicalOperator2_out1_s90,'Switch2',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Constant12_out1_s32,Constant13_out1_s33],...
    Switch3_out1_s111,...
    LogicalOperator5_out1_s93,'Switch3',...
    '>',0,'Floor','Wrap');


    pirelab.getAddComp(symDemodPiBy2BPSKHD,...
    [HDLCounter_out1_s84,step_value1_out1_s155],...
    adder_out1_s112,...
    'Floor','Wrap','adder',pirTyp5,'++');


    pirelab.getAddComp(symDemodPiBy2BPSKHD,...
    [EvenSymCounter_switch_out1_s83,step_value_out1_s154],...
    adder1_out1_s113,...
    'Floor','Wrap','adder1',pirTyp6,'+-');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay1_lowered_out1_s55,Delay1_bypass_out1_s54],...
    bypass_out_out1_s114,...
    delayMatch5_out1_s147,'bypass_out',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay2_lowered_out1_s57,Delay2_bypass_out1_s56],...
    bypass_out1_out1_s115,...
    delayMatch7_out1_s149,'bypass_out1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay3_lowered_out1_s59,Delay3_bypass_out1_s58],...
    bypass_out2_out1_s116,...
    delayMatch9_out1_s151,'bypass_out2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay4_lowered_out1_s61,Delay4_bypass_out1_s60],...
    bypass_out3_out1_s117,...
    delayMatch11_out1_s131,'bypass_out3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay5_lowered_out1_s63,Delay5_bypass_out1_s62],...
    bypass_out4_out1_s118,...
    delayMatch13_out1_s133,'bypass_out4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay6_lowered_out1_s65,Delay6_bypass_out1_s64],...
    bypass_out5_out1_s119,...
    delayMatch15_out1_s135,'bypass_out5',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay7_lowered_out1_s67,Delay7_bypass_out1_s66],...
    bypass_out6_out1_s120,...
    delayMatch17_out1_s137,'bypass_out6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [Delay8_lowered_out1_s69,Delay8_bypass_out1_s68],...
    bypass_out7_out1_s121,...
    delayMatch19_out1_s139,'bypass_out7',...
    '~=',0,'Floor','Wrap');


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    HDLCounter_out1_s84,...
    compare_out1_s122,...
    '==',fi(0,nt3,fiMath1,'hex','7'),...
    'compare',0);


    pirelab.getCompareToValueComp(symDemodPiBy2BPSKHD,...
    EvenSymCounter_switch_out1_s83,...
    compare1_out1_s123,...
    '==',fi(0,nt4,fiMath1,'hex','00'),...
    'compare1',1);


    pirelab.getMuxComp(symDemodPiBy2BPSKHD,...
    [bypass_out_out1_s114,bypass_out1_out1_s115,bypass_out2_out1_s116,bypass_out3_out1_s117,bypass_out4_out1_s118,bypass_out5_out1_s119,...
    bypass_out6_out1_s120,bypass_out7_out1_s121],...
    mux_out1_s152,...
    'mux');


    pirelab.getMuxComp(symDemodPiBy2BPSKHD,...
    [Constant10_out1_s30,Constant3_out1_s38,Constant2_out1_s37,Constant4_out1_s39,Constant5_out1_s40,Constant6_out1_s41,...
    Constant7_out1_s42,Constant8_out1_s43],...
    mux1_out1_s153,...
    'mux');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [countFrom1_out1_s127,adder_out1_s112],...
    switch_out1_s156,...
    compare_out1_s122,'switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [countFrom_out1_s126,adder1_out1_s113],...
    switch1_out1_s157,...
    compare1_out1_s123,'switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getMultiPortSwitchComp(symDemodPiBy2BPSKHD,...
    [validIn_s1,HDLCounter_out1_s84,switch_out1_s156],...
    switchEnable_out1_s158,...
    1,'Zero-based contiguous','Floor','Wrap','switchEnable',[]);


    pirelab.getMultiPortSwitchComp(symDemodPiBy2BPSKHD,...
    [validIn_s1,EvenSymCounter_switch_out1_s83,switch1_out1_s157],...
    switchEnable1_out1_s159,...
    1,'Zero-based contiguous','Floor','Wrap','switchEnable1',[]);


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [const1_out1_s125,switchEnable_out1_s158],...
    switchReset_out1_s160,...
    LogicalOperator4_out1_s92,'switchReset',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodPiBy2BPSKHD,...
    [const_out1_s124,switchEnable1_out1_s159],...
    switchReset1_out1_s161,...
    LogicalOperator3_out1_s91,'switchReset1',...
    '~=',0,'Floor','Wrap');




    pirelab.getWireComp(symDemodPiBy2BPSKHD,Delay11_out1_s47,dataOut);
    pirelab.getWireComp(symDemodPiBy2BPSKHD,delayMatch22_out1_s143,validOut);
    pirelab.getWireComp(symDemodPiBy2BPSKHD,delayMatch23_out1_s144,nonMul8FlagOut);
end

function hS=addSignal(symDemodPiBy2BPSKHD,sigName,pirTyp,simulinkRate)
    hS=symDemodPiBy2BPSKHD.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end