




function[T_in,mu_in,k_in,Pr_in,props]=preprocessTL(mdot,p,h_in,...
    T_TLU,rho_TLU,u_TLU,mu_TLU,k_TLU,Pr_TLU,...
    a,b,c,D_ref,S_ref,Nu_lam)

%#codegen
    coder.allowpcode('plain')


    h_TLU=u_TLU+p./rho_TLU;


    T_in=interp1(h_TLU,T_TLU,h_in,'linear','extrap');
    T_in_limited=min(max(T_in,T_TLU(1)),T_TLU(end));


    mu_in=interp1(T_TLU,mu_TLU,T_in_limited,'linear','extrap');
    k_in=interp1(T_TLU,k_TLU,T_in_limited,'linear','extrap');
    Pr_in=interp1(T_TLU,Pr_TLU,T_in_limited,'linear','extrap');


    props=struct(...
    'mdot',mdot,...
    'T_TLU',T_TLU,...
    'rho_TLU',rho_TLU,...
    'h_TLU',h_TLU,...
    'mu_TLU',mu_TLU,...
    'k_TLU',k_TLU,...
    'Pr_TLU',Pr_TLU,...
    'a',a,...
    'b',b,...
    'c',c,...
    'DS_ratio',D_ref/S_ref,...
    'Nu_lam',Nu_lam);

end