




function[hbar_in,HR_in,cpbar_in,mu_in,k_in,Pr_in,props]=preprocessMA(...
    mdot,p,T_in,x_w_in,x_g_in,...
    R_a,R_w,R_g,T_TLU,log_p_ws_TLU,h_w_vap_TLU,h_a_TLU,h_w_TLU,h_g_TLU,...
    cp_a_coeff,cp_w_coeff,cp_g_coeff,mu_a_TLU,mu_w_TLU,mu_g_TLU,...
    k_a_TLU,k_w_TLU,k_g_TLU,Pr_a_TLU,Pr_w_TLU,Pr_g_TLU,RH_ws,x_ag_min,...
    a,b,c,D_ref,S_ref,Nu_lam)

%#codegen
    coder.allowpcode('plain')


    if 1-x_w_in>=x_ag_min
        x_ag_in_smooth=1-x_w_in;
    elseif 1-x_w_in>=-10*x_ag_min
        x_ag_in_smooth=x_ag_min*exp((1-x_w_in-x_ag_min)/x_ag_min);
    else
        x_ag_in_smooth=x_ag_min*exp(-11);
    end
    x_w_in_smooth=1-x_ag_in_smooth;


    HR_in=x_w_in_smooth/x_ag_in_smooth;



    GR=x_g_in/x_ag_in_smooth;


    R_ag=R_a+(R_g-R_a)*GR;


    h_ag_TLU=h_a_TLU+(h_g_TLU-h_a_TLU)*GR;


    cp_ag_coeff=cp_a_coeff+(cp_g_coeff-cp_a_coeff)*GR;


    h_ag_in=interp1(T_TLU,h_ag_TLU,T_in,'linear','extrap');
    h_w_in=interp1(T_TLU,h_w_TLU,T_in,'linear','extrap');
    hbar_in=h_ag_in+HR_in*h_w_in;


    mdot_ag=x_ag_in_smooth*mdot;



    hbar_in_TLU=h_ag_TLU+HR_in*h_w_TLU;



    cpbar_in_coeff=cp_ag_coeff+HR_in*cp_w_coeff;



    R_in=(1-x_w_in-x_g_in)*R_a+x_w_in*R_w+x_g_in*R_g;
    y_w_in=x_w_in*R_w/R_in;
    y_g_in=x_g_in*R_g/R_in;
    y_a_in=1-y_w_in-y_g_in;



    mu_in_TLU=y_a_in*mu_a_TLU+y_w_in*mu_w_TLU+y_g_in*mu_g_TLU;
    k_in_TLU=y_a_in*k_a_TLU+y_w_in*k_w_TLU+y_g_in*k_g_TLU;
    Pr_in_TLU=y_a_in*Pr_a_TLU+y_w_in*Pr_w_TLU+y_g_in*Pr_g_TLU;



    T_in_limited=min(max(T_in,T_TLU(1)),T_TLU(end));
    cpbar_in=[1,T_in_limited,T_in_limited^2]*cpbar_in_coeff;



    mu_in=interp1(T_TLU,mu_in_TLU,T_in_limited,'linear','extrap');
    k_in=interp1(T_TLU,k_in_TLU,T_in_limited,'linear','extrap');
    Pr_in=interp1(T_TLU,Pr_in_TLU,T_in_limited,'linear','extrap');


    props=struct(...
    'T_TLU',T_TLU,...
    'h_ag_TLU',h_ag_TLU,...
    'h_w_TLU',h_w_TLU,...
    'h_l_TLU',h_w_TLU-h_w_vap_TLU,...
    'hbar_in_TLU',hbar_in_TLU,...
    'cp_ag_coeff',cp_ag_coeff,...
    'cp_w_coeff',cp_w_coeff,...
    'cpbar_in_coeff',cpbar_in_coeff,...
    'mu_TLU',[mu_a_TLU(:),mu_w_TLU(:),mu_g_TLU(:)],...
    'k_TLU',[k_a_TLU(:),k_w_TLU(:),k_g_TLU(:)],...
    'Pr_TLU',[Pr_a_TLU(:),Pr_w_TLU(:),Pr_g_TLU(:)],...
    'mu_in_TLU',mu_in_TLU,...
    'k_in_TLU',k_in_TLU,...
    'Pr_in_TLU',Pr_in_TLU,...
    'log_p_ws_TLU',log_p_ws_TLU,...
    'HR_in',HR_in,...
    'mdot_ag',mdot_ag,...
    'mdot_in',mdot,...
    'p',p,...
    'R_a',R_a,...
    'R_w',R_w,...
    'R_g',R_g,...
    'R_ag',R_ag,...
    'GR',GR,...
    'RH_ws',RH_ws,...
    'x_ag_min',x_ag_min,...
    'a',a,...
    'b',b,...
    'c',c,...
    'DS_ratio',D_ref/S_ref,...
    'Nu_lam',Nu_lam);

end