function h=EditWidget(propName,widgetName,widgetToolTip,sourceObj)




    if nargin~=4
        h=[];

        error(message('TLMGenerator:TLMTargetCC:EditWidget'));
    end

    h=tlmg.EditWidget;


    h.propName=propName;

    tags=tlmg.EditWidget.getWidgetTags(sourceObj,propName);


    h.labelW=struct(...
    'Type','text',...
    'Name',widgetName,...
    'Buddy',tags.editW,...
    'ToolTip',widgetToolTip,...
    'Tag',tags.labelW,...
    'Visible',true,...
    'Enabled',true...
    );

    h.editW=struct(...
    'Type','edit',...
    'ToolTip',widgetToolTip,...
    'Tag',tags.editW,...
    'ObjectProperty',h.propName,...
    'Source',sourceObj,...
    'Visible',true,...
    'Enabled',true...
    );


