


function blks=addTestScenario(testplan)

    switch(testplan)
    case 'ConstantRadius'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Constant Radius'};
    case 'DoubleLaneChange'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change/Double Lane Change';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Double Lane Change/ Fdbk'};
    case 'DriveCycle'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Bus↵Creator';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Bus↵Creator1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Constant';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Constant1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Constant2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Constant3';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Data Type Conversion';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Drive Cycle Source';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Ground';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Ground1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Ground2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/Signal Specification';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/DriveCycle/ Fdbk'};
    case 'Fishhook'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/Bus↵Creator';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/Fishhook';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/Ground';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/Ground1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/Ground2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Fishhook/ Fdbk'};
    case 'IncreasingSteer'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/Bus↵Creator';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/Ground';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/Ground1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/Ground2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/Increasing Steer';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Increasing Steer/ Fdbk'};
    case 'SinewithDwell'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/Bus↵Creator';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/Ground';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/Ground1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/Ground2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/Sine With Dwell';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Sine with Dwell/ Fdbk'};
    case 'SweptSine'
        blks={'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/VehFdbk ';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/Bus↵Creator';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/Ground';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/Ground1';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/Ground2';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/Swept Sine';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/ Vis';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/ Ref';...
        'VirtualVehicleTemplate/VehicleSenario/Reference Generator/Swept Sine/ Fdbk'};
    case 'Enable'
        blks={'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/VehFdbk';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Brake';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Bus↵Selector';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Bus↵Selector2';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Constant1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Constant2';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion10';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion12';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion4';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion5';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion6';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion7';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion8';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Data Type Conversion9';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Demux';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Demux1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Demux2';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Demux3';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/From';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/From1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Goto';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Goto1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Highbeam';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Integrator';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Left Signal';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Lowbeam';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Mux';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/Body Roll';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/Body Ptich';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/Body Yaw';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontLeft Pitch';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontRight Pitch';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearLeft Pitch';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearRight Ptich';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontLeft Roll';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontRight Roll';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearLeft Roll';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearRight Roll';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontLeft Yaw';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontRight Yaw';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearLeft Yaw';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearRight Yaw';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/AllParts';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/Body';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelFrontRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/WheelRearRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Rotation Concatenation/ConcatOut';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/BodyX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/BodyY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/BodyZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontLeftX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontRightX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearLeftX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearRightX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontLeftY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontRightY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearLeftY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearRightY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontLeftZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontRightZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearLeftZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearRightZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/AllParts';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/Body';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelFrontRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/WheelRearRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Part Translation Concatenation/ConcatOut';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Rate Transition';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Reverse';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Right Signal';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant1';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant10';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant11';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant12';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant17';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant2';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant3';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant32';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant33';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant4';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant5';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant6';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant7';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant8';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/Constant9';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/BodyX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/BodyY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/BodyZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontLeftX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontLeftY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontLeftZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontRightX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontRightY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontRightZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearLeftX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearLeftY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearLeftZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearRightX';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearRightY';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearRightZ';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/AllParts';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/Body';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelFrontRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearLeft';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/WheelRearRight';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/PartConcatenation/ConcatOut';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Scale/ScaleOut';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Simulation 3D Scene Configuration';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Simulation 3D Vehicle';...
        'VirtualVehicleTemplate/VehicleSenario/Engine3D/3D Engine/Unary Minus'};
    otherwise
        blks={};
    end