function[out]=createEmptySimplifiedSynchronousInitialConditions()%#codegen




    coder.allowpcode('plain');

    out=struct(...
    'si_Vmag0',nan,...
    'si_Vang0',nan,...
    'si_Pt0',nan,...
    'si_Qt0',nan,...
    'pu_Pt0',nan,...
    'pu_Qt0',nan,...
    'pu_Vmag0',nan,...
    'pu_It0',nan,...
    'phi0',nan,...
    'phi0_deg',nan,...
    'delta0',nan,...
    'delta0_deg',nan,...
    'pu_vd0',nan,...
    'pu_vq0',nan,...
    'pu_ed0',nan,...
    'pu_eq0',nan,...
    'pu_Emag0',nan,...
    'si_Emag0',nan,...
    'pu_id0',nan,...
    'pu_iq0',nan,...
    'si_torque0',nan,...
    'pu_torque0',nan,...
    'si_Pm0',nan,...
    'pu_Pm0',nan,...
    'angular_position0',nan,...
    'pu_psid0',nan,...
    'pu_psiq0',nan,...
    'pu_psi00',nan,...
    'si_ia0',nan,...
    'si_ib0',nan,...
    'si_ic0',nan);
end