function[synchronous_saturation]=createEmptySynchronousSaturation()%#codegen




    coder.allowpcode('plain');

    sub_struct=struct(...
    'ifd',nan,...
    'Vag',nan,...
    'L_unsaturated',nan,...
    'saturated_gradient',nan,...
    'saturated_offset',nan);

    synchronous_saturation=struct(...
    'original',sub_struct,...
    'derived',sub_struct,...
    'psi',nan,...
    'L_a',nan,...
    'K_s',nan);
end

