function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CBpMz0QAVPCeGac3Qny07Jgn5RAgO/at0UNReTaIPFPCzgBD9e3VccpMA6'...
        ,'g41a+XB13jtbmg5WHKwog3ADtEBnoXXlNGq7tdDlobx/+lVSMaL+19H1Z+if'...
        ,'kjzf7fbh5NN6sPaYlW2wYwg8+55S64tzsR4VnCRj/MvVBceTsuCDVJ+JoLbl'...
        ,'rxNldjwy8pkv5K6G8Uv8ac/OgMCt+TxE+CvyHvANcjPMwebMNXYRh4lhuusd'...
        ,'B84Srjh8fZv+nOaOlU4='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end