function buffInpGenAddr32APSK=elabBuffInpGenAddr32APSK(~,topNet,~,rate)






    pirTyp2=pir_boolean_t;
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp4=pir_ufixpt_t(3,0);
    pirTyp3=pir_ufixpt_t(5,0);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt1=numerictype(0,1,0);
    nt2=numerictype(0,3,0);

    inBuffInpGen32APSKAddr={'dataIn','validIn','resetIn'};
    controlType=pir_ufixpt_t(1,0);
    inTypeBuffInpGen32APSKAddr=[controlType,controlType,controlType];
    inRateBuffInpGen32APSKAddr=[rate,rate,rate];

    outBuffInpGen32APSKAddr={'addr32APSK','addr32APSKValidOut'};
    outTypeBuffInpGen32APSKAddr=[pir_ufixpt_t(5,0),controlType];

    buffInpGenAddr32APSK=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','buffInpGenAddr32APSK',...
    'InportNames',inBuffInpGen32APSKAddr,...
    'InportTypes',inTypeBuffInpGen32APSKAddr,...
    'InportRates',inRateBuffInpGen32APSKAddr,...
    'OutportNames',outBuffInpGen32APSKAddr,...
    'OutportTypes',outTypeBuffInpGen32APSKAddr...
    );


    dataIn_s0=buffInpGenAddr32APSK.PirInputSignals(1);
    validIn_s1=buffInpGenAddr32APSK.PirInputSignals(2);
    resetIn_s2=buffInpGenAddr32APSK.PirInputSignals(3);

    addr32APSK=buffInpGenAddr32APSK.PirOutputSignals(1);
    addr32APSKValidOut=buffInpGenAddr32APSK.PirOutputSignals(2);

    slRate1=rate;

    Switch_out1_s41=addSignal(buffInpGenAddr32APSK,'Switch_out1',pirTyp3,slRate1);

    LogicalOperator2_out1_s31=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator2_out1'),pirTyp2,slRate1);

    APSK32_out1_s3=addSignal(buffInpGenAddr32APSK,'APSK32_out1',pirTyp3,slRate1);
    CompareToConstant_out1_s4=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant_out1'),pirTyp2,slRate1);
    CompareToConstant1_out1_s5=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant1_out1'),pirTyp2,slRate1);
    CompareToConstant2_out1_s6=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant2_out1'),pirTyp2,slRate1);
    CompareToConstant3_out1_s7=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant3_out1'),pirTyp2,slRate1);
    CompareToConstant4_out1_s8=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant4_out1'),pirTyp2,slRate1);
    CompareToConstant5_out1_s9=addSignal(buffInpGenAddr32APSK,sprintf('Compare\nTo Constant5_out1'),pirTyp2,slRate1);
    Constant_out1_s10=addSignal(buffInpGenAddr32APSK,'Constant_out1',pirTyp4,slRate1);
    Constant4_out1_s11=addSignal(buffInpGenAddr32APSK,'Constant4_out1',pirTyp1,slRate1);
    Delay_out1_s12=addSignal(buffInpGenAddr32APSK,'Delay_out1',pirTyp4,slRate1);
    Delay1_out1_s13=addSignal(buffInpGenAddr32APSK,'Delay1_out1',pirTyp1,slRate1);
    Delay2_out1_s14=addSignal(buffInpGenAddr32APSK,'Delay2_out1',pirTyp1,slRate1);
    Delay3_out1_s15=addSignal(buffInpGenAddr32APSK,'Delay3_out1',pirTyp2,slRate1);
    Delay4_out1_s16=addSignal(buffInpGenAddr32APSK,'Delay4_out1',pirTyp1,slRate1);
    Delay5_out1_s17=addSignal(buffInpGenAddr32APSK,'Delay5_out1',pirTyp1,slRate1);
    Delay6_out1_s18=addSignal(buffInpGenAddr32APSK,'Delay6_out1',pirTyp1,slRate1);
    Delay7_out1_s19=addSignal(buffInpGenAddr32APSK,'Delay7_out1',pirTyp4,slRate1);
    Delay8_out1_s20=addSignal(buffInpGenAddr32APSK,'Delay8_out1',pirTyp4,slRate1);
    Delay9_out1_s21=addSignal(buffInpGenAddr32APSK,'Delay9_out1',pirTyp2,slRate1);
    HDLCounter_out1_s22=addSignal(buffInpGenAddr32APSK,'HDL Counter_out1',pirTyp4,slRate1);
    LogicalOperator_out1_s23=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator_out1'),pirTyp2,slRate1);
    LogicalOperator1_out1_s24=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator1_out1'),pirTyp2,slRate1);
    LogicalOperator10_out1_s25=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator10_out1'),pirTyp2,slRate1);
    LogicalOperator11_out1_s26=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator11_out1'),pirTyp2,slRate1);
    LogicalOperator12_out1_s27=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator12_out1'),pirTyp2,slRate1);
    LogicalOperator13_out1_s28=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator13_out1'),pirTyp2,slRate1);
    LogicalOperator14_out1_s29=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator14_out1'),pirTyp2,slRate1);
    LogicalOperator17_out1_s30=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator17_out1'),pirTyp2,slRate1);
    LogicalOperator3_out1_s32=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator3_out1'),pirTyp2,slRate1);
    LogicalOperator4_out1_s33=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator4_out1'),pirTyp2,slRate1);
    LogicalOperator5_out1_s34=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator5_out1'),pirTyp2,slRate1);
    LogicalOperator6_out1_s35=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator6_out1'),pirTyp2,slRate1);
    LogicalOperator7_out1_s36=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator7_out1'),pirTyp2,slRate1);
    LogicalOperator8_out1_s37=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator8_out1'),pirTyp2,slRate1);
    LogicalOperator9_out1_s38=addSignal(buffInpGenAddr32APSK,sprintf('Logical\nOperator9_out1'),pirTyp2,slRate1);
    RelationalOperator_out1_s39=addSignal(buffInpGenAddr32APSK,sprintf('Relational\nOperator_out1'),pirTyp2,slRate1);
    RelationalOperator1_out1_s40=addSignal(buffInpGenAddr32APSK,sprintf('Relational\nOperator1_out1'),pirTyp2,slRate1);
    y_s48=addSignal(buffInpGenAddr32APSK,'y',pirTyp3,slRate1);
    y_s49=addSignal(buffInpGenAddr32APSK,'y',pirTyp3,slRate1);
    Constant_out1_s50=addSignal(buffInpGenAddr32APSK,'Constant_out1',pirTyp1,slRate1);
    Constant1_out1_s51=addSignal(buffInpGenAddr32APSK,'Constant1_out1',pirTyp1,slRate1);
    Constant2_out1_s52=addSignal(buffInpGenAddr32APSK,'Constant2_out1',pirTyp1,slRate1);
    Constant3_out1_s53=addSignal(buffInpGenAddr32APSK,'Constant3_out1',pirTyp1,slRate1);
    Constant4_out1_s54=addSignal(buffInpGenAddr32APSK,'Constant4_out1',pirTyp1,slRate1);
    Switch1_out1_s55=addSignal(buffInpGenAddr32APSK,'Switch1_out1',pirTyp3,slRate1);
    HDLCounter_out1_s61=addSignal(buffInpGenAddr32APSK,'HDL Counter_out1',pirTyp4,slRate1);
    count_s62=addSignal(buffInpGenAddr32APSK,'count',pirTyp4,slRate1);
    count_reset_s63=addSignal(buffInpGenAddr32APSK,'count_reset',pirTyp4,slRate1);
    count_step_s64=addSignal(buffInpGenAddr32APSK,'count_step',pirTyp4,slRate1);
    count_from_s65=addSignal(buffInpGenAddr32APSK,'count_from',pirTyp4,slRate1);
    count_value_s66=addSignal(buffInpGenAddr32APSK,'count_value',pirTyp4,slRate1);
    need_to_wrap_s67=addSignal(buffInpGenAddr32APSK,'need_to_wrap',pirTyp2,slRate1);
    count_s68=addSignal(buffInpGenAddr32APSK,'count',pirTyp4,slRate1);
    count_s69=addSignal(buffInpGenAddr32APSK,'count',pirTyp4,slRate1);
    HDLCounter_out_s70=addSignal(buffInpGenAddr32APSK,'HDL Counter_out',pirTyp4,slRate1);
    HDLCounter_Initial_Val_out_s71=addSignal(buffInpGenAddr32APSK,'HDL Counter_Initial_Val_out',pirTyp4,slRate1);
    HDLCounter_ctrl_const_out_s72=addSignal(buffInpGenAddr32APSK,'HDL Counter_ctrl_const_out',pirTyp2,slRate1);
    HDLCounter_ctrl_delay_out_s73=addSignal(buffInpGenAddr32APSK,'HDL Counter_ctrl_delay_out',pirTyp2,slRate1);
    Delay1_delOut_s74=addSignal(buffInpGenAddr32APSK,'Delay1_delOut',pirTyp1,slRate1);
    Delay1_ectrl_s75=addSignal(buffInpGenAddr32APSK,'Delay1_ectrl',pirTyp1,slRate1);
    Delay1_last_value_s76=addSignal(buffInpGenAddr32APSK,'Delay1_last_value',pirTyp1,slRate1);
    Delay2_delOut_s77=addSignal(buffInpGenAddr32APSK,'Delay2_delOut',pirTyp1,slRate1);
    Delay2_ectrl_s78=addSignal(buffInpGenAddr32APSK,'Delay2_ectrl',pirTyp1,slRate1);
    Delay2_last_value_s79=addSignal(buffInpGenAddr32APSK,'Delay2_last_value',pirTyp1,slRate1);
    Delay4_delOut_s80=addSignal(buffInpGenAddr32APSK,'Delay4_delOut',pirTyp1,slRate1);
    Delay4_ectrl_s81=addSignal(buffInpGenAddr32APSK,'Delay4_ectrl',pirTyp1,slRate1);
    Delay4_last_value_s82=addSignal(buffInpGenAddr32APSK,'Delay4_last_value',pirTyp1,slRate1);
    Delay5_delOut_s83=addSignal(buffInpGenAddr32APSK,'Delay5_delOut',pirTyp1,slRate1);
    Delay5_ectrl_s84=addSignal(buffInpGenAddr32APSK,'Delay5_ectrl',pirTyp1,slRate1);
    Delay5_last_value_s85=addSignal(buffInpGenAddr32APSK,'Delay5_last_value',pirTyp1,slRate1);
    Delay6_delOut_s86=addSignal(buffInpGenAddr32APSK,'Delay6_delOut',pirTyp1,slRate1);
    Delay6_ectrl_s87=addSignal(buffInpGenAddr32APSK,'Delay6_ectrl',pirTyp1,slRate1);
    Delay6_last_value_s88=addSignal(buffInpGenAddr32APSK,'Delay6_last_value',pirTyp1,slRate1);

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant_out1_s50,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant','on',1,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant1_out1_s51,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant1','on',1,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant2_out1_s52,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant2','on',1,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant3_out1_s53,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant3','on',1,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant4_out1_s54,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant4','on',1,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant_out1_s10,...
    fi(0,nt2,fiMath1,'hex','5'),...
    'Constant','on',0,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    Constant4_out1_s11,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant4','on',1,'','','');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    Delay_out1_s12,...
    1,'Delay',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    validIn_s1,...
    Delay3_out1_s15,...
    1,'Delay3',...
    false,...
    0,0,[],0,0);

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Constant_out1_s10,...
    Delay7_out1_s19,...
    1,'Delay7',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Constant_out1_s10,...
    Delay8_out1_s20,...
    1,'Delay8',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    LogicalOperator14_out1_s29,...
    Delay9_out1_s21,...
    1,'Delay9',...
    false,...
    0,0,[],0,0);

    hC_13=pirelab.getConstComp(buffInpGenAddr32APSK,...
    count_step_s64,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'step_value','off',0,'','','');

    hC_13.addComment(sprintf(['  // Count limited, Unsigned Counter\n  //  initial value   = 1\n'...
    ,'  //  step value      = 1\n  //  count to value  = 5']));

    pirelab.getAddComp(buffInpGenAddr32APSK,...
    [HDLCounter_out1_s61,count_step_s64],...
    count_s62,...
    'Floor','Wrap','adder',pirTyp4,'++');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    count_from_s65,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'countFrom','off',0,'','','');

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [count_from_s65,count_s62],...
    count_value_s66,...
    need_to_wrap_s67,'switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s61,...
    need_to_wrap_s67,...
    '==',fi(0,nt2,fiMath1,'hex','5'),...
    'compare',0);

    pirelab.getMultiPortSwitchComp(buffInpGenAddr32APSK,...
    [validIn_s1,HDLCounter_out1_s61,count_value_s66],...
    count_s68,...
    1,'Zero-based contiguous','Floor','Wrap','switchEnable',[]);

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    count_reset_s63,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'const','off',0,'','','');

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [count_reset_s63,count_s68],...
    count_s69,...
    LogicalOperator12_out1_s27,'switchReset',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    count_s69,...
    HDLCounter_out_s70,...
    1,'HDL Counter',...
    double(0),...
    0,0,[],0,0);

    pirelab.getWireComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s61,...
    HDLCounter_out1_s22,...
    'HDL Counter_out1');

    pirelab.getWireComp(buffInpGenAddr32APSK,...
    Switch1_out1_s55,...
    APSK32_out1_s3,...
    'APSK32_out1');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    HDLCounter_Initial_Val_out_s71,...
    fi(0,nt2,fiMath1,'hex','1'),...
    'HDL Counter_Initial_Val','on',0,'','','');

    pirelab.getConstComp(buffInpGenAddr32APSK,...
    HDLCounter_ctrl_const_out_s72,...
    1,...
    'HDL Counter_ctrl_const');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    HDLCounter_ctrl_const_out_s72,...
    HDLCounter_ctrl_delay_out_s73,...
    1,'HDL Counter_ctrl_delay',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [HDLCounter_out_s70,HDLCounter_Initial_Val_out_s71],...
    HDLCounter_out1_s61,...
    HDLCounter_ctrl_delay_out_s73,'HDL Counter_switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [dataIn_s0,Delay1_delOut_s74],...
    Delay1_ectrl_s75,...
    LogicalOperator4_out1_s33,'Delay_Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay1_ectrl_s75,...
    Delay1_delOut_s74,...
    1,'Delay1_lowered',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [Delay1_delOut_s74,Delay1_last_value_s76],...
    Delay1_out1_s13,...
    LogicalOperator4_out1_s33,'bypass_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay1_out1_s13,...
    Delay1_last_value_s76,...
    1,'Delay1_bypass',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [dataIn_s0,Delay2_delOut_s77],...
    Delay2_ectrl_s78,...
    LogicalOperator3_out1_s32,'Delay_Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay2_ectrl_s78,...
    Delay2_delOut_s77,...
    1,'Delay2_lowered',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [Delay2_delOut_s77,Delay2_last_value_s79],...
    Delay2_out1_s14,...
    LogicalOperator3_out1_s32,'bypass_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay2_out1_s14,...
    Delay2_last_value_s79,...
    1,'Delay2_bypass',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [dataIn_s0,Delay4_delOut_s80],...
    Delay4_ectrl_s81,...
    LogicalOperator8_out1_s37,'Delay_Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay4_ectrl_s81,...
    Delay4_delOut_s80,...
    1,'Delay4_lowered',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [Delay4_delOut_s80,Delay4_last_value_s82],...
    Delay4_out1_s16,...
    LogicalOperator8_out1_s37,'bypass_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay4_out1_s16,...
    Delay4_last_value_s82,...
    1,'Delay4_bypass',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [dataIn_s0,Delay5_delOut_s83],...
    Delay5_ectrl_s84,...
    LogicalOperator7_out1_s36,'Delay_Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay5_ectrl_s84,...
    Delay5_delOut_s83,...
    1,'Delay5_lowered',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [Delay5_delOut_s83,Delay5_last_value_s85],...
    Delay5_out1_s17,...
    LogicalOperator7_out1_s36,'bypass_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay5_out1_s17,...
    Delay5_last_value_s85,...
    1,'Delay5_bypass',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [dataIn_s0,Delay6_delOut_s86],...
    Delay6_ectrl_s87,...
    LogicalOperator11_out1_s26,'Delay_Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay6_ectrl_s87,...
    Delay6_delOut_s86,...
    1,'Delay6_lowered',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);

    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [Delay6_delOut_s86,Delay6_last_value_s88],...
    Delay6_out1_s18,...
    LogicalOperator11_out1_s26,'bypass_out',...
    '~=',0,'Floor','Wrap');

    pirelab.getIntDelayComp(buffInpGenAddr32APSK,...
    Delay6_out1_s18,...
    Delay6_last_value_s88,...
    1,'Delay6_bypass',...
    double(0),...
    0,0,[],0,0);


    pirelab.getBitConcatComp(buffInpGenAddr32APSK,...
    [Delay1_out1_s13,Delay2_out1_s14,Delay4_out1_s16,Delay5_out1_s17,Delay6_out1_s18],...
    y_s48,...
    'Bit Concat');


    pirelab.getBitConcatComp(buffInpGenAddr32APSK,...
    [Constant_out1_s50,Constant1_out1_s51,Constant2_out1_s52,Constant3_out1_s53,Constant4_out1_s54],...
    y_s49,...
    'Bit Concat1');


    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [y_s48,y_s49],...
    Switch1_out1_s55,...
    LogicalOperator2_out1_s31,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    CompareToConstant_out1_s4,...
    '==',fi(0,nt2,fiMath1,'hex','2'),...
    sprintf('Compare\nTo Constant'),0);


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    CompareToConstant1_out1_s5,...
    '==',fi(0,nt2,fiMath1,'hex','3'),...
    sprintf('Compare\nTo Constant1'),0);


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    CompareToConstant2_out1_s6,...
    '==',fi(0,nt2,fiMath1,'hex','4'),...
    sprintf('Compare\nTo Constant2'),0);


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    CompareToConstant3_out1_s7,...
    '==',fi(0,nt2,fiMath1,'hex','5'),...
    sprintf('Compare\nTo Constant3'),0);


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    Delay7_out1_s19,...
    CompareToConstant4_out1_s8,...
    '==',fi(0,nt2,fiMath1,'hex','5'),...
    sprintf('Compare\nTo Constant4'),0);


    pirelab.getCompareToValueComp(buffInpGenAddr32APSK,...
    HDLCounter_out1_s22,...
    CompareToConstant5_out1_s9,...
    '==',fi(0,nt2,fiMath1,'hex','1'),...
    sprintf('Compare\nTo Constant5'),0);


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [validIn_s1,CompareToConstant5_out1_s9],...
    LogicalOperator_out1_s23,...
    'and',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [validIn_s1,CompareToConstant_out1_s4],...
    LogicalOperator1_out1_s24,...
    'and',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [validIn_s1,CompareToConstant3_out1_s7],...
    LogicalOperator10_out1_s25,...
    'and',sprintf('Logical\nOperator10'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,LogicalOperator10_out1_s25],...
    LogicalOperator11_out1_s26,...
    'or',sprintf('Logical\nOperator11'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator5_out1_s34,resetIn_s2],...
    LogicalOperator12_out1_s27,...
    'or',sprintf('Logical\nOperator12'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [Delay3_out1_s15,Delay9_out1_s21],...
    LogicalOperator13_out1_s28,...
    'and',sprintf('Logical\nOperator13'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    resetIn_s2,...
    LogicalOperator14_out1_s29,...
    'not',sprintf('Logical\nOperator14'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,CompareToConstant4_out1_s8],...
    LogicalOperator17_out1_s30,...
    'and',sprintf('Logical\nOperator17'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [RelationalOperator1_out1_s40,LogicalOperator13_out1_s28],...
    LogicalOperator2_out1_s31,...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,LogicalOperator1_out1_s24],...
    LogicalOperator3_out1_s32,...
    'or',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,LogicalOperator_out1_s23],...
    LogicalOperator4_out1_s33,...
    'or',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [RelationalOperator_out1_s39,validIn_s1],...
    LogicalOperator5_out1_s34,...
    'and',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [validIn_s1,CompareToConstant1_out1_s5],...
    LogicalOperator6_out1_s35,...
    'and',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,LogicalOperator9_out1_s38],...
    LogicalOperator7_out1_s36,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [LogicalOperator2_out1_s31,LogicalOperator6_out1_s35],...
    LogicalOperator8_out1_s37,...
    'or',sprintf('Logical\nOperator8'));


    pirelab.getLogicComp(buffInpGenAddr32APSK,...
    [validIn_s1,CompareToConstant2_out1_s6],...
    LogicalOperator9_out1_s38,...
    'and',sprintf('Logical\nOperator9'));


    pirelab.getRelOpComp(buffInpGenAddr32APSK,...
    [Constant_out1_s10,HDLCounter_out1_s22],...
    RelationalOperator_out1_s39,...
    '==',0,sprintf('Relational\nOperator'));


    pirelab.getRelOpComp(buffInpGenAddr32APSK,...
    [Delay8_out1_s20,Delay_out1_s12],...
    RelationalOperator1_out1_s40,...
    '==',0,sprintf('Relational\nOperator1'));


    pirelab.getSwitchComp(buffInpGenAddr32APSK,...
    [APSK32_out1_s3,Constant4_out1_s11],...
    Switch_out1_s41,...
    LogicalOperator17_out1_s30,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getWireComp(buffInpGenAddr32APSK,Switch_out1_s41,addr32APSK);
    pirelab.getWireComp(buffInpGenAddr32APSK,LogicalOperator2_out1_s31,addr32APSKValidOut);
end

function hS=addSignal(buffInpGenAddr32APSK,sigName,pirTyp,simulinkRate)
    hS=buffInpGenAddr32APSK.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end