




function table=getSldvMetricDescrTable

    persistent pSldvDescr


    if isempty(pSldvDescr)
        pSldvDescr={...
        'Design Verifier Test Objective',...
        'cvmetric_Sldv_test',...
        'TO',...
        0,...
        getString(message('Slvnv:simcoverage:TestObjective'));...
...
        'Design Verifier Proof Objective',...
        'cvmetric_Sldv_proof',...
        'PO',...
        0,...
        getString(message('Slvnv:simcoverage:ProofObjective'));...
...
        'Design Verifier Test Condition',...
        'cvmetric_Sldv_condition',...
        'TC',...
        0,...
        getString(message('Slvnv:simcoverage:TestCondition'));...
...
        'Design Verifier Assumption',...
        'cvmetric_Sldv_assumption',...
        'PA',...
        0,...
        getString(message('Slvnv:simcoverage:ProofAssumption'));...
        };
        pSldvDescr=cvi.MetricRegistry.setMetricEnums(pSldvDescr);
    end

    table=pSldvDescr;
