function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CxobCVARVPSvGe8XH3b1ZoEV2TpjkYxlL9E9GLB4GXZvuxDmlSZqhVKDa8'...
        ,'WbliR3wexcwf6GtaQ4X3JA/Up+1e3rPAI0ECWXWCAS7oHshcM+tb/5njmpWJ'...
        ,'WfX47/1rSuhMKdO31xZiR9PjgZ/3/92BDjfXtp/SZRMayd7MGfXdsKbAsIgS'...
        ,'m3sSFvYzW9/HLuGzQQQNbupX478w3xPwLFYt/HhDXADxtlBB+4Jd2tKaV6Sa'...
        ,'TVnoA7KUvQabpvcitPhYOnmrLEyh4YX8Dmt/hZ2K+dSU534dWs3tcRrC+Jal'...
        ,'ctlIEcGptw=='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end