
function DataDemux(~,hN,DataDemuxInSigs,DataDemuxOutSigs,...
    hInputDataT,slRate,blockInfo)


    hDataDemuxN=pirelab.createNewNetwork(...
    'Name','DataDemux',...
    'InportNames',{'rdData'},...
    'InportTypes',pirelab.createPirArrayType(hInputDataT,[blockInfo.RowSize+1,0]),...
    'InportRates',slRate,...
    'OutportNames',{'reciprocalData','rdDataNonDiag'},...
    'OutportTypes',[hInputDataT,pirelab.createPirArrayType(hInputDataT,[blockInfo.RowSize+1,0])]);

    hDataDemuxN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hDataDemuxN.PirOutputSignals)
        hDataDemuxN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hDataDemuxNinSigs=hDataDemuxN.PirInputSignals;
    hDataDemuxNoutSigs=hDataDemuxN.PirOutputSignals;


    rdDataSplit=hDataDemuxNinSigs(1).split;


    pirelab.getMuxComp(hDataDemuxN,...
    (rdDataSplit.PirOutputSignals(1:end))',...
    hDataDemuxNoutSigs(2),...
    'concatenate');

    pirelab.getWireComp(hDataDemuxN,...
    rdDataSplit.PirOutputSignals(end),...
    hDataDemuxNoutSigs(1),...
    'reciprocalData');

    pirelab.instantiateNetwork(hN,hDataDemuxN,DataDemuxInSigs,DataDemuxOutSigs,...
    [hDataDemuxN.Name,'_inst']);

end


