
function FwdOutRowColCounters(~,hN,FwdCntOutInSigs,FwdCntOutOutSigs,...
    hBoolT,hCounterT,slRate,blockInfo)


    hFwdCntOutN=pirelab.createNewNetwork(...
    'Name','FwdOutRowColCounters',...
    'InportNames',{'dataOutValid','fwdSubDone'},...
    'InportTypes',[hBoolT,hBoolT],...
    'InportRates',slRate*ones(1,2),...
    'OutportNames',{'colCountOut','rowCountOut'},...
    'OutportTypes',[hCounterT,hCounterT]);

    hFwdCntOutN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hFwdCntOutN.PirOutputSignals)
        hFwdCntOutN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hFwdCntOutNinSigs=hFwdCntOutN.PirInputSignals;
    hFwdCntOutNoutSigs=hFwdCntOutN.PirOutputSignals;

    Add_out1_s1=l_addSignal(hFwdCntOutN,'Add_out1',hCounterT,slRate);
    CompareToConstant_out1_s2=l_addSignal(hFwdCntOutN,sprintf('Compare\nTo Constant_out1'),hBoolT,slRate);
    CompareToConstant1_out1_s3=l_addSignal(hFwdCntOutN,sprintf('Compare\nTo Constant1_out1'),hBoolT,slRate);
    Constant_out1_s4=l_addSignal(hFwdCntOutN,'Constant_out1',hCounterT,slRate);
    LogicalOperator_out1_s5=l_addSignal(hFwdCntOutN,sprintf('Logical\nOperator_out1'),hBoolT,slRate);
    LogicalOperator1_out1_s6=l_addSignal(hFwdCntOutN,sprintf('Logical\nOperator1_out1'),hBoolT,slRate);
    Subtract_out1_s7=l_addSignal(hFwdCntOutN,'Subtract_out1',hCounterT,slRate);
    Switch_out1_s8=l_addSignal(hFwdCntOutN,'Switch_out1',hCounterT,slRate);
    Switch1_out1_s9=l_addSignal(hFwdCntOutN,'Switch1_out1',hCounterT,slRate);
    Switch2_out1_s10=l_addSignal(hFwdCntOutN,'Switch2_out1',hCounterT,slRate);
    colCountOut_out_s13=l_addSignal(hFwdCntOutN,'colCountOut_out',hCounterT,slRate);
    colCountOut_Initial_Val_out_s14=l_addSignal(hFwdCntOutN,'colCountOut_Initial_Val_out',hCounterT,slRate);
    colCountOut_ctrl_const_out_s15=l_addSignal(hFwdCntOutN,'colCountOut_ctrl_const_out',hBoolT,slRate);
    colCountOut_ctrl_delay_out_s16=l_addSignal(hFwdCntOutN,'colCountOut_ctrl_delay_out',hBoolT,slRate);

    pirelab.getConstComp(hFwdCntOutN,...
    Constant_out1_s4,...
    1,...
    'Constant','on',0,'','','');

    pirelab.getIntDelayComp(hFwdCntOutN,...
    Switch2_out1_s10,...
    colCountOut_out_s13,...
    1,'colCountOut',...
    double(0),...
    0,0,[],0,0);

    pirelab.getCounterComp(hFwdCntOutN,...
    [hFwdCntOutNinSigs(2),LogicalOperator_out1_s5],...
    hFwdCntOutNoutSigs(2),...
    'Count limited',1,1,blockInfo.RowSize,1,0,1,0,'rowCounter',1);


    pirelab.getConstComp(hFwdCntOutN,...
    colCountOut_Initial_Val_out_s14,...
    1,...
    'colCountOut_Initial_Val','on',0,'','','');

    pirelab.getConstComp(hFwdCntOutN,...
    colCountOut_ctrl_const_out_s15,...
    1,...
    'colCountOut_ctrl_const');

    pirelab.getIntDelayComp(hFwdCntOutN,...
    colCountOut_ctrl_const_out_s15,...
    colCountOut_ctrl_delay_out_s16,...
    1,'colCountOut_ctrl_delay',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(hFwdCntOutN,...
    [colCountOut_out_s13,colCountOut_Initial_Val_out_s14],...
    hFwdCntOutNoutSigs(1),...
    colCountOut_ctrl_delay_out_s16,'colCountOut_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getAddComp(hFwdCntOutN,...
    [hFwdCntOutNoutSigs(2),Constant_out1_s4],...
    Add_out1_s1,...
    'Floor','Wrap','Add',hCounterT,'++');


    pirelab.getCompareToValueComp(hFwdCntOutN,...
    hFwdCntOutNoutSigs(1),...
    CompareToConstant_out1_s2,...
    '==',1,...
    sprintf('Compare\nTo Constant'),0);


    pirelab.getCompareToValueComp(hFwdCntOutN,...
    hFwdCntOutNoutSigs(2),...
    CompareToConstant1_out1_s3,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant1'),0);


    pirelab.getLogicComp(hFwdCntOutN,...
    [hFwdCntOutNinSigs(1),CompareToConstant_out1_s2],...
    LogicalOperator_out1_s5,...
    'and',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hFwdCntOutN,...
    [CompareToConstant1_out1_s3,LogicalOperator_out1_s5],...
    LogicalOperator1_out1_s6,...
    'and',sprintf('Logical\nOperator1'));


    pirelab.getAddComp(hFwdCntOutN,...
    [hFwdCntOutNoutSigs(1),Constant_out1_s4],...
    Subtract_out1_s7,...
    'Floor','Wrap','Subtract',hCounterT,'+-');


    pirelab.getSwitchComp(hFwdCntOutN,...
    [Add_out1_s1,Switch1_out1_s9],...
    Switch_out1_s8,...
    LogicalOperator_out1_s5,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hFwdCntOutN,...
    [Subtract_out1_s7,hFwdCntOutNoutSigs(1)],...
    Switch1_out1_s9,...
    hFwdCntOutNinSigs(1),'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hFwdCntOutN,...
    [Constant_out1_s4,Switch_out1_s8],...
    Switch2_out1_s10,...
    LogicalOperator1_out1_s6,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.instantiateNetwork(hN,hFwdCntOutN,FwdCntOutInSigs,...
    FwdCntOutOutSigs,[hFwdCntOutN.Name,'_inst']);

end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end
