
function gaussJordanSwappingLogic(this,hN,gaussJordanSwapLogicInSigs,gaussJordanSwapLogicOutSigs,...
    hInputDataT,hBoolT,hCounterT,slRate,blockInfo)





    hgaussJordanSwappingLogicN=pirelab.createNewNetwork(...
    'Name','gaussJordanSwappingLogic',...
    'InportNames',{'diagValidIn','rowCount','readData','colCount','swapreadEnable'},...
    'InportTypes',[hBoolT,hCounterT,gaussJordanSwapLogicInSigs(3).Type,hCounterT,hBoolT],...
    'InportRates',slRate*ones(1,5),...
    'OutportNames',{'swapDataOut1','swapAddrOut','swapEnb','swapEnableOut','swapDone','isDiagZero','swapDataOut2'},...
    'OutportTypes',[gaussJordanSwapLogicOutSigs(1).Type,hCounterT,hBoolT,hBoolT,hBoolT,hBoolT,gaussJordanSwapLogicOutSigs(7).Type]);

    hgaussJordanSwappingLogicN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hgaussJordanSwappingLogicN.PirOutputSignals)
        hgaussJordanSwappingLogicN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hgaussJordanSwappingLogicNinSigs=hgaussJordanSwappingLogicN.PirInputSignals;
    hgaussJordanSwappingLogicNoutSigs=hgaussJordanSwappingLogicN.PirOutputSignals;


    diagValidIn=hgaussJordanSwappingLogicNinSigs(1);
    rowCount=hgaussJordanSwappingLogicNinSigs(2);
    readData=hgaussJordanSwappingLogicNinSigs(3);
    colCount=hgaussJordanSwappingLogicNinSigs(4);
    swapReadEnable=hgaussJordanSwappingLogicNinSigs(5);

    swapDataOut1=hgaussJordanSwappingLogicNoutSigs(1);
    swapAddrOut=hgaussJordanSwappingLogicNoutSigs(2);
    swapEnb=hgaussJordanSwappingLogicNoutSigs(3);
    swapEnableOut=hgaussJordanSwappingLogicNoutSigs(4);
    swapDone=hgaussJordanSwappingLogicNoutSigs(5);
    isDiagZero=hgaussJordanSwappingLogicNoutSigs(6);
    swapDataOut2=hgaussJordanSwappingLogicNoutSigs(7);

    if blockInfo.MatrixSize==1
        hArrayT=hInputDataT;
    else
        hArrayT=pirelab.createPirArrayType(hInputDataT,[blockInfo.MatrixSize,0]);
    end


    diagRowData=l_addSignal(hgaussJordanSwappingLogicN,'diagRowData',...
    hArrayT,slRate);

    diagRowDataEyeMem=l_addSignal(hgaussJordanSwappingLogicN,'diagRowDataEyeMem',...
    hArrayT,slRate);


    maxRowData=l_addSignal(hgaussJordanSwappingLogicN,'maxRowData',...
    hArrayT,slRate);

    maxRowDataEyeMem=l_addSignal(hgaussJordanSwappingLogicN,'maxRowDataEyeMem',...
    hArrayT,slRate);

    diagRowAddr=l_addSignal(hgaussJordanSwappingLogicN,'diagRowAddr',hCounterT,slRate);
    maxRowAddr=l_addSignal(hgaussJordanSwappingLogicN,'maxRowAddr',hCounterT,slRate);
    maxFinish=l_addSignal(hgaussJordanSwappingLogicN,'maxFinish',hBoolT,slRate);



    pirTyp1=pir_boolean_t;

    pirTyp3=gaussJordanSwapLogicInSigs(3).Type.BaseType;
    pirTyp2=hCounterT;
    pirTyp4=pir_unsigned_t(8);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt2=numerictype(0,ceil(log2(blockInfo.RowSize))+1,0);



    Abs_out1_s5=l_addSignal(hgaussJordanSwappingLogicN,'Abs_out1',pirTyp3,slRate);
    Abs1_out1_s6=l_addSignal(hgaussJordanSwappingLogicN,'Abs1_out1',pirTyp3,slRate);
    CompareToConstant1_out1_s7=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Compare\nTo Constant1_out1'),pirTyp1,slRate);
    Constant_out1_s8=l_addSignal(hgaussJordanSwappingLogicN,'Constant_out1',pirTyp1,slRate);
    Constant1_out1_s9=l_addSignal(hgaussJordanSwappingLogicN,'Constant1_out1',pirTyp1,slRate);
    Constant2_out1_s10=l_addSignal(hgaussJordanSwappingLogicN,'Constant2_out1',pirTyp1,slRate);
    Constant4_out1_s11=l_addSignal(hgaussJordanSwappingLogicN,'Constant4_out1',pirTyp1,slRate);
    Constant5_out1_s12=l_addSignal(hgaussJordanSwappingLogicN,'Constant5_out1',pirTyp1,slRate);
    DataTypeConversion_out1_s13=l_addSignal(hgaussJordanSwappingLogicN,'Data Type Conversion_out1',pirTyp4,slRate);


    Delay10_out1_s16=l_addSignal(hgaussJordanSwappingLogicN,'Delay10_out1',pirTyp1,slRate);

    Delay13_out1_s18=l_addSignal(hgaussJordanSwappingLogicN,'Delay13_out1',pirTyp1,slRate);
    Delay14_out1_s19=l_addSignal(hgaussJordanSwappingLogicN,'Delay14_out1',pirTyp2,slRate);

    Delay16_out1_s21=l_addSignal(hgaussJordanSwappingLogicN,'Delay16_out1',pirTyp1,slRate);
    Delay18_out1_s22=l_addSignal(hgaussJordanSwappingLogicN,'Delay18_out1',pirTyp1,slRate);
    Delay2_out1_s23=l_addSignal(hgaussJordanSwappingLogicN,'Delay2_out1',pirTyp2,slRate);
    Delay20_out1_s24=l_addSignal(hgaussJordanSwappingLogicN,'Delay20_out1',hArrayT,slRate);
    Delay21_out1_s25=l_addSignal(hgaussJordanSwappingLogicN,'Delay21_out1',hArrayT,slRate);
    Delay22_out1_s26=l_addSignal(hgaussJordanSwappingLogicN,'Delay22_out1',hArrayT,slRate);
    Delay24_out1_s28=l_addSignal(hgaussJordanSwappingLogicN,'Delay24_out1',pirTyp2,slRate);
    Delay25_out1_s29=l_addSignal(hgaussJordanSwappingLogicN,'Delay25_out1',pirTyp2,slRate);


    Delay6_out1_s33=l_addSignal(hgaussJordanSwappingLogicN,'Delay6_out1',pirTyp1,slRate);
    Delay7_out1_s34=l_addSignal(hgaussJordanSwappingLogicN,'Delay7_out1',pirTyp1,slRate);
    LogicalOperator_out1_s36=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Logical\nOperator_out1'),pirTyp1,slRate);
    LogicalOperator1_out1_s37=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Logical\nOperator1_out1'),pirTyp1,slRate);
    LogicalOperator3_out1_s38=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Logical\nOperator3_out1'),pirTyp1,slRate);
    RelationalOperator_out1_s39=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Relational\nOperator_out1'),pirTyp1,slRate);
    RelationalOperator1_out1_s40=l_addSignal(hgaussJordanSwappingLogicN,sprintf('Relational\nOperator1_out1'),pirTyp1,slRate);
    Selector_out1_s41=l_addSignal(hgaussJordanSwappingLogicN,'Selector_out1',pirTyp3,slRate);
    Selector1_out1_s42=l_addSignal(hgaussJordanSwappingLogicN,'Selector1_out1',pirTyp3,slRate);
    Selector2_out1_s43=l_addSignal(hgaussJordanSwappingLogicN,'Selector2_out1',hArrayT,slRate);
    Selector3_out1_s44=l_addSignal(hgaussJordanSwappingLogicN,'Selector3_out1',hArrayT,slRate);
    Switch_out1_s50=l_addSignal(hgaussJordanSwappingLogicN,'Switch_out1',hArrayT,slRate);
    Switch1_out1_s51=l_addSignal(hgaussJordanSwappingLogicN,'Switch1_out1',hArrayT,slRate);
    Switch10_out1_s52=l_addSignal(hgaussJordanSwappingLogicN,'Switch10_out1',pirTyp1,slRate);
    Switch11_out1_s53=l_addSignal(hgaussJordanSwappingLogicN,'Switch11_out1',hArrayT,slRate);
    Switch14_out1_s54=l_addSignal(hgaussJordanSwappingLogicN,'Switch14_out1',pirTyp2,slRate);
    Switch15_out1_s55=l_addSignal(hgaussJordanSwappingLogicN,'Switch15_out1',pirTyp1,slRate);
    Switch16_out1_s56=l_addSignal(hgaussJordanSwappingLogicN,'Switch16_out1',hArrayT,slRate);
    Switch17_out1_s57=l_addSignal(hgaussJordanSwappingLogicN,'Switch17_out1',hArrayT,slRate);
    Switch2_out1_s58=l_addSignal(hgaussJordanSwappingLogicN,'Switch2_out1',hArrayT,slRate);
    Switch3_out1_s59=l_addSignal(hgaussJordanSwappingLogicN,'Switch3_out1',pirTyp2,slRate);
    Switch4_out1_s60=l_addSignal(hgaussJordanSwappingLogicN,'Switch4_out1',pirTyp2,slRate);
    Switch5_out1_s61=l_addSignal(hgaussJordanSwappingLogicN,'Switch5_out1',pirTyp1,slRate);
    Switch9_out1_s62=l_addSignal(hgaussJordanSwappingLogicN,'Switch9_out1',pirTyp1,slRate);


    if strcmpi(blockInfo.latencyStrategy,'MAX')
        latencyRelOp=3;
    elseif strcmpi(blockInfo.latencyStrategy,'MIN')
        latencyRelOp=1;
    else
        latencyRelOp=0;
    end



    pirelab.getConstComp(hgaussJordanSwappingLogicN,...
    Constant_out1_s8,...
    1,...
    'Constant','on',0,'','','');



    pirelab.getConstComp(hgaussJordanSwappingLogicN,...
    Constant1_out1_s9,...
    0,...
    'Constant1','on',1,'','','');



    pirelab.getConstComp(hgaussJordanSwappingLogicN,...
    Constant2_out1_s10,...
    0,...
    'Constant2','on',1,'','','');



    pirelab.getConstComp(hgaussJordanSwappingLogicN,...
    Constant4_out1_s11,...
    1,...
    'Constant4','on',0,'','','');




    pirelab.getConstComp(hgaussJordanSwappingLogicN,...
    Constant5_out1_s12,...
    0,...
    'Constant5','on',1,'','','');



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch_out1_s50,...
    diagRowData,...
    1,'Delay',...
    single(0),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch1_out1_s51,...
    maxRowData,...
    1,'Delay1',...
    single(0),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    swapDone,...
    Delay10_out1_s16,...
    2,'Delay10',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch11_out1_s53,...
    diagRowDataEyeMem,...
    1,'Delay11',...
    single(0),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    RelationalOperator_out1_s39,...
    Delay13_out1_s18,...
    latencyRelOp,'Delay13',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    colCount,...
    Delay14_out1_s19,...
    1,'Delay14',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch16_out1_s56,...
    maxRowDataEyeMem,...
    1,'Delay15',...
    single(0),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    RelationalOperator1_out1_s40,...
    Delay16_out1_s21,...
    latencyRelOp,'Delay16',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    diagValidIn,...
    Delay18_out1_s22,...
    latencyRelOp,'Delay18',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch3_out1_s59,...
    Delay2_out1_s23,...
    1,'Delay2',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Selector2_out1_s43,...
    Delay20_out1_s24,...
    latencyRelOp,'Delay20',...
    single(0),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Selector3_out1_s44,...
    Delay21_out1_s25,...
    latencyRelOp,'Delay21',...
    single(0),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Selector2_out1_s43,...
    Delay22_out1_s26,...
    latencyRelOp,'Delay22',...
    single(0),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    LogicalOperator_out1_s36,...
    isDiagZero,...
    latencyRelOp,'Delay23',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Delay14_out1_s19,...
    Delay24_out1_s28,...
    latencyRelOp,'Delay24',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    colCount,...
    Delay25_out1_s29,...
    latencyRelOp,'Delay25',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch15_out1_s55,...
    maxFinish,...
    1,'Delay3',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Delay2_out1_s23,...
    maxRowAddr,...
    1,'Delay31',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch4_out1_s60,...
    diagRowAddr,...
    1,'Delay4',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    swapReadEnable,...
    Delay6_out1_s33,...
    1,'Delay6',...
    false,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Delay6_out1_s33,...
    Delay7_out1_s34,...
    latencyRelOp,'Delay7',...
    false,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanSwappingLogicN,...
    Switch9_out1_s62,...
    swapEnb,...
    1,'Delay8',...
    false,...
    0,0,[],0,0);



    pirelab.getAbsComp(hgaussJordanSwappingLogicN,...
    Selector_out1_s41,...
    Abs_out1_s5,...
    'Floor','Wrap','Abs');



    pirelab.getAbsComp(hgaussJordanSwappingLogicN,...
    Selector1_out1_s42,...
    Abs1_out1_s6,...
    'Floor','Wrap','Abs1');




    pirelab.getCompareToValueComp(hgaussJordanSwappingLogicN,...
    Delay25_out1_s29,...
    CompareToConstant1_out1_s7,...
    '==',blockInfo.MatrixSize+1,...
    sprintf('Compare\nTo Constant1'),0);




    pirelab.getDTCComp(hgaussJordanSwappingLogicN,...
    rowCount,...
    DataTypeConversion_out1_s13,...
    'Floor','Wrap','RWV','Data Type Conversion');



    pirelab.getLogicComp(hgaussJordanSwappingLogicN,...
    [LogicalOperator3_out1_s38,diagValidIn],...
    LogicalOperator_out1_s36,...
    'and',sprintf('Logical\nOperator'));



    pirelab.getLogicComp(hgaussJordanSwappingLogicN,...
    [Switch5_out1_s61,Delay16_out1_s21],...
    LogicalOperator1_out1_s37,...
    'and',sprintf('Logical\nOperator1'));



    pirelab.getLogicComp(hgaussJordanSwappingLogicN,...
    Delay10_out1_s16,...
    LogicalOperator3_out1_s38,...
    'not',sprintf('Logical\nOperator3'));



    pirelab.getRelOpComp(hgaussJordanSwappingLogicN,...
    [Abs_out1_s5,Abs1_out1_s6],...
    RelationalOperator_out1_s39,...
    '>',0,sprintf('Relational\nOperator'));



    pirelab.getRelOpComp(hgaussJordanSwappingLogicN,...
    [Delay14_out1_s19,rowCount],...
    RelationalOperator1_out1_s40,...
    '>',0,sprintf('Relational\nOperator1'));



    if blockInfo.MatrixSize==1
        pirelab.getWireComp(hgaussJordanSwappingLogicN,Selector2_out1_s43,...
        Selector_out1_s41,'SelectorOut');
        pirelab.getWireComp(hgaussJordanSwappingLogicN,maxRowData,...
        Selector1_out1_s42,'SelectorOut1');
    else
        pirelab.getSelectorComp(hgaussJordanSwappingLogicN,...
        [Selector2_out1_s43,DataTypeConversion_out1_s13],...
        Selector_out1_s41,...
        'One-based',{'Index vector (port)'},...
        {1:3},...
        {'1'},'1',...
        'Selector');

        pirelab.getSelectorComp(hgaussJordanSwappingLogicN,...
        [maxRowData,DataTypeConversion_out1_s13],...
        Selector1_out1_s42,...
        'One-based',{'Index vector (port)'},...
        {1:3},...
        {'1'},'1',...
        'Selector1');
    end




    pirelab.getSelectorComp(hgaussJordanSwappingLogicN,...
    readData,...
    Selector2_out1_s43,...
    'One-based',{'Index vector (dialog)'},...
    {1:blockInfo.MatrixSize},...
    {'1'},'1',...
    'Selector2');



    pirelab.getSelectorComp(hgaussJordanSwappingLogicN,...
    readData,...
    Selector3_out1_s44,...
    'One-based',{'Index vector (dialog)'},...
    {blockInfo.MatrixSize+1:blockInfo.MatrixSize*2},...
    {'1'},'1',...
    'Selector3');




    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay22_out1_s26,diagRowData],...
    Switch_out1_s50,...
    isDiagZero,'Switch',...
    '~=',0,'Floor','Wrap');




    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay20_out1_s24,Switch2_out1_s58],...
    Switch1_out1_s51,...
    Delay18_out1_s22,'Switch1',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Constant1_out1_s9,swapEnb],...
    Switch10_out1_s52,...
    swapDone,'Switch10',...
    '~=',0,'Floor','Wrap');




    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay21_out1_s25,diagRowDataEyeMem],...
    Switch11_out1_s53,...
    isDiagZero,'Switch11',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay24_out1_s28,Delay2_out1_s23],...
    Switch14_out1_s54,...
    LogicalOperator1_out1_s37,'Switch14',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Constant4_out1_s11,Constant5_out1_s12],...
    Switch15_out1_s55,...
    CompareToConstant1_out1_s7,'Switch15',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay21_out1_s25,Switch17_out1_s57],...
    Switch16_out1_s56,...
    Delay18_out1_s22,'Switch16',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay21_out1_s25,maxRowDataEyeMem],...
    Switch17_out1_s57,...
    LogicalOperator1_out1_s37,'Switch17',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay20_out1_s24,maxRowData],...
    Switch2_out1_s58,...
    LogicalOperator1_out1_s37,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay24_out1_s28,Switch14_out1_s54],...
    Switch3_out1_s59,...
    Delay18_out1_s22,'Switch3',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay24_out1_s28,diagRowAddr],...
    Switch4_out1_s60,...
    isDiagZero,'Switch4',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Delay13_out1_s18,Constant2_out1_s10],...
    Switch5_out1_s61,...
    Delay7_out1_s34,'Switch5',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hgaussJordanSwappingLogicN,...
    [Constant_out1_s8,Switch10_out1_s52],...
    Switch9_out1_s62,...
    isDiagZero,'Switch9',...
    '~=',0,'Floor','Wrap');








    swapDoneInSigs=[swapEnb,swapEnableOut];
    swapDoneOutSigs=swapDone;

    this.swapDoneSubsystem(hgaussJordanSwappingLogicN,swapDoneInSigs,...
    swapDoneOutSigs,hBoolT,slRate);



    swappingDataLogicInSigs=[swapEnb,diagRowData,swapDone,diagRowDataEyeMem,...
    maxRowDataEyeMem,diagRowAddr,maxFinish,maxRowData,maxRowAddr];
    swappingDataLogicOutSigs=[swapEnableOut,swapDataOut1,swapAddrOut,swapDataOut2];

    this.swappingDataLogic(hgaussJordanSwappingLogicN,swappingDataLogicInSigs,...
    swappingDataLogicOutSigs,hCounterT,hInputDataT,hBoolT,slRate,blockInfo);




    pirelab.instantiateNetwork(hN,hgaussJordanSwappingLogicN,gaussJordanSwapLogicInSigs,...
    gaussJordanSwapLogicOutSigs,[hgaussJordanSwappingLogicN.Name,'_inst']);


end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


