
function gaussJordanNonDiagDataComputation(~,hN,nonDiagDataComputationInSigs,nonDiagDataComputationOutSigs,...
    hBoolT,slRate,blockInfo)





    hgaussJordanNonDiagDataN=pirelab.createNewNetwork(...
    'Name','gaussJordanNonDiagDataComputation',...
    'InportNames',{'nonDiagValidInReg','subtractFirstInp','subtractFirstInpEyeMem','multiplyDivideInpOne','multiplyDivideInpTwo','multiplyDivideInpTwoEyeMem'},...
    'InportTypes',[hBoolT,nonDiagDataComputationInSigs(2).Type,nonDiagDataComputationInSigs(3).Type,...
    nonDiagDataComputationInSigs(4).Type,nonDiagDataComputationInSigs(5).Type,...
    nonDiagDataComputationInSigs(6).Type],...
    'InportRates',slRate*ones(1,6),...
    'OutportNames',{'nonDiagValidOut','nonDiagDataOut1','nonDiagDataOut2'},...
    'OutportTypes',[nonDiagDataComputationOutSigs(1).Type,nonDiagDataComputationOutSigs(2).Type,...
    nonDiagDataComputationOutSigs(3).Type]);

    hgaussJordanNonDiagDataN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hgaussJordanNonDiagDataN.PirOutputSignals)
        hgaussJordanNonDiagDataN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hgaussJordanNonDiagDataNinSigs=hgaussJordanNonDiagDataN.PirInputSignals;
    hgaussJordanNonDiagDataNoutSigs=hgaussJordanNonDiagDataN.PirOutputSignals;

    nonDiagValidInReg=hgaussJordanNonDiagDataNinSigs(1);
    subtractFirstInp=hgaussJordanNonDiagDataNinSigs(2);
    subtractFirstInpEyeMem=hgaussJordanNonDiagDataNinSigs(3);





    nonDiagValidOut=hgaussJordanNonDiagDataNoutSigs(1);
    nonDiagDataOut1=hgaussJordanNonDiagDataNoutSigs(2);
    nonDiagDataOut2=hgaussJordanNonDiagDataNoutSigs(3);


    pirTyp1=pir_boolean_t;
    pirTyp2=nonDiagDataComputationInSigs(2).Type;





    Delay10_out1_s7=l_addSignal(hgaussJordanNonDiagDataN,'Delay10_out1',pirTyp2,slRate);
    Delay15_out1_s8=l_addSignal(hgaussJordanNonDiagDataN,'Delay15_out1',pirTyp2,slRate);
    Delay17_out1_s9=l_addSignal(hgaussJordanNonDiagDataN,'Delay17_out1',pirTyp2,slRate);
    Delay18_out1_s10=l_addSignal(hgaussJordanNonDiagDataN,'Delay18_out1',pirTyp2,slRate);
    Delay19_out1_s11=l_addSignal(hgaussJordanNonDiagDataN,'Delay19_out1',pirTyp2,slRate);
    Delay27_out1_s13=l_addSignal(hgaussJordanNonDiagDataN,'Delay27_out1',pirTyp2,slRate);
    Delay29_out1_s14=l_addSignal(hgaussJordanNonDiagDataN,'Delay29_out1',pirTyp2,slRate);
    Delay4_out1_s16=l_addSignal(hgaussJordanNonDiagDataN,'Delay4_out1',pirTyp1,slRate);
    Delay43_out1_s17=l_addSignal(hgaussJordanNonDiagDataN,'Delay43_out1',pirTyp1,slRate);
    Delay7_out1_s19=l_addSignal(hgaussJordanNonDiagDataN,'Delay7_out1',pirTyp2,slRate);
    Product_out1_s20=l_addSignal(hgaussJordanNonDiagDataN,'Product_out1',pirTyp2,slRate);
    Product1_out1_s21=l_addSignal(hgaussJordanNonDiagDataN,'Product1_out1',pirTyp2,slRate);
    Subtract_out1_s22=l_addSignal(hgaussJordanNonDiagDataN,'Subtract_out1',pirTyp2,slRate);
    Subtract1_out1_s23=l_addSignal(hgaussJordanNonDiagDataN,'Subtract1_out1',pirTyp2,slRate);

    hMultC=pirelab.getMulComp(hgaussJordanNonDiagDataN,...
    [hgaussJordanNonDiagDataNinSigs(4),hgaussJordanNonDiagDataNinSigs(5)],...
    Product_out1_s20,...
    'Floor','Wrap','Product','**','',-1,0);



    pirelab.getMulComp(hgaussJordanNonDiagDataN,...
    [hgaussJordanNonDiagDataNinSigs(6),hgaussJordanNonDiagDataNinSigs(4)],...
    Product1_out1_s21,...
    'Floor','Wrap','Product1','**','',-1,0);


    hAddSubC=pirelab.getAddComp(hgaussJordanNonDiagDataN,...
    [Delay7_out1_s19,Delay10_out1_s7],...
    Subtract_out1_s22,...
    'Floor','Wrap','Subtract',pirTyp2,'+-');



    pirelab.getAddComp(hgaussJordanNonDiagDataN,...
    [Delay17_out1_s9,Delay18_out1_s10],...
    Subtract1_out1_s23,...
    'Floor','Wrap','Subtract1',pirTyp2,'+-');


    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay19_out1_s11,...
    Delay10_out1_s7,...
    1,'Delay10',...
    single(0),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Product1_out1_s21,...
    Delay15_out1_s8,...
    resolveLatencyForIPType(hMultC,'MUL',blockInfo.inputDataType),'Delay15',...
    single(0),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay27_out1_s13,...
    Delay17_out1_s9,...
    1,'Delay17',...
    single(0),...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay15_out1_s8,...
    Delay18_out1_s10,...
    1,'Delay18',...
    0,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Product_out1_s20,...
    Delay19_out1_s11,...
    resolveLatencyForIPType(hMultC,'MUL',blockInfo.inputDataType),'Delay19',...
    0,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Subtract1_out1_s23,...
    nonDiagDataOut2,...
    resolveLatencyForIPType(hAddSubC,'ADDSUB',blockInfo.inputDataType),'Delay20',...
    0,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    subtractFirstInpEyeMem,...
    Delay27_out1_s13,...
    resolveLatencyForIPType(hMultC,'MUL',blockInfo.inputDataType),'Delay27',...
    0,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    subtractFirstInp,...
    Delay29_out1_s14,...
    resolveLatencyForIPType(hMultC,'MUL',blockInfo.inputDataType),'Delay29',...
    0,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Subtract_out1_s22,...
    nonDiagDataOut1,...
    resolveLatencyForIPType(hAddSubC,'ADDSUB',blockInfo.inputDataType),'Delay32',...
    0,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay43_out1_s17,...
    Delay4_out1_s16,...
    1,'Delay4',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    nonDiagValidInReg,...
    Delay43_out1_s17,...
    resolveLatencyForIPType(hMultC,'MUL',blockInfo.inputDataType),'Delay43',...
    false,...
    0,0,[],0,0);




    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay4_out1_s16,...
    nonDiagValidOut,...
    resolveLatencyForIPType(hAddSubC,'ADDSUB',blockInfo.inputDataType),'Delay44',...
    false,...
    0,0,[],0,0);



    pirelab.getIntDelayComp(hgaussJordanNonDiagDataN,...
    Delay29_out1_s14,...
    Delay7_out1_s19,...
    1,'Delay7',...
    0,...
    0,0,[],0,0);








    pirelab.instantiateNetwork(hN,hgaussJordanNonDiagDataN,nonDiagDataComputationInSigs,...
    nonDiagDataComputationOutSigs,[hgaussJordanNonDiagDataN.Name,'_inst']);


end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end

function latency=resolveLatencyForIPType(hC,targetIPType,inputDataType)

    hDriver=hdlcurrentdriver;

    p=pir(hC.Owner.getCtxName);

    targetCompDataType=inputDataType;
    targetDriver=hDriver.getTargetCodeGenDriver(p);
    if isempty(targetDriver)||~strcmpi(class(targetDriver),'targetcodegen.nfpdriver')
        latency=-1;
        return;
    end

    latency=targetDriver.getDefaultLatency(targetIPType,targetCompDataType,hC);
end


