
function LowerTriangEnable(~,hN,LTEnableInSigs,LTEnableOutSigs,...
    slRate,blockInfo)


    hLTEnableN=pirelab.createNewNetwork(...
    'Name','LowerTriangEnable',...
    'InportNames',{'storeDone','rowDone','rowCount'},...
    'InportTypes',[LTEnableInSigs(1).Type,LTEnableInSigs(2).Type,...
    LTEnableInSigs(3).Type],...
    'InportRates',slRate*ones(1,3),...
    'OutportNames',{'lowerTriangDone','lowerTriangEnb'},...
    'OutportTypes',[LTEnableOutSigs(1).Type,LTEnableOutSigs(2).Type]);

    hLTEnableN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hLTEnableN.PirOutputSignals)
        hLTEnableN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hLTEnableNinSigs=hLTEnableN.PirInputSignals;
    hLTEnableNoutSigs=hLTEnableN.PirOutputSignals;


    storeDone=hLTEnableNinSigs(1);
    rowDone=hLTEnableNinSigs(2);
    rowCount=hLTEnableNinSigs(3);

    lowerTriangDone=hLTEnableNoutSigs(1);
    lowerTriangEnb=hLTEnableNoutSigs(2);


    hBoolT=pir_boolean_t;


    CompareToConstant_out1_s3=l_addSignal(hLTEnableN,sprintf('Compare\nTo Constant_out1'),hBoolT,slRate);
    Constant1_out1_s4=l_addSignal(hLTEnableN,'Constant1_out1',hBoolT,slRate);
    Constant2_out1_s5=l_addSignal(hLTEnableN,'Constant2_out1',hBoolT,slRate);
    Switch2_out1_s8=l_addSignal(hLTEnableN,'Switch2_out1',hBoolT,slRate);
    Switch3_out1_s9=l_addSignal(hLTEnableN,'Switch3_out1',hBoolT,slRate);


    pirelab.getConstComp(hLTEnableN,...
    Constant1_out1_s4,...
    1,...
    'Constant1','on',0,'','','');

    pirelab.getConstComp(hLTEnableN,...
    Constant2_out1_s5,...
    0,...
    'Constant2','on',1,'','','');


    pirelab.getIntDelayComp(hLTEnableN,...
    Switch2_out1_s8,...
    lowerTriangEnb,...
    1,'Delay2',...
    false,...
    0,0,[],0,0);

    pirelab.getCompareToValueComp(hLTEnableN,...
    rowCount,...
    CompareToConstant_out1_s3,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant'),0);


    pirelab.getLogicComp(hLTEnableN,...
    [rowDone,CompareToConstant_out1_s3],...
    lowerTriangDone,...
    'and',sprintf('Logical\nOperator'));

    pirelab.getSwitchComp(hLTEnableN,...
    [Constant1_out1_s4,Switch3_out1_s9],...
    Switch2_out1_s8,...
    storeDone,'Switch2',...
    '~=',0,'Floor','Wrap');

    pirelab.getSwitchComp(hLTEnableN,...
    [Constant2_out1_s5,lowerTriangEnb],...
    Switch3_out1_s9,...
    lowerTriangDone,'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.instantiateNetwork(hN,hLTEnableN,LTEnableInSigs,LTEnableOutSigs,...
    [hLTEnableN.Name,'_inst']);
end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end

