

function LTMultCounters(~,hN,LTMultCntInSigs,LTMultCntOutSigs,hBoolT,...
    hCounterT,slRate,blockInfo)


    hLTMultCntN=pirelab.createNewNetwork(...
    'Name','LTMultCounters',...
    'InportNames',{'matMultRdEnb','rowCount'},...
    'InportTypes',[hBoolT,hCounterT],...
    'InportRates',slRate*ones(1,2),...
    'OutportNames',{'matMultRdDone','colCount','rowCountEn'},...
    'OutportTypes',[hBoolT,hCounterT,hBoolT]);

    hLTMultCntN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hLTMultCntN.PirOutputSignals)
        hLTMultCntN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hLTMultCntNinSigs=hLTMultCntN.PirInputSignals;
    hLTMultCntNoutSigs=hLTMultCntN.PirOutputSignals;


    Add1_out1_s2=l_addSignal(hLTMultCntN,'Add1_out1',hCounterT,slRate);
    Add2_out1_s3=l_addSignal(hLTMultCntN,'Add2_out1',hCounterT,slRate);
    CompareToConstant_out1_s4=l_addSignal(hLTMultCntN,sprintf('Compare\nTo Constant_out1'),hBoolT,slRate);
    CompareToConstant1_out1_s5=l_addSignal(hLTMultCntN,sprintf('Compare\nTo Constant1_out1'),hBoolT,slRate);
    CompareToConstant2_out1_s6=l_addSignal(hLTMultCntN,sprintf('Compare\nTo Constant2_out1'),hBoolT,slRate);
    CompareToConstant3_out1_s7=l_addSignal(hLTMultCntN,sprintf('Compare\nTo Constant3_out1'),hBoolT,slRate);
    Constant2_out1_s8=l_addSignal(hLTMultCntN,'Constant2_out1',hCounterT,slRate);
    LogicalOperator1_out1_s12=l_addSignal(hLTMultCntN,sprintf('Logical\nOperator1_out1'),hBoolT,slRate);
    LogicalOperator3_out1_s14=l_addSignal(hLTMultCntN,sprintf('Logical\nOperator3_out1'),hBoolT,slRate);
    Switch1_out1_s15=l_addSignal(hLTMultCntN,'Switch1_out1',hCounterT,slRate);
    Switch2_out1_s16=l_addSignal(hLTMultCntN,'Switch2_out1',hCounterT,slRate);
    Switch3_out1_s17=l_addSignal(hLTMultCntN,'Switch3_out1',hCounterT,slRate);
    colCntReg_out_s19=l_addSignal(hLTMultCntN,'colCntReg_out',hCounterT,slRate);
    colCntReg_Initial_Val_out_s20=l_addSignal(hLTMultCntN,'colCntReg_Initial_Val_out',hCounterT,slRate);
    colCntReg_ctrl_const_out_s21=l_addSignal(hLTMultCntN,'colCntReg_ctrl_const_out',hBoolT,slRate);
    colCntReg_ctrl_delay_out_s22=l_addSignal(hLTMultCntN,'colCntReg_ctrl_delay_out',hBoolT,slRate);

    pirelab.getConstComp(hLTMultCntN,...
    Constant2_out1_s8,...
    1,...
    'Constant2','on',0,'','','');

    pirelab.getIntDelayComp(hLTMultCntN,...
    Switch1_out1_s15,...
    colCntReg_out_s19,...
    1,'colCntReg',...
    double(0),...
    0,0,[],0,0);


    pirelab.getConstComp(hLTMultCntN,...
    colCntReg_Initial_Val_out_s20,...
    1,...
    'colCntReg_Initial_Val','on',0,'','','');

    pirelab.getConstComp(hLTMultCntN,...
    colCntReg_ctrl_const_out_s21,...
    1,...
    'colCntReg_ctrl_const');

    pirelab.getIntDelayComp(hLTMultCntN,...
    colCntReg_ctrl_const_out_s21,...
    colCntReg_ctrl_delay_out_s22,...
    1,'colCntReg_ctrl_delay',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(hLTMultCntN,...
    [colCntReg_out_s19,colCntReg_Initial_Val_out_s20],...
    hLTMultCntNoutSigs(2),...
    colCntReg_ctrl_delay_out_s22,'colCntReg_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getAddComp(hLTMultCntN,...
    [Constant2_out1_s8,hLTMultCntNinSigs(2)],...
    Add1_out1_s2,...
    'Floor','Wrap','Add1',hCounterT,'++');


    pirelab.getAddComp(hLTMultCntN,...
    [Constant2_out1_s8,hLTMultCntNoutSigs(2)],...
    Add2_out1_s3,...
    'Floor','Wrap','Add2',hCounterT,'++');


    pirelab.getCompareToValueComp(hLTMultCntN,...
    hLTMultCntNoutSigs(2),...
    CompareToConstant_out1_s4,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant'),0);


    pirelab.getCompareToValueComp(hLTMultCntN,...
    hLTMultCntNinSigs(2),...
    CompareToConstant1_out1_s5,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant1'),0);


    pirelab.getCompareToValueComp(hLTMultCntN,...
    hLTMultCntNoutSigs(2),...
    CompareToConstant2_out1_s6,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant2'),0);


    pirelab.getCompareToValueComp(hLTMultCntN,...
    hLTMultCntNoutSigs(2),...
    CompareToConstant3_out1_s7,...
    '<',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant3'),0);


    pirelab.getLogicComp(hLTMultCntN,...
    [hLTMultCntNinSigs(1),LogicalOperator1_out1_s12],...
    hLTMultCntNoutSigs(1),...
    'and',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hLTMultCntN,...
    [CompareToConstant_out1_s4,CompareToConstant1_out1_s5],...
    LogicalOperator1_out1_s12,...
    'and',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hLTMultCntN,...
    [hLTMultCntNinSigs(1),CompareToConstant2_out1_s6],...
    hLTMultCntNoutSigs(3),...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hLTMultCntN,...
    [hLTMultCntNinSigs(1),CompareToConstant3_out1_s7],...
    LogicalOperator3_out1_s14,...
    'and',sprintf('Logical\nOperator3'));


    pirelab.getSwitchComp(hLTMultCntN,...
    [Constant2_out1_s8,Switch3_out1_s17],...
    Switch1_out1_s15,...
    hLTMultCntNoutSigs(1),'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hLTMultCntN,...
    [Add2_out1_s3,hLTMultCntNoutSigs(2)],...
    Switch2_out1_s16,...
    LogicalOperator3_out1_s14,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hLTMultCntN,...
    [Add1_out1_s2,Switch2_out1_s16],...
    Switch3_out1_s17,...
    hLTMultCntNoutSigs(3),'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.instantiateNetwork(hN,hLTMultCntN,LTMultCntInSigs,LTMultCntOutSigs,...
    [hLTMultCntN.Name,'_inst']);

end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end
