

function LTMultProcCounters(~,hN,LTMultProcCntInSigs,LTMultProcCntOutSigs,...
    slRate,blockInfo)


    hLTMultProcCntN=pirelab.createNewNetwork(...
    'Name','LTMultProcCounters',...
    'InportNames',{'prodValid'},...
    'InportTypes',LTMultProcCntInSigs(1).Type,...
    'InportRates',slRate,...
    'OutportNames',{'colCountOut','rowCountOut','invDone'},...
    'OutportTypes',[LTMultProcCntOutSigs(1).Type,LTMultProcCntOutSigs(2).Type,...
    LTMultProcCntOutSigs(3).Type]);

    hLTMultProcCntN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hLTMultProcCntN.PirOutputSignals)
        hLTMultProcCntN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hLTMultProcCntNinSigs=hLTMultProcCntN.PirInputSignals;
    hLTMultProcCntNoutSigs=hLTMultProcCntN.PirOutputSignals;


    if bitand(blockInfo.RowSize,blockInfo.RowSize*2-1)==blockInfo.RowSize
        hCounterT=hN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize))+1,...
        'FractionLength',0);
    else
        hCounterT=hN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize)),...
        'FractionLength',0);
    end
    hBoolT=pir_boolean_t;


    prodValid=hLTMultProcCntNinSigs(1);
    colCountOut=hLTMultProcCntNoutSigs(1);
    rowCountOut=hLTMultProcCntNoutSigs(2);
    invDone=hLTMultProcCntNoutSigs(3);



    Add_out1_s1=l_addSignal(hLTMultProcCntN,'Add_out1',hCounterT,slRate);
    Add3_out1_s2=l_addSignal(hLTMultProcCntN,'Add3_out1',hCounterT,slRate);
    CompareToConstant10_out1_s3=l_addSignal(hLTMultProcCntN,'Compare\nTo Constant10_out1',hBoolT,slRate);
    CompareToConstant7_out1_s4=l_addSignal(hLTMultProcCntN,'Compare\nTo Constant7_out1',hBoolT,slRate);
    CompareToConstant8_out1_s5=l_addSignal(hLTMultProcCntN,'Compare\nTo Constant8_out1',hBoolT,slRate);
    CompareToConstant9_out1_s6=l_addSignal(hLTMultProcCntN,'Compare\nTo Constant9_out1',hBoolT,slRate);
    Constant10_out1_s7=l_addSignal(hLTMultProcCntN,'Constant10_out1',hCounterT,slRate);
    LogicalOperator4_out1_s10=l_addSignal(hLTMultProcCntN,sprintf('Logical\nOperator4_out1'),hBoolT,slRate);
    LogicalOperator6_out1_s12=l_addSignal(hLTMultProcCntN,sprintf('Logical\nOperator6_out1'),hBoolT,slRate);
    Switch10_out1_s13=l_addSignal(hLTMultProcCntN,'Switch10_out1',hCounterT,slRate);
    Switch7_out1_s14=l_addSignal(hLTMultProcCntN,'Switch7_out1',hCounterT,slRate);
    Switch8_out1_s15=l_addSignal(hLTMultProcCntN,'Switch8_out1',hCounterT,slRate);
    colCntOut_out_s18=l_addSignal(hLTMultProcCntN,'colCntOut_out',hCounterT,slRate);
    colCntOut_Initial_Val_out_s19=l_addSignal(hLTMultProcCntN,'colCntOut_Initial_Val_out',hCounterT,slRate);
    colCntOut_ctrl_const_out_s20=l_addSignal(hLTMultProcCntN,'colCntOut_ctrl_const_out',hBoolT,slRate);
    colCntOut_ctrl_delay_out_s21=l_addSignal(hLTMultProcCntN,'colCntOut_ctrl_delay_out',hBoolT,slRate);

    pirelab.getConstComp(hLTMultProcCntN,...
    Constant10_out1_s7,...
    1,...
    'Constant10','on',0,'','','');

    pirelab.getIntDelayComp(hLTMultProcCntN,...
    Switch10_out1_s13,...
    colCntOut_out_s18,...
    1,'colCntOut',...
    double(0),...
    0,0,[],0,0);

    pirelab.getCounterComp(hLTMultProcCntN,...
    [invDone,LogicalOperator4_out1_s10],...
    rowCountOut,...
    'Count limited',1,1,blockInfo.RowSize,1,0,1,0,'rowCounter',1);


    pirelab.getConstComp(hLTMultProcCntN,...
    colCntOut_Initial_Val_out_s19,...
    1,...
    'colCntOut_Initial_Val','on',0,'','','');

    pirelab.getConstComp(hLTMultProcCntN,...
    colCntOut_ctrl_const_out_s20,...
    1,...
    'colCntOut_ctrl_const');

    pirelab.getIntDelayComp(hLTMultProcCntN,...
    colCntOut_ctrl_const_out_s20,...
    colCntOut_ctrl_delay_out_s21,...
    1,'colCntOut_ctrl_delay',...
    double(0),...
    0,0,[],0,0);

    pirelab.getSwitchComp(hLTMultProcCntN,...
    [colCntOut_out_s18,colCntOut_Initial_Val_out_s19],...
    colCountOut,...
    colCntOut_ctrl_delay_out_s21,'colCntOut_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getAddComp(hLTMultProcCntN,...
    [rowCountOut,Constant10_out1_s7],...
    Add_out1_s1,...
    'Floor','Wrap','Add',hCounterT,'++');


    pirelab.getAddComp(hLTMultProcCntN,...
    [colCountOut,Constant10_out1_s7],...
    Add3_out1_s2,...
    'Floor','Wrap','Add3',hCounterT,'++');


    pirelab.getCompareToValueComp(hLTMultProcCntN,...
    rowCountOut,...
    CompareToConstant10_out1_s3,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant10'),0);


    pirelab.getCompareToValueComp(hLTMultProcCntN,...
    colCountOut,...
    CompareToConstant7_out1_s4,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant7'),0);


    pirelab.getCompareToValueComp(hLTMultProcCntN,...
    rowCountOut,...
    CompareToConstant8_out1_s5,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant8'),0);


    pirelab.getCompareToValueComp(hLTMultProcCntN,...
    colCountOut,...
    CompareToConstant9_out1_s6,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant9'),0);


    pirelab.getLogicComp(hLTMultProcCntN,...
    [CompareToConstant7_out1_s4,prodValid],...
    LogicalOperator4_out1_s10,...
    'and',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hLTMultProcCntN,...
    [prodValid,CompareToConstant8_out1_s5,CompareToConstant9_out1_s6],...
    invDone,...
    'and',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hLTMultProcCntN,...
    [CompareToConstant10_out1_s3,LogicalOperator4_out1_s10],...
    LogicalOperator6_out1_s12,...
    'and',sprintf('Logical\nOperator6'));


    pirelab.getSwitchComp(hLTMultProcCntN,...
    [Constant10_out1_s7,Switch7_out1_s14],...
    Switch10_out1_s13,...
    LogicalOperator6_out1_s12,'Switch10',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hLTMultProcCntN,...
    [Add_out1_s1,Switch8_out1_s15],...
    Switch7_out1_s14,...
    LogicalOperator4_out1_s10,'Switch7',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hLTMultProcCntN,...
    [Add3_out1_s2,colCountOut],...
    Switch8_out1_s15,...
    prodValid,'Switch8',...
    '~=',0,'Floor','Wrap');

    pirelab.instantiateNetwork(hN,hLTMultProcCntN,LTMultProcCntInSigs,LTMultProcCntOutSigs,...
    [hLTMultProcCntN.Name,'_inst']);

end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


