

function MemoryController(this,hN,MemControlInSigs,MemControlOutSigs,hBoolT,...
    hAddrT,hInputDataT,slRate,blockInfo)



    hMemoryControllerN=pirelab.createNewNetwork(...
    'Name','MemoryController',...
    'InportNames',{'ready','validIn','wrEnbStore','wrAddrStore','wrDataStore',...
    'lowerTriangEnb','wrEnbLT','wrAddrLT','wrDataLT','rdAddrLT','fwdSubEnb',...
    'wrEnbFwdSub','wrAddrFwdSub','wrDataFwdSub','rdAddrFwdSub','matMultEnb',...
    'wrEnbMatMult','wrAddrMatMult','wrDataMatMult','rdAddrMatMult','outStreamEnb','rdAddrOut'},...
    'InportTypes',[hBoolT,hBoolT,MemControlInSigs(3).Type,...
    MemControlInSigs(4).Type,...
    MemControlInSigs(5).Type,...
    MemControlInSigs(6).Type,MemControlInSigs(7).Type,...
    MemControlInSigs(8).Type,...
    MemControlInSigs(9).Type,...
    MemControlInSigs(10).Type,MemControlInSigs(11).Type,...
    MemControlInSigs(12).Type,...
    MemControlInSigs(13).Type,...
    MemControlInSigs(14).Type,...
    MemControlInSigs(15).Type,...
    MemControlInSigs(16).Type,MemControlInSigs(17).Type,...
    MemControlInSigs(18).Type,...
    MemControlInSigs(19).Type,...
    MemControlInSigs(20).Type,MemControlInSigs(21).Type,MemControlInSigs(22).Type],...
    'InportRates',slRate*ones(1,22),...
    'OutportNames',{'readData'},...
    'OutportTypes',pirelab.createPirArrayType(hInputDataT,[blockInfo.RowSize+1,0]));

    hMemoryControllerN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hMemoryControllerN.PirOutputSignals)
        hMemoryControllerN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hMemControlNinSigs=hMemoryControllerN.PirInputSignals;
    hMemControlNoutSigs=hMemoryControllerN.PirOutputSignals;






    wrtEnbS=l_addSignal(hMemoryControllerN,'wrtEnb',...
    pirelab.createPirArrayType(hBoolT,[blockInfo.RowSize+1,0]),slRate);
    wrtAddrS=l_addSignal(hMemoryControllerN,'wrtAddr',...
    pirelab.createPirArrayType(hAddrT,[blockInfo.RowSize+1,0]),slRate);
    wrtDataS=l_addSignal(hMemoryControllerN,'wrtData',...
    pirelab.createPirArrayType(hInputDataT,[blockInfo.RowSize+1,0]),slRate);
    rdAddrS=l_addSignal(hMemoryControllerN,'rdAddr',...
    pirelab.createPirArrayType(hAddrT,[blockInfo.RowSize+1,0]),slRate);



    MemMuxInSigs=[hMemControlNinSigs(2),hMemControlNinSigs(1),hMemControlNinSigs(6),...
    hMemControlNinSigs(11),hMemControlNinSigs(16),hMemControlNinSigs(3),...
    hMemControlNinSigs(7),hMemControlNinSigs(12),hMemControlNinSigs(17),...
    hMemControlNinSigs(4),hMemControlNinSigs(8),hMemControlNinSigs(13),...
    hMemControlNinSigs(18),hMemControlNinSigs(5),hMemControlNinSigs(9),...
    hMemControlNinSigs(14),hMemControlNinSigs(19),hMemControlNinSigs(10),...
    hMemControlNinSigs(15),hMemControlNinSigs(20),hMemControlNinSigs(22),...
    hMemControlNinSigs(21)];
    MemMuxOutSigs=[wrtEnbS,wrtAddrS,wrtDataS,rdAddrS];


    this.MemoryMuxing(hMemoryControllerN,MemMuxInSigs,MemMuxOutSigs,hBoolT,hAddrT,...
    hInputDataT,slRate,blockInfo);


    MemoriesInSigs=[wrtEnbS,wrtAddrS,wrtDataS,rdAddrS];
    MemoriesOutSigs=hMemControlNoutSigs(1);

    this.Memories(hMemoryControllerN,MemoriesInSigs,MemoriesOutSigs,...
    hBoolT,hAddrT,hInputDataT,slRate,blockInfo);

    pirelab.instantiateNetwork(hN,hMemoryControllerN,MemControlInSigs,MemControlOutSigs,...
    [hMemoryControllerN.Name,'_inst']);

end

function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


