

function ProcDataControl(~,hN,ProcDataControlInSigs,ProcDataControlOutSigs,...
    hBoolT,hCounterT,slRate,blockInfo)


    hProcDataControlN=pirelab.createNewNetwork(...
    'Name','ProcDataControl',...
    'InportNames',{'diagValidIn','nonDiagValidIn'},...
    'InportTypes',[hBoolT,hBoolT],...
    'InportRates',slRate*ones(1,2),...
    'OutportNames',{'fwdDataOutValid','fwdSubDone','rowProcDone','colCountReg'},...
    'OutportTypes',[hBoolT,hBoolT,hBoolT,hCounterT]);

    hProcDataControlN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hProcDataControlN.PirOutputSignals)
        hProcDataControlN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hProcDataControlNinSigs=hProcDataControlN.PirInputSignals;
    hProcDataControlNoutSigs=hProcDataControlN.PirOutputSignals;


    if bitand(blockInfo.RowSize,blockInfo.RowSize*2-1)==blockInfo.RowSize
        hCounterT=hProcDataControlN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize))+1,...
        'FractionLength',0);
    else
        hCounterT=hProcDataControlN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize)),...
        'FractionLength',0);
    end


    CompareToConstant3_out1_s3=l_addSignal(hProcDataControlN,sprintf('Compare\nTo Constant3_out1'),...
    hBoolT,slRate);
    Delay_out1_s4=l_addSignal(hProcDataControlN,'Delay_out1',hBoolT,slRate);
    ForwardDone_out1_s5=l_addSignal(hProcDataControlN,'ForwardDone_out1',...
    hBoolT,slRate);
    HDLCounter_out1_s6=l_addSignal(hProcDataControlN,'HDL Counter_out1',hCounterT,slRate);
    LogicalOperator9_out1_s8=l_addSignal(hProcDataControlN,sprintf('Logical\nOperator9_out1'),...
    hBoolT,slRate);
    RelationalOperator_out1_s9=l_addSignal(hProcDataControlN,sprintf('Relational\nOperator_out1'),...
    hBoolT,slRate);
    ConstantZeroS=l_addSignal(hProcDataControlN,'ConstantZero',hCounterT,slRate);
    ConstantOneS=l_addSignal(hProcDataControlN,'ConstantOne',hCounterT,slRate);
    DelayOutS=l_addSignal(hProcDataControlN,'DelayOut',hCounterT,slRate);
    AddOutS=l_addSignal(hProcDataControlN,'AddOut',hCounterT,slRate);
    SwitchEnbOutS=l_addSignal(hProcDataControlN,'SwitchEnbOut',hCounterT,slRate);
    CompareToConstantOutS=l_addSignal(hProcDataControlN,'CompareToConstantOut',hBoolT,slRate);
    LogicalOutS=l_addSignal(hProcDataControlN,'LogicalOut',hBoolT,slRate);

    pirelab.getConstComp(hProcDataControlN,...
    ConstantZeroS,...
    0,...
    'Constant1','on',0,'','','');

    pirelab.getConstComp(hProcDataControlN,...
    ConstantOneS,...
    1,...
    'Constant1','on',0,'','','');

    pirelab.getSwitchComp(hProcDataControlN,...
    [ConstantZeroS,SwitchEnbOutS],...
    hProcDataControlNoutSigs(4),...
    LogicalOutS,'Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getSwitchComp(hProcDataControlN,...
    [AddOutS,DelayOutS],...
    SwitchEnbOutS,...
    hProcDataControlNoutSigs(1),'Switch',...
    '~=',0,'Floor','Wrap');

    pirelab.getLogicComp(hProcDataControlN,...
    [hProcDataControlNoutSigs(3),CompareToConstantOutS],...
    LogicalOutS,...
    'or',sprintf('Logical\nOperator1'));

    pirelab.getCompareToValueComp(hProcDataControlN,...
    DelayOutS,...
    CompareToConstantOutS,...
    '==',blockInfo.RowSize,...
    sprintf('Compare\nTo Constant3'),1);


    pirelab.getIntDelayComp(hProcDataControlN,...
    hProcDataControlNoutSigs(4),...
    DelayOutS,...
    1,'Delay',...
    0,...
    0,0,[],0,0);

    pirelab.getAddComp(hProcDataControlN,...
    [DelayOutS,ConstantOneS],...
    AddOutS,...
    'Floor','Wrap','Add',hCounterT,'++');

    pirelab.getIntDelayComp(hProcDataControlN,...
    hProcDataControlNoutSigs(1),...
    Delay_out1_s4,...
    1,'Delay',...
    false,...
    0,0,[],0,0);

    if blockInfo.RowSize==1
        pirelab.getCounterComp(hProcDataControlN,...
        [hProcDataControlNoutSigs(3),hProcDataControlNoutSigs(3)],...
        HDLCounter_out1_s6,...
        'Count limited',1,1,blockInfo.RowSize,1,0,1,0,'HDL Counter',1);
    else
        pirelab.getCounterComp(hProcDataControlN,...
        hProcDataControlNoutSigs(3),...
        HDLCounter_out1_s6,...
        'Count limited',1,1,blockInfo.RowSize,0,0,1,0,'HDL Counter',1);
    end


    pirelab.getIntDelayComp(hProcDataControlN,...
    LogicalOperator9_out1_s8,...
    hProcDataControlNoutSigs(3),...
    1,'RowProcDone',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hProcDataControlN,...
    ForwardDone_out1_s5,...
    hProcDataControlNoutSigs(2),...
    1,'fwdSubDoneReg',...
    false,...
    0,0,[],0,0);


    pirelab.getCompareToValueComp(hProcDataControlN,...
    DelayOutS,...
    CompareToConstant3_out1_s3,...
    '==',blockInfo.RowSize-1,...
    sprintf('Compare\nTo Constant3'),0);


    pirelab.getLogicComp(hProcDataControlN,...
    [CompareToConstant3_out1_s3,hProcDataControlNoutSigs(1)],...
    ForwardDone_out1_s5,...
    'and','ForwardDone');


    pirelab.getLogicComp(hProcDataControlN,...
    [hProcDataControlNinSigs(1),hProcDataControlNinSigs(2)],...
    hProcDataControlNoutSigs(1),...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hProcDataControlN,...
    [Delay_out1_s4,RelationalOperator_out1_s9],...
    LogicalOperator9_out1_s8,...
    'and',sprintf('Logical\nOperator9'));


    pirelab.getRelOpComp(hProcDataControlN,...
    [DelayOutS,HDLCounter_out1_s6],...
    RelationalOperator_out1_s9,...
    '==',0,sprintf('Relational\nOperator'));



    pirelab.instantiateNetwork(hN,hProcDataControlN,ProcDataControlInSigs,...
    ProcDataControlOutSigs,[hProcDataControlN.Name,'_inst']);


end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end



