
function RowColCounter(~,hN,RowColCounterInSigs,RowColCounterOutSigs,...
    slRate,blockInfo)



    hRowColCounterN=pirelab.createNewNetwork(...
    'Name','RowColCounter',...
    'InportNames',{'enable','storeDone'},...
    'InportTypes',[RowColCounterInSigs(1).Type,RowColCounterInSigs(2).Type],...
    'InportRates',slRate*ones(1,2),...
    'OutportNames',{'rowCount','colCount'},...
    'OutportTypes',[RowColCounterOutSigs(1).Type,RowColCounterOutSigs(2).Type]);

    hRowColCounterN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hRowColCounterN.PirOutputSignals)
        hRowColCounterN.PirOutputSignals(ii).SimulinkRate=slRate;
    end
    hRowColCounterinSigs=hRowColCounterN.PirInputSignals;
    hRowColCounteroutSigs=hRowColCounterN.PirOutputSignals;


    enable=hRowColCounterinSigs(1);
    storeDone=hRowColCounterinSigs(2);

    rowCount=hRowColCounteroutSigs(1);
    colCount=hRowColCounteroutSigs(2);


    hBoolT=pir_boolean_t;

    if bitand(blockInfo.RowSize,blockInfo.RowSize*2-1)==blockInfo.RowSize
        hCounterT=hN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize))+1,...
        'FractionLength',0);
    else
        hCounterT=hN.getType('FixedPoint','Signed',false,'WordLength',ceil(log2(blockInfo.RowSize)),...
        'FractionLength',0);
    end


    ConstantS=l_addSignal(hRowColCounterN,'Constant',hCounterT,slRate);
    rowCountOutS=l_addSignal(hRowColCounterN,'rowCountOut',hCounterT,slRate);
    rowCountEnS=l_addSignal(hRowColCounterN,sprintf('rowCountEn'),hBoolT,slRate);
    colCountEndEnS=l_addSignal(hRowColCounterN,sprintf('colCountEndEn'),hBoolT,slRate);

    pirelab.getConstComp(hRowColCounterN,...
    ConstantS,...
    blockInfo.RowSize,...
    'rowSizeConstant','on',0,'','','');

    pirelab.getCounterComp(hRowColCounterN,...
    [storeDone,rowCountEnS],...
    rowCountOutS,...
    'Count limited',1,1,blockInfo.RowSize,1,0,1,0,'rowCounter',1);

    pirelab.getIntDelayComp(hRowColCounterN,...
    rowCountOutS,...
    rowCount,...
    0,'Delay',...
    0,...
    0,0,[],0,0);

    pirelab.getCounterComp(hRowColCounterN,...
    [storeDone,enable],...
    colCount,...
    'Count limited',1,1,blockInfo.ColumnSize,1,0,1,0,'colCounter',1);


    pirelab.getLogicComp(hRowColCounterN,...
    [enable,colCountEndEnS],...
    rowCountEnS,...
    'and',sprintf('rowCountEn'));

    pirelab.getRelOpComp(hRowColCounterN,...
    [colCount,ConstantS],...
    colCountEndEnS,...
    '==',1,sprintf('colCountEndEn'));


    pirelab.instantiateNetwork(hN,hRowColCounterN,RowColCounterInSigs,RowColCounterOutSigs,...
    [hRowColCounterN.Name,'_inst']);

end

function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end
