

function TriggerLogic(~,hN,TriggerLogicInSigs,TriggerLogicOutSigs,hBoolT,slRate)


    hTriggerLogicN=pirelab.createNewNetwork(...
    'Name','TriggerLogic',...
    'InportNames',{'lowerTriangDone','forwardDone'},...
    'InportTypes',[hBoolT,hBoolT],...
    'InportRates',slRate*ones(1,2),...
    'OutportNames',{'fwdSubEnb','startPulse'},...
    'OutportTypes',[hBoolT,hBoolT]);

    hTriggerLogicN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hTriggerLogicN.PirOutputSignals)
        hTriggerLogicN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hTriggerLogicNinSigs=hTriggerLogicN.PirInputSignals;
    hTriggerLogicNoutSigs=hTriggerLogicN.PirOutputSignals;


    CompareToConstant2_out1_s2=l_addSignal(hTriggerLogicN,sprintf('Compare\nTo Constant2_out1'),hBoolT,slRate);
    CompareToConstant3_out1_s3=l_addSignal(hTriggerLogicN,sprintf('Compare\nTo Constant3_out1'),hBoolT,slRate);
    Constant_out1_s4=l_addSignal(hTriggerLogicN,'Constant_out1',hBoolT,slRate);
    Constant1_out1_s5=l_addSignal(hTriggerLogicN,'Constant1_out1',hBoolT,slRate);
    Delay1_out1_s7=l_addSignal(hTriggerLogicN,'Delay1_out1',hBoolT,slRate);
    LogicalOperator1_out1_s8=l_addSignal(hTriggerLogicN,sprintf('Logical\nOperator1_out1'),hBoolT,slRate);
    Switch_out1_s9=l_addSignal(hTriggerLogicN,'Switch_out1',hBoolT,slRate);
    Switch1_out1_s10=l_addSignal(hTriggerLogicN,'Switch1_out1',hBoolT,slRate);


    pirelab.getConstComp(hTriggerLogicN,...
    Constant_out1_s4,...
    boolean(1),...
    'Constant','on',0,'','','');


    pirelab.getConstComp(hTriggerLogicN,...
    Constant1_out1_s5,...
    boolean(0),...
    'Constant1','on',1,'','','');


    pirelab.getIntDelayComp(hTriggerLogicN,...
    Switch_out1_s9,...
    hTriggerLogicNoutSigs(1),...
    1,'Delay',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hTriggerLogicN,...
    hTriggerLogicNoutSigs(1),...
    Delay1_out1_s7,...
    1,'Delay1',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hTriggerLogicN,...
    LogicalOperator1_out1_s8,...
    hTriggerLogicNoutSigs(2),...
    1,'startForwardProc',...
    false,...
    0,0,[],0,0);


    pirelab.getCompareToValueComp(hTriggerLogicN,...
    hTriggerLogicNoutSigs(1),...
    CompareToConstant2_out1_s2,...
    '==',1,...
    sprintf('Compare\nTo Constant2'),0);


    pirelab.getCompareToValueComp(hTriggerLogicN,...
    Delay1_out1_s7,...
    CompareToConstant3_out1_s3,...
    '==',0,...
    sprintf('Compare\nTo Constant3'),1);


    pirelab.getLogicComp(hTriggerLogicN,...
    [CompareToConstant2_out1_s2,CompareToConstant3_out1_s3],...
    LogicalOperator1_out1_s8,...
    'and',sprintf('Logical\nOperator1'));


    pirelab.getSwitchComp(hTriggerLogicN,...
    [Constant_out1_s4,Switch1_out1_s10],...
    Switch_out1_s9,...
    hTriggerLogicNinSigs(1),'Switch',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hTriggerLogicN,...
    [Constant1_out1_s5,hTriggerLogicNoutSigs(1)],...
    Switch1_out1_s10,...
    hTriggerLogicNinSigs(2),'Switch1',...
    '~=',0,'Floor','Wrap');



    pirelab.instantiateNetwork(hN,hTriggerLogicN,TriggerLogicInSigs,TriggerLogicOutSigs,...
    [hTriggerLogicN.Name,'_inst']);


end


function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


