

function wrAddrGaussJordan(~,hN,WrAddrLTInSigs,WrAddrLTOutSigs,...
    hBoolT,hCounterT,hAddrT,slRate,blockInfo)




    hWrAddrLTN=pirelab.createNewNetwork(...
    'Name','wrAddrGaussJordan',...
    'InportNames',{'processingEnb','swapAddrOut','swapEnb','colCountOut'},...
    'InportTypes',[hBoolT,hCounterT,hBoolT,hCounterT],...
    'InportRates',slRate*ones(1,4),...
    'OutportNames',{'wrAddrGJ'},...
    'OutportTypes',pirelab.createPirArrayType(hAddrT,[blockInfo.RowSize*2,0]));

    hWrAddrLTN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hWrAddrLTN.PirOutputSignals)
        hWrAddrLTN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hWrAddrLTNinSigs=hWrAddrLTN.PirInputSignals;
    hWrAddrLTNoutSigs=hWrAddrLTN.PirOutputSignals;

    processingEnb=hWrAddrLTNinSigs(1);
    swapAddrOut=hWrAddrLTNinSigs(2);
    swapEnb=hWrAddrLTNinSigs(3);
    colCountOut=hWrAddrLTNinSigs(4);

    wrAddrGJ=hWrAddrLTNoutSigs(1);


    pirTyp4=pir_sfixpt_t(ceil(log2(blockInfo.MatrixSize))+2,0);
    pirTyp3=hAddrT;
    pirTyp2=hCounterT;

    Constant_out1_s5=l_addSignal(hWrAddrLTN,'Constant_out1',pirTyp2,slRate);
    Constant1_out1_s6=l_addSignal(hWrAddrLTN,'Constant1_out1',pirTyp3,slRate);
    Constant2_out1_s7=l_addSignal(hWrAddrLTN,'Constant2_out1',pirTyp2,slRate);
    Constant3_out1_s8=l_addSignal(hWrAddrLTN,'Constant3_out1',pirelab.createPirArrayType(pirTyp3,[blockInfo.MatrixSize*2,0]),slRate);
    Subtract_out1_s9=l_addSignal(hWrAddrLTN,'Subtract_out1',pirTyp3,slRate);
    Subtract1_out1_s10=l_addSignal(hWrAddrLTN,'Subtract1_out1',pirTyp3,slRate);
    Switch_out1_s11=l_addSignal(hWrAddrLTN,'Switch_out1',pirTyp3,slRate);
    Switch1_out1_s12=l_addSignal(hWrAddrLTN,'Switch1_out1',pirTyp3,slRate);


    pirelab.getConstComp(hWrAddrLTN,...
    Constant_out1_s5,...
    1,...
    'Constant','on',0,'','','');



    pirelab.getConstComp(hWrAddrLTN,...
    Constant1_out1_s6,...
    0,...
    'Constant1','on',1,'','','');




    pirelab.getConstComp(hWrAddrLTN,...
    Constant2_out1_s7,...
    1,...
    'Constant2','on',0,'','','');



    pirelab.getConstComp(hWrAddrLTN,...
    Constant3_out1_s8,...
    zeros(1,blockInfo.MatrixSize*2),...
    'Constant3','on',1,'','','');



    pirelab.getAssignmentComp(hWrAddrLTN,...
    [Constant3_out1_s8,Switch1_out1_s12],...
    wrAddrGJ,...
    'One-based',{'Assign all'},...
    {1},...
    {'1'},'1',...
    'Assignment1');




    pirelab.getAddComp(hWrAddrLTN,...
    [colCountOut,Constant_out1_s5],...
    Subtract_out1_s9,...
    'Floor','Wrap','Subtract',pirTyp4,'+-');


    pirelab.getAddComp(hWrAddrLTN,...
    [swapAddrOut,Constant2_out1_s7],...
    Subtract1_out1_s10,...
    'Floor','Wrap','Subtract1',pirTyp4,'+-');




    pirelab.getSwitchComp(hWrAddrLTN,...
    [Subtract_out1_s9,Constant1_out1_s6],...
    Switch_out1_s11,...
    processingEnb,'Switch',...
    '~=',0,'Floor','Wrap');



    pirelab.getSwitchComp(hWrAddrLTN,...
    [Subtract1_out1_s10,Switch_out1_s11],...
    Switch1_out1_s12,...
    swapEnb,'Switch1',...
    '~=',0,'Floor','Wrap');



    pirelab.instantiateNetwork(hN,hWrAddrLTN,WrAddrLTInSigs,WrAddrLTOutSigs,...
    [hWrAddrLTN.Name,'_inst']);

end

function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


