

function WrAddrLowerTriang(~,hN,WrAddrLTInSigs,WrAddrLTOutSigs,...
    hBoolT,hCounterT,hAddrT,slRate,blockInfo)


    hWrAddrLTN=pirelab.createNewNetwork(...
    'Name','WrAddrLowerTriang',...
    'InportNames',{'rowCount','lowerTriangEnb','writeCount'},...
    'InportTypes',[hCounterT,hBoolT,hCounterT],...
    'InportRates',slRate*ones(1,3),...
    'OutportNames',{'wrAddrLT'},...
    'OutportTypes',pirelab.createPirArrayType(hAddrT,[blockInfo.RowSize+1,0]));

    hWrAddrLTN.setTargetCompReplacementCandidate(true);


    for ii=1:numel(hWrAddrLTN.PirOutputSignals)
        hWrAddrLTN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hWrAddrLTNinSigs=hWrAddrLTN.PirInputSignals;
    hWrAddrLTNoutSigs=hWrAddrLTN.PirOutputSignals;

    Constant_out1_s3=l_addSignal(hWrAddrLTN,'Constant_out1',hCounterT,slRate);
    Constant1_out1_s4=l_addSignal(hWrAddrLTN,'Constant1_out1',hAddrT,slRate);
    Constant2_out1_s5=l_addSignal(hWrAddrLTN,'Constant2_out1',hCounterT,slRate);
    Subtract_out1_s6=l_addSignal(hWrAddrLTN,'Subtract_out1',hAddrT,slRate);
    Subtract1_out1_s7=l_addSignal(hWrAddrLTN,'Subtract1_out1',hAddrT,slRate);
    Switch_out1_s8=l_addSignal(hWrAddrLTN,'Switch_out1',hAddrT,slRate);


    pirelab.getConstComp(hWrAddrLTN,...
    Constant_out1_s3,...
    1,...
    'Constant','on',0,'','','');


    pirelab.getConstComp(hWrAddrLTN,...
    Constant1_out1_s4,...
    0,...
    'Constant1','on',1,'','','');


    pirelab.getConstComp(hWrAddrLTN,...
    Constant2_out1_s5,...
    1,...
    'Constant2','on',0,'','','');


    pirelab.getAddComp(hWrAddrLTN,...
    [hWrAddrLTNinSigs(3),Constant_out1_s3],...
    Subtract_out1_s6,...
    'Floor','Wrap','Subtract',hCounterT,'+-');


    pirelab.getAddComp(hWrAddrLTN,...
    [hWrAddrLTNinSigs(1),Constant2_out1_s5],...
    Subtract1_out1_s7,...
    'Floor','Wrap','Subtract1',hCounterT,'+-');


    pirelab.getSwitchComp(hWrAddrLTN,...
    [Subtract_out1_s6,Constant1_out1_s4],...
    Switch_out1_s8,...
    hWrAddrLTNinSigs(2),'Switch',...
    '~=',0,'Floor','Wrap');
    SwitchOut=hdlhandles(blockInfo.RowSize,1);
    for itr=1:blockInfo.RowSize
        SwitchOut(itr)=Switch_out1_s8;
    end

    pirelab.getMuxComp(hWrAddrLTN,...
    [(SwitchOut(1:end))',Subtract1_out1_s7],...
    hWrAddrLTNoutSigs(1),...
    'concatenate');


    pirelab.instantiateNetwork(hN,hWrAddrLTN,WrAddrLTInSigs,WrAddrLTOutSigs,...
    [hWrAddrLTN.Name,'_inst']);

end

function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


