
function wrDataGaussJordan(~,hN,WrDataLTInSigs,WrDataLTOutSigs,...
    hBoolT,hInputDataT,slRate,blockInfo)





    hWrDataLTN=pirelab.createNewNetwork(...
    'Name','wrDataGaussJordan',...
    'InportNames',{'nonDiagValidOut','nonDiagDataOut1','swapDataout1','dialValidOut',...
    'swapEnb','swapDataOut2','nonDiagDataOut2','diagDataOut1','diagDataOut2'},...
    'InportTypes',[hBoolT,hInputDataT,WrDataLTInSigs(3).Type,WrDataLTInSigs(4).Type,...
    WrDataLTInSigs(5).Type,WrDataLTInSigs(6).Type,WrDataLTInSigs(7).Type,...
    WrDataLTInSigs(8).Type,WrDataLTInSigs(9).Type],...
    'InportRates',slRate*ones(1,9),...
    'OutportNames',{'wrDataGJ'},...
    'OutportTypes',pirelab.createPirArrayType(hInputDataT,[blockInfo.MatrixSize*2,0]));

    hWrDataLTN.setTargetCompReplacementCandidate(true);

    for ii=1:numel(hWrDataLTN.PirOutputSignals)
        hWrDataLTN.PirOutputSignals(ii).SimulinkRate=slRate;
    end

    hWrDataLTNinSigs=hWrDataLTN.PirInputSignals;
    hWrDataLTNoutSigs=hWrDataLTN.PirOutputSignals;

    nonDiagValidOut=hWrDataLTNinSigs(1);
    nonDiagDataOut1=hWrDataLTNinSigs(2);
    swapDataOut1=hWrDataLTNinSigs(3);
    diagValidOut=hWrDataLTNinSigs(4);
    swapEnb=hWrDataLTNinSigs(5);
    swapDataOut2=hWrDataLTNinSigs(6);
    nonDiagDataOut2=hWrDataLTNinSigs(7);
    diagDataOut1=hWrDataLTNinSigs(8);
    diagDataOut2=hWrDataLTNinSigs(9);

    wrDataGJ=hWrDataLTNoutSigs(1);



    pirTyp2=hInputDataT;

    if blockInfo.MatrixSize==1
        hArrayT=pirTyp2;
    else
        hArrayT=pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize,0]);
    end

    Assignment1_out1_s9=l_addSignal(hWrDataLTN,'Assignment1_out1',hArrayT,slRate);
    Assignment2_out1_s10=l_addSignal(hWrDataLTN,'Assignment2_out1',hArrayT,slRate);
    Assignment3_out1_s11=l_addSignal(hWrDataLTN,'Assignment3_out1',hArrayT,slRate);
    Assignment4_out1_s12=l_addSignal(hWrDataLTN,'Assignment4_out1',hArrayT,slRate);
    Constant_out1_s13=l_addSignal(hWrDataLTN,'Constant_out1',pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    Constant3_out1_s14=l_addSignal(hWrDataLTN,'Constant3_out1',hArrayT,slRate);
    Switch_out1_s15=l_addSignal(hWrDataLTN,'Switch_out1',pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    Switch2_out1_s17=l_addSignal(hWrDataLTN,'Switch2_out1',pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    VectorConcatenate1_out1_s18=l_addSignal(hWrDataLTN,sprintf('Vector\nConcatenate1_out1'),pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    VectorConcatenate2_out1_s19=l_addSignal(hWrDataLTN,sprintf('Vector\nConcatenate2_out1'),pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    VectorConcatenate3_out1_s20=l_addSignal(hWrDataLTN,sprintf('Vector\nConcatenate3_out1'),pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);
    Switch_out1_reshape_s21=l_addSignal(hWrDataLTN,'Switch_out1_reshape',pirelab.createPirArrayType(pirTyp2,[blockInfo.MatrixSize*2,0]),slRate);



    pirelab.getConstComp(hWrDataLTN,...
    Constant_out1_s13,...
    zeros(1,blockInfo.MatrixSize*2),...
    'Constant','on',1,'','','');




    pirelab.getConstComp(hWrDataLTN,...
    Constant3_out1_s14,...
    zeros(1,blockInfo.MatrixSize),...
    'Constant3','on',1,'','','');

    if blockInfo.MatrixSize==1
        pirelab.getWireComp(hWrDataLTN,nonDiagDataOut2,Assignment1_out1_s9,'AssignmentOut1');
        pirelab.getWireComp(hWrDataLTN,nonDiagDataOut1,Assignment2_out1_s10,'AssignmentOut2');
        pirelab.getWireComp(hWrDataLTN,diagDataOut1,Assignment3_out1_s11,'AssignmentOut3');
        pirelab.getWireComp(hWrDataLTN,diagDataOut2,Assignment4_out1_s12,'AssignmentOut4');
    else
        pirelab.getAssignmentComp(hWrDataLTN,...
        [Constant3_out1_s14,nonDiagDataOut2],...
        Assignment1_out1_s9,...
        'One-based',{'Assign all'},...
        {1},...
        {'1'},'1',...
        'Assignment1');


        pirelab.getAssignmentComp(hWrDataLTN,...
        [Constant3_out1_s14,nonDiagDataOut1],...
        Assignment2_out1_s10,...
        'One-based',{'Assign all'},...
        {1},...
        {'1'},'1',...
        'Assignment2');


        pirelab.getAssignmentComp(hWrDataLTN,...
        [Constant3_out1_s14,diagDataOut1],...
        Assignment3_out1_s11,...
        'One-based',{'Assign all'},...
        {1},...
        {'1'},'1',...
        'Assignment3');


        pirelab.getAssignmentComp(hWrDataLTN,...
        [Constant3_out1_s14,diagDataOut2],...
        Assignment4_out1_s12,...
        'One-based',{'Assign all'},...
        {1},...
        {'1'},'1',...
        'Assignment4');
    end



    pirelab.getSwitchComp(hWrDataLTN,...
    [VectorConcatenate2_out1_s19,Switch2_out1_s17],...
    Switch_out1_s15,...
    nonDiagValidOut,'Switch',...
    '~=',0,'Floor','Wrap');



    pirelab.getWireComp(hWrDataLTN,...
    Switch_out1_s15,...
    Switch_out1_reshape_s21,...
    'Switch_out1_wire');

    pirelab.getSwitchComp(hWrDataLTN,...
    [VectorConcatenate1_out1_s18,Switch_out1_reshape_s21],...
    wrDataGJ,...
    swapEnb,'Switch1',...
    '~=',0,'Floor','Wrap');




    pirelab.getSwitchComp(hWrDataLTN,...
    [VectorConcatenate3_out1_s20,Constant_out1_s13],...
    Switch2_out1_s17,...
    diagValidOut,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getMuxComp(hWrDataLTN,...
    [swapDataOut1,swapDataOut2],...
    VectorConcatenate1_out1_s18,...
    'concatenate');



    pirelab.getMuxComp(hWrDataLTN,...
    [Assignment2_out1_s10,Assignment1_out1_s9],...
    VectorConcatenate2_out1_s19,...
    'concatenate');


    pirelab.getMuxComp(hWrDataLTN,...
    [Assignment3_out1_s11,Assignment4_out1_s12],...
    VectorConcatenate3_out1_s20,...
    'concatenate');


    pirelab.instantiateNetwork(hN,hWrDataLTN,WrDataLTInSigs,WrDataLTOutSigs,...
    [hWrDataLTN.Name,'_inst']);

end

function hS=l_addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=-1;
    hS.SimulinkRate=simulinkRate;
end


