function[status,c_err_string]=ne_advancing_solver_diagnose(topSys,...
    topInputs,...
    h,...
    includeNonlinear)






    problem_id='physmod:simscape:engine:mli:ne_pre_transient_diagnose:DependentOrInconsistentEquations';

    diff_vars_known=false;


    print_messages_including_special=true;
    probably_linear_top=ne_probably_linear_rows(topSys,topInputs);
    if includeNonlinear
        is_equation_included_top=true(topSys.NumStates,1);
    else
        is_equation_included_top=probably_linear_top;
    end




    random_well_scaled_constant=0.817303220653433;
    alph=h*random_well_scaled_constant;
    jac_fcn=@(sys,ss_inputs)(ne_sparse_system_method(sys,'M',ss_inputs)/alph-...
    ne_sparse_system_method(sys,'DXF',ss_inputs));
    [status,c_err_string]=ne_diagnose_internal(topSys,...
    topInputs,...
    problem_id,...
    problem_id,...
    diff_vars_known,...
    print_messages_including_special,...
    is_equation_included_top,...
    probably_linear_top,...
    includeNonlinear,...
    jac_fcn);

