classdef CheckIndexingMode<slcheck.subcheck
    properties
        IndexMode=1;
    end
    methods
        function obj=CheckIndexingMode(InitParams)
            obj.CompileMode='None';
            obj.Licenses={''};
            obj.ID=InitParams.Name;
            obj.IndexMode=InitParams.IndexMode;
        end
        function result=run(this)
            result=false;
            blkObj=this.getEntity();
            if 1==this.IndexMode

                errFlag=checkZeroIdxMode(blkObj);
            else

                errFlag=checkOneIdxMode(blkObj);
            end
            if errFlag
                vObj=ModelAdvisor.ResultDetail;
                ModelAdvisor.ResultDetail.setData(vObj,'SID',blkObj);
                result=this.setResult(vObj);
            end
        end
    end
end

function errorFlag=checkZeroIdxMode(blkObj)




    defidxSlBlks={'MATLAB Function','Truth Table','State Transition Table','Test Sequence','Fcn','MATLABSystem'};



    errorFlag=isa(blkObj,'Stateflow.Object')&&...
...
    ((isa(blkObj,'Stateflow.EMFunction'))||...
...
    (isa(blkObj,'Stateflow.Chart')&&strcmp(blkObj.ActionLanguage,'MATLAB'))||...
...
    (isa(blkObj,'Stateflow.TruthTable')&&strcmp(blkObj.Language,'MATLAB')))||...
...
    isa(blkObj,'Simulink.Object')&&...
...
    ((strcmp(blkObj.BlockType,'SubSystem')&&ismember(blkObj.SFBlockType,defidxSlBlks))||...
...
    (ismember(blkObj.BlockType,defidxSlBlks))||...
...
    (strcmp(blkObj.BlockType,'MultiPortSwitch')&&...
    any(strcmp(blkObj.DataPortOrder,{'One-based contiguous','Specify indices'})))||...
...
    ((~strcmp(blkObj.BlockType,'MultiPortSwitch'))&&strcmp(blkObj.IndexMode,'One-based')));
...
end

function errorFlag=checkOneIdxMode(blkObj)



    idxSlBlks={'Assignment','ForIterator','Find','Selector'};
    errorFlag=isa(blkObj,'Stateflow.Object')&&...
...
    ((isa(blkObj,'Stateflow.Chart')&&strcmp(blkObj.ActionLanguage,'C'))||...
...
    (isa(blkObj,'Stateflow.TruthTable')&&strcmp(blkObj.Language,'C')))||...
...
    isa(blkObj,'Simulink.Object')&&...
...
    ((strcmp(blkObj.BlockType,'MultiPortSwitch')&&...
    any(strcmp(blkObj.DataPortOrder,{'Zero-based contiguous','Specify indices'})))||...
...
    (ismember(blkObj.BlockType,idxSlBlks)&&strcmp(blkObj.IndexMode,'Zero-based')));
...
end