classdef ConfigurationPropView < rfpcb.internal.apps.transmissionLineDesigner.view.PropView



properties 
ConfigurationAccordionPanel( 1, 1 )matlab.ui.container.internal.AccordionPanel
RadioButtonGroup
SingleRadioButton
DifferentialRadioButton
DifferentialSeperationLabel
DifferentialSeperationEditField
CoupledLabel
CoupledCheckbox
StackConfigurationLabel
StackConfigurationDropdown
NumberOfAggressorsLabel
NumberOfAggressorsSpinner
LeftAggressorLabel
LeftAggressorEditField
RightAggressorLabel
RightAggressorLabelEditField
end 

methods 
function obj = ConfigurationPropView( Parent )


R36
Parent = matlab.ui.container.internal.Accordion( Parent = uigridlayout( 'RowHeight', { 'fit' }, 'ColumnWidth', { 'fit' }, 'Scrollable', 'on' ) );
end 
obj@rfpcb.internal.apps.transmissionLineDesigner.view.PropView( Parent );
end 


function create( obj )
import matlab.ui.container.internal.*;


obj.ConfigurationAccordionPanel = AccordionPanel( obj.CommonProperties,  ...
Parent = obj.Parent,  ...
Title = getString( message( 'rfpcb:transmissionlinedesigner:Configuration' ) ),  ...
Tag = 'Configuration' );


createLayout( obj, obj.ConfigurationAccordionPanel );


obj.RadioButtonGroup = uibuttongroup( obj.Layout,  ...
obj.CommonProperties,  ...
BorderType = "none",  ...
Clipping = "on" );
obj.SingleRadioButton = uiradiobutton( obj.RadioButtonGroup,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:SingleRadioButton' ) ),  ...
Tag = 'Single',  ...
WordWrap = 'off',  ...
Position = [ 2, 0, 91, 22 ] );
obj.DifferentialRadioButton = uiradiobutton( obj.RadioButtonGroup,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:DifferentialRadioButton' ) ),  ...
Tag = 'Differential',  ...
WordWrap = 'off',  ...
Position = [ 93, 0, 91, 22 ] );
obj.DifferentialSeperationLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:DifferentialSeparation' ) ),  ...
Tag = 'differentialSeparationLabel' );
createErrorImage( obj, 'differentialSeperationError' );
obj.DifferentialSeperationEditField = uieditfield( 'numeric',  ...
obj.CommonProperties,  ...
Parent = obj.Layout,  ...
Tag = 'DifferentialSeparation' );
obj.CoupledLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:Coupled' ) ),  ...
Tag = 'coupledLabel' );
obj.CoupledCheckbox = uicheckbox( obj.Layout,  ...
obj.CommonProperties,  ...
Text = '',  ...
Tag = 'Coupled' );
obj.StackConfigurationLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:StackConfiguration' ) ),  ...
Tag = 'stackConfigurationLabel' );
obj.StackConfigurationDropdown = uidropdown( obj.Layout,  ...
obj.CommonProperties,  ...
Items = { getString( message( 'rfpcb:transmissionlinedesigner:Adjacent' ) ), getString( message( 'rfpcb:transmissionlinedesigner:Broadside' ) ) },  ...
Tag = 'StackConfiguration' );
obj.NumberOfAggressorsLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:NumberOfAggressors' ) ),  ...
Tag = 'noOfAggressorsLabel' );
obj.NumberOfAggressorsSpinner = uispinner( obj.Layout,  ...
obj.CommonProperties,  ...
Tag = 'NumberOfAggressors',  ...
Limits = [ 0, Inf ] );
obj.LeftAggressorLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:LeftAggressorClearance' ) ),  ...
Tag = 'leftAggressorLabel' );
createErrorImage( obj, 'leftAggressorError' );
obj.LeftAggressorEditField = uieditfield( obj.Layout,  ...
obj.CommonProperties,  ...
Tag = 'LeftAggressorClearance' );
obj.RightAggressorLabel = uilabel( obj.Layout,  ...
obj.CommonProperties,  ...
Text = getString( message( 'rfpcb:transmissionlinedesigner:RightAggressorClearance' ) ),  ...
Tag = 'rightAggressorLabel' );
createErrorImage( obj, 'rightAggressorError' );
obj.RightAggressorLabelEditField = uieditfield( obj.Layout,  ...
obj.CommonProperties,  ...
Tag = 'RightAggressorClearance' );
end 


function layout( obj )
obj.RadioButtonGroup.Layout.Row = 1;
obj.RadioButtonGroup.Layout.Column = [ 1, 3 ];

obj.DifferentialSeperationLabel.Layout.Row = 2;
obj.DifferentialSeperationEditField.Layout.Row = 2;
obj.DifferentialSeperationLabel.Layout.Column = 1;
obj.DifferentialSeperationEditField.Layout.Column = 3;
errorImage = getErrorHandle( obj, 'DifferentialSeperation' );
errorImage.Layout.Row = 2;

obj.CoupledLabel.Layout.Row = 3;
obj.CoupledCheckbox.Layout.Row = 3;
obj.CoupledLabel.Layout.Column = 1;
obj.CoupledCheckbox.Layout.Column = 3;

obj.StackConfigurationLabel.Layout.Row = 4;
obj.StackConfigurationDropdown.Layout.Row = 4;
obj.StackConfigurationLabel.Layout.Column = 1;
obj.StackConfigurationDropdown.Layout.Column = 3;

obj.NumberOfAggressorsLabel.Layout.Row = 5;
obj.NumberOfAggressorsSpinner.Layout.Row = 5;
obj.NumberOfAggressorsLabel.Layout.Column = 1;
obj.NumberOfAggressorsSpinner.Layout.Column = 3;

obj.LeftAggressorLabel.Layout.Row = 6;
obj.LeftAggressorEditField.Layout.Row = 6;
obj.LeftAggressorLabel.Layout.Column = 1;
obj.LeftAggressorEditField.Layout.Column = 3;
errorImage = getErrorHandle( obj, 'LeftAggressor' );
errorImage.Layout.Row = 6;

obj.RightAggressorLabel.Layout.Row = 7;
obj.RightAggressorLabelEditField.Layout.Row = 7;
obj.RightAggressorLabel.Layout.Column = 1;
obj.RightAggressorLabelEditField.Layout.Column = 3;
errorImage = getErrorHandle( obj, 'RightAggressor' );
errorImage.Layout.Row = 7;


adjustLayout( obj );
end 
end 
end 


% Decoded using De-pcode utility v1.2 from file /tmp/tmpBMCkYz.p.
% Please follow local copyright laws when handling this file.

