classdef GetWaveExists<serdes.internal.ibisami.ami.parameter.GeneralReservedParameter

...
...
...
...
...
...
...
...



    methods
        function param=GetWaveExists()
            param.NodeName="GetWave_Exists";
            param.Usage=serdes.internal.ibisami.ami.usage.Info();
            param.Type=serdes.internal.ibisami.ami.type.Boolean();
            param.Format=serdes.internal.ibisami.ami.format.Value({true});
            param.Description="When True, this model supports AMI_GetWave (time domain) simulation.";
        end
    end
end

