classdef ModelName<serdes.internal.ibisami.ami.parameter.GeneralReservedParameter

...
...
...
...
...
...
...
...



    methods
        function param=ModelName()
            param.NodeName="Model_Name";
            param.Usage=serdes.internal.ibisami.ami.usage.In();
            param.Type=serdes.internal.ibisami.ami.type.String();
            param.Format=serdes.internal.ibisami.ami.format.Value("");
            param.Description="The name of the instantiated IBIS model.";
        end
    end
end

