function compGenConnectivity(this)






    hCD=hdlconnectivity.getConnectivityDirector;



    if this.inputpipelevels>0
        hCD.addRegister(this.inputs(1),this.areg(1),...
        this.clock,...
        this.clockenable,...
        'realonly',this.realonly);
        hCD.addRegister(this.inputs(2),this.breg(1),...
        this.clock,...
        this.clockenable,...
        'realonly',this.realonly);

        for ii=2:this.inputpipelevels
            hCD.addRegister(this.areg(ii-1),this.areg(ii),...
            this.clock,...
            this.clockenable,...
            'realonly',this.realonly);
            hCD.addRegister(this.breg(ii-1),this.breg(ii),...
            this.clock,...
            this.clockenable,...
            'realonly',this.realonly);
        end
    end

    if this.outputpipelevels>0
        if this.inputpipelevels==0
            hCD.addDriverReceiverRegistered({this.inputs(1),this.inputs(2)},this.mreg(1),...
            hdlgetcurrentclock,hdlgetcurrentclockenable);
        else
            hCD.addDriverReceiverRegistered({this.areg(end),this.breg(end)},this.mreg(1),...
            hdlgetcurrentclock,hdlgetcurrentclockenable);
        end
        for ii=2:this.outputpipelevels
            hCD.addRegister(this.mreg(ii-1),this.mreg(ii),...
            this.clock,...
            this.clockenable,...
            'realonly',this.realonly);
        end
    end


