function resFileNames=initDVResultStruct()
    resFileNames=struct('DataFile','',...
    'HarnessModel','',...
    'SystemTestFile','',...
    'Report','',...
    'PDFReport','',...
    'LogFile','',...
    'ExtractedModel','',...
    'BlockReplacementModel','',...
    'SLTestFile','');
end
