function dlgStruct=dlgAddContainer(this,varargin)




    dlgStruct=this.dlgContainer({
    struct('Type','pushbutton',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1],...
    'ObjectMethod','exploreAction',...
    'FilePath',fullfile(matlabroot,'toolbox','rptgen','resources','StylesheetEntry.png'))
    this.dlgText(getString(message('rptgen:RptgenML_StylesheetElement:addToCurrentLabel')),...
    'RowSpan',[1,1],...
    'ColSpan',[2,2])
    },getString(message('rptgen:RptgenML_StylesheetElement:addLabel')),...
    'LayoutGrid',[1,2],...
    'ColStretch',[0,1],...
    'Visible',isLibrary(this),...
    varargin{:});
