function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CxoUa0AQVPCeFmGh0DvW4s4zsAjQJjfoqEiKiqBx2Xx0l3DvlkhGVY/DZ8'...
        ,'FJJX0nhoeJmAwL+g2JyXpB+EHxJoFxzZCY9f9+ozVf1ht9yqGOMd4d3i8X5j'...
        ,'45VP8IbPE1cuwXV85zbA5vhMbfxD3Ja5wCRF8ctwEpx4J+fdyFkk2F0dafKv'...
        ,'eM67P2fUhi8MCmDLy86KzEmTCBe+florvj1/oj1bb6sDDZN/AW/3yp/yMbHl'...
        ,'XTOQ8j9fCva5eLmeqYxIDATsmTAnVhLOGdbH5Fencekb+xCYey3o6LqX+7a8'...
        ,'GrBDQcTWfwdeGA=='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end