classdef FeatureParameterPanel<images.internal.app.registration.ui.ParameterPanel





    properties(SetObservable,...
        GetAccess={?uitest.factory.Tester,...
        ?images.internal.app.registration.ui.DocumentArea})
hFeatureNumberSlider
hFeatureQualitySlider
hTransformType
hHasRotation
        TformList={'Rigid','Similarity','Affine','Projective'};
    end

    properties
        Tform='similarity';
        HasRotation=true;
    end

    methods

        function self=FeatureParameterPanel(hParent)

            import images.internal.app.registration.ui.*;

            self.PanelHeight=136;

            self.setupParameterPanel(hParent,getMessageString('featureParameters'),'featureParameters')

            self.setupFeatureComponents();

        end

        function setupFeatureComponents(self)

            import images.internal.app.registration.ui.*;

            pos=get(self.BodyPanel,'Position');
            border=2;
            height=20;

            newpos=[10,pos(4)-height,5*height,height];
            labelpos=[10+(5*height)+border,pos(4)-height,pos(3)-(5*height)-border-10,height-3];


            self.hTransformType=uidropdown(...
            'Parent',self.BodyPanel,...
            'Position',newpos,...
            'Items',self.TformList,...
            'ItemsData',1:numel(self.TformList),...
            'Value',2,...
            'Tag','FeatureTransformType',...
            'Tooltip',getMessageString('tformTypeTooltip'),...
            'ValueChangedFcn',@(hobj,evt)self.tformCallback(hobj,evt));

            uilabel('Parent',self.BodyPanel,...
            'Text',getMessageString('tformType'),...
            'Position',labelpos,...
            'Visible','on',...
            'VerticalAlignment','top',...
            'FontName',self.FontName,...
            'FontSize',self.FontSize);

            newpos(2)=pos(4)-(2*height)-(2*border);
            labelpos=[10,newpos(2),pos(3)-10,height-3];

            uilabel('Parent',self.BodyPanel,...
            'Text',getMessageString('numDetectedFeatures'),...
            'Position',labelpos,...
            'Visible','on',...
            'VerticalAlignment','bottom',...
            'FontName',self.FontName,...
            'FontSize',self.FontSize);

            newpos(2)=pos(4)-(2.5*height)-(3*border);
            newpos(3)=8*height;

            self.hFeatureNumberSlider=uislider('Parent',self.BodyPanel,...
            'Value',0.5,...
            'Position',[newpos(1:3),3],...
            'Visible','on',...
            'Limits',[0,1],...
            'MajorTicks',[],...
            'MinorTicks',[],...
            'Tag','FeatureNumberSlider',...
            'ValueChangedFcn',@(~,~)updateSettings(self));

            newpos(2)=pos(4)-(4*height)-(4*border);
            labelpos=[10,newpos(2),pos(3)-10,height-3];

            uilabel('Parent',self.BodyPanel,...
            'Text',getMessageString('qualityFeatures'),...
            'Position',labelpos,...
            'Visible','on',...
            'VerticalAlignment','bottom',...
            'FontName',self.FontName,...
            'FontSize',self.FontSize);

            newpos(2)=pos(4)-(4.5*height)-(5*border);
            newpos(3)=8*height;

            self.hFeatureQualitySlider=uislider('Parent',self.BodyPanel,...
            'Value',0.5,...
            'Position',[newpos(1:3),3],...
            'Visible','on',...
            'Limits',[0,1],...
            'MajorTicks',[],...
            'MinorTicks',[],...
            'Tag','FeatureQualitySlider',...
            'ValueChangedFcn',@(~,~)updateSettings(self));

            newpos(3)=height;
            newpos(2)=pos(4)-(6*height)-(6*border);
            labelpos=[10+height+border,newpos(2),pos(3)-10-height-border,height-3];

            self.hHasRotation=uicheckbox(...
            'Parent',self.BodyPanel,...
            'Value',1,...
            'Position',newpos,...
            'Tag','HasRotation',...
            'Text','',...
            'Tooltip',getMessageString('hasRotationTooltip'),...
            'ValueChangedFcn',@(hobj,evt)self.hasRotationCallback(hobj,evt));

            uilabel('Parent',self.BodyPanel,...
            'Text',getMessageString('hasRotation'),...
            'Position',labelpos,...
            'Visible','on',...
            'VerticalAlignment','top',...
            'FontName',self.FontName,...
            'FontSize',self.FontSize);

        end

        function tformCallback(self,~,evt)
            self.Tform=evt.Source.Items{evt.Source.Value};
            self.updateSettings();
        end

        function hasRotationCallback(self,~,evt)
            self.HasRotation=evt.Source.Value;
            self.updateSettings();
        end

    end

    methods

        function set.Tform(self,inputString)
            idx=find(strcmpi(self.TformList,inputString));%#ok<MCSUP>
            set(self.hTransformType,'Value',idx);%#ok<MCSUP>
            self.Tform=lower(inputString);
        end

        function set.HasRotation(self,TF)
            set(self.hHasRotation,'Value',TF);%#ok<MCSUP>
            self.HasRotation=TF;
        end
    end

end

