function simrfV2phaseshift(block,action)





    top_sys=bdroot(block);
    if strcmpi(get_param(top_sys,'BlockDiagramType'),'library')...
        &&strcmpi(get_param(block,'Parent'),'simrfV2elements')
        return;
    end





    switch(action)
    case 'simrfInit'

        MaskVals=get_param(block,'MaskValues');
        idxMaskNames=simrfV2getblockmaskparamsindex(block);
        MaskWSValues=simrfV2getblockmaskwsvalues(block);

        MaskDisplay='simrfV2icon_phase_shift';
        set_param(block,'MaskDisplay',MaskDisplay)


        switch lower(MaskVals{idxMaskNames.InternalGrounding})
        case 'on'

            simrfV2repblk(struct('RepBlk','In-','SrcBlk',...
            'simrfV2elements/Gnd','SrcLib','simrfV2elements',...
            'DstBlk','Gnd1'),block);
            replace_gnd_complete=simrfV2repblk(struct('RepBlk',...
            'Out-','SrcBlk','simrfV2elements/Gnd',...
            'SrcLib','simrfV2elements','DstBlk','Gnd2'),block);

            if replace_gnd_complete
                simrfV2connports(struct('SrcBlk','F2PORT_RF',...
                'SrcBlkPortStr','LConn','SrcBlkPortIdx',2,...
                'DstBlk','Gnd1','DstBlkPortStr','LConn',...
                'DstBlkPortIdx',1),block);
                simrfV2connports(struct('SrcBlk','F2PORT_RF',...
                'SrcBlkPortStr','RConn','SrcBlkPortIdx',2,...
                'DstBlk','Gnd2','DstBlkPortStr','LConn',...
                'DstBlkPortIdx',1),block);
            end
            MaskDisplay=simrfV2_add_portlabel(MaskDisplay,1,...
            {'In'},1,{'Out'},true);

        case 'off'

            simrfV2repblk(struct('RepBlk','Gnd1','SrcBlk',...
            'nesl_utility_internal/Connection Port','SrcLib',...
            'nesl_utility_internal','DstBlk','In-','Param',...
            {{'Side','Left','Orientation','Up','Port','3'}}),...
            block);
            replace_gnd_complete=simrfV2repblk(struct(...
            'RepBlk','Gnd2',...
            'SrcBlk','nesl_utility_internal/Connection Port',...
            'SrcLib','nesl_utility_internal',...
            'DstBlk','Out-','Param',...
            {{'Side','Right','Orientation','Up','Port','4'}}),...
            block);
            if replace_gnd_complete
                simrfV2connports(struct('SrcBlk','F2PORT_RF',...
                'SrcBlkPortStr','LConn','SrcBlkPortIdx',2,...
                'DstBlk','In-','DstBlkPortStr','RConn',...
                'DstBlkPortIdx',1),block);
                simrfV2connports(struct('SrcBlk','F2PORT_RF',...
                'SrcBlkPortStr','RConn','SrcBlkPortIdx',2,...
                'DstBlk','Out-','DstBlkPortStr','RConn',...
                'DstBlkPortIdx',1),block);
            end
            MaskDisplay=simrfV2_add_portlabel(MaskDisplay,2,...
            {'In'},2,{'Out'},false);
        end
        set_param(block,'MaskDisplay',MaskDisplay);


        if regexpi(get_param(top_sys,'SimulationStatus'),...
            '^(updating|initializing)$')
            validateattributes(MaskWSValues.PhaseShift,...
            {'numeric'},{'nonempty','scalar','finite','real'},'',...
            'Phase shift');

            if strcmpi(MaskVals{idxMaskNames.PhaseShift_unit},'rad')
                theta=MaskWSValues.PhaseShift;
            elseif strcmpi(MaskVals{idxMaskNames.PhaseShift_unit},'deg')
                theta=MaskWSValues.PhaseShift*pi/180;
            end

            freqs='[0, 1]';
            S(:,:,1)=[0,1;1,0];
            S(:,:,2)=[0,exp(-1i*theta);exp(1i*theta),0];

            s_1D=simrfV2_sparams3d_to_1d(S);

            set_param([block,'/F2PORT_RF'],'ZO','[50 50]',...
            'freqs',freqs,'S',simrfV2vector2str(s_1D));
        end
    end

end