function checkSensorParameters(Block)
    autoblkscheckparams(Block,...
    {...
    'sensorId',[1,1],{'gte',0;'lte',intmax('uint32')};...
    'SampleTime',[1,1],{'st',0};...
    'tmountOffset',[1,3],{};...
    'rmountOffset',[1,3],{};...
    }...
    );
end