function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CBo8zwQQVLiNCay68qT3stGpTgOKu4aLdtMzf3bkpkPMwwljMLrKQ9e1l7'...
        ,'E6eCOsRVtgxMQ1sx0R8GNsmpxoigSXRbUx+3s+jpQb/TC5tMrSiSUUp59P1K'...
        ,'ZnTqWbV8jVbNF0kuP8QJhN7PxxLfIksSUIrWoew3qwtBBcrsgKwdziB8rOSF'...
        ,'n/XnY9E9ouKq/gFpPRCYIGuXQVWRayF5hjoRMG6SsRaom1s61LQqhd0zd4To'...
        ,'pD18+ZhndcdHyQKc6tEcbtQ='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end