function tf=isNativeDomain(domain)





    domain=convertStringsToChars(domain);

    tf=any(strcmp(domain,{...
    'linktype_rmi_simulink',...
    'linktype_rmi_matlab',...
    'linktype_rmi_data',...
    'linktype_rmi_testmgr',...
    'linktype_rmi_safetymanager',...
    'linktype_rmi_slreq'}));
end
