function[widths,headings,height]=GetColInfo(this)


    maxPathLength=this.GetMaxPathLength;







    widths=[maxPathLength+3,10,11,12,10,14,10,12];
    headings={...
    'Full HDL Name',...
    'I/O Mode',...
    'HDL Type',...
    'HDL Dims',...
    sprintf('Sample\nTime'),...
    sprintf('Simulink\nData Type'),...
    'Sign',...
    sprintf('Fraction\nLength')...
    };
    height=4;
end
