function usprops=getunsupportedprops(this)





    usprops={'ClockEnableOutputPort',...
    'ClockInputs',...
    'CoefficientSource',...
    'DALUTPartition',...
    'DARadix',...
    'ReuseAccum',...
    'SerialPartition',...
    'MultiplierInputPipeline',...
    'MultiplierOutputPipeline'};


