classdef TxSjFrequency<serdes.internal.ibisami.ami.parameter.jitterandnoise.JitterCommon

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...

    properties
    end



    methods
        function param=TxSjFrequency()
            param.NodeName="Tx_Sj_Frequency";
            param.Description="The frequency, in hertz, of the sinusoidal jitter at the Tx.";
            param.Type=serdes.internal.ibisami.ami.type.Float();
            param.AllowedTypes="Float";
            param.DirectionRx=false;
        end
    end
end

