function elaborateCGIREML(this,net,params,inputSignals,outputSignals,compname,desc)




    SHARING_FACTOR=params.SHARING_FACTOR_ACTUAL;
    NUM_MUX_INPUTS=params.NUM_MUX_INPUTS_ACTUAL;
    NUM_ROWS=params.NUM_ROWS;

    fid=fopen(fullfile(matlabroot,...
    'toolbox','dsphdl','dsphdlutilities','+dsphdlsupport','+internal',...
    '@FIRFilter','cgireml',[compname,'.m']));
    fcnBody=fread(fid,Inf,'char=>char');

    fclose(fid);

    if NUM_ROWS==1

        inputControlComp=net.addComponent2(...
        'kind','cgireml',...
        'Name','InputControl',...
        'InputSignals',inputSignals,...
        'OutputSignals',outputSignals,...
        'EMLFileName',compname,...
        'EMLFileBody',fcnBody,...
        'EMLParams',{SHARING_FACTOR,NUM_MUX_INPUTS},...
        'EMLFlag_TreatInputIntsAsFixpt',true,...
        'EMLFlag_SaturateOnIntOverflow',false,...
        'BlockComment',desc);

    else

        inputControlComp=net.addComponent2(...
        'kind','cgireml',...
        'Name','InputControlInterleave',...
        'InputSignals',inputSignals,...
        'OutputSignals',outputSignals,...
        'EMLFileName',compname,...
        'EMLFileBody',fcnBody,...
        'EMLParams',{SHARING_FACTOR,NUM_MUX_INPUTS,NUM_ROWS},...
        'EMLFlag_TreatInputIntsAsFixpt',true,...
        'EMLFlag_SaturateOnIntOverflow',false,...
        'BlockComment',desc);


    end

    inputControlComp.runConcurrencyMaximizer(0);

end
