function filterTap=elabFilterTapSystolicS(~,topNet,blockInfo,dataRate,...
    din,coef,addin,syncReset,...
    tapout,...
    DATA_SIGN,DATA_WORDLENGTH,DATA_FRACTIONLENGTH,...
    COEF_WORDLENGTH,COEF_FRACTIONLENGTH,...
    OUTPUT_WORDLENGTH,OUTPUT_FRACTIONLENGTH)







    if~isempty(syncReset)
        InportNames={din.Name,coef.Name,addin.Name,syncReset.Name};
        InportTypes=[din.Type,coef.Type,addin.Type,syncReset.Type];
        InportRates=[dataRate;dataRate;dataRate;dataRate];
    else
        InportNames={din.Name,coef.Name,addin.Name};
        InportTypes=[din.Type,coef.Type,addin.Type];
        InportRates=[dataRate;dataRate;dataRate];
    end

    OutportNames={tapout.Name};
    OutportTypes=[tapout.Type];

    filterTap=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','FilterTapSystolic',...
    'InportNames',InportNames,...
    'InportTypes',InportTypes,...
    'InportRates',InportRates,...
    'OutportNames',OutportNames,...
    'OutportTypes',OutportTypes...
    );

    inputPort=filterTap.PirInputSignals;
    outputPort=filterTap.PirOutputSignals;
    din=inputPort(1);
    coef=inputPort(2);
    addin=inputPort(3);
    if blockInfo.inMode(2)
        syncReset=inputPort(4);
    else
        syncReset='';
    end

    tapout=outputPort(1);
    if strcmpi(blockInfo.synthesisTool,'Altera Quartus II')
        synthesis_tool=2;
    else
        synthesis_tool=1;
    end

    dinType=pirgetdatatypeinfo(din.Type);
    isComplex=logical(dinType.iscomplex);
    fid=fopen(fullfile(matlabroot,...
    'toolbox','dsphdl','dsphdlutilities','+dsphdlsupport','+internal',...
    '@FIRFilter','cgireml','FilterTapSystolicS.m'),'r');

    fcnBody=fread(fid,Inf,'char=>char')';
    fclose(fid);

    if isComplex
        din_re=filterTap.addSignal2('Type',din.Type.BaseType,'Name','din_re');
        din_re.SimulinkRate=dataRate;
        din_im=filterTap.addSignal2('Type',din.Type.BaseType,'Name','din_im');
        din_im.SimulinkRate=dataRate;
        addin_re=filterTap.addSignal2('Type',addin.Type.BaseType,'Name','addin_re');
        addin_re.SimulinkRate=dataRate;
        addin_im=filterTap.addSignal2('Type',addin.Type.BaseType,'Name','addin_im');
        addin_im.SimulinkRate=dataRate;
        tapout_re=filterTap.addSignal2('Type',tapout.Type.BaseType,'Name','tapout_re');
        tapout_re.SimulinkRate=dataRate;
        tapout_im=filterTap.addSignal2('Type',tapout.Type.BaseType,'Name','tapout_im');
        tapout_im.SimulinkRate=dataRate;
        pirelab.getComplex2RealImag(filterTap,din,[din_re,din_im],'Real and Imag');
        pirelab.getComplex2RealImag(filterTap,addin,[addin_re,addin_im],'Real and Imag');
        pirelab.getRealImag2Complex(filterTap,[tapout_re,tapout_im],tapout);

        desc='FilterTapSystolicS';

        tap_re=filterTap.addComponent2(...
        'kind','cgireml',...
        'Name','fTap',...
        'InputSignals',[din_re,coef,addin_re],...
        'OutputSignals',tapout_re,...
        'EMLFileName','FilterTapSystolicS',...
        'EMLFileBody',fcnBody,...
        'EMLParams',{DATA_SIGN,DATA_WORDLENGTH,DATA_FRACTIONLENGTH...
        ,COEF_WORDLENGTH,COEF_FRACTIONLENGTH,...
        OUTPUT_WORDLENGTH,OUTPUT_FRACTIONLENGTH,synthesis_tool},...
        'ExternalSynchronousResetSignal',syncReset,...
        'EMLFlag_TreatInputIntsAsFixpt',true,...
        'EMLFlag_SaturateOnIntOverflow',false,...
        'EMLFlag_TreatInputBoolsAsUfix1',false,...
        'BlockComment',desc);
        tap_re.runConcurrencyMaximizer(0);

        tap_im=filterTap.addComponent2(...
        'kind','cgireml',...
        'Name','fTap',...
        'InputSignals',[din_im,coef,addin_im],...
        'OutputSignals',tapout_im,...
        'EMLFileName','FilterTapSystolicS',...
        'EMLFileBody',fcnBody,...
        'EMLParams',{DATA_SIGN,DATA_WORDLENGTH,DATA_FRACTIONLENGTH...
        ,COEF_WORDLENGTH,COEF_FRACTIONLENGTH,...
        OUTPUT_WORDLENGTH,OUTPUT_FRACTIONLENGTH,synthesis_tool},...
        'ExternalSynchronousResetSignal',syncReset,...
        'EMLFlag_TreatInputIntsAsFixpt',true,...
        'EMLFlag_SaturateOnIntOverflow',false,...
        'EMLFlag_TreatInputBoolsAsUfix1',false,...
        'BlockComment',desc);

        tap_im.runConcurrencyMaximizer(0);

        if blockInfo.HDLGlobalReset
            tap_re.resetNone(false);
            tap_im.resetNone(false);
        else
            tap_re.resetNone(true);
            tap_im.resetNone(true);
        end
    else
        desc='FilterTapSystolicS';

        tap=filterTap.addComponent2(...
        'kind','cgireml',...
        'Name','fTap',...
        'InputSignals',[din,coef,addin],...
        'OutputSignals',tapout,...
        'EMLFileName','FilterTapSystolicS',...
        'EMLFileBody',fcnBody,...
        'EMLParams',{DATA_SIGN,DATA_WORDLENGTH,DATA_FRACTIONLENGTH...
        ,COEF_WORDLENGTH,COEF_FRACTIONLENGTH,...
        OUTPUT_WORDLENGTH,OUTPUT_FRACTIONLENGTH,synthesis_tool},...
        'ExternalSynchronousResetSignal',syncReset,...
        'EMLFlag_TreatInputIntsAsFixpt',true,...
        'EMLFlag_SaturateOnIntOverflow',false,...
        'EMLFlag_TreatInputBoolsAsUfix1',false,...
        'BlockComment',desc);

        tap.runConcurrencyMaximizer(0);

        if blockInfo.HDLGlobalReset
            tap.resetNone(false);
        else
            tap.resetNone(true);
        end
    end



end


