function BlockList=getNumericBlocks_na_0002_JMAAB()

    BlockList={'Sum','';...
    'ComplexToRealImag','';...
    'Product','';...
    'DotProduct','';...
    'Gain','';...
    'Signum','';...
    'SubSystem','Slider Gain';...
    'SubSystem','Compare To Zero';...
    'SubSystem','Compare To Constant';...
    'SubSystem','Detect Fall Negative';...
    'SubSystem','Detect Fall Nonpositive';...
    'SubSystem','Detect Rise Positive';...
    'SubSystem','Detect Rise Nonnegative';...
    'SubSystem','Detect Change';...
    'SubSystem','Detect Decrease';...
    'SubSystem','Detect Increase';...
    'RelationalOperator',''};
end
