








function nonRecommendedBlocks=getSampleTimeDependentBlocks()
    nonRecommendedBlocks={...
...
    'DiscreteFilter','';...
    'DiscreteFir','';...
    'DiscreteStateSpace','';...
    'DiscreteTransferFcn','';...
    'DiscreteZeroPole','';...
    'DiscreteIntegrator','';...
    'SubSystem','First Order Transfer Fcn';...
    'SubSystem','Lead or Lag Compensator';...
    'SubSystem','Transfer Fcn Real Zero';...
    'SubSystem','Discrete Derivative';...
...
    'SubSystem','Discrete Transfer Function with Initial Outputs';...
    'SubSystem','Discrete Transfer Function with Initial States';...
    'SubSystem','Discrete Zero-Pole with Initial Outputs';...
    'SubSystem','Discrete Zero-Pole with Initial States'...
    };
end

