function filterSpec=createVolumeModeFilterSpec()




    filterSpec={...
    '*.dcm; *.nii; *.nii.gz; *.nrrd','All Image Files';...
    '*.dcm','Digital Imaging and Communications in Medicine (*.dcm)';...
    '*.nii; *.nii.gz','Neuroimaging Informatics Technology Initiative (*.nii;*.nii.gz)';...
    '*.nrrd','Nearly Raw Raster Data (*.nrrd)';...
    '*.*','All Files (*.*)'};

end
