function updateDeps=ConcurrentTasksConfigure(~,msg)



    updateDeps=false;
    hDlg=msg.dialog;
    launchDialog(Simulink.SoftwareTarget.openModelSelector,hDlg,...
    'launchTaskEditor',...
    message('Simulink:taskEditor:TaskEditorModelSelectDlgTitle').getString,...
    message('Simulink:taskEditor:ModelSelectorDesc').getString,...
    @(x)(DeploymentDiagram.explorer(x)));

