function dlgStruct=getDialogSchema(this,name)




    [wImageFormat,tImageFormat]=this.dlgWidget('ImageFormat',...
    'RowSpan',[1,1],...
    'ColSpan',[2,2]);

    [wCaptureTabs,tCaptureTabs]=this.dlgWidget('CaptureTabs',...
    'RowSpan',[2,2],...
    'ColSpan',[2,2]);

    [wTimeDelay,tTimeDelay]=this.dlgWidget('TimeDelay',...
    'RowSpan',[3,3],...
    'ColSpan',[2,2]);

    wProperties=this.dlgContainer({
tImageFormat
wImageFormat
wCaptureTabs
tCaptureTabs
wTimeDelay
tTimeDelay
    },getString(message('rptgen:RptDialogSnapshot:Format')),...
    'LayoutGrid',[3,2],...
    'RowSpan',[1,1],...
    'ColSpan',[1,1]);

    wDisplayOptions=this.gr_dlgDisplayOptions([],[],...
    'RowSpan',[4,4],...
    'ColSpan',[1,1]);


    dlgStruct=this.dlgMain(name,{
wProperties
wDisplayOptions
    },...
    'LayoutGrid',[4,1],...
    'RowStretch',[0,0,0,1]);
