classdef(Abstract,ConstructOnLoad,UseClassDefaultsOnLoad,Hidden,...
    AllowedSubclasses={?matlab.graphics.controls.internal.Backdrop,...
    ?matlab.graphics.controls.internal.FadeGroup,...
    ?matlab.graphics.controls.internal.ProgressBar,...
    ?matlab.graphics.shape.internal.Button,...
    })Control<handle






end
