classdef BCI_Protocol<serdes.internal.ibisami.ami.parameter.BCIReservedParameter

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=BCI_Protocol()
            param.NodeName="BCI_Protocol";
            param.Usage=serdes.internal.ibisami.ami.usage.In;
            param.Type=serdes.internal.ibisami.ami.type.String;
            param.Format=serdes.internal.ibisami.ami.format.Value("Unknown");
            param.Description=...
            "This Device supports an Unknown Back-Channel Interface Protocol.";
            param.AllowedUsages=["In"];%#ok<*NBRAK>
            param.AllowedTypes=["String"];
            param.AllowedFormats=["Value","List"];
            param.EarliestRequiredVersion=7.0;
        end
    end
end

