classdef BCI_Training_UI<serdes.internal.ibisami.ami.parameter.BCIReservedParameter

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=BCI_Training_UI()
            param.NodeName="BCI_Training_UI";
            param.Usage=serdes.internal.ibisami.ami.usage.In;
            param.Type=serdes.internal.ibisami.ami.type.Integer;
            param.Format=serdes.internal.ibisami.ami.format.Value(1);
            param.Description=...
            "How long the time variant model may take to complete training.";
            param.AllowedUsages=["In"];%#ok<*NBRAK>
            param.AllowedTypes=["Integer"];
            param.AllowedFormats=["Value"];
            param.EarliestRequiredVersion=7.0;
            param.DirectionTx=false;
            param.DirectionRx=true;
        end
    end
end

