function writeSfcnMdlHeader(h,fid,infoStruct)%#ok<INUSL>





    thisDate=datestr(now,0);
    slVer=ver('simulink');


    if infoStruct.isCPP==false&&...
        infoStruct.canUseSFcnCGIRAPI==false
        fext='.c';
    else
        fext='.cpp';
    end

    fprintf(fid,'/*\n');
    fprintf(fid,' *   %s%s Simple C-MEX S-function for function call.\n',...
    infoStruct.Specs.SFunctionName,fext);
    fprintf(fid,' *\n');
    fprintf(fid,' *   ABSTRACT:\n');
    fprintf(fid,' *     The purpose of this sfunction is to call a simple legacy \n');
    fprintf(fid,' *     function during simulation:\n');
    fprintf(fid,' *\n');
    fprintf(fid,' *        %s\n',infoStruct.Specs.OutputFcnSpec);
    fprintf(fid,' *\n');
    fprintf(fid,' *   Simulink version           : %s %s %s\n',...
    slVer.Version,slVer.Release,slVer.Date);
    fprintf(fid,' *   %s source code generated on : %s\n',infoStruct.Specs.Options.language,thisDate);

    fprintf(fid,'\n');
    fprintf(fid,' * THIS S-FUNCTION IS GENERATED BY THE LEGACY CODE TOOL AND MAY NOT WORK IF MODIFIED\n');
    fprintf(fid,'\n');

    fprintf(fid,' */\n');
    fprintf(fid,'\n');



    fprintf(fid,'/*\n');
    fprintf(fid,'     %%%%%%-MATLAB_Construction_Commands_Start\n');
    fprintf(fid,'%s',legacycode.LCT.generateSpecConstructionCmd(infoStruct.Specs,'c'));
    fprintf(fid,'     %%%%%%-MATLAB_Construction_Commands_End\n');
    fprintf(fid,' */\n');
    fprintf(fid,'\n');



