function dstString=HTMLjsencode(srcString,choice)





    persistent EncodeTable;

    if isempty(EncodeTable)
        [EncodeTable]=loc_create_data;
    end

    if nargin~=2
usage
        return
    end;


    dstString='';
    switch choice
    case 'encode'
        for i=1:length(EncodeTable)
            srcString=strrep(srcString,EncodeTable(i,1),EncodeTable(i,2));
        end
        dstString=srcString;








    case 'decode'

        for i=length(EncodeTable):-1:1
            srcString=strrep(srcString,EncodeTable(i,2),EncodeTable(i,1));
        end
        dstString=srcString{:};
    otherwise
        usage;
        return
    end


    function usage
        disp(' dstString = HTMLjsencode(srcString, ''encode'')');
        disp(' dstString = HTMLjsencode(srcString, ''decode'')');

        function[EncodeTable]=loc_create_data





            EncodeTable=...
            {'z','z0';...
            '(','z1';...
            ')','z2';...
            '?','z3';...
            '&','z4';...
            '$','z5';...
            '|','z6';...
            '^','z7';...
            '{','z8';...
            '}','z9';...
            '''','za';...
            '"','zb';...
            '\','zc';...
            '[','zd';...
            ']','ze';...
            '/','zf';...
            '#','zg';...
            '<','zh';...
            '>','zi';...
            '.','zj';...
            '+','zk';...
            '=','zl';...
            '~','zm';...
            '@','zn';...
            '%','zo';...
            '`','zp';...
            ',','zq';...
            sprintf('\n'),'zr';...
            ' ','zs';...
            '*','zt';...
            ':','zu';...
            '!','zv';...
            ';','zw';...
            sprintf('\r'),'zx';...
            };



