function[testfailure,display]=getTestFailureText(this,signame_in,expected_in,isComplex)










    if(nargin<=3)
        isComplex=false;
    end

    if isComplex

        signame=signame_in{1};
        signame_im=signame_in{2};
        expected=expected_in{1};
        expected_im=expected_in{2};
    else
        signame=signame_in;
        expected=expected_in;
    end

    severitylevel_msg='ERROR';


    idx=hdlsignalfindname(signame);
    portsltype=hdlsignalsltype(idx);
    portvtype=hdlsignalvtype(idx);
    if iscell(portvtype)
        portsltype=portsltype{1};
        portvtype=portvtype{1};
    end

    [portsize,~,portsigned]=hdlgetsizesfromtype(portsltype);

    if hdlgetparameter('isvhdl')
        if strcmpi(portvtype,'real')
            testfailure=['abs( ',signame,' - ',...
            expected,') > ',this.doubleErrorMargin];
        elseif strfind(portvtype,'vector_of_real')
            testfailure=['NOT(isEqual(',signame,', ',expected,'))'];
        elseif~strcmp(this.fixedPointErrorMargin,'0')
            if portsigned==1&&~this.isStdLogicVector(portvtype)
                testfailure=['(Is_X(std_logic_vector(',signame,')) OR abs(',signame,'  - ',...
                expected,') > ',this.fixedPointErrorMargin,')'];%#ok<I18N_Concatenated_Msg>
            elseif portsigned==1&&this.isStdLogicVector(portvtype)
                testfailure=['(Is_X(',signame,') OR abs(signed(',signame,')  - signed(',...
                expected,')) > ',this.fixedPointErrorMargin,')'];%#ok<I18N_Concatenated_Msg>
            else
                testfailure=['(Is_X(',signame,') OR abs(signed( ''0'' & ',signame,')  - signed( ''0'' & ',...
                expected,')) > ',this.fixedPointErrorMargin,')'];%#ok<I18N_Concatenated_Msg>
            end
        else
            testfailure=[signame,' /= ',expected];
        end
    else
        gp=pir;
        isnfp=isNativeFloatingPointMode();
        if(portsize==0&&~gp.getTargetCodeGenSuccess&&~isnfp)
            testfailure=['abs_real($bitstoreal(',signame,') - ',...
            expected,') > ',this.doubleErrorMargin];
            if~isComplex
                display=['           $display("',...
                severitylevel_msg,' in ',signame,...
                ' at time %%t : Expected ''%%f'' Actual ''%%f''", \n',...
                '                    $time, ',expected,...
                ', $bitstoreal(',signame,'));\n'];%#ok<I18N_Concatenated_Msg>
            else
                testfailure=[testfailure,' || '...
                ,'abs_real($bitstoreal(',signame_im,') - ',...
                expected_im,') > ',this.doubleErrorMargin];
                display=['           $display("',...
                severitylevel_msg,' in ',signame,'/',signame_im...
                ,' at time %%t : '...
                ,'Expected (real) ''%%f'' Actual (real)''%%f'',',...
'Expected (imaginary) ''%%f'' Actual (imaginary)''%%f''",'...
                ,'\n',...
                '                    $time, ',...
                expected,', $bitstoreal(',signame,'), '...
                ,expected_im,', $bitstoreal(',signame_im,') '...
                ,');\n'];%#ok<I18N_Concatenated_Msg>
            end
        elseif~strcmp(this.fixedPointErrorMargin,'0')&&~gp.getTargetCodeGenSuccess
            if portsigned==1
                testfailure=['((abs(',signame,' - ',...
                expected,') > ',this.fixedPointErrorMargin,') !== 0 )'];
                if~isComplex
                    display=['               $display("',...
                    severitylevel_msg,'  in ',signame,...
                    ' at time %%t : Expected ''%%h'' Actual ''%%h''", \n',...
                    '                        $time, ',expected,...
                    ', ',signame,');\n'];%#ok<I18N_Concatenated_Msg>
                else
                    testfailure=[testfailure,' || '...
                    ,'((abs(',signame_im,' - ',...
                    expected_im,') > ',this.fixedPointErrorMargin,') !== 0 )'];
                    display=['               $display("',...
                    severitylevel_msg,'  in ',signame,'/',signame_im...
                    ,' at time %%t :'...
                    ,' Expected (real) ''%%h'' Actual (real) ''%%h'',',...
' Expected (imaginary) ''%%h'' Actual (imaginary) ''%%h''",'...
                    ,'\n',...
                    '                        $time, ',...
                    expected,', ',signame,', '...
                    ,expected_im,', ',signame_im,...
                    ');\n'];%#ok<I18N_Concatenated_Msg>
                end
            else
                testfailure=['((abs($signed(',signame,') - $signed (',...
                expected,')) > ',this.fixedPointErrorMargin,') !== 0 )'];%#ok<I18N_Concatenated_Msg>
                if~isComplex
                    display=['               $display("',...
                    severitylevel_msg,'  in ',signame,...
' at time %%t :'...
                    ,' Expected ''%%h'' Actual ''%%h''", \n',...
                    '                        $time, ',...
                    expected,', $signed(',signame,'));\n'];%#ok<I18N_Concatenated_Msg>
                else
                    testfailure=[testfailure,' || '...
                    ,'((abs($signed(',signame_im,') - $signed (',...
                    expected_im,')) > ',this.fixedPointErrorMargin,') !== 0 )'];
                    display=['               $display("',...
                    severitylevel_msg,'  in ',signame,'/',signame_im...
                    ,' at time %%t :'...
                    ,' Expected (real) ''%%h'' Actual (real) ''%%h'',',...
' Expected (imaginary) ''%%h'' Actual (imaginary) ''%%h''",'...
                    ,'\n',...
                    '                        $time, ',...
                    expected,', $signed(',signame,'),'...
                    ,expected_im,', $signed(',signame_im,'),'...
                    ,');\n'];%#ok<I18N_Concatenated_Msg>
                end
            end

        else
            testfailure=[signame,' !== ',expected];
            if~isComplex
                display=['           $display("',...
                severitylevel_msg,' in ',signame,...
' at time %%t :'...
                ,' Expected ''%%h'' Actual ''%%h''", \n',...
                '                    $time, ',...
                expected,', ',signame,');\n'];%#ok<I18N_Concatenated_Msg>
            else
                testfailure=[testfailure,' || '...
                ,signame_im,' !== ',expected_im];
                display=['           $display("',...
                severitylevel_msg,' in ',signame,'/',signame_im,...
' at time %%t :'...
                ,' Expected (real) ''%%h'' Actual (real) ''%%h'',',...
' Expected (imaginary) ''%%h'' Actual (imaginary) ''%%h''",'...
                ,'\n',...
                '                    $time, ',...
                expected,', ',signame,', ',...
                expected_im,', ',signame_im,', ',...
                ');\n'];%#ok<I18N_Concatenated_Msg>
            end
        end
    end


