function hdlbody=hdlclkgenbeh(this,srcDone,snkDone)


    if this.isDUTsingleClock
        clkComment='System Clock (fast clock) and reset';
    else
        clkComment='System Clocks (all rates) and reset (based off slowest clock)';
    end
    hdlbody=[this.insertComment({clkComment}),'\n'];

    if this.ForceClock==1
        if hdlgetparameter('isvhdl')
            if hdlgetparameter('clockedge')==0;
                clockHigh='''1''';
                clockLow='''0''';
            else
                clockHigh='''0''';
                clockLow='''1''';
            end

            if this.DutHasOutputs==true
                endsignaltest=['    IF ',hdlsignalname(snkDone),' = ''1'' THEN\n'];
            else
                endsignaltest=['    IF ',hdlsignalname(srcDone),' = ''1'' THEN\n'];
            end

            for ii=1:length(this.clockTable)
                if this.clockTable(ii).Kind==0
                    clockName=this.clockTable(ii).Name;
                    hdlbody=[hdlbody,...
                    '  ',clockName,'_gen: PROCESS\n',...
                    '  BEGIN\n',...
                    '    ',clockName,' <= ',clockHigh,';\n',...
                    '    WAIT FOR ',this.hdlclkhigh(clockName),';\n',...
                    '    ',clockName,' <= ',clockLow,';\n',...
                    '    WAIT FOR ',this.hdlclklow(clockName),';\n',...
                    endsignaltest,...
                    '      ',clockName,' <= ',clockHigh,';\n',...
                    '      WAIT FOR ',this.hdlclkhigh(clockName),';\n',...
                    '      ',clockName,' <= ',clockLow,';\n',...
                    '      WAIT FOR ',this.hdlclklow(clockName),';\n',...
                    '      WAIT;\n',...
                    '    END IF;\n',...
                    '  END PROCESS ',clockName,'_gen;\n\n'];%#ok<*AGROW>
                end
            end
        else
            if hdlgetparameter('clockedge')==0;
                clockHigh='1''b1';
                clockLow='1''b0';
            else
                clockHigh='1''b0';
                clockLow='1''b1';
            end


            if this.DutHasOutputs==true
                endsignaltest=['    if (',hdlsignalname(snkDone),' == 1) begin\n'];
            else
                endsignaltest=['    if (',hdlsignalname(srcDone),' == 1) begin\n'];
            end
            for ii=1:length(this.clockTable)
                if this.clockTable(ii).Kind==0
                    clockName=this.clockTable(ii).Name;
                    hdlbody=[hdlbody,...
                    '  always  // clock generation\n',...
                    '  begin // ',clockName,'_gen\n',...
                    '    ',clockName,' <= ',clockHigh,';\n',...
                    '    # ',this.hdlclkhigh(clockName),';\n',...
                    '    ',clockName,' <= ',clockLow,';\n',...
                    '    # ',this.hdlclklow(clockName),';\n',...
                    endsignaltest,...
                    '      ',clockName,' <= ',clockHigh,';\n',...
                    '      # ',this.hdlclkhigh(clockName),';\n',...
                    '      ',clockName,' <= ',clockLow,';\n',...
                    '      # ',this.hdlclklow(clockName),';\n',...
                    '      $stop;\n',...
                    '    end\n',...
                    '  end  // ',clockName,'_gen\n\n'];
                end
            end
        end

    end
