function renderWidgets(this)




    handles=this.Handles;
    statusBar=this.Application.Handles.statusBar;


    handles.RBWStatus=spcwidgets.Status(statusBar,...
    'Tag','RBWStatus',...
    'AutoGrow',true,...
    'Visible','off',...
    'Tooltip',getString(message('dspshared:SpectrumAnalyzer:RBWStatusTooltipString')));


    handles.SampleRateStatus=spcwidgets.Status(statusBar,...
    'Tag','SampleRateStatus',...
    'AutoGrow',true,...
    'Visible','off',...
    'Tooltip',getString(message('dspshared:SpectrumAnalyzer:SampleRateStatusTooltipString')));


    handles.TimeResolutionStatus=spcwidgets.Status(statusBar,...
    'Tag','TimeResolutionStatus',...
    'AutoGrow',true,...
    'AutoGrowAllowSkips',false,...
    'Visible','off',...
    'Tooltip',getString(message('dspshared:SpectrumAnalyzer:TimeResolutionStatusTooltipString')));


    handles.TimeOffsetStatus=spcwidgets.Status(statusBar,...
    'Tag','TimeOffsetStatus',...
    'AutoGrow',true,...
    'AutoGrowAllowSkips',false,...
    'Visible','off',...
    'Width',60,...
    'AutoGrowMin',100,...
    'Tooltip',getString(message('dspshared:SpectrumAnalyzer:SpectrogramTimeOffsetStatusTooltipString')));

    this.Handles=handles;
    setup(this,getVisualizationParent(this.Application));
