function names=getRootParameterNames(~)










    names={'MDLFileChangedOnDiskHandling',...
    'MDLFileChangedOnDiskChecks',...
    'AutoSaveOptions',...
    'ErrorIfLoadNewModel',...
    'ErrorIfLoadShadowedModel',...
    'NotifyIfLoadOldModel',...
    'SaveSLXThumbnail',...
    'ModelFileFormat',...
'ProtectedModelValidateCertificate'...
    };
