function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CxocaQBgVPiNCaKxmnYiyeWR5RPboOpGXTpkbxxCnnr3UXfUrS4ymJHkHp'...
        ,'GLAEMDId7w8gqSRSmYzpPX6WguQt07pIbtqLQdzh38qgTnDP7oYcxs4fNjjz'...
        ,'YVzL4J2toRESGzU98wwTmYHllsYbE55ieWrVYGq5McSP7C7SjAyaJMhFJuZF'...
        ,'77VJqlgcRIsRyyTkGDQC/V7Qas3RMA2CdECLvQUeIvU6kODNMAtZCLa+1i0+'...
        ,'9zqOKpjJURfnuiF/UQn8JiVDBdMspts8Cyg2btneowKAvjrPIidKWKak427a'...
        ,'mRY2'];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end