function out=getConfigRTW






    tgtGrp=[DAStudio.message('RTW:configSet:RTWTargetSelName'),' > '];
    buildGrp=[DAStudio.message('RTW:configSet:RTWBuildProName'),' > '];
    out={...
    [tgtGrp,strrep(DAStudio.message('RTW:configSet:RTWSystemTargetFileName'),':','')],'SystemTargetFile';...
    [tgtGrp,strrep(DAStudio.message('RTW:configSet:RTWTargetLangName'),':','')],'TargetLang';...
    [buildGrp,strrep(DAStudio.message('RTW:configSet:targetCommonTLCOptionsName'),':','')],'TLCOptions';...
    [buildGrp,DAStudio.message('RTW:configSet:RTWGenMakefileName')],'GenerateMakefile';...
    [buildGrp,strrep(DAStudio.message('RTW:configSet:targetCommonMakeCommName'),':','')],'MakeCommand';...
    [buildGrp,strrep(DAStudio.message('RTW:configSet:targetCommonTempMakeName'),':','')],'TemplateMakefile';...
    DAStudio.message('RTW:configSet:targetCommonGenCodeName'),'GenCodeOnly'...
    };
