function schema=simOutputMenu(cbinfo)



    schema=simOutputMenuV2(cbinfo);
end


function schema=simOutputMenuV2(cbinfo)
    schema=sl_container_schema;
    schema.tag='Simulink:SimulationRecordMenu';
    schema.label=DAStudio.message('Simulink:studio:SimulationRecordMenu');


    im=DAStudio.InterfaceManagerHelper(cbinfo.studio,'Simulink');

    laSchema=getLogicAnalyzerSchema();
    besSchemaFcn=getBirdsEyeScopeSchema();
    schema.childrenFcns={...
    @(x)Simulink.sdi.internal.SLMenus.openSDI(x,true),...
    laSchema,...
    besSchemaFcn,...
    'separator',...
    im.getAction('Simulink:InspectSelectedSignals'),...
    @(x)Simulink.sdi.internal.SLMenus.logSelectedSignals(x),...
    im.getAction('Simulink:SimulationRecord'),...
    'separator',...
    im.getAction('Simulink:ConfigureSignalLogging'),...
    im.getAction('Simulink:AboutSignalLogging'),...
    };

    schema.autoDisableWhen='Never';
end
