function copyMask(srcBlk,dstBlk)

    srcMask=Simulink.Mask.get(srcBlk);
    dstMask=Simulink.Mask.get(dstBlk);














    if isempty(srcMask)


        if~isempty(dstMask)&&IsLocalMask(dstMask)
            dstMask.delete;
        end

        return;
    end

    if srcMask.isAutoGeneratedModelBlockMask


        if~isempty(dstMask)
            try

                for i=1:length(srcMask.Parameters)
                    parameterName=srcMask.Parameters(i).Name;
                    dstMask.getParameter(parameterName).Value=srcMask.getParameter(parameterName).Value;
                end
            catch

            end
        end
        return;
    end


    if~IsLocalMask(srcMask)


        if~isempty(dstMask)&&IsLocalMask(dstMask)
            dstMask.delete;
        end


        dstMask=Simulink.Mask.get(dstBlk);
        if isempty(dstMask)
            return;
        end

        try
            set_param(dstBlk,'MaskValueString',get_param(srcBlk,'MaskValueString'));
        catch

        end

        return;
    end






    assert(~isempty(srcMask));


    assert(IsLocalMask(srcMask));

    if isempty(dstMask)||~IsLocalMask(dstMask)

        CopyMaskToDst(srcMask,dstBlk);
    else
        assert(IsLocalMask(dstMask));


        dstMask.delete;
        CopyMaskToDst(srcMask,dstBlk);
    end

end


function ret=IsLocalMask(maskObj)
    ret=strcmp(get_param(maskObj.getOwner.handle,'LinkStatus'),'none')||...
    maskObj.isMaskOnLinkBlock;
end

function CopyMaskToDst(srcMask,dstBlk)
    assert(~isempty(srcMask));

    try
        dstMask=Simulink.Mask.create(dstBlk);
        dstMask.copy(srcMask);
    catch ME
        Simulink.harness.internal.warn(ME);
    end
end
