function [ testingSinks, testingSinkValues ] = getTestingSinksList( ExpandedListOpts )


arguments

    ExpandedListOpts.IncludeChartAndAssmt = true;
end
import Simulink.harness.internal.TestHarnessSinkTypes;

testingSinks = { TestHarnessSinkTypes.OUTPORT.name,  ...
    TestHarnessSinkTypes.SCOPE.name,  ...
    TestHarnessSinkTypes.TO_WORKSPACE.name,  ...
    TestHarnessSinkTypes.TO_FILE.name,  ...
    TestHarnessSinkTypes.TERMINATOR.name,  ...
    TestHarnessSinkTypes.NONE.name,  ...
    TestHarnessSinkTypes.CUSTOM.name };

testingSinkValues = [ TestHarnessSinkTypes.OUTPORT.val,  ...
    TestHarnessSinkTypes.SCOPE.val,  ...
    TestHarnessSinkTypes.TO_WORKSPACE.val,  ...
    TestHarnessSinkTypes.TO_FILE.val,  ...
    TestHarnessSinkTypes.TERMINATOR.val,  ...
    TestHarnessSinkTypes.NONE.val,  ...
    TestHarnessSinkTypes.CUSTOM.val ];

if ExpandedListOpts.IncludeChartAndAssmt
    testingSinks{ end  + 1 } = TestHarnessSinkTypes.STATEFLOW.name;
    testingSinks{ end  + 1 } = TestHarnessSinkTypes.REACTIVE_TEST.name;

    testingSinkValues = [ testingSinkValues, TestHarnessSinkTypes.STATEFLOW.val ];
    testingSinkValues = [ testingSinkValues, TestHarnessSinkTypes.REACTIVE_TEST.val ];
end

end

