function isSLFuncBlock=isSimulinkFunctionBlockForHarnessCreation(harnessOwnerHandle)
    hanressOwnerUDD=get_param(harnessOwnerHandle,'Object');


    isSLFuncBlock=isa(hanressOwnerUDD,'Simulink.SubSystem')&&...
    ~isempty(find_system(Simulink.ID.getFullName(harnessOwnerHandle),...
    'MatchFilter',@Simulink.match.internal.filterOutInactiveVariantSubsystemChoices,...
    'FirstResultOnly','on',...
    'FollowLinks','on','BlockType','TriggerPort','IsSimulinkFunction','on'));
end
