

classdef slacademyprefs
    properties(Constant)


        SimulinkOnrampCourseCode='simulink';
        StateflowOnrampCourseCode='stateflow';
        ControlsOnrampCourseCode='controls';
        SimscapeOnrampCourseCode='simscape';
        CircuitsOnrampCourseCode='circuits';
        SimulinkFundamentalsCourseCode='slbe';
        PowerElectronicsOnrampCourseCode='powerelectronics';

        thisPath=fileparts(mfilename('fullpath'));
        filesepIndices=strfind(learning.simulink.preferences.slacademyprefs.thisPath,filesep);
        toolboxPath=learning.simulink.preferences.slacademyprefs.thisPath(1:learning.simulink.preferences.slacademyprefs.filesepIndices(end-3)-1);
        contentPath=fullfile(matlabroot,'derived','toolbox','learning','simulink','learning_content','content');


        webPath=learning.simulink.preferences.slacademyprefs.getWebPath();

        Paths=struct('SrcPath',{fullfile(learning.simulink.preferences.slacademyprefs.toolboxPath,'slbridge')},...
        'SLCustomizationsPath',{fullfile(learning.simulink.preferences.slacademyprefs.toolboxPath,'Prefs')},...
        'CoursePath',{fullfile(learning.simulink.preferences.slacademyprefs.webPath,...
        'learning_content','content')},...
        'UserPath',{fullfile(tempdir,'SimulinkTraining')})
        CourseMap=containers.Map({...
        learning.simulink.preferences.slacademyprefs.SimulinkOnrampCourseCode,...
        learning.simulink.preferences.slacademyprefs.StateflowOnrampCourseCode,...
        learning.simulink.preferences.slacademyprefs.ControlsOnrampCourseCode,...
        learning.simulink.preferences.slacademyprefs.SimscapeOnrampCourseCode,...
        learning.simulink.preferences.slacademyprefs.CircuitsOnrampCourseCode,...
        learning.simulink.preferences.slacademyprefs.SimulinkFundamentalsCourseCode,...
        learning.simulink.preferences.slacademyprefs.PowerElectronicsOnrampCourseCode,...
        },learning.simulink.preferences.slacademyprefs.getCourseObjects());
        Remote=struct('RelApplicationURL',{'static/sltraining/'});

        productNames={'Simulink','Stateflow','Simulink Control Design','Simscape','Simscape Electrical'};
        licenseNames={'simulink','stateflow','simulink_control_design','simscape','power_system_blocks'};
        prodLicMap=containers.Map(learning.simulink.preferences.slacademyprefs.productNames,...
        learning.simulink.preferences.slacademyprefs.licenseNames);
    end

    methods(Static,Access=private)
        function webPath=getWebPath()
            filePath=mfilename('fullpath');
            v=version('-release');
            isR2018b=strcmp(v,'2018b');
            if isR2018b
                p=strrep(fileparts(filePath),...
                ['m',filesep,'+learning',filesep,'+simulink',filesep,'+preferences',filesep,'@slacademyprefs'],'');
                webPath=fileparts(fullfile(p));
            else
                webPath=fullfile(matlabroot,'derived/toolbox/learning/simulink/');
            end
        end

        function courseObjs=getCourseObjects()




            SimulinkOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Simulink Onramp',{'Simulink'},learning.simulink.preferences.Category.FREE,...
            'learning:simulink:requirements:CourseTitle',...
            14,2,'');
            StateflowOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Stateflow Onramp',{'Stateflow'},learning.simulink.preferences.Category.FREE,...
            'learning:simulink:stateflowOnrampRequirements:CourseTitle',...
            12,2,'');

            ControlsOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Control Design Onramp with Simulink',{'Simulink Control Design'},...
            learning.simulink.preferences.Category.FREE,...
            'learning:simulink:controlsRequirements:CourseTitle',...
            7,1,'');
            SimscapeOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Simscape Onramp',{'Simscape'},learning.simulink.preferences.Category.FREE,...
            'learning:simulink:simscapeOnrampRequirements:CourseTitle',...
            9,1.5,'');
            CircuitsOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Circuit Simulation Onramp',{'Simscape Electrical','Simscape'},...
            learning.simulink.preferences.Category.FREE,...
            'learning:simulink:circuitsOnrampRequirements:CourseTitle',...
            7,2,'');
            SimulinkFundamentalsCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Simulink Fundamentals',{'Simulink'},...
            learning.simulink.preferences.Category.PAID,...
            'learning:simulink:simulinkFundamentalsRequirements:CourseTitle',...
            9,10,'/access/simulink-fundamentals/slbe');
            PowerElectronicsOnrampCourseInfo=learning.simulink.preferences.CourseInfo(...
            'Power Electronics Simulation Onramp',{'Simscape Electrical','Simscape'},...
            learning.simulink.preferences.Category.FREE,...
            'learning:simulink:powerElectronicsOnrampRequirements:CourseTitle',...
            5,1.5,'');
            courseObjs={...
            SimulinkOnrampCourseInfo,...
            StateflowOnrampCourseInfo,...
            ControlsOnrampCourseInfo,...
            SimscapeOnrampCourseInfo,...
            CircuitsOnrampCourseInfo,...
            SimulinkFundamentalsCourseInfo,...
PowerElectronicsOnrampCourseInfo
            };
        end
    end

end