function out = convertToStruct( schedule )

arguments
schedule( 1, 1 )simulink.schedule.OrderedSchedule
end 

out = struct(  ...
'Description', { schedule.Description },  ...
'PartitionProperties', { schedule.PartitionProperties },  ...
'IsExportFunction', { schedule.IsExportFunction },  ...
'Version', { schedule.Version },  ...
'Events', { schedule.Events } );

end 
