function dlgStruct=getDialogSchema(this,name)









    dlgStruct=this.dlgMain(name,{
    this.dlgContainer({
    this.dlgWidget('isBlock',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1])
    this.dlgWidget('isLibrary',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1])
    this.dlgWidget('isReferenceBlock',...
    'RowSpan',[3,3],...
    'ColSpan',[1,1])
    this.dlgWidget('isLinkStatus',...
    'RowSpan',[4,4],...
    'ColSpan',[1,1])
    },getString(message('RptgenSL:rsl_CLibInfo:tableColumnsLabel')),...
    'LayoutGrid',[4,1],...
    'ColStretch',[1],...
    'RowStretch',[0,0,0,0],...
    'ColSpan',[1,1],...
    'RowSpan',[1,1])
    this.dlgContainer({
    this.dlgWidget('Title',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1])
    this.dlgWidget('Sort',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1])
    this.dlgWidget('MergeRows',...
    'RowSpan',[3,3],...
    'ColSpan',[1,1])
    },getString(message('RptgenSL:rsl_CLibInfo:displayOptionsLabel')),...
    'LayoutGrid',[4,1],...
    'ColStretch',[1],...
    'RowStretch',[0,0,0,1],...
    'ColSpan',[1,1],...
    'RowSpan',[2,2])
    },'LayoutGrid',[2,1],...
    'RowStretch',[0,1],...
    'ColStretch',[1]);
