function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2CxpEa0AQVPCeFmGh0DvW4ISdpulL1ObjbpMgLtbBGyPjSPYsUOIH/Ytbv9'...
        ,'DH91MDId11q1AdtgEt92j2sq/ZxLQorLij8gfl02bHcIvL3NssocQ6QFv0o7'...
        ,'4+yAsU85IRjRxJmk/mxB7iwCzYAi2GLGNoVcyQJXleBfw0GGW3AIL2pXUYdt'...
        ,'tlMnr8yOuvEQ51rXbm5s6ESmqSGoVz7RBmxXjHZcP3kMgxnPenLz+p8SHG4w'...
        ,'d/QKwF0tgaufkeF86Cqfb9+ooxYSigkT3rFZXzKKorKel9QmM5JyaOaBRpKN'...
        ,'XeChDg=='];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end