function dlgStruct=getDialogSchema(this,name)




    dlgStruct=this.dlgMain(name,{
    this.hierGetDialogSchema(name)
    this.dlgContainer({
    this.dlgWidget('ShowJunctions')
    this.dlgWidget('ShowTransitions')
    this.dlgWidget('ShowPorts')
    this.dlgWidget('SkipAutogenerated')
    },getString(message('RptgenSL:rsf_csf_hier:childrenLabel')))
    this.list_getDialogSchema(name)
    });





