function[nLeft,isAll]=hierLeft(this,thisNode)




    if isa(thisNode,'Stateflow.Machine')
        nLeft=rptgen_sf.csf_hier.hierSibling(thisNode,slroot,true);
        isAll=true;
    elseif isa(thisNode,'Stateflow.Chart')
        nLeft=rptgen_sf.csf_hier.hierSibling(thisNode,thisNode.Machine,true);
        isAll=true;

    elseif isa(thisNode,'Stateflow.Object')

        if isa(thisNode,"handle.handle")
            nLeft=left(thisNode);
        else
            nLeft=thisNode.getPrevious;
        end
        isAll=false;

        if this.SkipAutogenerated&&...
            ~isempty(nLeft)&&...
            ~rptgen_sf.isNotAutogenerated(nLeft)
            [nLeft,isAll]=hierLeft(this,nLeft);
        end

    else
        nLeft=[];
        isAll=false;
    end

