function dlgStruct=getDialogSchema(this,name)




    fName=fullfile(this.PathName,this.FileName);

    if~exist(fName,'file')
        descMsg=sprintf(getString(message('rptgen:RptgenML_LibraryFile:cannotFindLabel')),fName);
    else
        try
            fid=fopen(fName,'r');
            descMsg=fread(fid,512,'char*1=>char')';
            fclose(fid);
        catch
            descMsg=getString(message('rptgen:RptgenML_LibraryFile:cannotReadMsg'));
        end
    end

    dlgStruct=this.dlgMain(name,{
    this.dlgContainer({
    struct('Type','pushbutton',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1],...
    'ObjectMethod','exploreAction',...
    'FilePath',fullfile(matlabroot,'toolbox','rptgen','resources','Convert.png'),...
    'Enabled',1)
    this.dlgText(getString(message('rptgen:RptgenML_LibraryFile:sendToConverterLabel')),...
    'RowSpan',[1,1],...
    'ColSpan',[2,2])
    struct('Type','pushbutton',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1],...
    'MatlabMethod','edit',...
    'MatlabArgs',{{fName}},...
    'FilePath',fullfile(matlabroot,'toolbox','rptgen','resources','open.png'),...
    'Enabled',1)
    this.dlgText(getString(message('rptgen:RptgenML_LibraryFile:editAsTextLabel')),...
    'RowSpan',[2,2],...
    'ColSpan',[2,2])
    },getString(message('rptgen:RptgenML_LibraryFile:actionsLabel')),'LayoutGrid',[2,2],'ColStretch',[0,1],'RowSpan',[1,1],'ColSpan',[1,1])
    this.dlgContainer({
    this.dlgText(descMsg,...
    'WordWrap',1)
    },getString(message('rptgen:RptgenML_LibraryFile:previewLabel')),'RowSpan',[2,2],'ColSpan',[1,1])
    },'LayoutGrid',[2,1],'RowStretch',[0,1]);

