function[mapName,relativePathToMapFile,found]=getBlockHelpMapNameAndPath(block_type)








    blks={...
    'dsphdl.BiquadFilter','dsphdlbiquad';...
    'dsphdl.Channelizer','dsphdlchannelizer';...
    'dsphdl.ChannelSynthesizer','dsphdlsynthesizer';...
    'dsphdl.CICDecimator','dsphdlcicdecimator';...
    'dsphdl.CICInterpolator','dsphdlcicinterpolator';...
    'dsphdl.ComplexToMagnitudeAngle','dsphdlmagangle';...
    'dsphdl.FarrowRateConverter','dsphdlfarrow';...
    'dsphdl.FFT','dsphdlfft';...
    'dsphdl.FIRDecimator','dsphdlfirdecimator';...
    'dsphdl.FIRFilter','dsphdlfir';...
    'dsphdl.FIRInterpolator','dsphdlfirinterpolator';...
    'dsphdl.FIRRateConverter','dsphdlfirrateconverter';...
    'dsphdl.IFFT','dsphdlifft';...
    'dsphdl.NCO','dsphdlnco';...
    'dsphdl.private.HDLFIRRateConverter','dsphdlfirrateconverterobs';...
    'dsphdl.Downsampler','dsphdldownsampler';...
    'dsphdl.Upsampler','dsphdlupsampler';...
    };

    relativePathToMapFile='/dsphdl/dsphdl.map';

    blkidx=strcmp(block_type,blks(:,1));


    found=false;
    mapName='User Defined';
    if any(blkidx)
        found=true;
        mapName=blks(blkidx,2);
    end
