function schema









    pkgSF=findpackage('rptgen_sf');
    pkgUD=findpackage('rptgen_ud');

    h=schema.class(pkgSF,'csf_count',pkgUD.findclass('cud_obj_count'));


    p=rptgen.prop(h,'SkipAutogenerated','bool',true,...
    getString(message('RptgenSL:rsf_csf_count:skipAutoGeneratedLabel')),'SIMULINK_Report_Gen');


    rptgen.makeStaticMethods(h,{
    },{
'count_getChildObjects'
'count_getObjectClass'
'count_getObjectType'
'count_getPropsrc'
'count_getRootObject'
'count_getTitle'
    });