function populateConfigureCtrlVariablesData(modelHandle,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp)





    import slvariants.internal.manager.ui.config.VMgrConstants;
    modelName=getfullname(modelHandle);
    waitBar=createWaitBar(modelName);
    if waitBar.wasCanceled
        waitBarCancelled(modelName,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp);
        return;
    end
    slvariants.internal.manager.configgen.preProcessDataFromModel(modelHandle);
    if waitBar.wasCanceled
        waitBarCancelled(modelName,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp);
        return;
    end
    ctrlVarsData=slvariants.internal.manager.configgen.getCtrlVarsData(modelHandle);
    if waitBar.wasCanceled
        waitBarCancelled(modelName,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp);
        return;
    end
    newDialogSource=slvariants.internal.manager.ui.configgen.ConfigCtrlVariablesDialogSchema(ctrlVarsData,modelName);
    autoGenConfigureCtrlVarDDGComp.updateSource(newDialogSource);
    if waitBar.wasCanceled
        waitBarCancelled(modelName,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp);
        return;
    end
    waitBar.hide();

    newDialogSource=slvariants.internal.manager.ui.configgen.GeneratedConfigsDialogSchema(ctrlVarsData,modelName);
    autoGeneratedConfigsDDGComp.updateSource(newDialogSource);
    if numel(ctrlVarsData)<1
        noCtrlVariablesFound=MException(message('Simulink:VariantManager:AutoGenConfigNoControlVariablesFound'));
        sldiagviewer.reportInfo(noCtrlVariablesFound,'Component',VMgrConstants.DiagComponentName,'Category',VMgrConstants.DiagAutoGenConfigCategory);
    end
    slvariants.internal.manager.ui.configgen.refreshToolStripActions(modelName);
end

function title=getTitleForWaitBar(modelName)
    title=message('Simulink:VariantManagerUI:FrameTitlevm').getString()+" : "+modelName;
end

function waitBar=createWaitBar(modelName)
    waitBar=DAStudio.WaitBar;
    waitBar.setWindowTitle(getTitleForWaitBar(modelName));
    waitBar.setLabelText(message('Simulink:VariantManagerUI:AutoGenConfigWaitBarLabelText').getString());
    waitBar.setCircularProgressBar(true);
    waitBar.show();
end

function waitBarCancelled(modelName,autoGenConfigureCtrlVarDDGComp,autoGeneratedConfigsDDGComp)
    import slvariants.internal.manager.ui.config.VMgrConstants;

    newDialogSource=slvariants.internal.manager.ui.configgen.ConfigCtrlVariablesDialogSchema({},modelName);
    autoGenConfigureCtrlVarDDGComp.updateSource(newDialogSource);
    newDialogSource=slvariants.internal.manager.ui.configgen.GeneratedConfigsDialogSchema({},modelName);
    autoGeneratedConfigsDDGComp.updateSource(newDialogSource);
    slvariants.internal.manager.ui.configgen.refreshToolStripActions(modelName);
    info=getString(message('Simulink:VariantManagerUI:AutoGenConfigPopulateCtrlVarsCancelled'));
    sldiagviewer.reportInfo(info,'Component',VMgrConstants.DiagComponentName,'Category',VMgrConstants.DiagAutoGenConfigCategory);
end
