function paramsStruct=getBlkParametersAndCallbacks(blkHdl,autoComplete)






    prm=get_param(blkHdl,'ObjectParameters');
    parameters=fieldnames(prm);



    paramsStruct.anno='';


    paramsStruct.cbk.fcns='';
    paramsStruct.cbk.temp='';
    paramsStruct.cbk.cbData={};


    cbkExcludeList={'ErrorFcn','lpcCoeffOutFcn','ClickFcn','PressFcn'};


    if(license('test','Simulink_Control_Design')&&...
        strcmp(get_param(blkHdl,'BlockType'),'SubSystem'))
        parameters{end+1}='SCDConfigFcn';
    end

    for i=1:length(parameters)

        if length(parameters{i})>3&&...
            ~isempty(strfind(parameters{i}(end-2:end),'Fcn'))&&...
            ~any(strcmp(parameters{i},cbkExcludeList))
            if~isempty(get_param(blkHdl,parameters{i}))
                paramsStruct.cbk.fcns=[paramsStruct.cbk.fcns;{[parameters{i},'*']}];
            else
                paramsStruct.cbk.fcns=[paramsStruct.cbk.fcns;{[parameters{i}]}];
            end
            paramsStruct.cbk.temp=[paramsStruct.cbk.temp;{[parameters{i}]}];
            paramsStruct.cbk.cbData=[paramsStruct.cbk.cbData;{get_param(blkHdl,parameters{i})}];
        else



            if(length(parameters{i})>4&&...
                ((strcmp(parameters{i}(1:4),'Mask')&&...
                ~strcmp(parameters{i},'MaskType'))||...
                (strcmp(parameters{i}(1:4),'Port')&&...
                ~strcmp(parameters{i},'PortDimensions'))||...
                strcmp(parameters{i}(1:4),'Font'))...
                )||...
                (length(parameters{i})>3&&strcmp(parameters{i}(1:3),'RTW'))||...
                (length(parameters{i})>7&&strcmp(parameters{i}(1:7),'ExtMode'))||...
                (length(parameters{i})>5&&strcmp(parameters{i}(1:5),'Paper'))||...
                (length(parameters{i})>7&&strcmp(parameters{i}(1:7),'Current'))||...
                (length(parameters{i})>12&&...
                strcmp(parameters{i}(1:12),'CompiledPort'))||...
                (length(parameters{i})>12&&...
                strcmp(parameters{i}(1:12),'ModelBrowser')...
                )||...
                strcmp(parameters{i},'Position')||...
                strcmp(parameters{i},'AttributesFormatString')||...
                strcmp(parameters{i},'UserData')||...
                strcmp(parameters{i},'DialogParameters')||...
                strcmp(parameters{i},'CompiledSampleTime')||...
                strcmp(parameters{i},'Blocks')||...
                strcmp(parameters{i},'Lines')||...
                strcmp(parameters{i},'ModelParamTableInfo')||...
                strcmp(parameters{i},'Location')||...
                strcmp(parameters{i},'Open')||...
                strcmp(parameters{i},'ReferencedWSVars')||...
                strcmp(parameters{i},'ScrollbarOffset')||...
                strcmp(parameters{i},'ScreenColor')||...
                strcmp(parameters{i},'ZoomFactor')||...
                strcmp(parameters{i},'ReportName')||...
                strcmp(parameters{i},'InputSignalNames')||...
                strcmp(parameters{i},'OutputSignalNames')||...
                strcmp(parameters{i},'Selected')


                continue;
            else
                if autoComplete
                    prefix='<';
                else
                    prefix='%<';
                end
                paramsStruct.anno=cat(2,paramsStruct.anno,{[prefix,parameters{i},'>']});
            end
        end
    end


    [paramsStruct.cbk.temp,idx]=sort(paramsStruct.cbk.temp);
    paramsStruct.cbk.fcns=paramsStruct.cbk.fcns(idx);
    paramsStruct.cbk.cbData=paramsStruct.cbk.cbData(idx);


    paramsStruct.anno=sort(paramsStruct.anno);


    if slfeature('PreStartCallback')<1
        idx=strcmp(paramsStruct.cbk.fcns,'PreStartFcn')|strcmp(paramsStruct.cbk.fcns,'PreStartFcn*');
        paramsStruct.cbk.fcns(idx)=[];
        paramsStruct.cbk.cbData(idx)=[];
        paramsStruct.cbk.temp(idx)=[];
    end
end
