function dlgStruct=getDialogSchema(this,name)




    descPanelContent{1}=this.dlgText(...
    getString(message('rptgen:RptgenML_DB2DOMTemplateBrowser:browserDescription')),...
    'WordWrap',true,...
    'RowSpan',[1,1],...
    'ColSpan',[1,2]);


    dlgStruct=this.dlgMain(name,{
    this.dlgContainer(descPanelContent,...
    getString(message('rptgen:RptgenML_DB2DOMTemplateBrowser:gettingStartedLabel')),...
    'RowSpan',[1,1],...
    'ColSpan',[1,1],...
    'LayoutGrid',[2,2],...
    'ColStretch',[0,1])
    RptgenML.dlgChildContainer(this,'',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1]),...
    },'DialogTitle',getString(message('rptgen:RptgenML_DB2DOMTemplateBrowser:templateBrowserLabel')));


