



function emitBodyStart(this,codeWriter)

    bodyTxt={...
    '',...
    '% Verify the Simulink version',...
    'verify_simulink_version();',...
    '',...
    '% Get the current directory',...
    'currDir = pwd;',...
    '',...
    '% Get the MATLAB search path, remove the toolbox sub-directories except LCT demos',...
    'matlabPath = legacycode.lct.util.getSearchPath();',...
    '',...
    '% Declare cell arrays for storing the paths',...
    'allIncPaths = {};',...
'allSrcPaths = {};'...
    };

    cellfun(@(aLine)codeWriter.wLine(aLine),bodyTxt);

    if this.EmittingObjsIsSingleCPPMexFile
        codeWriter.wLine('allSrcs = {};');
    end


    bodyTxt={...
    '',...
    '% Get the build type',...
'isSimTarget = is_simulation_target();'...
    };

    cellfun(@(aLine)codeWriter.wLine(aLine),bodyTxt);


    if this.EmittingObjsHasLibs
        codeWriter.wLine('allLibs = {};');
    end


    bodyTxt={...
    '% Get the serialized paths information',...
    'info = get_serialized_info();',...
    '',...
    };

    cellfun(@(aLine)codeWriter.wLine(aLine),bodyTxt);


