



function emitHelpers(~,codeWriter)

    bodyTxt={...
    '%% ------------------------------------------------------------------------',...
    'function verify_simulink_version()',...
    '',...
    '% Retrieve Simulink version',...
    'slVerStruct = ver(''simulink'');',...
    'slVer = str2double(strsplit(slVerStruct.Version,''.''));',...
    '% Verify that the actual platform supports the function used',...
    'if slVer(1)<8 || (slVer(1)==8 && slVer(2)<7)',...
    '    DAStudio.error(''Simulink:tools:LCTErrorBadSimulinkVersion'', slVerStruct.Version)',...
    'end',...
    '',...
    '%% ------------------------------------------------------------------------',...
    'function pathSet = correct_path_name(pathSet)',...
    '',...
    'for ii = 1:numel(pathSet)',...
    '    pathSet{ii} = coder.make.internal.transformPaths(pathSet{ii});',...
    'end',...
    'pathSet = RTW.uniquePath(pathSet);',...
''...
    };

    cellfun(@(aLine)codeWriter.wLine(aLine),bodyTxt);

    bodyTxt={...
    '%% ------------------------------------------------------------------------',...
    'function isSimTarget = is_simulation_target()',...
    '',...
    '% Default output value',...
    'isSimTarget = 0;',...
    '',...
    '% Get the current model and the code generation type to decide',...
    '% if we must link with the host libraries or with the target libraries',...
    'try',...
    '    modelName = get_param(0, ''CurrentSystem'');',...
    '    if ~isempty(modelName)',...
    '        modelName = bdroot(modelName);',...
    '        sysTarget = get_param(modelName, ''RTWSystemTargetFile'');',...
    '        isSimTarget = ~isempty([strfind(sysTarget, ''rtwsfcn'') strfind(sysTarget, ''accel'')]);',...
    '',...
    '        mdlRefSimTarget = get_param(modelName,''ModelReferenceTargetType'');',...
    '        isSimTarget = strcmpi(mdlRefSimTarget, ''SIM'') || isSimTarget;',...
    '',...
    '        % Verify again it''s not Accelerator',...
    '        if ~isSimTarget',...
    '            simMode = get_param(modelName, ''SimulationMode'');',...
    '            simStat = get_param(modelName, ''SimulationStatus'');',...
    '            isSimTarget = strcmp(simStat, ''initializing'') & strcmp(simMode, ''accelerator'');',...
    '        end',...
    '    end',...
    'catch',...
'end'...
    };
    cellfun(@(aLine)codeWriter.wLine(aLine),bodyTxt);


