function[serializedStruct,colIdx]=serialize_multicolumn_timetable_bus(...
    this,...
    interpolation,...
    values,...
    colIdx,...
    aobHierarchy,...
    nodeIdx,...
    block,...
    inputPath,...
    dataPath,...
portBusType...
    )




    aobDimensions=aobHierarchy(nodeIdx).Dimensions;
    dim=[numel(aobHierarchy(nodeIdx).Children),aobDimensions];
    emptyData=cell(dim);
    fields=cell(numel(aobHierarchy(nodeIdx).Children),1);
    fIdx=1;
    for chIdx=aobHierarchy(nodeIdx).Children
        fields{fIdx}=aobHierarchy(chIdx).Name;
        fIdx=fIdx+1;
    end
    serializedStruct=cell2struct(emptyData,fields,1);
    for idxAob=1:prod(aobHierarchy(nodeIdx).Dimensions)
        fieldIdx=1;
        for childIdx=aobHierarchy(nodeIdx).Children
            isSubBus=~isempty(aobHierarchy(childIdx).Children);
            if isSubBus
                [serializedStruct(idxAob).(fields{fieldIdx}),colIdx]=...
                this.serialize_multicolumn_timetable_bus(...
                interpolation,...
                values,...
                colIdx,...
                aobHierarchy,...
                childIdx,...
                block,...
                inputPath,...
                dataPath,...
portBusType...
                );
            else
                if colIdx>size(values,2)
                    this.throwError(...
                    false,...
                    'Simulink:SimInput:LoadingMultiColumnTimetableLeafMismatch',...
                    dataPath,...
block...
                    );
                end
                dataPathChild=[dataPath,'{',num2str(colIdx),'}'];
                serializedStruct(idxAob).(fields{fieldIdx})=...
                this.serialize_element(...
                interpolation,...
                values(:,colIdx),...
                aobHierarchy,...
                childIdx,...
                block,...
                inputPath,...
                dataPathChild,...
                false,...
portBusType...
                );
                colIdx=colIdx+1;
            end
            fieldIdx=fieldIdx+1;
        end
    end
end
