function hTopN=getHalfGainPow2Comp(hN,latency,slRate)
    p=pir(hN.getCtxName);
    denormal=transformnfp.handleDenormal();
    hTopN=addNetworks(p,denormal);

    pipestage=zeros(1,4);
    if~denormal
        switch latency
        case 0
            pipestage=zeros(1,4);
        case 1
            pipestage(4)=1;
        case 2
            pipestage=[1,0,0,1];
        otherwise
            assert(false,'Illegal latency number in nfp_gain_comp.');
        end
    else
        switch latency
        case 0
            pipestage=zeros(1,4);
        case 1
            pipestage(3)=1;
        case 2
            pipestage=[0,0,1,1];
        case 3
            pipestage=[1,0,1,1];
        case 4
            pipestage=[1,1,1,1];
        otherwise
            assert(false,'Illegal latency number in nfp_gain_comp.');
        end
    end
    createNetworks(p,denormal,pipestage,slRate);
end

function hTopN=addNetworks(p,denormal)
    hN=p.addNetwork;
    hN.Name='GainPow2_Half';
    hN.FullPath='Half_GainPow2_HDL_model/GainPow2_Half';
    hTopN=hN;
    hN=p.addNetwork;
    hN.Name='GainPow2_Main';
    hN.FullPath='Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main';

    if(denormal)
        hN=p.addNetwork;
        hN.Name='GainPow2_Main_Denormals';
        hN.FullPath='Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals';
        hN=p.addNetwork;
        hN.Name='Rounding_Denormals';
        hN.FullPath='Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals/Rounding_Denormals';
    else
        hN=p.addNetwork;
        hN.Name='GainPow2_Main_Normals';
        hN.FullPath='Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Normals';
    end
end

function createNetworks(p,denormal,pipestage,slRate)
    if(denormal)
        hN_n8=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals/Rounding_Denormals');
        createNetwork_n8(p,hN_n8,pipestage,slRate);
        hN_n2=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals');
        createNetwork_n2(p,hN_n2,pipestage,slRate);
    else
        hN_n3=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Normals');
        createNetwork_n3(p,hN_n3,pipestage,slRate);
    end
    hN_n1=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main');
    createNetwork_n1(p,hN_n1,denormal,slRate);
    hN_n0=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half');
    createNetwork_n0(p,hN_n0,slRate);
end

function hN=createNetwork_n3(~,hN,pipestage,slRate)
    pirTyp5=pir_boolean_t;
    pirTyp3=pir_sfixpt_t(6,0);
    pirTyp6=pir_sfixpt_t(7,0);
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp4=pir_ufixpt_t(10,0);
    pirTyp8=pir_ufixpt_t(2,0);
    pirTyp9=pir_ufixpt_t(4,0);
    pirTyp2=pir_ufixpt_t(5,0);
    pirTyp7=pir_ufixpt_t(7,0);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt4=numerictype(0,1,0);
    nt2=numerictype(0,10,0);
    nt1=numerictype(0,2,0);
    nt3=numerictype(0,5,0);
    nt5=numerictype(1,6,0);



    hN.addInputPort('In1');
    In1_s0=addSignal(hN,'In1',pirTyp1,slRate);
    In1_s0.addDriver(hN,0);

    hN.addInputPort('In2');
    In2_s1=addSignal(hN,'In2',pirTyp1,slRate);
    In2_s1.addDriver(hN,1);

    hN.addInputPort('In3');
    In3_s2=addSignal(hN,'In3',pirTyp2,slRate);
    In3_s2.addDriver(hN,2);

    hN.addInputPort('In4');
    In4_s3=addSignal(hN,'In4',pirTyp3,slRate);
    In4_s3.addDriver(hN,3);

    hN.addInputPort('In5');
    In5_s4=addSignal(hN,'In5',pirTyp4,slRate);
    In5_s4.addDriver(hN,4);

    hN.addOutputPort('Out1');
    Delay3_PS_4_out1_s22=addSignal(hN,'Delay3_PS_4_out1',pirTyp5,slRate);
    Delay3_PS_4_out1_s22.addReceiver(hN,0);

    hN.addOutputPort('Out2');
    Delay6_PS_5_out1_s25=addSignal(hN,'Delay6_PS_5_out1',pirTyp2,slRate);
    Delay6_PS_5_out1_s25.addReceiver(hN,1);

    hN.addOutputPort('Out3');
    Delay7_PS_4_out1_s26=addSignal(hN,'Delay7_PS_4_out1',pirTyp4,slRate);
    Delay7_PS_4_out1_s26.addReceiver(hN,2);

    Add_out1_s5=addSignal(hN,'Add_out1',pirTyp6,slRate);
    BitConcat_out1_s6=addSignal(hN,'Bit Concat_out1',pirTyp7,slRate);
    BitConcat1_out1_s7=addSignal(hN,'Bit Concat1_out1',pirTyp7,slRate);
    BitReduce_out1_s8=addSignal(hN,'Bit Reduce_out1',pirTyp1,slRate);
    BitReduce1_out1_s9=addSignal(hN,'Bit Reduce1_out1',pirTyp1,slRate);
    BitReduce2_out1_s10=addSignal(hN,'Bit Reduce2_out1',pirTyp1,slRate);
    BitReduce3_out1_s11=addSignal(hN,'Bit Reduce3_out1',pirTyp1,slRate);
    BitSlice_out1_s12=addSignal(hN,'Bit Slice_out1',pirTyp1,slRate);
    BitSlice1_out1_s13=addSignal(hN,'Bit Slice1_out1',pirTyp2,slRate);
    BitSlice2_out1_s14=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    BitSlice3_out1_s15=addSignal(hN,'Bit Slice3_out1',pirTyp1,slRate);
    Constant_out1_s16=addSignal(hN,'Constant_out1',pirTyp8,slRate);
    Constant1_out1_s17=addSignal(hN,'Constant1_out1',pirTyp4,slRate);
    DataTypeConversion_out1_s18=addSignal(hN,'Data Type Conversion_out1',pirTyp6,slRate);
    DataTypeConversion1_out1_s19=addSignal(hN,'Data Type Conversion1_out1',pirTyp6,slRate);
    Delay1_PS_1_out1_s20=addSignal(hN,'Delay1_PS_1_out1',pirTyp2,slRate);
    Delay2_PS_1_out1_s21=addSignal(hN,'Delay2_PS_1_out1',pirTyp1,slRate);
    Delay4_PS_1_out1_s23=addSignal(hN,'Delay4_PS_1_out1',pirTyp3,slRate);
    Delay5_PS_1_out1_s24=addSignal(hN,'Delay5_PS_1_out1',pirTyp1,slRate);
    Delay_PS_1_out1_s27=addSignal(hN,'Delay_PS_1_out1',pirTyp4,slRate);
    y_s28=addSignal(hN,'y',pirTyp2,slRate);
    LogicalOperator_out1_s29=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp5,slRate);
    LogicalOperator1_out1_s30=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s31=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s32=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    LogicalOperator4_out1_s33=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    LogicalOperator5_out1_s34=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp5,slRate);
    LogicalOperator6_out1_s35=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp5,slRate);
    LogicalOperator7_out1_s36=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp5,slRate);
    LogicalOperator8_out1_s37=addSignal(hN,sprintf('Logical\nOperator8_out1'),pirTyp5,slRate);
    Switch_out1_s38=addSignal(hN,'Switch_out1',pirTyp4,slRate);
    Switch1_out1_s39=addSignal(hN,'Switch1_out1',pirTyp2,slRate);
    BitConcat2_out1_s41=addSignal(hN,'Bit Concat2_out1',pirTyp2,slRate);
    BitConcat4_out1_s42=addSignal(hN,'Bit Concat4_out1',pirTyp8,slRate);
    BitConcat5_out1_s43=addSignal(hN,'Bit Concat5_out1',pirTyp9,slRate);


    pirelab.getConstComp(hN,...
    Constant_out1_s16,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant1_out1_s17,...
    fi(0,nt2,fiMath1,'hex','000'),...
    'Constant1','on',1,'','','');


    pirelab.getIntDelayComp(hN,...
    In3_s2,...
    Delay1_PS_1_out1_s20,...
    pipestage(1),'Delay1_PS_1',...
    fi(0,nt3,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In1_s0,...
    Delay2_PS_1_out1_s21,...
    pipestage(1),'Delay2_PS_1',...
    fi(0,nt4,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    LogicalOperator1_out1_s30,...
    Delay3_PS_4_out1_s22,...
    pipestage(4),'Delay3_PS_4',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In4_s3,...
    Delay4_PS_1_out1_s23,...
    pipestage(1),'Delay4_PS_1',...
    fi(0,nt5,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In2_s1,...
    Delay5_PS_1_out1_s24,...
    pipestage(1),'Delay5_PS_1',...
    fi(0,nt4,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Switch1_out1_s39,...
    Delay6_PS_5_out1_s25,...
    pipestage(4),'Delay6_PS_5',...
    fi(0,nt3,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Switch_out1_s38,...
    Delay7_PS_4_out1_s26,...
    pipestage(4),'Delay7_PS_4',...
    fi(0,nt2,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In5_s4,...
    Delay_PS_1_out1_s27,...
    pipestage(1),'Delay_PS_1',...
    fi(0,nt2,fiMath1,'hex','000'),...
    0,0,[],0,0);

    pirelab.getWireComp(hN,...
    BitConcat2_out1_s41,...
    y_s28,...
    'y');


    pirelab.getAddComp(hN,...
    [DataTypeConversion_out1_s18,DataTypeConversion1_out1_s19],...
    Add_out1_s5,...
    'Floor','Wrap','Add',pirTyp6,'++');


    pirelab.getBitConcatComp(hN,...
    [Constant_out1_s16,Delay1_PS_1_out1_s20],...
    BitConcat_out1_s6,...
    'Bit Concat');


    pirelab.getBitConcatComp(hN,...
    [BitSlice_out1_s12,Delay4_PS_1_out1_s23],...
    BitConcat1_out1_s7,...
    'Bit Concat1');


    pirelab.getBitReduceComp(hN,...
    Delay1_PS_1_out1_s20,...
    BitReduce_out1_s8,...
    'AND','Bit Reduce');


    pirelab.getBitReduceComp(hN,...
    Delay1_PS_1_out1_s20,...
    BitReduce1_out1_s9,...
    'OR','Bit Reduce1');


    pirelab.getBitReduceComp(hN,...
    BitSlice1_out1_s13,...
    BitReduce2_out1_s10,...
    'AND','Bit Reduce2');


    pirelab.getBitReduceComp(hN,...
    BitSlice1_out1_s13,...
    BitReduce3_out1_s11,...
    'OR','Bit Reduce3');


    pirelab.getBitSliceComp(hN,...
    Delay4_PS_1_out1_s23,...
    BitSlice_out1_s12,...
    5,5,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    Add_out1_s5,...
    BitSlice1_out1_s13,...
    4,0,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    Add_out1_s5,...
    BitSlice2_out1_s14,...
    5,5,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    Add_out1_s5,...
    BitSlice3_out1_s15,...
    6,6,'Bit Slice3');


    pirelab.getDTCComp(hN,...
    BitConcat_out1_s6,...
    DataTypeConversion_out1_s18,...
    'Floor','Wrap','SI','Data Type Conversion');


    pirelab.getDTCComp(hN,...
    BitConcat1_out1_s7,...
    DataTypeConversion1_out1_s19,...
    'Floor','Wrap','SI','Data Type Conversion1');


    pirelab.getBitConcatComp(hN,...
    [BitConcat5_out1_s43,LogicalOperator5_out1_s34],...
    BitConcat2_out1_s41,...
    'Bit Concat2');


    pirelab.getBitConcatComp(hN,...
    [LogicalOperator5_out1_s34,LogicalOperator5_out1_s34],...
    BitConcat4_out1_s42,...
    'Bit Concat4');


    pirelab.getBitConcatComp(hN,...
    [BitConcat4_out1_s42,BitConcat4_out1_s42],...
    BitConcat5_out1_s43,...
    'Bit Concat5');


    pirelab.getLogicComp(hN,...
    [BitReduce_out1_s8,LogicalOperator6_out1_s35,BitSlice3_out1_s15,BitSlice2_out1_s14],...
    LogicalOperator_out1_s29,...
    'or',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hN,...
    [Delay2_PS_1_out1_s21,Delay5_PS_1_out1_s24],...
    LogicalOperator1_out1_s30,...
    'xor',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitSlice3_out1_s15,BitSlice2_out1_s14,BitReduce2_out1_s10,LogicalOperator6_out1_s35,LogicalOperator8_out1_s37],...
    LogicalOperator2_out1_s31,...
    'nor',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitReduce_out1_s8,LogicalOperator2_out1_s31],...
    LogicalOperator3_out1_s32,...
    'or',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(hN,...
    BitSlice3_out1_s15,...
    LogicalOperator4_out1_s33,...
    'not',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [BitReduce_out1_s8,LogicalOperator7_out1_s36],...
    LogicalOperator5_out1_s34,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    BitReduce1_out1_s9,...
    LogicalOperator6_out1_s35,...
    'not',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitReduce1_out1_s9,LogicalOperator4_out1_s33],...
    LogicalOperator7_out1_s36,...
    'and',sprintf('Logical\nOperator7'));


    pirelab.getLogicComp(hN,...
    BitReduce3_out1_s11,...
    LogicalOperator8_out1_s37,...
    'not',sprintf('Logical\nOperator8'));


    pirelab.getSwitchComp(hN,...
    [Delay_PS_1_out1_s27,Constant1_out1_s17],...
    Switch_out1_s38,...
    LogicalOperator3_out1_s32,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [y_s28,BitSlice1_out1_s13],...
    Switch1_out1_s39,...
    LogicalOperator_out1_s29,'Switch1',...
    '~=',0,'Floor','Wrap');


end

function hN=createNetwork_n8(~,hN,pipestage,slRate)
    pirTyp3=pir_boolean_t;
    pirTyp5=pir_ufixpt_t(1,0);
    pirTyp4=pir_ufixpt_t(10,0);
    pirTyp2=pir_ufixpt_t(11,0);
    pirTyp6=pir_ufixpt_t(4,0);
    pirTyp1=pir_ufixpt_t(5,0);
    pirTyp7=pir_ufixpt_t(9,0);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt1=numerictype(0,10,0);
    nt3=numerictype(0,4,0);
    nt2=numerictype(0,5,0);
    nt4=numerictype(0,9,0);



    hN.addInputPort('Exp');
    Exp_s0=addSignal(hN,'Exp',pirTyp1,slRate);
    Exp_s0.addDriver(hN,0);

    hN.addInputPort('MantExtended');
    MantExtended_s1=addSignal(hN,'MantExtended',pirTyp2,slRate);
    MantExtended_s1.addDriver(hN,1);

    hN.addInputPort('sticky');
    sticky_s2=addSignal(hN,'sticky',pirTyp3,slRate);
    sticky_s2.addDriver(hN,2);

    hN.addOutputPort('Exp1');
    Exp_Cast_1_Like_Exp__out1_s14=addSignal(hN,'Exp + cast(1, like, Exp)_out1',pirTyp1,slRate);
    Exp_Cast_1_Like_Exp__out1_s14.addReceiver(hN,0);

    hN.addOutputPort('MantRounded');
    Mant_tmp_Cast_2_Like_Man____out1_s16=addSignal(hN,'Mant_tmp + cast(2, like, Man..._out1',pirTyp4,slRate);
    Mant_tmp_Cast_2_Like_Man____out1_s16.addReceiver(hN,1);

    x_bitget_Mant_tmp_1___0_______out1_s3=addSignal(hN,'(bitget(Mant_tmp, 1) ~= 0) && ..._out1',pirTyp3,slRate);
    x_bitget_Mant_tmp_1___0______1_out1_s4=addSignal(hN,'(bitget(Mant_tmp, 1) ~= 0) && ...1_out1',pirTyp3,slRate);
    x_bitget_Mant_tmp_2___0_______out1_s5=addSignal(hN,'(bitget(Mant_tmp, 2) ~= 0) || ..._out1',pirTyp3,slRate);
    BitConcat1_out1_s6=addSignal(hN,'Bit Concat1_out1',pirTyp4,slRate);
    BitConcat2_out1_s7=addSignal(hN,'Bit Concat2_out1',pirTyp1,slRate);
    BitReduce_out1_s8=addSignal(hN,'Bit Reduce_out1',pirTyp5,slRate);
    BitSlice4_out1_s9=addSignal(hN,'BitSlice4_out1',pirTyp4,slRate);
    Delay1_PS_4_out1_s10=addSignal(hN,'Delay1_PS_4_out1',pirTyp4,slRate);
    Delay2_PS_4_out1_s11=addSignal(hN,'Delay2_PS_4_out1',pirTyp1,slRate);
    Delay3_PS_4_out1_s12=addSignal(hN,'Delay3_PS_4_out1',pirTyp1,slRate);
    Delay_PS_4_out1_s13=addSignal(hN,'Delay_PS_4_out1',pirTyp4,slRate);
    LSB_out1_s15=addSignal(hN,'LSB_out1',pirTyp5,slRate);
    Round_out1_s17=addSignal(hN,'Round_out1',pirTyp5,slRate);
    cast_1_Like_Exp__out1_s18=addSignal(hN,'cast(1, like, Exp) _out1',pirTyp6,slRate);
    cast_2_Like_Mant_tmp__out1_s19=addSignal(hN,'cast(2, like, Mant_tmp) _out1',pirTyp7,slRate);


    pirelab.getIntDelayComp(hN,...
    BitSlice4_out1_s9,...
    Delay1_PS_4_out1_s10,...
    pipestage(4),'Delay1_PS_4',...
    fi(0,nt1,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitConcat2_out1_s7,...
    Delay2_PS_4_out1_s11,...
    pipestage(4),'Delay2_PS_4',...
    fi(0,nt2,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Exp_s0,...
    Delay3_PS_4_out1_s12,...
    pipestage(4),'Delay3_PS_4',...
    fi(0,nt2,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitConcat1_out1_s6,...
    Delay_PS_4_out1_s13,...
    pipestage(4),'Delay_PS_4',...
    fi(0,nt1,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getConstComp(hN,...
    cast_1_Like_Exp__out1_s18,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'cast(1, like, Exp) ','on',1,'','','');


    pirelab.getConstComp(hN,...
    cast_2_Like_Mant_tmp__out1_s19,...
    fi(0,nt4,fiMath1,'hex','000'),...
    'cast(2, like, Mant_tmp) ','on',1,'','','');


    pirelab.getLogicComp(hN,...
    [Round_out1_s17,x_bitget_Mant_tmp_2___0_______out1_s5],...
    x_bitget_Mant_tmp_1___0_______out1_s3,...
    'and','(bitget(Mant_tmp, 1) ~= 0) && ...');


    pirelab.getLogicComp(hN,...
    [BitReduce_out1_s8,x_bitget_Mant_tmp_1___0_______out1_s3],...
    x_bitget_Mant_tmp_1___0______1_out1_s4,...
    'and','(bitget(Mant_tmp, 1) ~= 0) && ...1');


    pirelab.getLogicComp(hN,...
    [LSB_out1_s15,sticky_s2],...
    x_bitget_Mant_tmp_2___0_______out1_s5,...
    'or','(bitget(Mant_tmp, 2) ~= 0) || ...');


    pirelab.getBitConcatComp(hN,...
    [cast_2_Like_Mant_tmp__out1_s19,x_bitget_Mant_tmp_1___0_______out1_s3],...
    BitConcat1_out1_s6,...
    'Bit Concat1');


    pirelab.getBitConcatComp(hN,...
    [cast_1_Like_Exp__out1_s18,x_bitget_Mant_tmp_1___0______1_out1_s4],...
    BitConcat2_out1_s7,...
    'Bit Concat2');


    pirelab.getBitReduceComp(hN,...
    BitSlice4_out1_s9,...
    BitReduce_out1_s8,...
    'AND','Bit Reduce');


    pirelab.getBitSliceComp(hN,...
    MantExtended_s1,...
    BitSlice4_out1_s9,...
    10,1,'BitSlice4');


    pirelab.getAddComp(hN,...
    [Delay3_PS_4_out1_s12,Delay2_PS_4_out1_s11],...
    Exp_Cast_1_Like_Exp__out1_s14,...
    'Floor','Wrap','Exp + cast(1, like, Exp)',pirTyp1,'++');


    pirelab.getBitSliceComp(hN,...
    MantExtended_s1,...
    LSB_out1_s15,...
    1,1,'LSB');


    pirelab.getAddComp(hN,...
    [Delay1_PS_4_out1_s10,Delay_PS_4_out1_s13],...
    Mant_tmp_Cast_2_Like_Man____out1_s16,...
    'Floor','Wrap','Mant_tmp + cast(2, like, Man...',pirTyp4,'++');


    pirelab.getBitSliceComp(hN,...
    MantExtended_s1,...
    Round_out1_s17,...
    0,0,'Round');


end

function hN=createNetwork_n2(p,hN,pipestage,slRate)
    pirTyp5=pir_boolean_t;
    pirTyp3=pir_sfixpt_t(6,0);
    pirTyp6=pir_sfixpt_t(7,0);
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp4=pir_ufixpt_t(10,0);
    pirTyp8=pir_ufixpt_t(11,0);
    pirTyp10=pir_ufixpt_t(12,0);
    pirTyp12=pir_ufixpt_t(2,0);
    pirTyp13=pir_ufixpt_t(3,0);
    pirTyp7=pir_ufixpt_t(4,0);
    pirTyp2=pir_ufixpt_t(5,0);
    pirTyp11=pir_ufixpt_t(6,0);
    pirTyp9=pir_ufixpt_t(7,0);
    pirTyp14=pir_unsigned_t(8);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt2=numerictype(0,1,0);
    nt7=numerictype(0,10,0);
    nt6=numerictype(0,11,0);
    nt8=numerictype(0,12,0);
    nt3=numerictype(0,2,0);
    nt5=numerictype(0,3,0);
    nt1=numerictype(0,4,0);
    nt9=numerictype(0,5,0);
    nt10=numerictype(1,6,0);
    nt4=numerictype(1,7,0);




    hN.addInputPort('In1');
    In1_s0=addSignal(hN,'In1',pirTyp1,slRate);
    In1_s0.addDriver(hN,0);

    hN.addInputPort('In2');
    In2_s1=addSignal(hN,'In2',pirTyp1,slRate);
    In2_s1.addDriver(hN,1);

    hN.addInputPort('In3');
    In3_s2=addSignal(hN,'In3',pirTyp2,slRate);
    In3_s2.addDriver(hN,2);

    hN.addInputPort('In4');
    In4_s3=addSignal(hN,'In4',pirTyp3,slRate);
    In4_s3.addDriver(hN,3);

    hN.addInputPort('In5');
    In5_s4=addSignal(hN,'In5',pirTyp4,slRate);
    In5_s4.addDriver(hN,4);

    hN.addOutputPort('Out1');
    Delay19_PS_4_out1_s48=addSignal(hN,'Delay19_PS_4_out1',pirTyp5,slRate);
    Delay19_PS_4_out1_s48.addReceiver(hN,0);

    hN.addOutputPort('Out2');
    Rounding_Denormals_out1_s68=addSignal(hN,'Rounding_Denormals_out1',pirTyp2,slRate);
    Rounding_Denormals_out1_s68.addReceiver(hN,1);

    hN.addOutputPort('Out3');
    Rounding_Denormals_out2_s69=addSignal(hN,'Rounding_Denormals_out2',pirTyp4,slRate);
    Rounding_Denormals_out2_s69.addReceiver(hN,2);

    Add_out1_s5=addSignal(hN,'Add_out1',pirTyp6,slRate);
    Add1_out1_s6=addSignal(hN,'Add1_out1',pirTyp6,slRate);
    Add2_out1_s7=addSignal(hN,'Add2_out1',pirTyp6,slRate);
    Add3_out1_s8=addSignal(hN,'Add3_out1',pirTyp7,slRate);
    BitConcat_out1_s9=addSignal(hN,'Bit Concat_out1',pirTyp8,slRate);
    BitConcat1_out1_s10=addSignal(hN,'Bit Concat1_out1',pirTyp9,slRate);
    BitConcat2_out1_s11=addSignal(hN,'Bit Concat2_out1',pirTyp9,slRate);
    BitConcat3_out1_s12=addSignal(hN,'Bit Concat3_out1',pirTyp9,slRate);
    BitConcat4_out1_s13=addSignal(hN,'Bit Concat4_out1',pirTyp10,slRate);
    BitConcat5_out1_s14=addSignal(hN,'Bit Concat5_out1',pirTyp11,slRate);
    BitConcat6_out1_s15=addSignal(hN,'Bit Concat6_out1',pirTyp8,slRate);
    BitReduce_out1_s16=addSignal(hN,'Bit Reduce_out1',pirTyp1,slRate);
    BitReduce1_out1_s17=addSignal(hN,'Bit Reduce1_out1',pirTyp1,slRate);
    BitReduce2_out1_s18=addSignal(hN,'Bit Reduce2_out1',pirTyp1,slRate);
    BitSlice_out1_s19=addSignal(hN,'Bit Slice_out1',pirTyp1,slRate);
    BitSlice1_out1_s20=addSignal(hN,'Bit Slice1_out1',pirTyp8,slRate);
    BitSlice2_out1_s21=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    BitSlice3_out1_s22=addSignal(hN,'Bit Slice3_out1',pirTyp2,slRate);
    BitSlice4_out1_s23=addSignal(hN,'Bit Slice4_out1',pirTyp4,slRate);
    BitwiseOperator_out1_s24=addSignal(hN,sprintf('Bitwise\nOperator_out1'),pirTyp2,slRate);
    CompareToConstant_out1_s25=addSignal(hN,sprintf('Compare\nTo Constant_out1'),pirTyp5,slRate);
    Constant_out1_s26=addSignal(hN,'Constant_out1',pirTyp12,slRate);
    Constant1_out1_s27=addSignal(hN,'Constant1_out1',pirTyp6,slRate);
    Constant2_out1_s28=addSignal(hN,'Constant2_out1',pirTyp13,slRate);
    Constant3_out1_s29=addSignal(hN,'Constant3_out1',pirTyp7,slRate);
    Constant4_out1_s30=addSignal(hN,'Constant4_out1',pirTyp1,slRate);
    Constant5_out1_s31=addSignal(hN,'Constant5_out1',pirTyp12,slRate);
    Constant6_out1_s32=addSignal(hN,'Constant6_out1',pirTyp7,slRate);
    Constant7_out1_s33=addSignal(hN,'Constant7_out1',pirTyp8,slRate);
    Constant8_out1_s34=addSignal(hN,'Constant8_out1',pirTyp1,slRate);
    DataTypeConversion_out1_s35=addSignal(hN,'Data Type Conversion_out1',pirTyp6,slRate);
    DataTypeConversion1_out1_s36=addSignal(hN,'Data Type Conversion1_out1',pirTyp6,slRate);
    DataTypeConversion2_out1_s37=addSignal(hN,'Data Type Conversion2_out1',pirTyp6,slRate);
    DataTypeConversion3_out1_s38=addSignal(hN,'Data Type Conversion3_out1',pirTyp6,slRate);
    Delay10_PS_3_out1_s39=addSignal(hN,'Delay10_PS_3_out1',pirTyp5,slRate);
    Delay11_PS_3_out1_s40=addSignal(hN,'Delay11_PS_3_out1',pirTyp1,slRate);
    Delay12_PS_3_out1_s41=addSignal(hN,'Delay12_PS_3_out1',pirTyp5,slRate);
    Delay13_PS_2_out1_s42=addSignal(hN,'Delay13_PS_2_out1',pirTyp8,slRate);
    Delay14_PS_2_out1_s43=addSignal(hN,'Delay14_PS_2_out1',pirTyp7,slRate);
    Delay15_PS_2_out1_s44=addSignal(hN,'Delay15_PS_2_out1',pirTyp5,slRate);
    Delay16_PS_2_out1_s45=addSignal(hN,'Delay16_PS_2_out1',pirTyp1,slRate);
    Delay17_PS_2_out1_s46=addSignal(hN,'Delay17_PS_2_out1',pirTyp5,slRate);
    Delay18_PS_2_out1_s47=addSignal(hN,'Delay18_PS_2_out1',pirTyp6,slRate);
    Delay1_PS_1_out1_s49=addSignal(hN,'Delay1_PS_1_out1',pirTyp1,slRate);
    Delay23_PS_2_out1_s50=addSignal(hN,'Delay23_PS_2_out1',pirTyp7,slRate);
    Delay24_PS_1_out1_s51=addSignal(hN,'Delay24_PS_1_out1',pirTyp4,slRate);
    Delay25_PS_3_out1_s52=addSignal(hN,'Delay25_PS_3_out1',pirTyp8,slRate);
    Delay2_PS_1_out1_s53=addSignal(hN,'Delay2_PS_1_out1',pirTyp1,slRate);
    Delay3_PS_3_out1_s54=addSignal(hN,'Delay3_PS_3_out1',pirTyp10,slRate);
    Delay4_PS_1_out1_s55=addSignal(hN,'Delay4_PS_1_out1',pirTyp2,slRate);
    Delay5_PS_1_out1_s56=addSignal(hN,'Delay5_PS_1_out1',pirTyp3,slRate);
    Delay6_PS_3_out1_s57=addSignal(hN,'Delay6_PS_3_out1',pirTyp7,slRate);
    Delay7_PS_2_out1_s58=addSignal(hN,'Delay7_PS_2_out1',pirTyp6,slRate);
    Delay8_PS_3_out1_s59=addSignal(hN,'Delay8_PS_3_out1',pirTyp2,slRate);
    Delay9_PS_3_out1_s60=addSignal(hN,'Delay9_PS_3_out1',pirTyp6,slRate);
    y_s61=addSignal(hN,'y',pirTyp2,slRate);
    y_s62=addSignal(hN,'y',pirTyp2,slRate);
    FindFirst_2_out1_s63=addSignal(hN,'FindFirst_2_out1',pirTyp7,slRate);
    LogicalOperator_out1_s64=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp5,slRate);
    LogicalOperator1_out1_s65=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s66=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s67=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    Saturation_out1_s70=addSignal(hN,'Saturation_out1',pirTyp7,slRate);
    ShiftArithmetic_out1_s71=addSignal(hN,sprintf('Shift\nArithmetic_out1'),pirTyp8,slRate);
    ShiftArithmetic1_out1_s72=addSignal(hN,sprintf('Shift\nArithmetic1_out1'),pirTyp10,slRate);
    Switch_out1_s73=addSignal(hN,'Switch_out1',pirTyp6,slRate);
    Switch1_out1_s74=addSignal(hN,'Switch1_out1',pirTyp2,slRate);
    Switch2_out1_s75=addSignal(hN,'Switch2_out1',pirTyp8,slRate);
    Switch3_out1_s76=addSignal(hN,'Switch3_out1',pirTyp7,slRate);
    Switch4_out1_s77=addSignal(hN,'Switch4_out1',pirTyp8,slRate);
    get_Sticky1_out1_s78=addSignal(hN,'get_Sticky1_out1',pirTyp5,slRate);
    BitConcat2_out1_s80=addSignal(hN,'Bit Concat2_out1',pirTyp2,slRate);
    BitConcat4_out1_s81=addSignal(hN,'Bit Concat4_out1',pirTyp12,slRate);
    BitConcat5_out1_s82=addSignal(hN,'Bit Concat5_out1',pirTyp7,slRate);
    BitConcat2_out1_s84=addSignal(hN,'Bit Concat2_out1',pirTyp2,slRate);
    BitConcat4_out1_s85=addSignal(hN,'Bit Concat4_out1',pirTyp12,slRate);
    BitConcat5_out1_s86=addSignal(hN,'Bit Concat5_out1',pirTyp7,slRate);
    BitSlice1_out1_s88=addSignal(hN,'Bit Slice1_out1',pirTyp12,slRate);
    BitSlice4_out1_s89=addSignal(hN,'Bit Slice4_out1',pirTyp14,slRate);
    Bottom8Bits_out1_s90=addSignal(hN,'Bottom 8 bits_out1',pirTyp7,slRate);
    Constant_out1_s91=addSignal(hN,'Constant_out1',pirTyp7,slRate);
    Middle8Bits_out1_s92=addSignal(hN,'Middle 8 bits_out1',pirTyp7,slRate);
    Middle8Bits_out2_s93=addSignal(hN,'Middle 8 bits_out2',pirTyp5,slRate);
    Switch_out1_s94=addSignal(hN,'Switch_out1',pirTyp7,slRate);
    BitSlice1_out1_s95=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate);
    BitSlice2_out1_s96=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    BitSlice3_out1_s97=addSignal(hN,'Bit Slice3_out1',pirTyp1,slRate);
    BitSlice4_out1_s98=addSignal(hN,'Bit Slice4_out1',pirTyp1,slRate);
    BitSlice5_out1_s99=addSignal(hN,'Bit Slice5_out1',pirTyp1,slRate);
    BitSlice6_out1_s100=addSignal(hN,'Bit Slice6_out1',pirTyp1,slRate);
    BitSlice7_out1_s101=addSignal(hN,'Bit Slice7_out1',pirTyp1,slRate);
    BitSlice8_out1_s102=addSignal(hN,'Bit Slice8_out1',pirTyp1,slRate);
    Constant1_out1_s103=addSignal(hN,'Constant1_out1',pirTyp7,slRate);
    Constant2_out1_s104=addSignal(hN,'Constant2_out1',pirTyp7,slRate);
    Constant3_out1_s105=addSignal(hN,'Constant3_out1',pirTyp7,slRate);
    Constant4_out1_s106=addSignal(hN,'Constant4_out1',pirTyp7,slRate);
    Constant5_out1_s107=addSignal(hN,'Constant5_out1',pirTyp7,slRate);
    Constant6_out1_s108=addSignal(hN,'Constant6_out1',pirTyp7,slRate);
    Constant7_out1_s109=addSignal(hN,'Constant7_out1',pirTyp7,slRate);
    Constant8_out1_s110=addSignal(hN,'Constant8_out1',pirTyp7,slRate);
    LogicalOperator_out1_s111=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp5,slRate);
    LogicalOperator1_out1_s112=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s113=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s114=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    Switch1_out1_s115=addSignal(hN,'Switch1_out1',pirTyp7,slRate);
    Switch10_out1_s116=addSignal(hN,'Switch10_out1',pirTyp7,slRate);
    Switch2_out1_s117=addSignal(hN,'Switch2_out1',pirTyp7,slRate);
    Switch3_out1_s118=addSignal(hN,'Switch3_out1',pirTyp7,slRate);
    Switch4_out1_s119=addSignal(hN,'Switch4_out1',pirTyp7,slRate);
    Switch6_out1_s120=addSignal(hN,'Switch6_out1',pirTyp7,slRate);
    Switch8_out1_s121=addSignal(hN,'Switch8_out1',pirTyp7,slRate);
    Switch9_out1_s122=addSignal(hN,'Switch9_out1',pirTyp7,slRate);
    BitSlice10_out1_s123=addSignal(hN,'Bit Slice10_out1',pirTyp1,slRate);
    BitSlice9_out1_s124=addSignal(hN,'Bit Slice9_out1',pirTyp1,slRate);
    Constant10_out1_s125=addSignal(hN,'Constant10_out1',pirTyp7,slRate);
    Constant9_out1_s126=addSignal(hN,'Constant9_out1',pirTyp7,slRate);
    LogicalOperator14_out1_s127=addSignal(hN,sprintf('Logical\nOperator14_out1'),pirTyp5,slRate);
    Switch12_out1_s128=addSignal(hN,'Switch12_out1',pirTyp7,slRate);
    BitConcat5_out1_s130=addSignal(hN,'Bit Concat5_out1',pirTyp7,slRate);
    BitConcat6_out1_s131=addSignal(hN,'Bit Concat6_out1',pirTyp7,slRate);
    BitReduce3_out1_s132=addSignal(hN,'Bit Reduce3_out1',pirTyp1,slRate);
    BitSlice1_out1_s133=addSignal(hN,'Bit Slice1_out1',pirTyp7,slRate);
    BitSlice2_out1_s134=addSignal(hN,'Bit Slice2_out1',pirTyp12,slRate);
    BitSlice3_out1_s135=addSignal(hN,'Bit Slice3_out1',pirTyp1,slRate);
    BitwiseOperator_out1_s136=addSignal(hN,sprintf('Bitwise\nOperator_out1'),pirTyp7,slRate);
    BitwiseOperator1_out1_s137=addSignal(hN,sprintf('Bitwise\nOperator1_out1'),pirTyp7,slRate);
    LogicalOperator4_out1_s138=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    x0_2_out1_s141=addSignal(hN,'0-2_out1',pirTyp5,slRate);
    x3_6_out1_s142=addSignal(hN,'3-6_out1',pirTyp5,slRate);
    x43_4_out1_s143=addSignal(hN,'43-4_out1',pirTyp5,slRate);
    x7_10_out1_s144=addSignal(hN,'7-10_out1',pirTyp5,slRate);
    BitReduce_out1_s145=addSignal(hN,'Bit Reduce_out1',pirTyp1,slRate);
    BitReduce1_out1_s146=addSignal(hN,'Bit Reduce1_out1',pirTyp1,slRate);
    BitReduce2_out1_s147=addSignal(hN,'Bit Reduce2_out1',pirTyp1,slRate);
    BitSlice_out1_s148=addSignal(hN,'Bit Slice_out1',pirTyp13,slRate);
    BitSlice1_out1_s149=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate);
    BitSlice10_out1_s150=addSignal(hN,'Bit Slice10_out1',pirTyp7,slRate);
    BitSlice2_out1_s151=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    BitSlice3_out1_s152=addSignal(hN,'Bit Slice3_out1',pirTyp1,slRate);
    BitSlice5_out1_s153=addSignal(hN,'Bit Slice5_out1',pirTyp1,slRate);
    BitSlice6_out1_s154=addSignal(hN,'Bit Slice6_out1',pirTyp7,slRate);
    BitSlice7_out1_s155=addSignal(hN,'Bit Slice7_out1',pirTyp13,slRate);
    BitSlice8_out1_s156=addSignal(hN,'Bit Slice8_out1',pirTyp7,slRate);
    BitSlice9_out1_s157=addSignal(hN,'Bit Slice9_out1',pirTyp13,slRate);
    LogicalOperator1_out1_s158=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s159=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    BitSlice_out1_s160=addSignal(hN,'Bit Slice_out1',pirTyp1,slRate);
    BitSlice1_out1_s161=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate);
    BitSlice2_out1_s162=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    Constant_out1_s163=addSignal(hN,'Constant_out1',pirTyp5,slRate);
    LogicalOperator1_out1_s164=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s165=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s166=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    LogicalOperator4_out1_s167=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    LogicalOperator5_out1_s168=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp5,slRate);
    LogicalOperator6_out1_s169=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp5,slRate);
    LogicalOperator7_out1_s170=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp5,slRate);
    BitSlice_out1_s171=addSignal(hN,'Bit Slice_out1',pirTyp1,slRate);
    BitSlice1_out1_s172=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate);
    BitSlice2_out1_s173=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    LogicalOperator1_out1_s174=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s175=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s176=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    LogicalOperator4_out1_s177=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    LogicalOperator5_out1_s178=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp5,slRate);
    LogicalOperator6_out1_s179=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp5,slRate);
    LogicalOperator7_out1_s180=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp5,slRate);
    LogicalOperator1_out1_s181=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s182=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s183=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    LogicalOperator4_out1_s184=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    LogicalOperator5_out1_s185=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp5,slRate);
    LogicalOperator6_out1_s186=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp5,slRate);
    BitSlice_out1_s187=addSignal(hN,'Bit Slice_out1',pirTyp1,slRate);
    BitSlice1_out1_s188=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate);
    BitSlice2_out1_s189=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate);
    LogicalOperator1_out1_s190=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp5,slRate);
    LogicalOperator2_out1_s191=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp5,slRate);
    LogicalOperator3_out1_s192=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp5,slRate);
    LogicalOperator4_out1_s193=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp5,slRate);
    LogicalOperator5_out1_s194=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp5,slRate);
    LogicalOperator6_out1_s195=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp5,slRate);
    LogicalOperator7_out1_s196=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp5,slRate);


    pirelab.getConstComp(hN,...
    Constant1_out1_s103,...
    fi(0,nt1,fiMath1,'hex','a'),...
    'Constant1','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant2_out1_s104,...
    fi(0,nt1,fiMath1,'hex','9'),...
    'Constant2','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant3_out1_s105,...
    fi(0,nt1,fiMath1,'hex','8'),...
    'Constant3','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant4_out1_s106,...
    fi(0,nt1,fiMath1,'hex','7'),...
    'Constant4','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant5_out1_s107,...
    fi(0,nt1,fiMath1,'hex','6'),...
    'Constant5','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant6_out1_s108,...
    fi(0,nt1,fiMath1,'hex','5'),...
    'Constant6','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant7_out1_s109,...
    fi(0,nt1,fiMath1,'hex','4'),...
    'Constant7','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant8_out1_s110,...
    fi(0,nt1,fiMath1,'hex','3'),...
    'Constant8','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant10_out1_s125,...
    fi(0,nt1,fiMath1,'hex','1'),...
    'Constant10','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant9_out1_s126,...
    fi(0,nt1,fiMath1,'hex','2'),...
    'Constant9','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant_out1_s91,...
    fi(0,nt1,fiMath1,'hex','b'),...
    'Constant','on',0,'','','');

    pirelab.getWireComp(hN,...
    Switch10_out1_s116,...
    Bottom8Bits_out1_s90,...
    'Bottom 8 bits_out1');

    pirelab.getWireComp(hN,...
    Switch12_out1_s128,...
    Middle8Bits_out1_s92,...
    'Middle 8 bits_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator14_out1_s127,...
    Middle8Bits_out2_s93,...
    'Middle 8 bits_out2');

    hRefN=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals/Rounding_Denormals');
    Rounding_Denormals=hN.addComponent('ntwk_instance_comp',hRefN);
    Rounding_Denormals.Name='Rounding_Denormals';
    pirelab.connectNtwkInstComp(Rounding_Denormals,...
    [Switch1_out1_s74,Switch2_out1_s75,get_Sticky1_out1_s78],...
    [Rounding_Denormals_out1_s68,Rounding_Denormals_out2_s69]);


    pirelab.getConstComp(hN,...
    Constant_out1_s163,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant','on',1,'','','');

    pirelab.getWireComp(hN,...
    LogicalOperator5_out1_s168,...
    x0_2_out1_s141,...
    '0-2_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator5_out1_s178,...
    x3_6_out1_s142,...
    '3-6_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator5_out1_s185,...
    x43_4_out1_s143,...
    '43-4_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator5_out1_s194,...
    x7_10_out1_s144,...
    '7-10_out1');


    pirelab.getConstComp(hN,...
    Constant_out1_s26,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'Constant','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant1_out1_s27,...
    fi(0,nt4,fiMath1,'hex','01'),...
    'Constant1','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant2_out1_s28,...
    fi(0,nt5,fiMath1,'hex','0'),...
    'Constant2','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant3_out1_s29,...
    fi(0,nt1,fiMath1,'hex','1'),...
    'Constant3','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant4_out1_s30,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant4','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant5_out1_s31,...
    fi(0,nt3,fiMath1,'hex','0'),...
    'Constant5','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant6_out1_s32,...
    fi(0,nt1,fiMath1,'hex','0'),...
    'Constant6','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant7_out1_s33,...
    fi(0,nt6,fiMath1,'hex','000'),...
    'Constant7','on',1,'','','');


    pirelab.getConstComp(hN,...
    Constant8_out1_s34,...
    fi(0,nt2,fiMath1,'hex','0'),...
    'Constant8','on',1,'','','');


    pirelab.getIntDelayComp(hN,...
    Delay15_PS_2_out1_s44,...
    Delay10_PS_3_out1_s39,...
    pipestage(3),'Delay10_PS_3',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay16_PS_2_out1_s45,...
    Delay11_PS_3_out1_s40,...
    pipestage(3),'Delay11_PS_3',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay17_PS_2_out1_s46,...
    Delay12_PS_3_out1_s41,...
    pipestage(3),'Delay12_PS_3',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitConcat_out1_s9,...
    Delay13_PS_2_out1_s42,...
    pipestage(2),'Delay13_PS_2',...
    fi(0,nt6,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Switch3_out1_s76,...
    Delay14_PS_2_out1_s43,...
    pipestage(2),'Delay14_PS_2',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    LogicalOperator2_out1_s66,...
    Delay15_PS_2_out1_s44,...
    pipestage(2),'Delay15_PS_2',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitReduce1_out1_s17,...
    Delay16_PS_2_out1_s45,...
    pipestage(2),'Delay16_PS_2',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    LogicalOperator_out1_s64,...
    Delay17_PS_2_out1_s46,...
    pipestage(2),'Delay17_PS_2',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    DataTypeConversion2_out1_s37,...
    Delay18_PS_2_out1_s47,...
    pipestage(2),'Delay18_PS_2',...
    fi(0,nt4,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay12_PS_3_out1_s41,...
    Delay19_PS_4_out1_s48,...
    pipestage(4),'Delay19_PS_4',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In1_s0,...
    Delay1_PS_1_out1_s49,...
    pipestage(1),'Delay1_PS_1',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Add3_out1_s8,...
    Delay23_PS_2_out1_s50,...
    pipestage(2),'Delay23_PS_2',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In5_s4,...
    Delay24_PS_1_out1_s51,...
    pipestage(1),'Delay24_PS_1',...
    fi(0,nt7,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitConcat6_out1_s15,...
    Delay25_PS_3_out1_s52,...
    pipestage(3),'Delay25_PS_3',...
    fi(0,nt6,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In2_s1,...
    Delay2_PS_1_out1_s53,...
    pipestage(1),'Delay2_PS_1',...
    fi(0,nt2,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitConcat4_out1_s13,...
    Delay3_PS_3_out1_s54,...
    pipestage(3),'Delay3_PS_3',...
    fi(0,nt8,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In3_s2,...
    Delay4_PS_1_out1_s55,...
    pipestage(1),'Delay4_PS_1',...
    fi(0,nt9,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    In4_s3,...
    Delay5_PS_1_out1_s56,...
    pipestage(1),'Delay5_PS_1',...
    fi(0,nt10,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Saturation_out1_s70,...
    Delay6_PS_3_out1_s57,...
    pipestage(3),'Delay6_PS_3',...
    fi(0,nt1,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Add_out1_s5,...
    Delay7_PS_2_out1_s58,...
    pipestage(2),'Delay7_PS_2',...
    fi(0,nt4,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    BitSlice3_out1_s22,...
    Delay8_PS_3_out1_s59,...
    pipestage(3),'Delay8_PS_3',...
    fi(0,nt9,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Add1_out1_s6,...
    Delay9_PS_3_out1_s60,...
    pipestage(3),'Delay9_PS_3',...
    fi(0,nt4,fiMath1,'hex','00'),...
    0,0,[],0,0);

    pirelab.getWireComp(hN,...
    BitConcat2_out1_s80,...
    y_s61,...
    'y');

    pirelab.getWireComp(hN,...
    BitConcat2_out1_s84,...
    y_s62,...
    'y');

    pirelab.getWireComp(hN,...
    Switch_out1_s94,...
    FindFirst_2_out1_s63,...
    'FindFirst_2_out1');

    pirelab.getWireComp(hN,...
    BitwiseOperator1_out1_s137,...
    Saturation_out1_s70,...
    'Saturation_out1');

    pirelab.getWireComp(hN,...
    x43_4_out1_s143,...
    get_Sticky1_out1_s78,...
    'get_Sticky1_out1');


    pirelab.getAddComp(hN,...
    [Switch_out1_s73,DataTypeConversion_out1_s35],...
    Add_out1_s5,...
    'Floor','Wrap','Add',pirTyp6,'++');


    pirelab.getAddComp(hN,...
    [Delay7_PS_2_out1_s58,Delay18_PS_2_out1_s47],...
    Add1_out1_s6,...
    'Floor','Wrap','Add1',pirTyp6,'+-');


    pirelab.getAddComp(hN,...
    [DataTypeConversion3_out1_s38,Delay7_PS_2_out1_s58],...
    Add2_out1_s7,...
    'Floor','Wrap','Add2',pirTyp6,'+-');


    pirelab.getAddComp(hN,...
    [Constant3_out1_s29,Switch3_out1_s76],...
    Add3_out1_s8,...
    'Floor','Wrap','Add3',pirTyp7,'++');


    pirelab.getBitConcatComp(hN,...
    [BitReduce_out1_s16,Delay24_PS_1_out1_s51],...
    BitConcat_out1_s9,...
    'Bit Concat');


    pirelab.getBitConcatComp(hN,...
    [BitSlice_out1_s19,Delay5_PS_1_out1_s56],...
    BitConcat1_out1_s10,...
    'Bit Concat1');


    pirelab.getBitConcatComp(hN,...
    [Constant_out1_s26,Delay4_PS_1_out1_s55],...
    BitConcat2_out1_s11,...
    'Bit Concat2');


    pirelab.getBitConcatComp(hN,...
    [Constant2_out1_s28,Switch3_out1_s76],...
    BitConcat3_out1_s12,...
    'Bit Concat3');


    pirelab.getBitConcatComp(hN,...
    [ShiftArithmetic_out1_s71,Constant4_out1_s30],...
    BitConcat4_out1_s13,...
    'Bit Concat4');


    pirelab.getBitConcatComp(hN,...
    [Constant5_out1_s31,Delay23_PS_2_out1_s50],...
    BitConcat5_out1_s14,...
    'Bit Concat5');


    pirelab.getBitConcatComp(hN,...
    [BitSlice4_out1_s23,Constant8_out1_s34],...
    BitConcat6_out1_s15,...
    'Bit Concat6');


    pirelab.getBitReduceComp(hN,...
    Delay4_PS_1_out1_s55,...
    BitReduce_out1_s16,...
    'OR','Bit Reduce');


    pirelab.getBitReduceComp(hN,...
    Delay4_PS_1_out1_s55,...
    BitReduce1_out1_s17,...
    'AND','Bit Reduce1');


    pirelab.getBitReduceComp(hN,...
    Delay24_PS_1_out1_s51,...
    BitReduce2_out1_s18,...
    'OR','Bit Reduce2');


    pirelab.getBitSliceComp(hN,...
    Delay5_PS_1_out1_s56,...
    BitSlice_out1_s19,...
    5,5,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    ShiftArithmetic1_out1_s72,...
    BitSlice1_out1_s20,...
    10,0,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    ShiftArithmetic1_out1_s72,...
    BitSlice2_out1_s21,...
    11,11,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    Add1_out1_s6,...
    BitSlice3_out1_s22,...
    4,0,'Bit Slice3');


    pirelab.getBitSliceComp(hN,...
    Delay13_PS_2_out1_s42,...
    BitSlice4_out1_s23,...
    9,0,'Bit Slice4');


    pirelab.getBitwiseOpComp(hN,...
    [Delay8_PS_3_out1_s59,y_s62],...
    BitwiseOperator_out1_s24,...
    'AND',sprintf('Bitwise\nOperator'),0,...
    double(0),1);


    pirelab.getCompareToValueComp(hN,...
    Delay9_PS_3_out1_s60,...
    CompareToConstant_out1_s25,...
    '>=',fi(0,nt4,fiMath1,'hex','1f'),...
    sprintf('Compare\nTo Constant'),0);


    pirelab.getDTCComp(hN,...
    BitConcat1_out1_s10,...
    DataTypeConversion_out1_s35,...
    'Floor','Wrap','SI','Data Type Conversion');


    pirelab.getDTCComp(hN,...
    BitConcat2_out1_s11,...
    DataTypeConversion1_out1_s36,...
    'Floor','Wrap','SI','Data Type Conversion1');


    pirelab.getDTCComp(hN,...
    BitConcat3_out1_s12,...
    DataTypeConversion2_out1_s37,...
    'Floor','Wrap','SI','Data Type Conversion2');


    pirelab.getDTCComp(hN,...
    BitConcat5_out1_s14,...
    DataTypeConversion3_out1_s38,...
    'Floor','Wrap','SI','Data Type Conversion3');


    pirelab.getBitConcatComp(hN,...
    [BitConcat5_out1_s82,Delay10_PS_3_out1_s39],...
    BitConcat2_out1_s80,...
    'Bit Concat2');


    pirelab.getBitConcatComp(hN,...
    [Delay10_PS_3_out1_s39,Delay10_PS_3_out1_s39],...
    BitConcat4_out1_s81,...
    'Bit Concat4');


    pirelab.getBitConcatComp(hN,...
    [BitConcat4_out1_s81,BitConcat4_out1_s81],...
    BitConcat5_out1_s82,...
    'Bit Concat5');


    pirelab.getBitConcatComp(hN,...
    [BitConcat5_out1_s86,BitSlice2_out1_s21],...
    BitConcat2_out1_s84,...
    'Bit Concat2');


    pirelab.getBitConcatComp(hN,...
    [BitSlice2_out1_s21,BitSlice2_out1_s21],...
    BitConcat4_out1_s85,...
    'Bit Concat4');


    pirelab.getBitConcatComp(hN,...
    [BitConcat4_out1_s85,BitConcat4_out1_s85],...
    BitConcat5_out1_s86,...
    'Bit Concat5');


    pirelab.getBitSliceComp(hN,...
    Delay24_PS_1_out1_s51,...
    BitSlice1_out1_s88,...
    9,8,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    Delay24_PS_1_out1_s51,...
    BitSlice4_out1_s89,...
    7,0,'Bit Slice4');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice1_out1_s95,...
    1,1,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice2_out1_s96,...
    2,2,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice3_out1_s97,...
    3,3,'Bit Slice3');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice4_out1_s98,...
    0,0,'Bit Slice4');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice5_out1_s99,...
    4,4,'Bit Slice5');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice6_out1_s100,...
    5,5,'Bit Slice6');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice7_out1_s101,...
    6,6,'Bit Slice7');


    pirelab.getBitSliceComp(hN,...
    BitSlice4_out1_s89,...
    BitSlice8_out1_s102,...
    7,7,'Bit Slice8');


    pirelab.getLogicComp(hN,...
    [BitSlice3_out1_s97,BitSlice2_out1_s96],...
    LogicalOperator_out1_s111,...
    'or',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hN,...
    [BitSlice8_out1_s102,BitSlice7_out1_s101],...
    LogicalOperator1_out1_s112,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s112,LogicalOperator3_out1_s114],...
    LogicalOperator2_out1_s113,...
    'or',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitSlice6_out1_s100,BitSlice5_out1_s99],...
    LogicalOperator3_out1_s114,...
    'or',sprintf('Logical\nOperator3'));


    pirelab.getSwitchComp(hN,...
    [Constant2_out1_s104,Switch2_out1_s117],...
    Switch1_out1_s115,...
    BitSlice1_out1_s95,'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch9_out1_s122,Switch4_out1_s119],...
    Switch10_out1_s116,...
    LogicalOperator2_out1_s113,'Switch10',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant1_out1_s103,Constant_out1_s91],...
    Switch2_out1_s117,...
    BitSlice4_out1_s98,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant4_out1_s106,Constant3_out1_s105],...
    Switch3_out1_s118,...
    BitSlice3_out1_s97,'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch3_out1_s118,Switch1_out1_s115],...
    Switch4_out1_s119,...
    LogicalOperator_out1_s111,'Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant6_out1_s108,Constant5_out1_s107],...
    Switch6_out1_s120,...
    BitSlice6_out1_s100,'Switch6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant8_out1_s110,Constant7_out1_s109],...
    Switch8_out1_s121,...
    BitSlice8_out1_s102,'Switch8',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch8_out1_s121,Switch6_out1_s120],...
    Switch9_out1_s122,...
    LogicalOperator1_out1_s112,'Switch9',...
    '~=',0,'Floor','Wrap');


    pirelab.getBitSliceComp(hN,...
    BitSlice1_out1_s88,...
    BitSlice10_out1_s123,...
    1,1,'Bit Slice10');


    pirelab.getBitSliceComp(hN,...
    BitSlice1_out1_s88,...
    BitSlice9_out1_s124,...
    0,0,'Bit Slice9');


    pirelab.getLogicComp(hN,...
    [BitSlice10_out1_s123,BitSlice9_out1_s124],...
    LogicalOperator14_out1_s127,...
    'or',sprintf('Logical\nOperator14'));


    pirelab.getSwitchComp(hN,...
    [Constant10_out1_s125,Constant9_out1_s126],...
    Switch12_out1_s128,...
    BitSlice10_out1_s123,'Switch12',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Middle8Bits_out1_s92,Bottom8Bits_out1_s90],...
    Switch_out1_s94,...
    Middle8Bits_out2_s93,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getLogicComp(hN,...
    [Delay1_PS_1_out1_s49,Delay2_PS_1_out1_s53],...
    LogicalOperator_out1_s64,...
    'xor',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hN,...
    [Delay11_PS_3_out1_s40,CompareToConstant_out1_s25,LogicalOperator3_out1_s67],...
    LogicalOperator1_out1_s65,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitReduce_out1_s16,BitReduce2_out1_s18],...
    LogicalOperator2_out1_s66,...
    'or',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    Delay10_PS_3_out1_s39,...
    LogicalOperator3_out1_s67,...
    'not',sprintf('Logical\nOperator3'));


    pirelab.getBitConcatComp(hN,...
    [BitReduce3_out1_s132,BitReduce3_out1_s132,BitReduce3_out1_s132,BitReduce3_out1_s132],...
    BitConcat5_out1_s130,...
    'Bit Concat5');


    pirelab.getBitConcatComp(hN,...
    [LogicalOperator4_out1_s138,LogicalOperator4_out1_s138,LogicalOperator4_out1_s138,LogicalOperator4_out1_s138],...
    BitConcat6_out1_s131,...
    'Bit Concat6');


    pirelab.getBitReduceComp(hN,...
    BitSlice2_out1_s134,...
    BitReduce3_out1_s132,...
    'OR','Bit Reduce3');


    pirelab.getBitSliceComp(hN,...
    Add2_out1_s7,...
    BitSlice1_out1_s133,...
    3,0,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    Add2_out1_s7,...
    BitSlice2_out1_s134,...
    5,4,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    Add2_out1_s7,...
    BitSlice3_out1_s135,...
    6,6,'Bit Slice3');


    pirelab.getBitwiseOpComp(hN,...
    [BitConcat5_out1_s130,BitSlice1_out1_s133],...
    BitwiseOperator_out1_s136,...
    'OR',sprintf('Bitwise\nOperator'),0,...
    double(0),1);


    pirelab.getBitwiseOpComp(hN,...
    [BitConcat6_out1_s131,BitwiseOperator_out1_s136],...
    BitwiseOperator1_out1_s137,...
    'AND',sprintf('Bitwise\nOperator1'),0,...
    double(0),1);


    pirelab.getLogicComp(hN,...
    BitSlice3_out1_s135,...
    LogicalOperator4_out1_s138,...
    'not',sprintf('Logical\nOperator4'));


    pirelab.getDynamicBitShiftComp(hN,...
    [Delay13_PS_2_out1_s42,Delay14_PS_2_out1_s43],...
    ShiftArithmetic_out1_s71,...
    'left',sprintf('shift\narithmetic'));


    pirelab.getDynamicBitShiftComp(hN,...
    [Delay3_PS_3_out1_s54,Delay6_PS_3_out1_s57],...
    ShiftArithmetic1_out1_s72,...
    'right',sprintf('shift\narithmetic1'));


    pirelab.getSwitchComp(hN,...
    [DataTypeConversion1_out1_s36,Constant1_out1_s27],...
    Switch_out1_s73,...
    BitReduce_out1_s16,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [y_s61,BitwiseOperator_out1_s24],...
    Switch1_out1_s74,...
    LogicalOperator1_out1_s65,'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch4_out1_s77,BitSlice1_out1_s20],...
    Switch2_out1_s75,...
    LogicalOperator1_out1_s65,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant6_out1_s32,FindFirst_2_out1_s63],...
    Switch3_out1_s76,...
    BitReduce_out1_s16,'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Delay25_PS_3_out1_s52,Constant7_out1_s33],...
    Switch4_out1_s77,...
    Delay11_PS_3_out1_s40,'Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getBitSliceComp(hN,...
    BitSlice_out1_s148,...
    BitSlice_out1_s160,...
    0,0,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    BitSlice_out1_s148,...
    BitSlice1_out1_s161,...
    1,1,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    BitSlice_out1_s148,...
    BitSlice2_out1_s162,...
    2,2,'Bit Slice2');


    pirelab.getLogicComp(hN,...
    [LogicalOperator2_out1_s165,BitSlice1_out1_s161],...
    LogicalOperator1_out1_s164,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitSlice2_out1_s162,BitSlice5_out1_s153],...
    LogicalOperator2_out1_s165,...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitSlice_out1_s160,LogicalOperator7_out1_s170],...
    LogicalOperator3_out1_s166,...
    'and',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s164,BitSlice2_out1_s151],...
    LogicalOperator4_out1_s167,...
    'and',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s167,LogicalOperator6_out1_s169],...
    LogicalOperator5_out1_s168,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator3_out1_s166,Constant_out1_s163],...
    LogicalOperator6_out1_s169,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitSlice5_out1_s153,BitSlice2_out1_s151],...
    LogicalOperator7_out1_s170,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getBitSliceComp(hN,...
    BitSlice7_out1_s155,...
    BitSlice_out1_s171,...
    0,0,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    BitSlice7_out1_s155,...
    BitSlice1_out1_s172,...
    1,1,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    BitSlice7_out1_s155,...
    BitSlice2_out1_s173,...
    2,2,'Bit Slice2');


    pirelab.getLogicComp(hN,...
    [LogicalOperator2_out1_s175,BitSlice1_out1_s172],...
    LogicalOperator1_out1_s174,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitSlice2_out1_s173,BitSlice5_out1_s153],...
    LogicalOperator2_out1_s175,...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitSlice_out1_s171,LogicalOperator7_out1_s180],...
    LogicalOperator3_out1_s176,...
    'and',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s174,BitSlice2_out1_s151],...
    LogicalOperator4_out1_s177,...
    'and',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s177,LogicalOperator6_out1_s179],...
    LogicalOperator5_out1_s178,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator3_out1_s176,BitReduce_out1_s145],...
    LogicalOperator6_out1_s179,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitSlice5_out1_s153,BitSlice2_out1_s151],...
    LogicalOperator7_out1_s180,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator2_out1_s182,x7_10_out1_s144],...
    LogicalOperator1_out1_s181,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator2_out1_s159,BitSlice1_out1_s149],...
    LogicalOperator2_out1_s182,...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [x3_6_out1_s142,BitSlice1_out1_s149],...
    LogicalOperator3_out1_s183,...
    'and',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s181,BitSlice3_out1_s152],...
    LogicalOperator4_out1_s184,...
    'and',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s184,LogicalOperator6_out1_s186],...
    LogicalOperator5_out1_s185,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator3_out1_s183,x0_2_out1_s141],...
    LogicalOperator6_out1_s186,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s157,...
    BitSlice_out1_s187,...
    0,0,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s157,...
    BitSlice1_out1_s188,...
    1,1,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s157,...
    BitSlice2_out1_s189,...
    2,2,'Bit Slice2');


    pirelab.getLogicComp(hN,...
    [LogicalOperator2_out1_s191,BitSlice1_out1_s188],...
    LogicalOperator1_out1_s190,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitSlice2_out1_s189,BitSlice5_out1_s153],...
    LogicalOperator2_out1_s191,...
    'and',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitSlice_out1_s187,LogicalOperator7_out1_s196],...
    LogicalOperator3_out1_s192,...
    'and',sprintf('Logical\nOperator3'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s190,BitSlice2_out1_s151],...
    LogicalOperator4_out1_s193,...
    'and',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s193,LogicalOperator6_out1_s195],...
    LogicalOperator5_out1_s194,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator3_out1_s192,LogicalOperator1_out1_s158],...
    LogicalOperator6_out1_s195,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitSlice5_out1_s153,BitSlice2_out1_s151],...
    LogicalOperator7_out1_s196,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getBitReduceComp(hN,...
    BitSlice6_out1_s154,...
    BitReduce_out1_s145,...
    'OR','Bit Reduce');


    pirelab.getBitReduceComp(hN,...
    BitSlice8_out1_s156,...
    BitReduce1_out1_s146,...
    'OR','Bit Reduce1');


    pirelab.getBitReduceComp(hN,...
    BitSlice10_out1_s150,...
    BitReduce2_out1_s147,...
    'OR','Bit Reduce2');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice_out1_s148,...
    2,0,'Bit Slice');


    pirelab.getBitSliceComp(hN,...
    Delay6_PS_3_out1_s57,...
    BitSlice1_out1_s149,...
    2,2,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice10_out1_s150,...
    11,8,'Bit Slice10');


    pirelab.getBitSliceComp(hN,...
    Delay6_PS_3_out1_s57,...
    BitSlice2_out1_s151,...
    1,1,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    Delay6_PS_3_out1_s57,...
    BitSlice3_out1_s152,...
    3,3,'Bit Slice3');


    pirelab.getBitSliceComp(hN,...
    Delay6_PS_3_out1_s57,...
    BitSlice5_out1_s153,...
    0,0,'Bit Slice5');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice6_out1_s154,...
    3,0,'Bit Slice6');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice7_out1_s155,...
    6,4,'Bit Slice7');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice8_out1_s156,...
    7,4,'Bit Slice8');


    pirelab.getBitSliceComp(hN,...
    Delay3_PS_3_out1_s54,...
    BitSlice9_out1_s157,...
    10,8,'Bit Slice9');


    pirelab.getLogicComp(hN,...
    [BitReduce1_out1_s146,BitReduce_out1_s145],...
    LogicalOperator1_out1_s158,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [BitReduce2_out1_s147,LogicalOperator1_out1_s158],...
    LogicalOperator2_out1_s159,...
    'or',sprintf('Logical\nOperator2'));


end

function hN=createNetwork_n1(p,hN,denormal,slRate)
    pirTyp5=pir_ufixpt_t(1,0);
    pirTyp3=pir_sfixpt_t(6,0);
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp4=pir_ufixpt_t(10,0);
    pirTyp2=pir_ufixpt_t(5,0);






    hN.addInputPort('In1 ');
    In1_s0=addSignal(hN,'In1 ',pirTyp1,slRate);
    In1_s0.addDriver(hN,0);

    hN.addInputPort('In2 ');
    In2_s1=addSignal(hN,'In2 ',pirTyp1,slRate);
    In2_s1.addDriver(hN,1);

    hN.addInputPort('In3 ');
    In3_s2=addSignal(hN,'In3 ',pirTyp2,slRate);
    In3_s2.addDriver(hN,2);

    hN.addInputPort('In4 ');
    In4_s3=addSignal(hN,'In4 ',pirTyp3,slRate);
    In4_s3.addDriver(hN,3);

    hN.addInputPort('In5 ');
    In5_s4=addSignal(hN,'In5 ',pirTyp4,slRate);
    In5_s4.addDriver(hN,4);

    hN.addOutputPort(' Out1');
    GainPow2_Main_Normals_out1_s5=addSignal(hN,'GainPow2_Main_Normals_out1',pirTyp5,slRate);
    GainPow2_Main_Normals_out1_s5.addReceiver(hN,0);

    hN.addOutputPort(' Out2');
    GainPow2_Main_Normals_out2_s6=addSignal(hN,'GainPow2_Main_Normals_out2',pirTyp2,slRate);
    GainPow2_Main_Normals_out2_s6.addReceiver(hN,1);

    hN.addOutputPort(' Out3');
    GainPow2_Main_Normals_out3_s7=addSignal(hN,'GainPow2_Main_Normals_out3',pirTyp4,slRate);
    GainPow2_Main_Normals_out3_s7.addReceiver(hN,2);


    if(denormal)
        hRefN=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Denormals');
        GainPow2_Main_Normals=hN.addComponent('ntwk_instance_comp',hRefN);
        GainPow2_Main_Normals.Name='GainPow2_Main_Denormals';
        pirelab.connectNtwkInstComp(GainPow2_Main_Normals,...
        [In1_s0,In2_s1,In3_s2,In4_s3,In5_s4],...
        [GainPow2_Main_Normals_out1_s5,GainPow2_Main_Normals_out2_s6,GainPow2_Main_Normals_out3_s7]);
    else
        hRefN=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main/GainPow2_Main_Normals');
        GainPow2_Main_Normals=hN.addComponent('ntwk_instance_comp',hRefN);
        GainPow2_Main_Normals.Name='GainPow2_Main_Normals';
        pirelab.connectNtwkInstComp(GainPow2_Main_Normals,...
        [In1_s0,In2_s1,In3_s2,In4_s3,In5_s4],...
        [GainPow2_Main_Normals_out1_s5,GainPow2_Main_Normals_out2_s6,GainPow2_Main_Normals_out3_s7]);
    end

end

function hN=createNetwork_n0(p,hN,slRate)
    pirTyp5=pir_ufixpt_t(1,0);
    pirTyp4=pir_sfixpt_t(6,0);
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp3=pir_ufixpt_t(10,0);
    pirTyp2=pir_ufixpt_t(5,0);






    hN.addInputPort('aSign');
    aSign_s0=addSignal(hN,'aSign',pirTyp1,slRate);
    aSign_s0.addDriver(hN,0);

    hN.addInputPort('aExponent');
    aExponent_s1=addSignal(hN,'aExponent',pirTyp2,slRate);
    aExponent_s1.addDriver(hN,1);

    hN.addInputPort('aMantissa');
    aMantissa_s2=addSignal(hN,'aMantissa',pirTyp3,slRate);
    aMantissa_s2.addDriver(hN,2);

    hN.addInputPort('bSign');
    bSign_s3=addSignal(hN,'bSign',pirTyp1,slRate);
    bSign_s3.addDriver(hN,3);

    hN.addInputPort('bExponent');
    bExponent_s4=addSignal(hN,'bExponent',pirTyp4,slRate);
    bExponent_s4.addDriver(hN,4);

    hN.addOutputPort('Sign');
    GainPow2_Main_out1_s5=addSignal(hN,'GainPow2_Main_out1',pirTyp5,slRate);
    GainPow2_Main_out1_s5.addReceiver(hN,0);

    hN.addOutputPort('Exponent');
    GainPow2_Main_out2_s6=addSignal(hN,'GainPow2_Main_out2',pirTyp2,slRate);
    GainPow2_Main_out2_s6.addReceiver(hN,1);

    hN.addOutputPort('Mantissa');
    GainPow2_Main_out3_s7=addSignal(hN,'GainPow2_Main_out3',pirTyp3,slRate);
    GainPow2_Main_out3_s7.addReceiver(hN,2);


    hRefN=p.findNetwork('fullname','Half_GainPow2_HDL_model/GainPow2_Half/GainPow2_Main');
    GainPow2_Main=hN.addComponent('ntwk_instance_comp',hRefN);
    GainPow2_Main.Name='GainPow2_Main';
    pirelab.connectNtwkInstComp(GainPow2_Main,...
    [aSign_s0,bSign_s3,aExponent_s1,bExponent_s4,aMantissa_s2],...
    [GainPow2_Main_out1_s5,GainPow2_Main_out2_s6,GainPow2_Main_out3_s7]);


end

function hS=addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end
