function hTopN=getSingleCeilComp(hN,latency,slRate)


    p=pir(hN.getCtxName);
    hTopN=addNetworks(p);
    pipestage=zeros(1,5);
    switch latency
    case 0
        pipestage=zeros(1,5);
    case 1
        pipestage=[0,0,0,1,0];
    case 2
        pipestage=[1,1,0,0,0];
    case 3
        pipestage=[1,0,1,0,1];
    case 4
        pipestage=[1,1,0,1,1];
    case 5
        pipestage=ones(1,5);
    otherwise
        assert(false,'Illegal latency number for rounding in ceil mode.');
    end
    createNetworks(p,pipestage,latency,slRate);
end

function hTopN=addNetworks(p)
    hN=p.addNetwork;
    hN.Name='NFP_Mathworks_Ceil_Single';
    hN.FullPath='Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single';
    hTopN=hN;
    hN=p.addNetwork;
    hN.Name='initCycles';
    hN.FullPath='Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles';
    hN=p.addNetwork;
    hN.Name='InitCycles';
    hN.FullPath='Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles/InitCycles';
end

function createNetworks(p,pipestage,latency,slRate)
    hN_n6=p.findNetwork('fullname','Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles/InitCycles');
    createNetwork_n6(p,hN_n6,pipestage,latency,slRate);
    hN_n5=p.findNetwork('fullname','Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles');
    createNetwork_n5(p,hN_n5,slRate);
    hN_n0=p.findNetwork('fullname','Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single');
    createNetwork_n0(p,hN_n0,pipestage,slRate);
end

function hN=createNetwork_n6(~,hN,pipestage,latency,slRate1)
    if(latency>0)
        pirTyp4=pir_ufixpt_t(1,0);
        pirTyp1=pir_ufixpt_t(1,0);
        pirTyp3=pir_ufixpt_t(23,0);
        pirTyp5=pir_ufixpt_t(3,0);
        pirTyp2=pir_ufixpt_t(8,0);

        fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

        nt2=numerictype(0,1,0);
        nt3=numerictype(0,23,0);
        nt1=numerictype(0,3,0);
        nt4=numerictype(0,8,0);


        hN.addInputPort('inSign');
        inSign_s0=addSignal(hN,'inSign',pirTyp1,slRate1);
        inSign_s0.addDriver(hN,0);

        hN.addInputPort('inExponent');
        inExponent_s1=addSignal(hN,'inExponent',pirTyp2,slRate1);
        inExponent_s1.addDriver(hN,1);

        hN.addInputPort('inMantissa');
        inMantissa_s2=addSignal(hN,'inMantissa',pirTyp3,slRate1);
        inMantissa_s2.addDriver(hN,2);

        hN.addOutputPort('OutSign');
        Delay3_PS_5_out1_s6=addSignal(hN,'Delay3_PS_5_out1',pirTyp1,slRate1);
        Delay3_PS_5_out1_s6.addReceiver(hN,0);

        hN.addOutputPort('OutExponent');
        Delay4_PS_5_out1_s7=addSignal(hN,'Delay4_PS_5_out1',pirTyp2,slRate1);
        Delay4_PS_5_out1_s7.addReceiver(hN,1);

        hN.addOutputPort('OutMantissa');
        Delay5_PS_5_out1_s8=addSignal(hN,'Delay5_PS_5_out1',pirTyp3,slRate1);
        Delay5_PS_5_out1_s8.addReceiver(hN,2);

        Constant1_out1_s3=addSignal(hN,'Constant1_out1',pirTyp1,slRate1);
        Constant2_out1_s4=addSignal(hN,'Constant2_out1',pirTyp3,slRate1);
        Constant3_out1_s5=addSignal(hN,'Constant3_out1',pirTyp2,slRate1);
        InitCycles1_out1_s9=addSignal(hN,'InitCycles1_out1',pirTyp4,slRate1);
        Switch1_out1_s10=addSignal(hN,'Switch1_out1',pirTyp1,slRate1);
        Switch5_out1_s11=addSignal(hN,'Switch5_out1',pirTyp3,slRate1);
        Switch6_out1_s12=addSignal(hN,'Switch6_out1',pirTyp2,slRate1);
        Add_out1_s13=addSignal(hN,'Add_out1',pirTyp5,slRate1);
        Constant7_out1_s14=addSignal(hN,'Constant7_out1',pirTyp5,slRate1);
        Constant8_out1_s15=addSignal(hN,'Constant8_out1',pirTyp4,slRate1);
        DataTypeConversion_out1_s16=addSignal(hN,'Data Type Conversion_out1',pirTyp1,slRate1);
        Delay1_out1_s17=addSignal(hN,'Delay1_out1',pirTyp4,slRate1);
        Delay3_out1_s18=addSignal(hN,'Delay3_out1',pirTyp5,slRate1);
        Delay4_out1_s19=addSignal(hN,'Delay4_out1',pirTyp4,slRate1);
        LogicalOperator_out1_s20=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp4,slRate1);
        RelationalOperator_out1_s21=addSignal(hN,sprintf('Relational\nOperator_out1'),pirTyp4,slRate1);
        if latency>2
            latencyStr=dec2hex(latency-2);
        elseif latency>0
            latencyStr=dec2hex(latency-1);
        else
            latencyStr='0';
        end

        pirelab.getConstComp(hN,...
        Constant7_out1_s14,...
        fi(0,nt1,fiMath1,'hex',latencyStr),...
        'Constant7','on',0,'','','');


        pirelab.getConstComp(hN,...
        Constant8_out1_s15,...
        fi(0,nt2,fiMath1,'hex','1'),...
        'Constant8','on',0,'','','');


        pirelab.getIntDelayComp(hN,...
        RelationalOperator_out1_s21,...
        Delay1_out1_s17,...
        1,'Delay1',...
        true,...
        0,0,[],0,0);


        pirelab.getIntDelayComp(hN,...
        Add_out1_s13,...
        Delay3_out1_s18,...
        1,'Delay3',...
        fi(0,nt1,fiMath1,'hex','0'),...
        0,0,[],0,0);


        pirelab.getIntDelayComp(hN,...
        RelationalOperator_out1_s21,...
        Delay4_out1_s19,...
        1,'Delay4',...
        true,...
        0,0,[],0,0);

        pirelab.getAnnotationComp(hN,...
        'Display');


        pirelab.getConstComp(hN,...
        Constant1_out1_s3,...
        fi(0,nt2,fiMath1,'hex','0'),...
        'Constant1','on',1,'','','');


        pirelab.getConstComp(hN,...
        Constant2_out1_s4,...
        fi(0,nt3,fiMath1,'hex','000000'),...
        'Constant2','on',1,'','','');


        pirelab.getConstComp(hN,...
        Constant3_out1_s5,...
        fi(0,nt4,fiMath1,'hex','00'),...
        'Constant3','on',1,'','','');


        pirelab.getIntDelayComp(hN,...
        Switch1_out1_s10,...
        Delay3_PS_5_out1_s6,...
        pipestage(5),'Delay3_PS_5',...
        fi(0,nt2,fiMath1,'hex','0'),...
        0,0,[],0,0);


        pirelab.getIntDelayComp(hN,...
        Switch6_out1_s12,...
        Delay4_PS_5_out1_s7,...
        pipestage(5),'Delay4_PS_5',...
        uint8(0),...
        0,0,[],0,0);


        pirelab.getIntDelayComp(hN,...
        Switch5_out1_s11,...
        Delay5_PS_5_out1_s8,...
        pipestage(5),'Delay5_PS_5',...
        fi(0,nt3,fiMath1,'hex','000000'),...
        0,0,[],0,0);

        pirelab.getWireComp(hN,...
        Delay1_out1_s17,...
        InitCycles1_out1_s9,...
        'InitCycles1_out1');


        pirelab.getAddComp(hN,...
        [Delay3_out1_s18,DataTypeConversion_out1_s16],...
        Add_out1_s13,...
        'Floor','Wrap','Add',pirTyp5,'++');


        pirelab.getDTCComp(hN,...
        LogicalOperator_out1_s20,...
        DataTypeConversion_out1_s16,...
        'Floor','Wrap','RWV','Data Type Conversion');


        pirelab.getLogicComp(hN,...
        [Constant8_out1_s15,Delay4_out1_s19],...
        LogicalOperator_out1_s20,...
        'and',sprintf('Logical\nOperator'));


        pirelab.getRelOpComp(hN,...
        [Add_out1_s13,Constant7_out1_s14],...
        RelationalOperator_out1_s21,...
        '<=',0,sprintf('Relational\nOperator'));


        pirelab.getSwitchComp(hN,...
        [Constant1_out1_s3,inSign_s0],...
        Switch1_out1_s10,...
        InitCycles1_out1_s9,'Switch1',...
        '~=',0,'Floor','Wrap');


        pirelab.getSwitchComp(hN,...
        [Constant2_out1_s4,inMantissa_s2],...
        Switch5_out1_s11,...
        InitCycles1_out1_s9,'Switch5',...
        '~=',0,'Floor','Wrap');


        pirelab.getSwitchComp(hN,...
        [Constant3_out1_s5,inExponent_s1],...
        Switch6_out1_s12,...
        InitCycles1_out1_s9,'Switch6',...
        '~=',0,'Floor','Wrap');
    else
        pirTyp1=pir_ufixpt_t(1,0);
        pirTyp3=pir_ufixpt_t(23,0);
        pirTyp2=pir_ufixpt_t(8,0);


        hN.addInputPort('inSign');
        inSign_s0=addSignal(hN,'inSign',pirTyp1,slRate1);
        inSign_s0.addDriver(hN,0);

        hN.addInputPort('inExponent');
        inExponent_s1=addSignal(hN,'inExponent',pirTyp2,slRate1);
        inExponent_s1.addDriver(hN,1);

        hN.addInputPort('inMantissa');
        inMantissa_s2=addSignal(hN,'inMantissa',pirTyp3,slRate1);
        inMantissa_s2.addDriver(hN,2);

        hN.addOutputPort('OutSign');
        inSign_s0.addReceiver(hN,0);

        hN.addOutputPort('OutExponent');
        inExponent_s1.addReceiver(hN,1);

        hN.addOutputPort('OutMantissa');
        inMantissa_s2.addReceiver(hN,2);


    end

end

function hN=createNetwork_n5(p,hN,slRate1)
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp3=pir_ufixpt_t(23,0);
    pirTyp2=pir_ufixpt_t(8,0);


    hN.addInputPort('inSign');
    inSign_s0=addSignal(hN,'inSign',pirTyp1,slRate1);
    inSign_s0.addDriver(hN,0);

    hN.addInputPort('inExponent');
    inExponent_s1=addSignal(hN,'inExponent',pirTyp2,slRate1);
    inExponent_s1.addDriver(hN,1);

    hN.addInputPort('inMantissa');
    inMantissa_s2=addSignal(hN,'inMantissa',pirTyp3,slRate1);
    inMantissa_s2.addDriver(hN,2);

    hN.addOutputPort('OutSign');
    InitCycles_out1_s3=addSignal(hN,'InitCycles_out1',pirTyp1,slRate1);
    InitCycles_out1_s3.addReceiver(hN,0);

    hN.addOutputPort('OutExponent');
    InitCycles_out2_s4=addSignal(hN,'InitCycles_out2',pirTyp2,slRate1);
    InitCycles_out2_s4.addReceiver(hN,1);

    hN.addOutputPort('OutMantissa');
    InitCycles_out3_s5=addSignal(hN,'InitCycles_out3',pirTyp3,slRate1);
    InitCycles_out3_s5.addReceiver(hN,2);


    hRefN=p.findNetwork('fullname','Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles/InitCycles');
    InitCycles=hN.addComponent('ntwk_instance_comp',hRefN);
    InitCycles.Name='InitCycles';
    pirelab.connectNtwkInstComp(InitCycles,...
    [inSign_s0,inExponent_s1,inMantissa_s2],...
    [InitCycles_out1_s3,InitCycles_out2_s4,InitCycles_out3_s5]);


end

function hN=createNetwork_n0(p,hN,pipestage,slRate1)
    pirTyp6=pir_ufixpt_t(1,0);
    pirTyp11=pir_sfixpt_t(32,0);
    pirTyp1=pir_ufixpt_t(1,0);
    pirTyp8=pir_ufixpt_t(10,0);
    pirTyp3=pir_ufixpt_t(23,0);
    pirTyp10=pir_ufixpt_t(24,0);
    pirTyp5=pir_ufixpt_t(31,0);
    pirTyp12=pir_ufixpt_t(32,0);
    pirTyp7=pir_ufixpt_t(6,0);
    pirTyp9=pir_ufixpt_t(9,0);
    pirTyp4=pir_unsigned_t(32);
    pirTyp2=pir_ufixpt_t(8,0);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt3=numerictype(0,1,0);
    nt5=numerictype(0,10,0);
    nt2=numerictype(0,23,0);
    nt4=numerictype(0,31,0);
    nt1=numerictype(0,6,0);
    nt6=numerictype(0,8,0);



    hN.addInputPort('aSign');
    aSign_s0=addSignal(hN,'aSign',pirTyp1,slRate1);
    aSign_s0.addDriver(hN,0);

    hN.addInputPort('aExponent');
    aExponent_s1=addSignal(hN,'aExponent',pirTyp2,slRate1);
    aExponent_s1.addDriver(hN,1);

    hN.addInputPort('aMantissa');
    aMantissa_s2=addSignal(hN,'aMantissa',pirTyp3,slRate1);
    aMantissa_s2.addDriver(hN,2);

    hN.addOutputPort('cSign');
    initCycles_out1_s44=addSignal(hN,'initCycles_out1',pirTyp1,slRate1);
    initCycles_out1_s44.addReceiver(hN,0);

    hN.addOutputPort('cExponent');
    initCycles_out2_s45=addSignal(hN,'initCycles_out2',pirTyp2,slRate1);
    initCycles_out2_s45.addReceiver(hN,1);

    hN.addOutputPort('cMantissa');
    initCycles_out3_s46=addSignal(hN,'initCycles_out3',pirTyp3,slRate1);
    initCycles_out3_s46.addReceiver(hN,2);

    Add_out1_s3=addSignal(hN,'Add_out1',pirTyp4,slRate1);
    BitSlice1_out1_s4=addSignal(hN,'Bit Slice1_out1',pirTyp3,slRate1);
    BitSlice2_out1_s5=addSignal(hN,'Bit Slice2_out1',pirTyp2,slRate1);
    BitSlice3_out1_s6=addSignal(hN,'Bit Slice3_out1',pirTyp5,slRate1);
    BitSlice4_out1_s7=addSignal(hN,'Bit Slice4_out1',pirTyp5,slRate1);
    ConcatExpandMant_out1_s8=addSignal(hN,'ConcatExpandMant_out1',pirTyp5,slRate1);
    Constant136_out1_s9=addSignal(hN,'Constant136_out1',pirTyp3,slRate1);
    Constant77_out1_s10=addSignal(hN,'Constant77_out1',pirTyp1,slRate1);
    Delay10_PS_4_out1_s11=addSignal(hN,'Delay10_PS_4_out1',pirTyp2,slRate1);
    Delay11_PS_4_out1_s12=addSignal(hN,'Delay11_PS_4_out1',pirTyp5,slRate1);
    Delay12_PS_4_out1_s13=addSignal(hN,'Delay12_PS_4_out1',pirTyp6,slRate1);
    Delay13_PS_4_out1_s14=addSignal(hN,'Delay13_PS_4_out1',pirTyp3,slRate1);
    Delay14_PS_4_out1_s15=addSignal(hN,'Delay14_PS_4_out1',pirTyp1,slRate1);
    Delay2_PS_1_out1_s16=addSignal(hN,'Delay2_PS_1_out1',pirTyp2,slRate1);
    Delay2_PS_2_3_out1_s17=addSignal(hN,'Delay2_PS_2_3_out1',pirTyp2,slRate1);
    Delay3_PS_1_out1_s18=addSignal(hN,'Delay3_PS_1_out1',pirTyp3,slRate1);
    Delay3_PS_3_4_out1_s19=addSignal(hN,'Delay3_PS_3_4_out1',pirTyp2,slRate1);
    Delay4_PS_2_out1_s20=addSignal(hN,'Delay4_PS_2_out1',pirTyp7,slRate1);
    Delay4_PS_2_4_out1_s21=addSignal(hN,'Delay4_PS_2_4_out1',pirTyp6,slRate1);
    Delay5_PS_2_out1_s22=addSignal(hN,'Delay5_PS_2_out1',pirTyp8,slRate1);
    Delay5_PS_3_out1_s23=addSignal(hN,'Delay5_PS_3_out1',pirTyp6,slRate1);
    Delay6_PS_4_out1_s24=addSignal(hN,'Delay6_PS_4_out1',pirTyp5,slRate1);
    Delay7_PS_3_out1_s25=addSignal(hN,'Delay7_PS_3_out1',pirTyp5,slRate1);
    Delay8_PS_2_3_out1_s26=addSignal(hN,'Delay8_PS_2_3_out1',pirTyp3,slRate1);
    Delay_PS_1_2_out1_s27=addSignal(hN,'Delay_PS_1_2_out1',pirTyp1,slRate1);
    Delay_PS_3_out1_s28=addSignal(hN,'Delay_PS_3_out1',pirTyp1,slRate1);
    Exponent0_out1_s29=addSignal(hN,'Exponent0_out1',pirTyp2,slRate1);
    Exponent127_out1_s30=addSignal(hN,'Exponent127_out1',pirTyp2,slRate1);
    ExponentBias_out1_s31=addSignal(hN,'ExponentBias_out1',pirTyp2,slRate1);
    FindFirst1PosFromLSB_out1_s32=addSignal(hN,'FindFirst1PosFromLSB_out1',pirTyp7,slRate1);
    LogicalOperator_out1_s33=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp6,slRate1);
    Mask_out1_s34=addSignal(hN,'Mask_out1',pirTyp5,slRate1);
    ShiftBinaryPoint_out1_s35=addSignal(hN,'ShiftBinaryPoint_out1',pirTyp5,slRate1);
    Switch_out1_s36=addSignal(hN,'Switch_out1',pirTyp2,slRate1);
    Switch1_out1_s37=addSignal(hN,'Switch1_out1',pirTyp5,slRate1);
    Switch2_out1_s38=addSignal(hN,'Switch2_out1',pirTyp3,slRate1);
    Switch3_out1_s39=addSignal(hN,'Switch3_out1',pirTyp3,slRate1);
    Switch4_out1_s40=addSignal(hN,'Switch4_out1',pirTyp2,slRate1);
    Switch5_out1_s41=addSignal(hN,'Switch5_out1',pirTyp2,slRate1);
    TrueExponent_out1_s42=addSignal(hN,'TrueExponent_out1',pirTyp9,slRate1);
    constant_out1_s43=addSignal(hN,'constant_out1',pirTyp5,slRate1);
    initialBinaryPointPos_out1_s47=addSignal(hN,'initialBinaryPointPos_out1',pirTyp5,slRate1);
    isExponentGt150_out1_s48=addSignal(hN,'isExponentGt150_out1',pirTyp6,slRate1);
    isExponentLt127_out1_s49=addSignal(hN,'isExponentLt127_out1',pirTyp6,slRate1);
    isExponentZero_out1_s50=addSignal(hN,'isExponentZero_out1',pirTyp6,slRate1);
    isInputInteger_out1_s51=addSignal(hN,'isInputInteger_out1',pirTyp6,slRate1);
    isInputPositive_out1_s52=addSignal(hN,'isInputPositive_out1',pirTyp6,slRate1);
    isInputZero_out1_s53=addSignal(hN,'isInputZero_out1',pirTyp6,slRate1);
    isMantissaZero_out1_s54=addSignal(hN,'isMantissaZero_out1',pirTyp6,slRate1);
    isPosLtShiftlength_out1_s55=addSignal(hN,'isPosLtShiftlength_out1',pirTyp6,slRate1);
    isSignedness_out1_s56=addSignal(hN,'isSignedness_out1',pirTyp6,slRate1);
    mantissaFractionlength_out1_s57=addSignal(hN,'mantissaFractionlength_out1',pirTyp2,slRate1);
    normalizedMantissa_out1_s58=addSignal(hN,'normalizedMantissa_out1',pirTyp10,slRate1);
    shiftlength_out1_s59=addSignal(hN,'shiftlength_out1',pirTyp8,slRate1);
    tempExpAndMant_out1_s60=addSignal(hN,'tempExpAnd Mant_out1',pirTyp5,slRate1);
    tempExpAndMantInc_out1_s61=addSignal(hN,'tempExpAndMantInc_out1',pirTyp4,slRate1);
    BitSlice2_out1_s63=addSignal(hN,'Bit Slice2_out1',pirTyp2,slRate1);
    BitSlice8_out1_s64=addSignal(hN,'Bit Slice8_out1',pirTyp2,slRate1);
    BitSlice9_out1_s65=addSignal(hN,'Bit Slice9_out1',pirTyp2,slRate1);
    Constant_out1_s66=addSignal(hN,'Constant_out1',pirTyp7,slRate1);
    Middle8Bits_out1_s67=addSignal(hN,'Middle 8 bits_out1',pirTyp7,slRate1);
    Middle8Bits_out2_s68=addSignal(hN,'Middle 8 bits_out2',pirTyp6,slRate1);
    Switch_out1_s69=addSignal(hN,'Switch_out1',pirTyp7,slRate1);
    Switch1_out1_s70=addSignal(hN,'Switch1_out1',pirTyp7,slRate1);
    Top8Bits_out1_s71=addSignal(hN,'Top 8 bits_out1',pirTyp7,slRate1);
    lower8Bits_out1_s72=addSignal(hN,'lower 8 bits_out1',pirTyp7,slRate1);
    lower8Bits_out2_s73=addSignal(hN,'lower 8 bits_out2',pirTyp6,slRate1);
    BitSlice10_out1_s74=addSignal(hN,'Bit Slice10_out1',pirTyp1,slRate1);
    BitSlice11_out1_s75=addSignal(hN,'Bit Slice11_out1',pirTyp1,slRate1);
    BitSlice12_out1_s76=addSignal(hN,'Bit Slice12_out1',pirTyp1,slRate1);
    BitSlice13_out1_s77=addSignal(hN,'Bit Slice13_out1',pirTyp1,slRate1);
    BitSlice14_out1_s78=addSignal(hN,'Bit Slice14_out1',pirTyp1,slRate1);
    BitSlice15_out1_s79=addSignal(hN,'Bit Slice15_out1',pirTyp1,slRate1);
    BitSlice16_out1_s80=addSignal(hN,'Bit Slice16_out1',pirTyp1,slRate1);
    BitSlice9_out1_s81=addSignal(hN,'Bit Slice9_out1',pirTyp1,slRate1);
    Constant10_out1_s82=addSignal(hN,'Constant10_out1',pirTyp7,slRate1);
    Constant11_out1_s83=addSignal(hN,'Constant11_out1',pirTyp7,slRate1);
    Constant12_out1_s84=addSignal(hN,'Constant12_out1',pirTyp7,slRate1);
    Constant13_out1_s85=addSignal(hN,'Constant13_out1',pirTyp7,slRate1);
    Constant14_out1_s86=addSignal(hN,'Constant14_out1',pirTyp7,slRate1);
    Constant15_out1_s87=addSignal(hN,'Constant15_out1',pirTyp7,slRate1);
    Constant16_out1_s88=addSignal(hN,'Constant16_out1',pirTyp7,slRate1);
    Constant9_out1_s89=addSignal(hN,'Constant9_out1',pirTyp7,slRate1);
    LogicalOperator12_out1_s90=addSignal(hN,sprintf('Logical\nOperator12_out1'),pirTyp6,slRate1);
    LogicalOperator13_out1_s91=addSignal(hN,sprintf('Logical\nOperator13_out1'),pirTyp6,slRate1);
    LogicalOperator14_out1_s92=addSignal(hN,sprintf('Logical\nOperator14_out1'),pirTyp6,slRate1);
    LogicalOperator4_out1_s93=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp6,slRate1);
    LogicalOperator5_out1_s94=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp6,slRate1);
    LogicalOperator6_out1_s95=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp6,slRate1);
    LogicalOperator7_out1_s96=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp6,slRate1);
    Switch12_out1_s97=addSignal(hN,'Switch12_out1',pirTyp7,slRate1);
    Switch13_out1_s98=addSignal(hN,'Switch13_out1',pirTyp7,slRate1);
    Switch15_out1_s99=addSignal(hN,'Switch15_out1',pirTyp7,slRate1);
    Switch16_out1_s100=addSignal(hN,'Switch16_out1',pirTyp7,slRate1);
    Switch18_out1_s101=addSignal(hN,'Switch18_out1',pirTyp7,slRate1);
    Switch20_out1_s102=addSignal(hN,'Switch20_out1',pirTyp7,slRate1);
    Switch21_out1_s103=addSignal(hN,'Switch21_out1',pirTyp7,slRate1);
    BitSlice1_out1_s104=addSignal(hN,'Bit Slice1_out1',pirTyp1,slRate1);
    BitSlice2_out1_s105=addSignal(hN,'Bit Slice2_out1',pirTyp1,slRate1);
    BitSlice3_out1_s106=addSignal(hN,'Bit Slice3_out1',pirTyp1,slRate1);
    BitSlice4_out1_s107=addSignal(hN,'Bit Slice4_out1',pirTyp1,slRate1);
    BitSlice5_out1_s108=addSignal(hN,'Bit Slice5_out1',pirTyp1,slRate1);
    BitSlice6_out1_s109=addSignal(hN,'Bit Slice6_out1',pirTyp1,slRate1);
    BitSlice7_out1_s110=addSignal(hN,'Bit Slice7_out1',pirTyp1,slRate1);
    BitSlice8_out1_s111=addSignal(hN,'Bit Slice8_out1',pirTyp1,slRate1);
    Constant1_out1_s112=addSignal(hN,'Constant1_out1',pirTyp7,slRate1);
    Constant2_out1_s113=addSignal(hN,'Constant2_out1',pirTyp7,slRate1);
    Constant3_out1_s114=addSignal(hN,'Constant3_out1',pirTyp7,slRate1);
    Constant4_out1_s115=addSignal(hN,'Constant4_out1',pirTyp7,slRate1);
    Constant5_out1_s116=addSignal(hN,'Constant5_out1',pirTyp7,slRate1);
    Constant6_out1_s117=addSignal(hN,'Constant6_out1',pirTyp7,slRate1);
    Constant7_out1_s118=addSignal(hN,'Constant7_out1',pirTyp7,slRate1);
    Constant8_out1_s119=addSignal(hN,'Constant8_out1',pirTyp7,slRate1);
    LogicalOperator_out1_s120=addSignal(hN,sprintf('Logical\nOperator_out1'),pirTyp6,slRate1);
    LogicalOperator1_out1_s121=addSignal(hN,sprintf('Logical\nOperator1_out1'),pirTyp6,slRate1);
    LogicalOperator2_out1_s122=addSignal(hN,sprintf('Logical\nOperator2_out1'),pirTyp6,slRate1);
    LogicalOperator3_out1_s123=addSignal(hN,sprintf('Logical\nOperator3_out1'),pirTyp6,slRate1);
    Switch1_out1_s124=addSignal(hN,'Switch1_out1',pirTyp7,slRate1);
    Switch10_out1_s125=addSignal(hN,'Switch10_out1',pirTyp7,slRate1);
    Switch2_out1_s126=addSignal(hN,'Switch2_out1',pirTyp7,slRate1);
    Switch3_out1_s127=addSignal(hN,'Switch3_out1',pirTyp7,slRate1);
    Switch4_out1_s128=addSignal(hN,'Switch4_out1',pirTyp7,slRate1);
    Switch6_out1_s129=addSignal(hN,'Switch6_out1',pirTyp7,slRate1);
    Switch8_out1_s130=addSignal(hN,'Switch8_out1',pirTyp7,slRate1);
    Switch9_out1_s131=addSignal(hN,'Switch9_out1',pirTyp7,slRate1);
    BitSlice10_out1_s132=addSignal(hN,'Bit Slice10_out1',pirTyp1,slRate1);
    BitSlice11_out1_s133=addSignal(hN,'Bit Slice11_out1',pirTyp1,slRate1);
    BitSlice12_out1_s134=addSignal(hN,'Bit Slice12_out1',pirTyp1,slRate1);
    BitSlice13_out1_s135=addSignal(hN,'Bit Slice13_out1',pirTyp1,slRate1);
    BitSlice14_out1_s136=addSignal(hN,'Bit Slice14_out1',pirTyp1,slRate1);
    BitSlice15_out1_s137=addSignal(hN,'Bit Slice15_out1',pirTyp1,slRate1);
    BitSlice16_out1_s138=addSignal(hN,'Bit Slice16_out1',pirTyp1,slRate1);
    BitSlice9_out1_s139=addSignal(hN,'Bit Slice9_out1',pirTyp1,slRate1);
    Constant10_out1_s140=addSignal(hN,'Constant10_out1',pirTyp7,slRate1);
    Constant11_out1_s141=addSignal(hN,'Constant11_out1',pirTyp7,slRate1);
    Constant12_out1_s142=addSignal(hN,'Constant12_out1',pirTyp7,slRate1);
    Constant13_out1_s143=addSignal(hN,'Constant13_out1',pirTyp7,slRate1);
    Constant14_out1_s144=addSignal(hN,'Constant14_out1',pirTyp7,slRate1);
    Constant15_out1_s145=addSignal(hN,'Constant15_out1',pirTyp7,slRate1);
    Constant16_out1_s146=addSignal(hN,'Constant16_out1',pirTyp7,slRate1);
    Constant9_out1_s147=addSignal(hN,'Constant9_out1',pirTyp7,slRate1);
    LogicalOperator12_out1_s148=addSignal(hN,sprintf('Logical\nOperator12_out1'),pirTyp6,slRate1);
    LogicalOperator13_out1_s149=addSignal(hN,sprintf('Logical\nOperator13_out1'),pirTyp6,slRate1);
    LogicalOperator14_out1_s150=addSignal(hN,sprintf('Logical\nOperator14_out1'),pirTyp6,slRate1);
    LogicalOperator4_out1_s151=addSignal(hN,sprintf('Logical\nOperator4_out1'),pirTyp6,slRate1);
    LogicalOperator5_out1_s152=addSignal(hN,sprintf('Logical\nOperator5_out1'),pirTyp6,slRate1);
    LogicalOperator6_out1_s153=addSignal(hN,sprintf('Logical\nOperator6_out1'),pirTyp6,slRate1);
    LogicalOperator7_out1_s154=addSignal(hN,sprintf('Logical\nOperator7_out1'),pirTyp6,slRate1);
    Switch12_out1_s155=addSignal(hN,'Switch12_out1',pirTyp7,slRate1);
    Switch13_out1_s156=addSignal(hN,'Switch13_out1',pirTyp7,slRate1);
    Switch15_out1_s157=addSignal(hN,'Switch15_out1',pirTyp7,slRate1);
    Switch16_out1_s158=addSignal(hN,'Switch16_out1',pirTyp7,slRate1);
    Switch18_out1_s159=addSignal(hN,'Switch18_out1',pirTyp7,slRate1);
    Switch20_out1_s160=addSignal(hN,'Switch20_out1',pirTyp7,slRate1);
    Switch21_out1_s161=addSignal(hN,'Switch21_out1',pirTyp7,slRate1);


    pirelab.getConstComp(hN,...
    Constant10_out1_s82,...
    fi(0,nt1,fiMath1,'hex','0f'),...
    'Constant10','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant11_out1_s83,...
    fi(0,nt1,fiMath1,'hex','0e'),...
    'Constant11','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant12_out1_s84,...
    fi(0,nt1,fiMath1,'hex','0d'),...
    'Constant12','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant13_out1_s85,...
    fi(0,nt1,fiMath1,'hex','0c'),...
    'Constant13','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant14_out1_s86,...
    fi(0,nt1,fiMath1,'hex','0b'),...
    'Constant14','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant15_out1_s87,...
    fi(0,nt1,fiMath1,'hex','0a'),...
    'Constant15','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant16_out1_s88,...
    fi(0,nt1,fiMath1,'hex','09'),...
    'Constant16','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant9_out1_s89,...
    fi(0,nt1,fiMath1,'hex','10'),...
    'Constant9','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant1_out1_s112,...
    fi(0,nt1,fiMath1,'hex','18'),...
    'Constant1','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant2_out1_s113,...
    fi(0,nt1,fiMath1,'hex','17'),...
    'Constant2','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant3_out1_s114,...
    fi(0,nt1,fiMath1,'hex','16'),...
    'Constant3','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant4_out1_s115,...
    fi(0,nt1,fiMath1,'hex','15'),...
    'Constant4','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant5_out1_s116,...
    fi(0,nt1,fiMath1,'hex','14'),...
    'Constant5','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant6_out1_s117,...
    fi(0,nt1,fiMath1,'hex','13'),...
    'Constant6','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant7_out1_s118,...
    fi(0,nt1,fiMath1,'hex','12'),...
    'Constant7','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant8_out1_s119,...
    fi(0,nt1,fiMath1,'hex','11'),...
    'Constant8','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant10_out1_s140,...
    fi(0,nt1,fiMath1,'hex','07'),...
    'Constant10','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant11_out1_s141,...
    fi(0,nt1,fiMath1,'hex','06'),...
    'Constant11','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant12_out1_s142,...
    fi(0,nt1,fiMath1,'hex','05'),...
    'Constant12','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant13_out1_s143,...
    fi(0,nt1,fiMath1,'hex','04'),...
    'Constant13','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant14_out1_s144,...
    fi(0,nt1,fiMath1,'hex','03'),...
    'Constant14','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant15_out1_s145,...
    fi(0,nt1,fiMath1,'hex','02'),...
    'Constant15','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant16_out1_s146,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant16','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant9_out1_s147,...
    fi(0,nt1,fiMath1,'hex','08'),...
    'Constant9','on',0,'','','');


    pirelab.getConstComp(hN,...
    Constant_out1_s66,...
    fi(0,nt1,fiMath1,'hex','00'),...
    'Constant','on',1,'','','');

    pirelab.getWireComp(hN,...
    Switch13_out1_s98,...
    Middle8Bits_out1_s67,...
    'Middle 8 bits_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator12_out1_s90,...
    Middle8Bits_out2_s68,...
    'Middle 8 bits_out2');

    pirelab.getWireComp(hN,...
    Switch10_out1_s125,...
    Top8Bits_out1_s71,...
    'Top 8 bits_out1');

    pirelab.getWireComp(hN,...
    Switch13_out1_s156,...
    lower8Bits_out1_s72,...
    'lower 8 bits_out1');

    pirelab.getWireComp(hN,...
    LogicalOperator12_out1_s148,...
    lower8Bits_out2_s73,...
    'lower 8 bits_out2');

    hRefN=p.findNetwork('fullname','Single_Ceil_Scalar/NFP_Mathworks_Ceil_Single/initCycles');
    initCycles=hN.addComponent('ntwk_instance_comp',hRefN);
    initCycles.Name='initCycles';
    pirelab.connectNtwkInstComp(initCycles,...
    [Delay14_PS_4_out1_s15,Switch4_out1_s40,Switch3_out1_s39],...
    [initCycles_out1_s44,initCycles_out2_s45,initCycles_out3_s46]);


    pirelab.getConstComp(hN,...
    Constant136_out1_s9,...
    fi(0,nt2,fiMath1,'hex','000000'),...
    'Constant136','off',1,'','','');




    pirelab.getConstComp(hN,...
    Constant77_out1_s10,...
    fi(0,nt3,fiMath1,'hex','1'),...
    'Constant77','off',0,'','','');




    pirelab.getIntDelayComp(hN,...
    Delay2_PS_2_3_out1_s17,...
    Delay10_PS_4_out1_s11,...
    pipestage(4),'Delay10_PS_4',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    tempExpAndMant_out1_s60,...
    Delay11_PS_4_out1_s12,...
    pipestage(4),'Delay11_PS_4',...
    fi(0,nt4,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    LogicalOperator_out1_s33,...
    Delay12_PS_4_out1_s13,...
    pipestage(4),'Delay12_PS_4',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay8_PS_2_3_out1_s26,...
    Delay13_PS_4_out1_s14,...
    pipestage(4),'Delay13_PS_4',...
    fi(0,nt2,fiMath1,'hex','000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay_PS_3_out1_s28,...
    Delay14_PS_4_out1_s15,...
    pipestage(4),'Delay14_PS_4',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    aExponent_s1,...
    Delay2_PS_1_out1_s16,...
    pipestage(1),'Delay2_PS_1',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay2_PS_1_out1_s16,...
    Delay2_PS_2_3_out1_s17,...
    sum(pipestage(2:3)),'Delay2_PS_2_3',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    aMantissa_s2,...
    Delay3_PS_1_out1_s18,...
    pipestage(1),'Delay3_PS_1',...
    fi(0,nt2,fiMath1,'hex','000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Switch_out1_s36,...
    Delay3_PS_3_4_out1_s19,...
    sum(pipestage(3:4)),'Delay3_PS_3_4',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    FindFirst1PosFromLSB_out1_s32,...
    Delay4_PS_2_out1_s20,...
    pipestage(2),'Delay4_PS_2',...
    fi(0,nt1,fiMath1,'hex','00'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    isInputInteger_out1_s51,...
    Delay4_PS_2_4_out1_s21,...
    sum(pipestage(2:4)),'Delay4_PS_2_4',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    shiftlength_out1_s59,...
    Delay5_PS_2_out1_s22,...
    pipestage(2),'Delay5_PS_2',...
    fi(0,nt5,fiMath1,'hex','000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    isPosLtShiftlength_out1_s55,...
    Delay5_PS_3_out1_s23,...
    pipestage(3),'Delay5_PS_3',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay7_PS_3_out1_s25,...
    Delay6_PS_4_out1_s24,...
    pipestage(4),'Delay6_PS_4',...
    fi(0,nt4,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    ShiftBinaryPoint_out1_s35,...
    Delay7_PS_3_out1_s25,...
    pipestage(3),'Delay7_PS_3',...
    fi(0,nt4,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay3_PS_1_out1_s18,...
    Delay8_PS_2_3_out1_s26,...
    sum(pipestage(2:3)),'Delay8_PS_2_3',...
    fi(0,nt2,fiMath1,'hex','000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    aSign_s0,...
    Delay_PS_1_2_out1_s27,...
    sum(pipestage(1:2)),'Delay_PS_1_2',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(hN,...
    Delay_PS_1_2_out1_s27,...
    Delay_PS_3_out1_s28,...
    pipestage(3),'Delay_PS_3',...
    fi(0,nt3,fiMath1,'hex','0'),...
    0,0,[],0,0);


    pirelab.getConstComp(hN,...
    Exponent0_out1_s29,...
    fi(0,nt6,fiMath1,'hex','00'),...
    'Exponent0','on',1,'','','');


    pirelab.getConstComp(hN,...
    Exponent127_out1_s30,...
    fi(0,nt6,fiMath1,'hex','7f'),...
    'Exponent127','on',0,'','','');


    pirelab.getConstComp(hN,...
    ExponentBias_out1_s31,...
    fi(0,nt6,fiMath1,'hex','7f'),...
    'ExponentBias','on',0,'','','');


    pirelab.getConstComp(hN,...
    constant_out1_s43,...
    fi(0,nt4,fiMath1,'hex','00000001'),...
    'constant','on',0,'','','');


    pirelab.getConstComp(hN,...
    initialBinaryPointPos_out1_s47,...
    fi(0,nt4,fiMath1,'hex','00000001'),...
    'initialBinaryPointPos','on',0,'','','');


    pirelab.getConstComp(hN,...
    mantissaFractionlength_out1_s57,...
    fi(0,nt6,fiMath1,'hex','17'),...
    'mantissaFractionlength','off',0,'','','');

    pirelab.getWireComp(hN,...
    Switch1_out1_s70,...
    FindFirst1PosFromLSB_out1_s32,...
    'FindFirst1PosFromLSB_out1');


    pirelab.getAddComp(hN,...
    [Delay7_PS_3_out1_s25,constant_out1_s43],...
    Add_out1_s3,...
    'Floor','Wrap','Add',pirTyp11,'+-');


    pirelab.getBitSliceComp(hN,...
    Switch1_out1_s37,...
    BitSlice1_out1_s4,...
    22,0,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    Switch1_out1_s37,...
    BitSlice2_out1_s5,...
    30,23,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    Add_out1_s3,...
    BitSlice3_out1_s6,...
    30,0,'Bit Slice3');


    pirelab.getBitSliceComp(hN,...
    tempExpAndMantInc_out1_s61,...
    BitSlice4_out1_s7,...
    30,0,'Bit Slice4');


    pirelab.getBitConcatComp(hN,...
    [Delay2_PS_2_3_out1_s17,Delay8_PS_2_3_out1_s26],...
    ConcatExpandMant_out1_s8,...
    'ConcatExpandMant');


    pirelab.getBitSliceComp(hN,...
    normalizedMantissa_out1_s58,...
    BitSlice2_out1_s63,...
    23,16,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    normalizedMantissa_out1_s58,...
    BitSlice8_out1_s64,...
    7,0,'Bit Slice8');


    pirelab.getBitSliceComp(hN,...
    normalizedMantissa_out1_s58,...
    BitSlice9_out1_s65,...
    15,8,'Bit Slice9');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice10_out1_s74,...
    6,6,'Bit Slice10');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice11_out1_s75,...
    5,5,'Bit Slice11');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice12_out1_s76,...
    4,4,'Bit Slice12');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice13_out1_s77,...
    3,3,'Bit Slice13');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice14_out1_s78,...
    2,2,'Bit Slice14');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice15_out1_s79,...
    1,1,'Bit Slice15');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice16_out1_s80,...
    0,0,'Bit Slice16');


    pirelab.getBitSliceComp(hN,...
    BitSlice9_out1_s65,...
    BitSlice9_out1_s81,...
    7,7,'Bit Slice9');


    pirelab.getLogicComp(hN,...
    [LogicalOperator6_out1_s95,LogicalOperator13_out1_s91],...
    LogicalOperator12_out1_s90,...
    'or',sprintf('Logical\nOperator12'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s93,LogicalOperator14_out1_s92],...
    LogicalOperator13_out1_s91,...
    'or',sprintf('Logical\nOperator13'));


    pirelab.getLogicComp(hN,...
    [BitSlice10_out1_s74,BitSlice9_out1_s81],...
    LogicalOperator14_out1_s92,...
    'or',sprintf('Logical\nOperator14'));


    pirelab.getLogicComp(hN,...
    [BitSlice12_out1_s76,BitSlice11_out1_s75],...
    LogicalOperator4_out1_s93,...
    'or',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [BitSlice16_out1_s80,BitSlice15_out1_s79],...
    LogicalOperator5_out1_s94,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator5_out1_s94,LogicalOperator7_out1_s96],...
    LogicalOperator6_out1_s95,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitSlice14_out1_s78,BitSlice13_out1_s77],...
    LogicalOperator7_out1_s96,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getSwitchComp(hN,...
    [Constant10_out1_s82,Constant9_out1_s89],...
    Switch12_out1_s97,...
    BitSlice10_out1_s74,'Switch12',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch21_out1_s103,Switch16_out1_s100],...
    Switch13_out1_s98,...
    LogicalOperator6_out1_s95,'Switch13',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant12_out1_s84,Constant11_out1_s83],...
    Switch15_out1_s99,...
    BitSlice12_out1_s76,'Switch15',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch15_out1_s99,Switch12_out1_s97],...
    Switch16_out1_s100,...
    LogicalOperator4_out1_s93,'Switch16',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant14_out1_s86,Constant13_out1_s85],...
    Switch18_out1_s101,...
    BitSlice14_out1_s78,'Switch18',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant16_out1_s88,Constant15_out1_s87],...
    Switch20_out1_s102,...
    BitSlice16_out1_s80,'Switch20',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch20_out1_s102,Switch18_out1_s101],...
    Switch21_out1_s103,...
    LogicalOperator5_out1_s94,'Switch21',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Middle8Bits_out1_s67,Top8Bits_out1_s71],...
    Switch_out1_s69,...
    Middle8Bits_out2_s68,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [lower8Bits_out1_s72,Switch_out1_s69],...
    Switch1_out1_s70,...
    lower8Bits_out2_s73,'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice1_out1_s104,...
    6,6,'Bit Slice1');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice2_out1_s105,...
    5,5,'Bit Slice2');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice3_out1_s106,...
    4,4,'Bit Slice3');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice4_out1_s107,...
    7,7,'Bit Slice4');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice5_out1_s108,...
    3,3,'Bit Slice5');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice6_out1_s109,...
    2,2,'Bit Slice6');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice7_out1_s110,...
    1,1,'Bit Slice7');


    pirelab.getBitSliceComp(hN,...
    BitSlice2_out1_s63,...
    BitSlice8_out1_s111,...
    0,0,'Bit Slice8');


    pirelab.getLogicComp(hN,...
    [BitSlice3_out1_s106,BitSlice2_out1_s105],...
    LogicalOperator_out1_s120,...
    'or',sprintf('Logical\nOperator'));


    pirelab.getLogicComp(hN,...
    [BitSlice8_out1_s111,BitSlice7_out1_s110],...
    LogicalOperator1_out1_s121,...
    'or',sprintf('Logical\nOperator1'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator1_out1_s121,LogicalOperator3_out1_s123],...
    LogicalOperator2_out1_s122,...
    'or',sprintf('Logical\nOperator2'));


    pirelab.getLogicComp(hN,...
    [BitSlice6_out1_s109,BitSlice5_out1_s108],...
    LogicalOperator3_out1_s123,...
    'or',sprintf('Logical\nOperator3'));


    pirelab.getSwitchComp(hN,...
    [Constant2_out1_s113,Switch2_out1_s126],...
    Switch1_out1_s124,...
    BitSlice1_out1_s104,'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch9_out1_s131,Switch4_out1_s128],...
    Switch10_out1_s125,...
    LogicalOperator2_out1_s122,'Switch10',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant1_out1_s112,Constant_out1_s66],...
    Switch2_out1_s126,...
    BitSlice4_out1_s107,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant4_out1_s115,Constant3_out1_s114],...
    Switch3_out1_s127,...
    BitSlice3_out1_s106,'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch3_out1_s127,Switch1_out1_s124],...
    Switch4_out1_s128,...
    LogicalOperator_out1_s120,'Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant6_out1_s117,Constant5_out1_s116],...
    Switch6_out1_s129,...
    BitSlice6_out1_s109,'Switch6',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant8_out1_s119,Constant7_out1_s118],...
    Switch8_out1_s130,...
    BitSlice8_out1_s111,'Switch8',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch8_out1_s130,Switch6_out1_s129],...
    Switch9_out1_s131,...
    LogicalOperator1_out1_s121,'Switch9',...
    '~=',0,'Floor','Wrap');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice10_out1_s132,...
    6,6,'Bit Slice10');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice11_out1_s133,...
    5,5,'Bit Slice11');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice12_out1_s134,...
    4,4,'Bit Slice12');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice13_out1_s135,...
    3,3,'Bit Slice13');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice14_out1_s136,...
    2,2,'Bit Slice14');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice15_out1_s137,...
    1,1,'Bit Slice15');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice16_out1_s138,...
    0,0,'Bit Slice16');


    pirelab.getBitSliceComp(hN,...
    BitSlice8_out1_s64,...
    BitSlice9_out1_s139,...
    7,7,'Bit Slice9');


    pirelab.getLogicComp(hN,...
    [LogicalOperator6_out1_s153,LogicalOperator13_out1_s149],...
    LogicalOperator12_out1_s148,...
    'or',sprintf('Logical\nOperator12'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator4_out1_s151,LogicalOperator14_out1_s150],...
    LogicalOperator13_out1_s149,...
    'or',sprintf('Logical\nOperator13'));


    pirelab.getLogicComp(hN,...
    [BitSlice10_out1_s132,BitSlice9_out1_s139],...
    LogicalOperator14_out1_s150,...
    'or',sprintf('Logical\nOperator14'));


    pirelab.getLogicComp(hN,...
    [BitSlice12_out1_s134,BitSlice11_out1_s133],...
    LogicalOperator4_out1_s151,...
    'or',sprintf('Logical\nOperator4'));


    pirelab.getLogicComp(hN,...
    [BitSlice16_out1_s138,BitSlice15_out1_s137],...
    LogicalOperator5_out1_s152,...
    'or',sprintf('Logical\nOperator5'));


    pirelab.getLogicComp(hN,...
    [LogicalOperator5_out1_s152,LogicalOperator7_out1_s154],...
    LogicalOperator6_out1_s153,...
    'or',sprintf('Logical\nOperator6'));


    pirelab.getLogicComp(hN,...
    [BitSlice14_out1_s136,BitSlice13_out1_s135],...
    LogicalOperator7_out1_s154,...
    'or',sprintf('Logical\nOperator7'));


    pirelab.getSwitchComp(hN,...
    [Constant10_out1_s140,Constant9_out1_s147],...
    Switch12_out1_s155,...
    BitSlice10_out1_s132,'Switch12',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch21_out1_s161,Switch16_out1_s158],...
    Switch13_out1_s156,...
    LogicalOperator6_out1_s153,'Switch13',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant12_out1_s142,Constant11_out1_s141],...
    Switch15_out1_s157,...
    BitSlice12_out1_s134,'Switch15',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch15_out1_s157,Switch12_out1_s155],...
    Switch16_out1_s158,...
    LogicalOperator4_out1_s151,'Switch16',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant14_out1_s144,Constant13_out1_s143],...
    Switch18_out1_s159,...
    BitSlice14_out1_s136,'Switch18',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant16_out1_s146,Constant15_out1_s145],...
    Switch20_out1_s160,...
    BitSlice16_out1_s138,'Switch20',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Switch20_out1_s160,Switch18_out1_s159],...
    Switch21_out1_s161,...
    LogicalOperator5_out1_s152,'Switch21',...
    '~=',0,'Floor','Wrap');




    pirelab.getLogicComp(hN,...
    [isInputPositive_out1_s52,Delay5_PS_3_out1_s23],...
    LogicalOperator_out1_s33,...
    'and',sprintf('Logical\nOperator'));


    pirelab.getBitwiseOpComp(hN,...
    BitSlice3_out1_s6,...
    Mask_out1_s34,...
    'NOT','Mask',0,...
    double(0),1);


    pirelab.getDynamicBitShiftComp(hN,...
    [initialBinaryPointPos_out1_s47,Delay5_PS_2_out1_s22],...
    ShiftBinaryPoint_out1_s35,...
    'left','shiftbinarypoint');


    pirelab.getSwitchComp(hN,...
    [Exponent0_out1_s29,Exponent127_out1_s30],...
    Switch_out1_s36,...
    isSignedness_out1_s56,'Switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [BitSlice4_out1_s7,Delay11_PS_4_out1_s12],...
    Switch1_out1_s37,...
    Delay12_PS_4_out1_s13,'Switch1',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Constant136_out1_s9,BitSlice1_out1_s4],...
    Switch2_out1_s38,...
    isExponentLt127_out1_s49,'Switch2',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Delay13_PS_4_out1_s14,Switch2_out1_s38],...
    Switch3_out1_s39,...
    Delay4_PS_2_4_out1_s21,'Switch3',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Delay10_PS_4_out1_s11,Switch5_out1_s41],...
    Switch4_out1_s40,...
    Delay4_PS_2_4_out1_s21,'Switch4',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(hN,...
    [Delay3_PS_3_4_out1_s19,BitSlice2_out1_s5],...
    Switch5_out1_s41,...
    isExponentLt127_out1_s49,'Switch5',...
    '~=',0,'Floor','Wrap');


    pirelab.getAddComp(hN,...
    [Delay2_PS_1_out1_s16,ExponentBias_out1_s31],...
    TrueExponent_out1_s42,...
    'Floor','Wrap','TrueExponent',pirTyp11,'+-');


    pirelab.getCompareToValueComp(hN,...
    Delay2_PS_1_out1_s16,...
    isExponentGt150_out1_s48,...
    '>=',fi(0,nt6,fiMath1,'hex','96'),...
    'isExponentGt150',0);


    pirelab.getCompareToValueComp(hN,...
    Delay10_PS_4_out1_s11,...
    isExponentLt127_out1_s49,...
    '<',fi(0,nt6,fiMath1,'hex','7f'),...
    'isExponentLt127',0);


    pirelab.getCompareToValueComp(hN,...
    Delay2_PS_1_out1_s16,...
    isExponentZero_out1_s50,...
    '==',double(0),...
    'isExponentZero',0);


    pirelab.getLogicComp(hN,...
    [isExponentGt150_out1_s48,isInputZero_out1_s53],...
    isInputInteger_out1_s51,...
    'or','isInputInteger');


    pirelab.getCompareToValueComp(hN,...
    Delay_PS_3_out1_s28,...
    isInputPositive_out1_s52,...
    '==',fi(0,nt3,fiMath1,'hex','0'),...
    'isInputPositive',1);


    pirelab.getLogicComp(hN,...
    [isExponentZero_out1_s50,isMantissaZero_out1_s54],...
    isInputZero_out1_s53,...
    'and','isInputZero');


    pirelab.getCompareToValueComp(hN,...
    Delay3_PS_1_out1_s18,...
    isMantissaZero_out1_s54,...
    '==',double(0),...
    'isMantissaZero',0);


    pirelab.getRelOpComp(hN,...
    [Delay4_PS_2_out1_s20,Delay5_PS_2_out1_s22],...
    isPosLtShiftlength_out1_s55,...
    '<=',0,'isPosLtShiftlength');


    pirelab.getCompareToValueComp(hN,...
    Delay_PS_1_2_out1_s27,...
    isSignedness_out1_s56,...
    '==',fi(0,nt3,fiMath1,'hex','1'),...
    'isSignedness',0);


    pirelab.getBitConcatComp(hN,...
    [Constant77_out1_s10,Delay3_PS_1_out1_s18],...
    normalizedMantissa_out1_s58,...
    'normalizedMantissa');


    pirelab.getAddComp(hN,...
    [mantissaFractionlength_out1_s57,TrueExponent_out1_s42],...
    shiftlength_out1_s59,...
    'Floor','Wrap','shiftlength',pirTyp11,'+-');


    pirelab.getBitwiseOpComp(hN,...
    [ConcatExpandMant_out1_s8,Mask_out1_s34],...
    tempExpAndMant_out1_s60,...
    'AND','tempExpAnd Mant',0,...
    double(0),1);


    pirelab.getAddComp(hN,...
    [Delay6_PS_4_out1_s24,Delay11_PS_4_out1_s12],...
    tempExpAndMantInc_out1_s61,...
    'Floor','Wrap','tempExpAndMantInc',pirTyp12,'++');


end

function hS=addSignal(hN,sigName,pirTyp,simulinkRate)
    hS=hN.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end
