function getSinglePackComp(hN,hInSignals,hOutSignals,compName)
    hNewC=hN.addComponent2('kind','cgireml',...
    'Name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'EMLFileName','nfp_pack32',...
    'EMLParams',{});
    hNewC.treatInputIntsAsFixpt(false);
    hNewC.treatInputBoolsAsUfix1(false);
    hNewC.saturateOnIntOverflow(false);
    hNewC.addComment('Combine FP sign, exponent, mantissa into 32 bit word');
end
