classdef AttenuatorDialog<handle






    properties
Parent
Panel
Layout
        Width=0
        Height=0
Listeners
    end

    properties(Dependent)
Name
Attenuation
Zin
Zout
    end

    properties(Access=private)
Title
NameLabel
NameEdit
AttenuationLabel
AttenuationEdit
AttenuationUnits
ZinLabel
ZinEdit
ZinUnits
ZoutLabel
ZoutEdit
ZoutUnits
ApplyLabel
        IsReturnKey=0
        NameChanged=0
        OtherPropertiesChanged=0
    end

    methods


        function self=AttenuatorDialog(parent)




            if nargin==0
                parent=figure;
            end
            self.Parent=parent;
            createUIControls(self)
            layoutUIControls(self)
            addListeners(self)
        end

        function setFigureKeyPress(self)





            if self.Parent.View.UseAppContainer
                set(self.Parent.View.ParametersFig.Figure,...
                'KeyPressFcn',@(h,e)FigKeyEventCanvas(self,e));
                self.Listeners.KeyPress=addlistener(...
                self.Parent.View.ParametersFig.Figure,...
                'WindowKeyPress',@(h,e)FigKeyEvent(self,e));
            else
                set(self.Parent.View.ParametersFig,...
                'KeyPressFcn',@(h,e)FigKeyEventCanvas(self,e));
                self.Listeners.KeyPress=addlistener(...
                self.Parent.View.ParametersFig,...
                'WindowKeyPress',@(h,e)FigKeyEvent(self,e));
            end
        end
    end

    methods


        function str=get.Name(self)
            if self.Parent.View.UseAppContainer
                str=self.NameEdit.Value;
            else
                str=self.NameEdit.String;
            end
        end

        function set.Name(self,str)
            if self.Parent.View.UseAppContainer
                self.NameEdit.Value=str;
            else
                self.NameEdit.String=str;
            end
        end

        function val=get.Attenuation(self)
            if self.Parent.View.UseAppContainer
                val=self.AttenuationEdit.Value;%#ok<*ST2NM>
            else
                val=str2num(self.AttenuationEdit.String);%#ok<*ST2NM>
            end
        end

        function set.Attenuation(self,val)
            if self.Parent.View.UseAppContainer
                self.AttenuationEdit.Value=val;
            else
                self.AttenuationEdit.String=num2str(val);
            end
        end

        function val=get.Zin(self)
            if self.Parent.View.UseAppContainer
                val=self.ZinEdit.Value;
            else
                val=str2num(self.ZinEdit.String);
            end
        end

        function set.Zin(self,val)
            if self.Parent.View.UseAppContainer
                self.ZinEdit.Value=val;
            else
                self.ZinEdit.String=num2str(val);
            end
        end

        function val=get.Zout(self)
            if self.Parent.View.UseAppContainer
                val=self.ZoutEdit.Value;
            else
                val=str2num(self.ZoutEdit.String);
            end
        end

        function set.Zout(self,val)
            if self.Parent.View.UseAppContainer
                self.ZoutEdit.Value=val;
            else
                self.ZoutEdit.String=num2str(val);
            end
        end

        function setListenersEnable(self,val)
            self.Listeners.Name.Enabled=val;
            self.Listeners.Attenuation.Enabled=val;
            self.Listeners.Zin.Enabled=val;
            self.Listeners.Zout.Enabled=val;
        end

        function resetDialogAccess(self)


            whiteColor=[1,1,1];
            self.NameEdit.BackgroundColor=whiteColor;
            self.AttenuationEdit.BackgroundColor=whiteColor;
            self.ZinEdit.BackgroundColor=whiteColor;
            self.ZoutEdit.BackgroundColor=whiteColor;
            self.OtherPropertiesChanged=0;
            self.NameChanged=0;
            self.ApplyLabel.Enable='off';
            self.Parent.View.setStatusBarMsg('');
        end

        function enableUIControls(self,val)




            if val==false
                val='off';
            elseif val==true
                val='on';
            end
            self.NameEdit.Enable=val;
            self.AttenuationEdit.Enable=val;
            self.ZinEdit.Enable=val;
            self.ZoutEdit.Enable=val;
            if strcmpi(val,'on')
                if self.OtherPropertiesChanged||...
                    self.NameChanged
                    self.ApplyLabel.Enable='on';
                else
                    self.ApplyLabel.Enable='off';
                end
            else
                self.ApplyLabel.Enable='off';
            end
        end
    end

    methods(Access=private)


        function createUIControls(self)


            userData=struct(...
            'Dialog','attenuator',...
            'Stage',self.Parent.SelectedStage);
            if self.Parent.View.UseAppContainer

                self.Layout=uigridlayout(...
                'Parent',self.Parent.View.ParametersFig.Figure,...
                'Scrollable','on',...
                'Tag','Layout',...
                'RowSpacing',3,...
                'ColumnSpacing',2,...
                'Visible','off');
                self.Title=uilabel(...
                'UserData',userData,...
                'Tag','TitleLabel',...
                'Parent',self.Layout,...
                'Text',' Attenuator Element',...
                'FontColor',[0,0,0],...
                'BackgroundColor',[.94,.94,.94],...
                'HorizontalAlignment','left');
                self.NameLabel=uilabel(...
                'UserData',userData,...
                'Tag','NameLabel',...
                'Parent',self.Layout,...
                'Text','Name',...
                'HorizontalAlignment','right');
                self.NameEdit=uieditfield(...
                'UserData',userData,...
                'Tag','NameEditField',...
                'Parent',self.Layout,...
                'Value','Attenuator',...
                'HorizontalAlignment','left');
                self.AttenuationLabel=uilabel(...
                'UserData',userData,...
                'Tag','AttenuationLabel',...
                'Parent',self.Layout,...
                'Text','Attenuation',...
                'HorizontalAlignment','right');
                self.AttenuationEdit=uieditfield(...
                'numeric',...
                'UserData',userData,...
                'Tag','AttenuationEditField',...
                'Parent',self.Layout,...
                'Value',0,...
                'HorizontalAlignment','left');
                self.AttenuationUnits=uilabel(...
                'UserData',userData,...
                'Tag','AttenuationUnitsLabel',...
                'Parent',self.Layout,...
                'Text','dB',...
                'HorizontalAlignment','left');
                self.ZinLabel=uilabel(...
                'UserData',userData,...
                'Tag','ZinLabel',...
                'Parent',self.Layout,...
                'Text','Input Impedance',...
                'HorizontalAlignment','right');
                self.ZinEdit=uieditfield(...
                'numeric',...
                'UserData',userData,...
                'Tag','ZinEditField',...
                'Parent',self.Layout,...
                'Value',50,...
                'Tag',...
                'Zin',...
                'HorizontalAlignment','left');
                self.ZinUnits=uilabel(...
                'UserData',userData,...
                'Tag','ZinUnitsLabel',...
                'Parent',self.Layout,...
                'Text','Ohm',...
                'HorizontalAlignment','left');
                self.ZoutLabel=uilabel(...
                'UserData',userData,...
                'Tag','ZoutLabel',...
                'Parent',self.Layout,...
                'Text','Output Impedance',...
                'HorizontalAlignment','right');
                self.ZoutEdit=uieditfield(...
                'numeric',...
                'UserData',userData,...
                'Tag','ZoutEditField',...
                'Parent',self.Layout,...
                'Value',50,...
                'Tag',...
                'Zout',...
                'HorizontalAlignment','left');
                self.ZoutUnits=uilabel(...
                'UserData',userData,...
                'Tag','ZoutUnitsLabel',...
                'Parent',self.Layout,...
                'Text','Ohm',...
                'HorizontalAlignment','left');
                self.ApplyLabel=uibutton(...
                'Tag','ApplyButton',...
                'Parent',self.Layout,...
                'Text','Apply',...
                'HorizontalAlignment','center',...
                'Tooltip','Apply parameters to selected Element (Enter)');

                for i=1:length(self.Layout.RowHeight)
                    self.Layout.RowHeight{i}=29;
                end
            else
                self.Panel=uipanel(...
                'Parent',self.Parent.View.ParametersFig,...
                'Title','',...
                'BorderType','line',...
                'HighlightColor',[.5,.5,.5],...
                'Visible','on');
                self.Title=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','TitleLabel',...
                'String',' Attenuator Element',...
                'ForegroundColor',[0,0,0],...
                'BackgroundColor',[.94,.94,.94],...
                'HorizontalAlignment','left');
                self.NameLabel=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','NameLabel',...
                'String','Name',...
                'HorizontalAlignment','right');
                self.NameEdit=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','edit',...
                'Tag','Name',...
                'String','Attenuator',...
                'HorizontalAlignment','left');
                self.AttenuationLabel=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','AttenuationLabel',...
                'String','Attenuation',...
                'HorizontalAlignment','right');
                self.AttenuationEdit=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','edit',...
                'Tag','Attenuation',...
                'String','0',...
                'HorizontalAlignment','left');
                self.AttenuationUnits=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','AttenuationUnitsLabel',...
                'String','dB',...
                'HorizontalAlignment','left');
                self.ZinLabel=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','ZinLabel',...
                'String','Input Impedance',...
                'HorizontalAlignment','right');
                self.ZinEdit=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','edit',...
                'Tag','Zin',...
                'String','50',...
                'Tag',...
                'Zin',...
                'HorizontalAlignment','left');
                self.ZinUnits=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','ZinUnitsLabel',...
                'String','Ohm',...
                'HorizontalAlignment','left');
                self.ZoutLabel=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','ZoutLabel',...
                'String','Output Impedance',...
                'HorizontalAlignment','right');
                self.ZoutEdit=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','edit',...
                'Tag','Zout',...
                'String','50',...
                'Tag',...
                'Zout',...
                'HorizontalAlignment','left');
                self.ZoutUnits=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','text',...
                'Tag','ZoutUnitsLabel',...
                'String','Ohm',...
                'HorizontalAlignment','left');
                self.ApplyLabel=uicontrol(...
                'UserData',userData,...
                'Parent',self.Panel,...
                'Style','pushbutton',...
                'String','Apply',...
                'Tag','ApplyTag',...
                'HorizontalAlignment','center',...
                'Tooltip','Apply parameters to selected Element (Enter)');
            end
        end


        function layoutUIControls(self)


            hspacing=3;
            vspacing=4;
            w1=rf.internal.apps.budget.SystemParametersSection.Width1;
            w2=rf.internal.apps.budget.SystemParametersSection.Width2;
            w3=rf.internal.apps.budget.SystemParametersSection.Width3;
            titleHt=16;
            if self.Parent.View.UseAppContainer
            else
                self.Layout=...
                matlabshared.application.layout.GridBagLayout(...
                self.Panel,...
                'VerticalGap',vspacing,...
                'HorizontalGap',hspacing,...
                'VerticalWeights',[0,0,0,0,0,0,1],...
                'HorizontalWeights',[0,1,0]);
            end
            row=1;
            self.Parent.addTitle(self.Layout,self.Title,row,[1,3],...
            titleHt,hspacing,vspacing,self.Parent.View.UseAppContainer)
            h=24;
            row=row+1;
            self.Parent.addText(self.Layout,self.NameLabel,row,1,w1,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addEdit(self.Layout,self.NameEdit,row,2,w2,...
            h,self.Parent.View.UseAppContainer)
            row=row+1;
            self.Parent.addText(self.Layout,self.AttenuationLabel,row,1,w1,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addEdit(self.Layout,self.AttenuationEdit,row,2,w2,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addText(self.Layout,self.AttenuationUnits,row,3,w3,...
            h,self.Parent.View.UseAppContainer)
            row=row+1;
            self.Parent.addText(self.Layout,self.ZinLabel,row,1,w1,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addEdit(self.Layout,self.ZinEdit,row,2,w2,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addText(self.Layout,self.ZinUnits,row,3,w3,...
            h,self.Parent.View.UseAppContainer)
            row=row+1;
            self.Parent.addText(self.Layout,self.ZoutLabel,row,1,w1,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addEdit(self.Layout,self.ZoutEdit,row,2,w2,...
            h,self.Parent.View.UseAppContainer)
            self.Parent.addText(self.Layout,self.ZoutUnits,row,3,w3,...
            h,self.Parent.View.UseAppContainer)
            row=row+1;
            self.Parent.addText(self.Layout,self.ApplyLabel,row,2,w3,h+10,...
            self.Parent.View.UseAppContainer)

            if self.Parent.View.UseAppContainer
                w=500;
                h=500;
                self.Layout.Visible='on';
            else
                [~,~,w,h]=getMinimumSize(self.Layout);
                self.Width=sum(w)+self.Layout.HorizontalGap*(numel(w)+1);
                self.Height=max(h(2:end-1))*numel(h(2:end))+...
                self.Layout.VerticalGap*(numel(h(2:end-1))+1)+(titleHt+2)+10;
            end
        end

        function parameterChanged(self,e)


            i=self.Parent.View.Canvas.SelectIdx;
            if strcmpi(e.EventName,'PostSet')||...
                strcmpi(e.EventName,'ValueChanged')||...
                strcmpi(e.EventName,'ButtonPushed')

                if self.Parent.View.UseAppContainer
                    name=e.Source.Tag;
                    uiObject=e.Source;
                    uiObjectType=class(uiObject);
                else
                    name=e.AffectedObject.Tag;
                    uiObject=e.AffectedObject;
                    uiObjectType=uiObject.Style;
                end
                key='';
            elseif strcmpi(e.EventName,'KeyPress')

                name=e.Source.Tag;
                uiObject=e.Source;
                uiObjectType=uiObject.Style;
                a=get(self.Parent.View.ParametersFig,'CurrentCharacter');
                if isempty(a)


                    return;
                end
                key=e.Key;
                if any(strcmpi(key,{'leftarrow',...
                    'uparrow',...
                    'downarrow',...
                    'rightarrow'}))

                    return;
                end
            end
            drawnow;

            applyflag=1;
            valueChangedColor=[1,0.96,0.88];
            if~strcmpi(name,'ApplyButton')||~strcmpi(name,'ApplyTag')
                if~any(strcmpi(uiObjectType,{'popupmenu','matlab.ui.control.DropDown'}))
                    if~strcmpi(key,'return')



                        if strcmpi(name,'NameEditField')||strcmpi(name,'Name')
                            self.NameChanged=1;
                        elseif~strcmpi(name,'ApplyButton')||~strcmpi(name,'ApplyTag')
                            self.OtherPropertiesChanged=1;
                        end
                    end
                end
            end
            if~strcmpi(key,'return')


                switch name
                case{'NameEditField','Name'}
                    self.NameEdit.BackgroundColor=valueChangedColor;
                case{'AttenuationEditField','Attenuation'}
                    self.AttenuationEdit.BackgroundColor=valueChangedColor;
                case{'ZinEditField','Zin'}
                    self.ZinEdit.BackgroundColor=valueChangedColor;
                case{'ZoutEditField','Zout'}
                    self.ZoutEdit.BackgroundColor=valueChangedColor;
                case{'ApplyButton','ApplyTag'}
                    try
                        applyflag=0;
                        applyFunction(self);
                    catch me
                        h=errordlg(me.message,'Error Dialog','modal');
                        uiwait(h)
                        self.Parent.View.enableActions(true);
                    end
                end
            end
            if self.IsReturnKey
                try
                    applyflag=0;
                    self.applyFunction();
                catch me
                    h=errordlg(me.message,'Error Dialog','modal');
                    uiwait(h)
                    self.Parent.View.enableActions(true);
                end
            end
            self.IsReturnKey=0;
            if applyflag
                self.ApplyLabel.Enable='on';
                self.Parent.View.setStatusBarMsg(...
                'Click ''Apply'' or hit ''Enter'' to update Attenuator parameters.');
                if self.Parent.View.UseAppContainer
                    self.Parent.notify('DisableCanvas',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyButton','off'));
                else
                    self.Parent.notify('DisableCanvas',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyTag','off'));
                end
            end
        end

        function applyFunction(self)


            if self.Parent.View.UseAppContainer
                valueString='Value';
            else
                valueString='String';
            end
            if~self.NameChanged&&~self.OtherPropertiesChanged

                self.IsReturnKey=0;
                i=self.Parent.View.Canvas.SelectIdx;
                if self.Parent.View.UseAppContainer
                    self.Parent.notify('DisableCanvas',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyButton','inactive'));
                else
                    self.Parent.notify('DisableCanvas',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyTag','inactive'));
                end
                return;
            end
            self.Parent.View.enableActions(false);
            i=self.Parent.View.Canvas.SelectIdx;
            Attenuatorobj=self.simrfV2_attenuator_design();
            if self.Parent.View.UseAppContainer
                self.Parent.notify('DisableCanvas',...
                rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                'ApplyButton','inactive'));
            else
                self.Parent.notify('DisableCanvas',...
                rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                'ApplyTag','inactive'));
            end
            if self.NameChanged&&~self.OtherPropertiesChanged

                self.Parent.notify('ElementParameterChanged',...
                rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                'Name',self.NameEdit.(valueString)));
            else


                if self.Parent.View.UseAppContainer
                    self.Parent.notify('ElementParameterChanged',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyButton',Attenuatorobj));
                else
                    self.Parent.notify('ElementParameterChanged',...
                    rf.internal.apps.budget.ElementParameterChangedEventData(i,...
                    'ApplyTag',Attenuatorobj));
                end
            end
            whiteColor=[1,1,1];
            self.NameEdit.BackgroundColor=whiteColor;
            self.AttenuationEdit.BackgroundColor=whiteColor;
            self.ZinEdit.BackgroundColor=whiteColor;
            self.ZoutEdit.BackgroundColor=whiteColor;
            self.ApplyLabel.Enable='off';
            self.Parent.View.setStatusBarMsg('');
            enableIP2(self.Parent.View.Toolstrip,false);
            self.NameChanged=0;
            self.OtherPropertiesChanged=0;
            self.IsReturnKey=0;
            self.Parent.View.enableActions(true);
        end

        function FigKeyEvent(self,ev)

            if isa(self.Parent.ElementDialog,'rf.internal.apps.budget.AttenuatorDialog')
                key=ev.Key;
                switch key
                case 'return'
                    self.IsReturnKey=1;
                end
            end
        end

        function FigKeyEventCanvas(self,ev)



            if isa(self.Parent.ElementDialog,'rf.internal.apps.budget.AttenuatorDialog')
                key=ev.Key;
                switch key
                case 'return'
                    try
                        self.applyFunction();
                    catch me
                        h=errordlg(me.message,'Error Dialog','modal');
                        uiwait(h)
                        self.Parent.View.enableActions(true);
                    end
                end
            end
        end


        function addListeners(self)


            if self.Parent.View.UseAppContainer
                self.NameEdit.ValueChangedFcn=@(h,e)parameterChanged(self,e);
                self.AttenuationEdit.ValueChangedFcn=@(h,e)parameterChanged(self,e);
                self.ZinEdit.ValueChangedFcn=@(h,e)parameterChanged(self,e);
                self.ZoutEdit.ValueChangedFcn=@(h,e)parameterChanged(self,e);
                self.ApplyLabel.ButtonPushedFcn=@(h,e)parameterChanged(self,e);
            else
                self.NameEdit.KeyPressFcn=@(h,e)parameterChanged(self,e);
                self.AttenuationEdit.KeyPressFcn=@(h,e)parameterChanged(self,e);
                self.ZinEdit.KeyPressFcn=@(h,e)parameterChanged(self,e);
                self.ZoutEdit.KeyPressFcn=@(h,e)parameterChanged(self,e);
                self.Listeners.Apply=addlistener(self.ApplyLabel,...
                'Value',...
                'PostSet',@(h,e)parameterChanged(self,e));
            end
        end

        function Attenuatorobj=simrfV2_attenuator_design(self)
            Attenuatorobj=attenuator(...
            'Name',self.Name,...
            'Attenuation',self.Attenuation,...
            'Zin',self.Zin,...
            'Zout',self.Zout);
        end
    end
end




