function cssFile=generateStylesheet(profile)

    profileName=profile.getName;
    cssFile=[profileName,'.css'];

    css=sprintf("/* STYLESHEET FOR %s */\n/* Autogenerated on %s */\n\n",...
    profile.friendlyName,datestr(now));

    prototypes=profile.prototypes.toArray;
    for idx=1:length(prototypes)
        p=prototypes(idx);
        if p.abstract
            continue;
        end
        name=p.fullyQualifiedName;
        name=strrep(name,'.','-');
        css=css+"."+name+sprintf(" {\n%s\n}\n\n",getTempRule(idx));
    end

    fid=fopen(cssFile,'w');
    fprintf(fid,css);
    fclose(fid);

    profile.stylesheet=cssFile;

    fprintf('Generated profile stylesheet template: %s\n',cssFile);

    function rule=getTempRule(idx)

        colorPairs={...
        'darkblue','mediumblue';...
        'skyblue','lightskyblue';...
        'sandybrown','wheat';...
        };
        numColors=size(colorPairs,1);
        idx=mod(idx,numColors)+1;

        color1=colorPairs{idx,1};
        color2=colorPairs{idx,2};

        rule=sprintf('    border-color: %s;\n    background: linear-gradient(to top, %s, %s);',...
        color1,color1,color2);

