function sl_postprocess(h)














    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transmission Line'),...
    sprintf('ee_lib/Passive/Lines/Transmission Line (Three-Phase)')});


    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Ideal Rectifier'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value Rectifier (Three-Phase)')});


    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Diode'),...
    sprintf('ee_lib/Semiconductors & Converters/Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Diode (Piecewise Linear)'),...
    sprintf('ee_lib/Semiconductors & Converters/Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Thyristor'),...
    sprintf('ee_lib/Semiconductors & Converters/Thyristor (Piecewise Linear)')});


    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Current Source'),...
    sprintf('ee_lib/Sources/Current Source (Three-Phase)')});
    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Voltage Source'),...
    sprintf('ee_lib/Sources/Voltage Source (Three-Phase)')});


    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Stepper Motor and Driver/Stepper Motor'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Eddy Current'),...
    sprintf('ee_lib/Passive/Eddy Current')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Nonlinear Inductor'),...
    sprintf('ee_lib/Passive/Nonlinear Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Nonlinear Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Nonlinear Transformer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Reluctance with Hysteresis'),...
    sprintf('ee_lib/Passive/Reluctance with Hysteresis')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Varistor'),...
    sprintf('ee_lib/Passive/Varistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Resolver'),...
    sprintf('ee_lib/Sensors & Transducers/Resolver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Battery (Table-Based)'),...
    sprintf('ee_lib/Sources/Battery (Table-Based)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Incremental Shaft Encoder'),...
    sprintf('ee_lib/Sensors & Transducers/Incremental Shaft Encoder')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Battery'),...
    sprintf('ee_lib/Sources/Battery')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Delta Reference'),...
    sprintf('ee_lib/Connectors & References/Delta Reference (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Floating Neutral'),...
    sprintf('ee_lib/Connectors & References/Floating Neutral (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Grounded Neutral'),...
    sprintf('ee_lib/Connectors & References/Grounded Neutral (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Neutral Port'),...
    sprintf('ee_lib/Connectors & References/Neutral Port (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Open Circuit'),...
    sprintf('ee_lib/Connectors & References/Open Circuit (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Phase Permute'),...
    sprintf('ee_lib/Connectors & References/Phase Permute')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Connections/Phase Splitter'),...
    sprintf('ee_lib/Connectors & References/Phase Splitter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine Measurement'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine Measurement')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Machine Inertia'),...
    sprintf('ee_lib/Electromechanical/Mechanical/Machine Inertia')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Machine Mechanical Power (pu)'),...
    sprintf('ee_lib/Electromechanical/Mechanical/Machine Mechanical Power')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Machine Mechanical Power (SI)'),...
    sprintf('ee_lib/Electromechanical/Mechanical/Machine Mechanical Power')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine Field Circuit (pu)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Field Circuit')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine Field Circuit (SI)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Field Circuit')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine Measurement'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Measurement')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Single Phase)/Single-Phase Asynchronous Machine (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine (Single-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Single Phase)/Single-Phase Asynchronous Machine (fundamental, SI)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine (Single-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Squirrel Cage)/Asynchronous Machine Squirrel Cage (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine Squirrel Cage')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Squirrel Cage)/Asynchronous Machine Squirrel Cage (fundamental, SI)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine Squirrel Cage')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Wound Rotor)/Asynchronous Machine Wound Rotor (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine Wound Rotor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Asynchronous Machine (Wound Rotor)/Asynchronous Machine Wound Rotor (fundamental, SI)'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Induction Machine Wound Rotor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Permanent Magnet Rotor/Brushless DC Motor'),...
    sprintf('ee_lib/Electromechanical/Permanent Magnet/BLDC')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Permanent Magnet Rotor/Hybrid Excitation Synchronous Machine'),...
    sprintf('ee_lib/Electromechanical/Permanent Magnet/Hybrid Excitation PMSM')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Permanent Magnet Rotor/Permanent Magnet Synchronous Motor'),...
    sprintf('ee_lib/Electromechanical/Permanent Magnet/PMSM')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Permanent Magnet Rotor/Single-Phase Permanent Magnet Synchronous Motor'),...
    sprintf('ee_lib/Electromechanical/Permanent Magnet/PMSM (Single-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Reluctance/Switched Reluctance Machine'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Switched Reluctance Machine')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Reluctance/Five-Phase Switched Reluctance Machine'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Switched Reluctance Machine (Multi-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Reluctance/Four-Phase Switched Reluctance Machine'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Switched Reluctance Machine (Multi-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Reluctance/Synchronous Reluctance Machine'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Synchronous Reluctance Machine')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Round Rotor)/Synchronous Machine Round Rotor (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Round Rotor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Round Rotor)/Synchronous Machine Round Rotor (standard)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Round Rotor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Salient Pole)/Synchronous Machine Salient Pole (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Salient Pole')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Salient Pole)/Synchronous Machine Salient Pole (standard)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Salient Pole')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Simplified)/Synchronous Machine Model 1.0 (SI parameters)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Model 1.0')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Simplified)/Synchronous Machine Model 2.1 (fundamental)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Model 2.1')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Synchronous Machine (Simplified)/Synchronous Machine Model 2.1 (standard)'),...
    sprintf('ee_lib/Electromechanical/Synchronous/Synchronous Machine Model 2.1')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Machines/Stepper Motor and Driver/Stepper Motor Driver'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/AC Cable'),...
    sprintf('ee_lib/Passive/Lines/AC Cable (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Coupled Lines'),...
    sprintf('ee_lib/Passive/Lines/Coupled Lines (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Delta-Connected Load'),...
    sprintf('ee_lib/Passive/RLC Assemblies/Delta-Connected Load')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Faults/Enabled Fault'),...
    sprintf('pe_lib/Deprecated/Enabled Fault')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Faults/Time-Based Fault'),...
    sprintf('pe_lib/Deprecated/Time-Based Fault')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Coupled Lines (Pair)'),...
    sprintf('ee_lib/Passive/Lines/Coupled Lines (Pair)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Fundamental Components/Tap-Changing Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Tap-Changing Transformer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/RLC'),...
    sprintf('ee_lib/Passive/RLC Assemblies/RLC (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Time Varying/Wye-Connected Variable Load'),...
    sprintf('ee_lib/Passive/RLC Assemblies/Wye-Connected Variable Load')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Time Varying/Wye-Connected Variable Load (lagging)'),...
    sprintf('ee_lib/Passive/RLC Assemblies/Wye-Connected Variable Load (lagging)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Delta-Delta Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Two-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Wye-Delta1 Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Two-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Wye-Delta11 Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Two-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Wye-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Two-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Delta11-Delta11-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Three-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Delta1-Delta1-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Three-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Wye-Delta11-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Three-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Wye-Delta1-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Three-Winding Transformer (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Zigzag-Delta11-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Zigzag-Delta-Wye Transformer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Zigzag-Delta1-Wye Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Zigzag-Delta-Wye Transformer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Fundamental Components/Primary Winding'),...
    sprintf('pe_lib/Deprecated/Primary Winding')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Fundamental Components/Secondary Winding'),...
    sprintf('pe_lib/Deprecated/Secondary Winding')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transformers/Fundamental Components/Winding'),...
    sprintf('ee_lib/Passive/Winding')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Transmission Line (Three-Phase)'),...
    sprintf('ee_lib/Passive/Lines/Transmission Line (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Passive Devices/Wye-Connected Load'),...
    sprintf('ee_lib/Passive/RLC Assemblies/Wye-Connected Load')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Average-Value DC-DC Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value DC-DC Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Average-Value Chopper'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value Chopper')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Four-Quadrant Chopper'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Four-Quadrant Chopper')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/One-Quadrant Chopper'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/One-Quadrant Chopper')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Two-Quadrant Chopper'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Two-Quadrant Chopper')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Converter (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Bidirectional DC-DC Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Bidirectional DC-DC Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Boost Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Boost Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Buck Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Buck Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Buck-Boost Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Buck-Boost Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Four-Pulse Gate Multiplexer'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Four-Pulse Gate Multiplexer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Commutation Diode'),...
    sprintf('ee_lib/Semiconductors & Converters/Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Diode'),...
    sprintf('ee_lib/Semiconductors & Converters/Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/GTO'),...
    sprintf('ee_lib/Semiconductors & Converters/GTO')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Ideal Semiconductor Switch'),...
    sprintf('ee_lib/Semiconductors & Converters/Ideal Semiconductor Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/IGBT'),...
    sprintf('ee_lib/Semiconductors & Converters/IGBT (Ideal, Switching)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/MOSFET'),...
    sprintf('ee_lib/Semiconductors & Converters/MOSFET (Ideal, Switching)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Thermal/Cauer Thermal Model Element'),...
    sprintf('ee_lib/Passive/Thermal/Cauer Thermal Model Element')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Thermal/Foster Thermal Model'),...
    sprintf('ee_lib/Passive/Thermal/Foster Thermal Model')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Thermal/Thermal Resistor'),...
    sprintf('ee_lib/Passive/Thermal/Thermal Resistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Fundamental Components/Thyristor (Piecewise Linear)'),...
    sprintf('ee_lib/Semiconductors & Converters/Thyristor (Piecewise Linear)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Average-Value Inverter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value Inverter (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Average-Value Rectifier'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value Rectifier (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Average-Value Voltage Source Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Average-Value Voltage Source Converter (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Rectifier'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Rectifier (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Six-Pulse Gate Multiplexer'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Six-Pulse Gate Multiplexer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Three-Level Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Three-Level Converter (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Twelve-Pulse Gate Multiplexer'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Twelve-Pulse Gate Multiplexer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Semiconductors/Two-Pulse Gate Multiplexer'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/Two-Pulse Gate Multiplexer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Three Element Demux'),...
    sprintf('ee_lib/Connectors & References/Three Element Demux')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Current Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/Current Sensor (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Line Voltage Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/Line Voltage Sensor (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sensors/Phase Voltage Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/Phase Voltage Sensor (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Supercapacitor'),...
    sprintf('ee_lib/Passive/Supercapacitor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Controlled Current Source (Three-Phase)'),...
    sprintf('ee_lib/Sources/Controlled Current Source (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Current Source (Three-Phase)'),...
    sprintf('ee_lib/Sources/Current Source (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Sources/Voltage Source (Three-Phase)'),...
    sprintf('ee_lib/Sources/Voltage Source (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Circuit Breaker'),...
    ''});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Fundamental Components/Single-Phase Circuit Breaker'),...
    ''});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Fundamental Components/Single-Phase Circuit Breaker (with arc)'),...
    ''});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Fundamental Components/Single-Phase Switch'),...
    ''});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Fundamental Components/Single-Phase Two-Way Switch'),...
    ''});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Switch'),...
    sprintf('ee_lib/Switches & Breakers/SPST Switch (Three-Phase)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('pe_lib/Switches & Breakers/Two-Way Switch'),...
    sprintf('ee_lib/Switches & Breakers/SPDT Switch (Three-Phase)')});

end
