function lib(libInfo)

    libName=pm_message('sm:library:bodyElements:Name');
    libInfo.SLBlockProperties.Name=libName;
    libInfo.Annotation=[libName,' Library'];
    libInfo.DVGIconKey='SMLibrary.body_elements_lib';

    libInfo.OrderofChildren={'graphic',...
    'inertia',...
    'brick_solid',...
    'cylindrical_solid',...
    'ellipsoidal_solid',...
    'extruded_solid',...
    'external_file_solid',...
    'revolved_solid',...
    'spherical_solid',...
    'flexible_bodies',...
    'variable_mass'};


    fte1=simmechanics.sli.internal.ForwardingTableEntry;
    fte1.OldPath='sm_lib/Body Elements/Solid';
    fte1.XFormFunction='simmechanics.library.body_elements.sl_postprocess3';
    libInfo.setForwardingTableEntries('R2019b',fte1);