
function registerPluggableVisualizations()
    try
        connector.ensureServiceOn();
    catch me %#ok<NASGU>
        return
    end


    sdi_visuals.registerVisual(...
    'texteditorplugin',...
    getString(message('SDI:sdi:TextEditorVisualName')),...
    '/toolbox/shared/sdi_visuals/texteditor/web/texteditorplugin.xml');


    sdi_visuals.registerVisual(...
    'mapsplugin',...
    getString(message('SDI:sdi:MapVisualName')),...
    '/toolbox/shared/sdi_visuals/maps/web/mapsplugin.xml');


    sdi_visuals.registerVisual(...
    'xyplotplugin',...
    getString(message('SDI:sdi:XYPlotVisualName')),...
    '/toolbox/shared/sdi_visuals/xyplot/web/xyplotplugin.xml');


    sdi_visuals.registerVisual(...
    'sparklinesplugin',...
    getString(message('SDI:sdi:SparklinesVisualName')),...
    '/toolbox/shared/sdi_visuals/sparklines/web/sparklinesplugin.xml');


    sdi_visuals.registerVisual(...
    'arrayplotplugin',...
    getString(message('SDI:sdi:ArrayPlotVisualName')),...
    '/toolbox/shared/sdi_visuals/arrayplot/web/arrayplotplugin.xml');


    if Simulink.sdi.enableSDIVideo>1
        videoName=getString(message('SDI:sdi:VideoVisualName'));
        sdi_visuals.registerVisual(...
        'videoplugin',...
        videoName,...
        '/toolbox/shared/sdi_video/video/web/videoplugin.xml');
    end
end