function setRunDescription(this,runID,desc)
    this.sigRepository.setRunDescription(runID,desc);
    this.dirty=true;
    notify(this,'propertyChangeEvent',...
    Simulink.sdi.internal.SDIEvent('propertyChangeEvent',runID,...
    Simulink.sdi.internal.StringDict.mgDescription,...
    desc));
    notify(this,'treeRunPropertyEvent',...
    Simulink.sdi.internal.SDIEvent('treeRunPropertyEvent',...
    runID,desc,'runDescription'));
end