function setSignalLineWidth(this,id,value)
    this.sigRepository.setSignalLineWidth(id,value);
    notify(this,'treeSignalPropertyEvent',...
    Simulink.sdi.internal.SDIEvent('treeSignalPropertyEvent',...
    id,value,'linewidth'));
    value=this.getSignalLine(id);
    this.dirty=true;
    notify(this,'propertyChangeEvent',...
    Simulink.sdi.internal.SDIEvent('propertyChangeEvent',id,...
    Simulink.sdi.internal.StringDict.mgLine,value));
end