function runJHighlightAction(...
    jHighlightData,...
    slEditorStyler,...
    jLayout,...
    jComparisonReport)





    jFilePath=jHighlightData.getFile().getAbsolutePath();
    jNodePath=jHighlightData.getNodeHighlightPath();

    positionManager=slxmlcomp.internal.highlight.PositionManager.getInstance();
    positionManager.highlight(...
    char(jHighlightData.getHighlightType()),...
    char(jNodePath),...
    char(jLayout.getLegacyMATLABLayout()),...
    char(jHighlightData.getPositionID()),...
    char(jFilePath),...
    jComparisonReport,...
slEditorStyler...
    );

end
