function customLayerList=dlhdl_customLayer_registration










    customLayerList={...
    dlhdl.CustomLayer('Name','Addition',...
    'Layer',additionLayer(2),...
    'Model','model/customLayers/dnnfpgaAdditionLayerModel.slx')
    dlhdl.CustomLayer('Name','Multiplication',...
    'Layer',multiplicationLayer(2),...
    'Model','model/customLayers/dnnfpgaMultiplicationLayerModel.slx')
    dlhdl.CustomLayer('Name','Sigmoid',...
    'Layer',sigmoidLayer('Name','sigmoidLayer'),...
    'Model','model/customLayers/dnnfpgaSigmoidLayerModel.slx')
    dlhdl.CustomLayer('Name','Exponential',...
    'Layer',dnnfpga.layer.ExponentialLayer('Name','expoLayer'),...
    'Model','model/customLayers/dnnfpgaExponentialLayerModel.slx')
    dlhdl.CustomLayer('Name','TanhLayer',...
    'Layer',tanhLayer('Name','tanhLayer'),...
    'Model','model/customLayers/dnnfpgaTanhLayerModel.slx')
    dlhdl.CustomLayer('Name','Identity',...
    'Layer',dnnfpga.layer.identityLayer(),...
    'Model','model/customLayers/dnnfpgaIdentityLayerModel.slx')
    dlhdl.CustomLayer('Name','Resize2D',...
    'Layer',dnnfpga.custom.Resize2DLayer([10,10],[20,20]),...
    'Model','model/customLayers/dnnfpgaResize2DLayerModel.slx')
    };

end

