classdef(Abstract)Pam4Threshold<serdes.internal.ibisami.ami.parameter.ReservedParameter

...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=Pam4Threshold()
            param.Usage=serdes.internal.ibisami.ami.usage.Info();
            param.Type=serdes.internal.ibisami.ami.type.Float();
            param.AllowedUsages=["Info","InOut","Out","Dep"];
            param.AllowedTypes="Float";
            param.AllowedFormats="Value";
            param.DirectionTx=false;
        end
    end
end

