classdef Pam4CenterEyeOffset<serdes.internal.ibisami.ami.parameter.modulation.Pam4EyeOffset

...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=Pam4CenterEyeOffset()
            param.NodeName="PAM4_CenterEyeOffset";
            param.Description="The center eye sampling offset.";
            param.Format=serdes.internal.ibisami.ami.format.Value(0.0);
        end
    end
end

