classdef PAMThresholds<serdes.internal.ibisami.ami.parameter.ReservedParameter


...
...
...
...
...
...
...
...
...
...
...
...



    methods
        function param=PAMThresholds()
            param.NodeName="PAM_Thresholds";
            param.Description="Thresholds for waveform and eye processing.";
            param.Format=serdes.internal.ibisami.ami.format.Value("0");
            param.Usage=serdes.internal.ibisami.ami.usage.Out();
            param.Type=serdes.internal.ibisami.ami.type.String();
            param.AllowedUsages="Out";
            param.AllowedTypes="String";
            param.AllowedFormats="Value";
            param.DirectionTx=false;
            param.EarliestRequiredVersion=7.2;
        end
    end
end

