function schema

















    pkg=findpackage('RptgenRTW');
    pkgRG=findpackage('rptgen');

    h=schema.class(pkg,'CImportCode',pkgRG.findclass('rpt_section'));


    p=rptgen.prop(h,'Source_files__auto_generated','bool',true,...
    DAStudio.message('RTW:report:sourceFilesAutoGenerated'));


    p=rptgen.prop(h,'Header_files__auto_generated','bool',true,...
    DAStudio.message('RTW:report:headerFilesAutoGenerated'));


    p=rptgen.prop(h,'include_rtw_c','bool',true,...
    DAStudio.message('RTW:report:includeGeneratedSourceFiles'));


    p=rptgen.prop(h,'include_rtw_h','bool',true,...
    DAStudio.message('RTW:report:includeGeneratedHeaderFiles'));


    p=rptgen.prop(h,'Custom_files','bool',false,...
    DAStudio.message('RTW:report:customFiles'));


    rptgen.makeStaticMethods(h,{
    },{
    });


