function out=createFilterByLinkTypesHtml()
    import slreq.report.internal.rtmx.*
    allTypes=slreq.utils.getAllLinkTypes;
    typeList=[];
    for index=1:length(allTypes)
        cType=allTypes(index);
        typeStr=createCellStr('input',cType.typeName,...
        'type','checkbox',...
        'id',['filter',cType.typeName],...
        'onclick','filterTypes()',...
        'checked','true',...
        'disabled','true');
        typeList=sprintf('%s%s',typeList,typeStr);
    end

    filterByTypeFunctionName='filterByType(this)';
    radioButton=createCellStr('input','Filter By Types','type','checkbox',...
    'name','Filter By Types',...
    'id','filterCheckbox',...
    'onclick',filterByTypeFunctionName);
    out=sprintf('%s%s',radioButton,typeList);

end

