function options=getRMBClickOptions(filterType,sid)

    options.propDesc=getDescription(filterType,sid);
    options.Type=filterType;
    options.value=sid;
    options.id=filterType;
    options.rationale=options.propDesc;
    options.checkIDs={...
    '.*',...
    DAStudio.message('slcheck:filtercatalog:CheckSelectorGUI')};
    options.checkOptions={...
    DAStudio.message('ModelAdvisor:engine:ExclusionAllChecks'),...
    DAStudio.message('ModelAdvisor:engine:CheckSelector')};
    options.checkType='ModelAdvisor';
    options.includeChildren=1;
    options.name='';

end

function desc=getDescription(type,sid)
    persistent DescriptionMap;
    if isempty(DescriptionMap)
        keySet={...
        'Block',...
        'Subsystem',...
        'BlockType',...
        'MaskType',...
        'Library',...
        'Transition',...
        'Event',...
        'State',...
        'Junction',...
        'GraphicalFunction',...
        'TruthTable',...
        'SimulinkFunction',...
        'MATLABFunction',...
        'SimulinkBasedState',...
        'Chart',...
        };
        valueSet={...
        DAStudio.message('slcheck:filtercatalog:ExclusionBlock'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionSubsystem'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionBlockType',sid),...
        DAStudio.message('slcheck:filtercatalog:ExclusionMaskType',sid),...
        DAStudio.message('slcheck:filtercatalog:ExclusionLibrary',sid),...
        DAStudio.message('slcheck:filtercatalog:ExclusionTransition'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionTemporalEvent',sid),...
        DAStudio.message('slcheck:filtercatalog:ExclusionState'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionJunction'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionGraphicalFunction'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionTruthTable'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionSimulinkFunction'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionMATLABFunction'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionSimulinkBasedState'),...
        DAStudio.message('slcheck:filtercatalog:ExclusionChartWithAllDescendants'),...
        };
        DescriptionMap=containers.Map(keySet,valueSet);
    end
    desc=DescriptionMap(type);
end



