function chart=getSFChartObject(blkObj)










    chart=find(blkObj,...
    '-depth',1,...
    'Name',blkObj.Name,...
    '-isa','Stateflow.Chart',...
    '-or','-isa','Stateflow.EMChart',...
    '-or','-isa','Stateflow.TruthTableChart',...
    '-or','-isa','Stateflow.StateTransitionTableChart',...
    '-or','-isa','Stateflow.LinkChart');%#ok<*GTARG>

end
