function RTOS=createDefaultRTOS(h)




    RTOS=struct('enable','off',...
    'TSK','',...
    'schedulerType','Rate priority');

    RTOS.TSK=struct('stackSize',4096,...
    'staticStackMemSegment','',...
    'dynamicStackMemSegment','');
