function err=getValidationError(excep,type,source,pathInHierarchy)





    err=struct(...
    'Exception',{excep},...
    'Type',{type},...
    'Source',{source},...
    'PathInHierarchy',{pathInHierarchy});
end
