function SpeedRedCback(block);








    PresetModel=get_param(gcb,'PresetModel');
    if~strcmp(PresetModel,'No')
        Indice=eval(PresetModel(1:2));
        load('SpeedRedParameters');
        set_param(block,'i',mat2str(SpeedRedParameters(Indice).i));
        set_param(block,'Jrdh',mat2str(SpeedRedParameters(Indice).Jrdh));
        set_param(block,'eff',mat2str(SpeedRedParameters(Indice).eff));
        set_param(block,'Ksh',mat2str(SpeedRedParameters(Indice).Ksh));
        set_param(block,'Bsh',mat2str(SpeedRedParameters(Indice).Bsh));
        set_param(block,'Ksl',mat2str(SpeedRedParameters(Indice).Ksl));
        set_param(block,'Bsl',mat2str(SpeedRedParameters(Indice).Bsl));

        maskEnables={'on',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off'};

    else
        maskEnables={'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on'};
    end
    if sps_Authoring(bdroot(block))
        set_param(block,'MaskEnables',maskEnables);
    end