function[]=spsDrivesActiveRectifierCbak(block,action)

    switchType=get_param(block,'Device');

    if strcmp(action,'initialization')
        set_param([block,'/Detailed/Rectifier_3ph'],'Device',switchType);
    end


    detailLevel=get_param(block,'detailLevel');
    if~isequal(get_param(block,'LabelModeActiveChoice'),detailLevel)
        set_param(block,'LabelModeActiveChoice',detailLevel);
    end

    switch detailLevel
    case 'Detailed'
        switch switchType
        case{'GTO / Diodes'}
            gtoParameters='on';
            igbtParameters='off';
            forwardVoltages='on';
        case{'MOSFET / Diodes'}
            gtoParameters='off';
            igbtParameters='off';
            forwardVoltages='off';
        case{'IGBT / Diodes'}
            gtoParameters='off';
            igbtParameters='on';
            forwardVoltages='on';
        end

        maskEnables={...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'off',...
        forwardVoltages,...
        'off',...
        gtoParameters,...
        igbtParameters,...
        'off',...
        'on',...
        'on',...
        'on',...
        };
    case 'Average'


        switch get_param(bdroot(block),'SimulationStatus')
        case 'initializing'

            Vs=getSPSmaskvalues(block,{'Vs'});
            if Vs==0
                pere=bdroot(block);
                block=strrep(block,char(10),' ');
                block=strrep(block,pere,'');
                block=block(2:end);
                error(message('physmod:powersys:common:GreaterThan',block,'Nominal line voltage Vn',0));
            end
        end

        maskEnables={...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'off',...
        'off',...
        'off',...
        'on',...
        'on',...
        'off',...
        'off',...
        'off',...
        'off',...
        'on',...
        'on',...
        'on',...
        'on',...
        };
    end
    if sps_Authoring(bdroot(block))
        set_param(block,'MaskEnables',maskEnables);
    end
    set_param(block,'MaskVisibilities',maskEnables);
