function[]=spsDrivesFieldOrientedControllercCbak(block)


    detailLevel=get_param(block,'detailLevel');

    handlemask=Simulink.Mask.get(block);
    hdle_daxis_gbox=handlemask.getDialogControl('daxis_gbox');
    hdle_qaxis_gbox=handlemask.getDialogControl('qaxis_gbox');

    switch detailLevel
    case 'Detailed'
        modulationType=get_param(block,'modulationType');

        switch modulationType

        case 'Hysteresis'


            variant='Detailed';
            if~isequal(get_param(block,'LabelModeActiveChoice'),variant)
                set_param(block,'LabelModeActiveChoice',variant);
            end

            maskEnables={...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'off',...
            'off',...
            'off',...
            'off',...
            'off',...
            'off',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            };
            maskVisibilities={...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'off',...
            'off',...
            'off',...
            'off',...
            'off',...
            'off',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            };
            hdle_daxis_gbox.Visible='off';
            hdle_qaxis_gbox.Visible='off';

        case 'SVM'



            variant='Detailed_SVM';
            if~isequal(get_param(block,'LabelModeActiveChoice'),variant)
                set_param(block,'LabelModeActiveChoice',variant);
            end

            maskEnables={...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'off',...
            'off',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            };
            maskVisibilities={...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'off',...
            'off',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            'on',...
            };
            hdle_daxis_gbox.Visible='on';
            hdle_qaxis_gbox.Visible='on';
        end
    case 'Average'


        variant='Average';
        if~isequal(get_param(block,'LabelModeActiveChoice'),variant)
            set_param(block,'LabelModeActiveChoice',variant);
        end

        maskEnables={...
        'on',...
        'off',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        };
        maskVisibilities={...
        'on',...
        'off',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'off',...
        'on',...
        'on',...
        'on',...
        'on',...
        'on',...
        };

        hdle_daxis_gbox.Visible='off';
        hdle_qaxis_gbox.Visible='off';
    otherwise
        error(['Unknown detail level ''',detailLevel,'''.']);
    end
    if sps_Authoring(bdroot(block))
        set_param(block,'MaskEnables',maskEnables);
    end
    set_param(block,'MaskVisibilities',maskVisibilities);