function[]=spsDrivesMaskControllerSinglePhaseIm(block,driveType,averageValue);%#ok











    switch driveType

    case 'AC9'




        controllerType=get_param(block,'controllerType');
        regulationType=get_param(block,'regulationType');
        handlemask=Simulink.Mask.get(block);

        maskParameters=ones(1,52);
        maskParameters(:,52)=0;





        if strcmp(controllerType,'FOC')
            maskParameters(:,44:45)=zeros(1,2);
        elseif strcmp(controllerType,'DTC (two-level hysteresis)')||strcmp(controllerType,'DTC (five-level hysteresis)')
            maskParameters(1,43)=0;
        end


        if strcmp(regulationType,'Speed regulation')
            p=handlemask.getDialogControl('Speedramp');
            p.Visible='on';
            p=handlemask.getDialogControl('PIregulator');
            p.Visible='on';
        elseif strcmp(regulationType,'Torque regulation')
            p=handlemask.getDialogControl('Speedramp');
            p.Visible='off';
            p=handlemask.getDialogControl('PIregulator');
            p.Visible='off';
            maskParameters(1,33)=0;
        end

    end
    maskEnables(1==maskParameters)={'on'};
    maskEnables(0==maskParameters)={'off'};
    maskVisibilities=maskEnables;

    if strcmp('Speed w',get_param(block,'MechanicalLoad'))
        maskVisibilities{12}='off';
        maskVisibilities{13}='off';

    else
        maskVisibilities{12}='on';
        maskVisibilities{13}='on';

    end

    maskVisibilities{25}='off';
    set_param(block,'MaskEnables',maskEnables);
    set_param(block,'MaskVisibilities',maskVisibilities);

end

...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
...
