



function metricKind=getCodeCovResStructInfoForMetric(metricName)

    [~,metricIdx]=ismember(metricName,{'decision','condition','mcdc','complexity',...
    'cvmetric_Structural_block','cvmetric_Structural_relationalop',...
    'cvmetric_funentry','cvmetric_funcall'});
    if metricIdx==0

        metricKind=[];
        return
    end

    persistent resStructInfo
    if isempty(resStructInfo)
        resStructInfo={...
        internal.cxxfe.instrum.MetricKind.DECISION;...
        internal.cxxfe.instrum.MetricKind.CONDITION;...
        internal.cxxfe.instrum.MetricKind.MCDC;...
        internal.cxxfe.instrum.MetricKind.CYCLO_CPLX;...
        internal.cxxfe.instrum.MetricKind.STATEMENT;...
        internal.cxxfe.instrum.MetricKind.RELATIONAL_BOUNDARY;...
        internal.cxxfe.instrum.MetricKind.FUN_ENTRY;...
        internal.cxxfe.instrum.MetricKind.FUN_CALL...
        };
    end

    resInfo=resStructInfo(metricIdx,:);
    metricKind=resInfo{1};
