function result=toUseSLXC(buildArgs)




    result=~Simulink.ModelReference.ProtectedModel.protectingModel(buildArgs.TopOfBuildModel)&&...
    strcmp(buildArgs.ModelReferenceTargetType,'NONE')&&...
    ~buildArgs.IsRapidAccelerator&&...
    ~buildArgs.IsSimulinkAccelerator&&...
    ~buildArgs.SubSystemBuild&&...
    ~buildArgs.IsLibraryContextCodeGen&&...
    ~buildArgs.IsXILSubsystemHiddenModelBuild&&...
    ~internal.fmudialog.export.IsFMUTarget(buildArgs.TopOfBuildModel);
end
