function returnValue = selectiveParamUndoRedoFilterHelper( requestedAction )








persistent blockTypesCell;

if isempty( blockTypesCell ) && ~iscell( blockTypesCell )
blockTypesCell = {  ...
'BusCreator',  ...
'BusSelector',  ...
'DataStoreRead',  ...
'DataStoreWrite',  ...
'Reference',  ...
'Sum',  ...
'EntityServer',  ...
'Queue',  ...
'NewDESResourcePool',  ...
'EntityGenerator',  ...
'EntityTerminator',  ...
'SubSystem::CIC Filter',  ...
'SubSystem::PID 1dof',  ...
'SubSystem::PID 2dof',  ...
'ModelReference' };
end 

if strcmp( requestedAction, 'GetList' )
returnValue = blockTypesCell;
else 
returnValue = [  ];
end 
end 

% Decoded using De-pcode utility v1.2 from file /tmp/tmpkrgBg1.p.
% Please follow local copyright laws when handling this file.

