function usprops=getunsupportedprops(this)






    usprops={'ClockEnableOutputPort',...
    'ClockInputs',...
    'CoefficientSource',...
    'DALUTPartition',...
    'DARadix',...
    'FracDelayPort',...
    'ReuseAccum',...
    'SerialPartition'};


