function layerList=getDefaultSupportedLayers()








    layerList={'nnet.cnn.layer.AdditionLayer',...
    'nnet.internal.cnn.coder.MultiplicationLayer',...
    'nnet.cnn.layer.SigmoidLayer',...
    'dnnfpga.layer.ExponentialLayer',...
    'nnet.cnn.layer.TanhLayer',...
    'dnnfpga.layer.identityLayer',...
    'dnnfpga.custom.Resize2DLayer',...
    };


end

