function out=checkIfValidSimInput(simInput)

    expectedFields={'TestCaseId','PermutationId','Model','Mode','SubSystem','AutoGenHarness',...
    'HarnessName','PreLoadScript','PostLoadScript',...
    'CleanupScript','ConfigName','IsReference',...
    'ConfigRefPath','InputMappingString','InputFilePath',...
    'IsSigBuilderUsed','IsSigMapUsed','SigBuilderGroupName','VarName',...
    'InitialState','IsInitialStateEnabled','StartTime','IsStartTimeEnabled',...
    'StopTime','IsStopTimeEnabled','OverrideSILPILMode',...
    'SaveOutput','SaveState','SaveFinalState','SignalLogging','DSMLogging','OutputCtrlEnabled',...
    'OverridesStruct','ConfigSetOverrideSetting','TestIteration','InputType',...
    'RunOnTarget','TargetApplication','TargetComputer','LoadApplicationFrom',...
    'IncludeExternalInputs','LoggedSignalSetId'
    };
    out=(isstruct(simInput)&&isempty(find(isfield(simInput,expectedFields)~=1,1)));

end
