function dlgStruct=loop_getDialogSchema(this,name)




    if~builtin('license','checkout','SIMULINK_Report_Gen')
        dlgStruct=this.buildErrorMessage('panel',true);
        return;

    end

    termTypes=listTerminalTypes(rptgen_sf.appdata_sf);
    if this.LockType
        oTypes={};
        for i=1:length(termTypes)
            if(get(this,['isReport',termTypes{i}]))
                oTypes{end+1}=this.dlgText(sprintf(getString(message('RptgenSL:rsf_csf_obj_loop:reportOnObjectsLabel')),termTypes{i}));
            end
        end
        if isempty(oTypes)


            oTypes{1}=this.dlgWidget('LockType',...
            'DialogRefresh',1,...
            'Name',getString(message('RptgenSL:rsf_csf_obj_loop:noTypesReportedLabel')));
        end
    else
        for i=length(termTypes):-1:1
            oTypes{i}=this.dlgWidget(['isReport',termTypes{i}]);
        end
    end

    dlgStruct={
    this.dlgContainer(oTypes,getString(message('RptgenSL:rsf_csf_obj_loop:objectTypesLabel')))
    this.dlgContainer({
    this.dlgWidget('Depth',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1])
    this.dlgWidget('SkipAutogenerated',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1])
    this.dlgWidget('RemoveRedundant',...
    'RowSpan',[3,3],...
    'ColSpan',[1,1])
    RptgenML.twoColumnTable(this,'SFFilterTerms','isSFFilterList',...
    'RowSpan',[4,4],...
    'ColSpan',[1,1])
    },getString(message('RptgenSL:rsf_csf_obj_loop:loopOptionsLabel')),'LayoutGrid',[4,1],'RowStretch',[0,0,0,1])
    };
