



function flag=isSupportedStateflowMATLABAst(node)
    assert(isa(node,'slci.ast.SFAst'));

    if isa(node,'slci.ast.SFAstMatlabFunctionCallForStateflow')
        flag=node.isSFSLFunction...
        ||node.IsGraphicalFunction...
        ||node.IsTruthTable;
    else
        supportedClasses={
        'slci.ast.SFAstCastFunction',...
        'slci.ast.SFAstDirectCast',...
        'slci.ast.SFAstDivide',...
        'slci.ast.SFAstEqualAssignment',...
        'slci.ast.SFAstNum',...
        'slci.ast.SFAstTrueFalse',...
        'slci.ast.SFAstZeros',...
        'slci.ast.SFAstOnes',...
        'slci.ast.SFAstEye',...
        'slci.ast.SFAstDiag',...
        'slci.ast.SFAstGreaterThan',...
        'slci.ast.SFAstGreaterThanOrEqual',...
        'slci.ast.SFAstIdentifier',...
        'slci.ast.SFAstEnd',...
        'slci.ast.SFAstArray',...
        'slci.ast.SFAstRow',...
        'slci.ast.SFAstConcatenateLB',...
        'slci.ast.SFAstColon',...
        'slci.ast.SFAstIsEqual',...
        'slci.ast.SFAstIsNotEqual',...
        'slci.ast.SFAstLesserThan',...
        'slci.ast.SFAstLesserThanOrEqual',...
        'slci.ast.SFAstLogicalAnd',...
        'slci.ast.SFAstLogicalOr',...
        'slci.ast.SFAstAndAnd',...
        'slci.ast.SFAstOrOr',...
        'slci.ast.SFAstMinus',...
        'slci.ast.SFAstNot',...
        'slci.ast.SFAstPlus',...
        'slci.ast.SFAstTimes',...
        'slci.ast.SFAstUminus',...
        'slci.ast.SFAstUplus',...
        'slci.ast.SFAstCTranspose',...
        'slci.ast.SFAstDotTranspose',...
        'slci.ast.SFAstMul',...
        'slci.ast.SFAstDotDiv',...
        'slci.ast.SFAstDotLDiv',...
        'slci.ast.SFAstDotPow',...
        'slci.ast.SFAstRoot',...
        'slci.ast.SFAstMatlabFunctionCallOutput',...
        'slci.ast.SFAstMathBuiltin',...
        'slci.ast.SFAstMin',...
        'slci.ast.SFAstMax',...
        'slci.ast.SFAstSize',...
        'slci.ast.SFAstLength',...
        'slci.ast.SFAstNumel',...
        'slci.ast.SFAstNullCopy',...
        'slci.ast.SFAstIsTester',...
        'slci.ast.SFAstBitAnd',...
        'slci.ast.SFAstBitOr',...
        'slci.ast.SFAstBitXor',...
        'slci.ast.SFAstBitCmp',...
        'slci.ast.SFAstBitShift',...
        'slci.ast.SFAstBitGet',...
        'slci.ast.SFAstBitSet',...
        'slci.ast.SFAstDotProduct',...
        'slci.ast.SFAstOuterCfgElse',...
        'slci.ast.SFAstInnerCfgElse',...
        'slci.ast.SFAstTransIntoState',...
        'slci.ast.SFAstTransOutOfState',...
        'slci.ast.SFAstExplicitEvent',...
        'slci.ast.SFAstMatlabFunctionDef',...
        'slci.ast.SFAstSendFunction',...
        'slci.ast.SFAstPow',...
        'slci.ast.SFAstTransOutOfAtomicSubchart',...
        'slci.ast.SFAstTransIntoAtomicSubchart',...
'slci.ast.SFAstSimulinkFunctionCall'
        };

        flag=any(contains(supportedClasses,class(node)));
    end
end
