

function flag=isUnsupportedMatlabAst(node)

    assert(isa(node,'slci.ast.SFAst'));

    if isa(node,'slci.ast.SFAstTilde')
        flag=~isa(node.getParent(),...
        'slci.ast.SFAstMatlabFunctionCallOutput');
    else
        unsupportedClasses={'slci.ast.SFAstUnsupported',...
        'slci.ast.SFAstString',...
        'slci.ast.SFAstLC',...
        'slci.ast.SFAstReturn',...
        'slci.ast.SFAstVarargin',...
        'slci.ast.SFAstVarargout',...
        'slci.ast.SFAstWhile',...
        'slci.ast.SFAstBreak',...
        'slci.ast.SFAstContinue',...
        };

        flag=any(strcmpi(class(node),unsupportedClasses));
    end

    if~flag&&isa(node.ParentBlock,'slci.simulink.StateflowBlock')
        flag=~slci.matlab.astTranslator.isSupportedStateflowMATLABAst(node);
    end

end
