function DataTypeNames = sfbGetBuiltinDataTypeNames(  )
DataTypeNames = {  ...
'double', 'single',  ...
'int8', 'uint8',  ...
'int16', 'uint16',  ...
'int32', 'uint32',  ...
'boolean' ...
 };

% Decoded using De-pcode utility v1.2 from file /tmp/tmpVR0FPt.p.
% Please follow local copyright laws when handling this file.

