function symDemodQPSKScalar=elabQPSKScalarSymDemodNet(~,topNet,blockInfo,rate,inpWL,inpFL)

    if inpFL<-14
        addIncBits=0;
    else
        addIncBits=14+inpFL;
    end

    pirTyp2=pir_boolean_t;
    pirTyp8=pir_sfixpt_t(16,-14);
    pirTyp1=pir_sfixpt_t(inpWL,inpFL);
    pirTyp3=pir_sfixpt_t(inpWL+4,inpFL);
    pirTyp4=pir_sfixpt_t(inpWL+5,inpFL);
    pirTyp11=pir_sfixpt_t(inpWL+5+addIncBits,min(inpFL,-14));
    pirTyp10=pir_sfixpt_t(inpWL+16,inpFL-14);
    pirTyp6=pir_sfixpt_t(inpWL+17,inpFL-14);
    pirTyp9=pir_sfixpt_t(2*(inpWL+4),2*inpFL);
    pirTyp5=pir_ufixpt_t(9,0);
    pirTyp7=pir_unsigned_t(8);

    fiMath1=fimath('RoundingMethod','Nearest','OverflowAction','Saturate','ProductMode','FullPrecision','SumMode','FullPrecision');

    nt4=numerictype(0,1,0);
    nt1=numerictype(0,8,0);
    nt6=numerictype(1,16,14);
    nt5=numerictype(1,inpWL,-inpFL);
    nt2=numerictype(1,inpWL+4,-inpFL);
    nt3=numerictype(1,inpWL+5,-inpFL);
    nt8=numerictype(1,inpWL+16,-inpFL+14);
    nt7=numerictype(1,2*(inpWL+4),-2*inpFL);

    inportNameQPSK={'dataIn','validIn'};
    controlType=pir_ufixpt_t(1,0);
    inType=pir_complex_t(pir_sfixpt_t(inpWL,inpFL));
    inTypeQPSK=[inType,controlType];
    inDataRateQPSK=[rate,rate];

    outportNameQPSK={'dataOut','validOut','readyOut'};
    outTypeQPSK=[pirTyp3,controlType,controlType];

    symDemodQPSKScalar=pirelab.createNewNetwork(...
    'Network',topNet,...
    'Name','symDemodQPSKScalar',...
    'InportNames',inportNameQPSK,...
    'InportTypes',inTypeQPSK,...
    'InportRates',inDataRateQPSK,...
    'OutportNames',outportNameQPSK,...
    'OutportTypes',outTypeQPSK...
    );


    dataIn_s0=symDemodQPSKScalar.PirInputSignals(1);
    validIn_s1=symDemodQPSKScalar.PirInputSignals(2);

    dataOut=symDemodQPSKScalar.PirOutputSignals(1);
    validOut=symDemodQPSKScalar.PirOutputSignals(2);
    readyOut=symDemodQPSKScalar.PirOutputSignals(3);

    slRate1=rate;

    Switch10_out1_s164=addSignal(symDemodQPSKScalar,'Switch10_out1',pirTyp3,slRate1);
    delayMatch13_out1_s183=addSignal(symDemodQPSKScalar,'delayMatch13_out1',pirTyp2,slRate1);
    OR_out1_s121=addSignal(symDemodQPSKScalar,'OR_out1',pirTyp2,slRate1);

    AND_out1_s2=addSignal(symDemodQPSKScalar,'AND_out1',pirTyp2,slRate1);
    AND1_out1_s3=addSignal(symDemodQPSKScalar,'AND1_out1',pirTyp2,slRate1);
    Add_out1_s4=addSignal(symDemodQPSKScalar,'Add_out1',pirTyp4,slRate1);
    Add1_out1_s5=addSignal(symDemodQPSKScalar,'Add1_out1',pirTyp4,slRate1);
    Add2_out1_s6=addSignal(symDemodQPSKScalar,'Add2_out1',pirTyp5,slRate1);
    Add3_out1_s7=addSignal(symDemodQPSKScalar,'Add3_out1',pirTyp5,slRate1);
    Add4_out1_s8=addSignal(symDemodQPSKScalar,'Add4_out1',pirTyp6,slRate1);
    Add5_out1_s9=addSignal(symDemodQPSKScalar,'Add5_out1',pirTyp6,slRate1);
    CompareToConstant_out1_s10=addSignal(symDemodQPSKScalar,'Compare To Constant_out1',pirTyp2,slRate1);
    CompareToConstant1_out1_s11=addSignal(symDemodQPSKScalar,'Compare To Constant1_out1',pirTyp2,slRate1);
    CompareToConstant2_out1_s12=addSignal(symDemodQPSKScalar,'Compare To Constant2_out1',pirTyp2,slRate1);
    CompareToConstant5_out1_s13=addSignal(symDemodQPSKScalar,'Compare To Constant5_out1',pirTyp2,slRate1);
    ComplexToReal_Imag3_out1_s14=addSignal(symDemodQPSKScalar,'Complex to Real-Imag3_out1',pirTyp1,slRate1);
    ComplexToReal_Imag3_out2_s15=addSignal(symDemodQPSKScalar,'Complex to Real-Imag3_out2',pirTyp1,slRate1);
    Constant_out1_s16=addSignal(symDemodQPSKScalar,'Constant_out1',pirTyp7,slRate1);
    Constant1_out1_s17=addSignal(symDemodQPSKScalar,'Constant1_out1',pirTyp7,slRate1);
    Constant10_out1_s18=addSignal(symDemodQPSKScalar,'Constant10_out1',pirTyp7,slRate1);
    Constant11_out1_s19=addSignal(symDemodQPSKScalar,'Constant11_out1',pirTyp7,slRate1);
    Constant12_out1_s20=addSignal(symDemodQPSKScalar,'Constant12_out1',pirTyp7,slRate1);
    Constant13_out1_s21=addSignal(symDemodQPSKScalar,'Constant13_out1',pirTyp7,slRate1);
    Constant14_out1_s22=addSignal(symDemodQPSKScalar,'Constant14_out1',pirTyp7,slRate1);
    Constant15_out1_s23=addSignal(symDemodQPSKScalar,'Constant15_out1',pirTyp7,slRate1);
    Constant16_out1_s24=addSignal(symDemodQPSKScalar,'Constant16_out1',pirTyp7,slRate1);
    Constant17_out1_s25=addSignal(symDemodQPSKScalar,'Constant17_out1',pirelab.createPirArrayType(pirTyp7,[2,0]),slRate1);
    Constant18_out1_s26=addSignal(symDemodQPSKScalar,'Constant18_out1',pirTyp7,slRate1);
    Constant19_out1_s27=addSignal(symDemodQPSKScalar,'Constant19_out1',pirelab.createPirArrayType(pirTyp7,[2,0]),slRate1);
    Constant2_out1_s28=addSignal(symDemodQPSKScalar,'Constant2_out1',pirelab.createPirArrayType(pirTyp7,[2,0]),slRate1);
    Constant3_out1_s29=addSignal(symDemodQPSKScalar,'Constant3_out1',pirTyp7,slRate1);
    Constant4_out1_s30=addSignal(symDemodQPSKScalar,'Constant4_out1',pirelab.createPirArrayType(pirTyp7,[2,0]),slRate1);
    Constant5_out1_s31=addSignal(symDemodQPSKScalar,'Constant5_out1',pirTyp3,slRate1);
    Constant6_out1_s32=addSignal(symDemodQPSKScalar,'Constant6_out1',pirTyp7,slRate1);
    Constant7_out1_s33=addSignal(symDemodQPSKScalar,'Constant7_out1',pirTyp7,slRate1);
    Constant8_out1_s34=addSignal(symDemodQPSKScalar,'Constant8_out1',pirTyp7,slRate1);
    Constant9_out1_s35=addSignal(symDemodQPSKScalar,'Constant9_out1',pirTyp7,slRate1);
    DataTypeConversion_out1_s36=addSignal(symDemodQPSKScalar,'Data Type Conversion_out1',pirTyp3,slRate1);
    DataTypeConversion1_out1_s37=addSignal(symDemodQPSKScalar,'Data Type Conversion1_out1',pirTyp3,slRate1);
    DataTypeConversion10_out1_s38=addSignal(symDemodQPSKScalar,'Data Type Conversion10_out1',pirTyp3,slRate1);
    DataTypeConversion11_out1_s39=addSignal(symDemodQPSKScalar,'Data Type Conversion11_out1',pirTyp7,slRate1);
    DataTypeConversion12_out1_s40=addSignal(symDemodQPSKScalar,'Data Type Conversion12_out1',pirTyp7,slRate1);
    DataTypeConversion13_out1_s41=addSignal(symDemodQPSKScalar,'Data Type Conversion13_out1',pirTyp3,slRate1);
    DataTypeConversion14_out1_s42=addSignal(symDemodQPSKScalar,'Data Type Conversion14_out1',pirTyp3,slRate1);
    DataTypeConversion2_out1_s43=addSignal(symDemodQPSKScalar,'Data Type Conversion2_out1',pirTyp3,slRate1);
    DataTypeConversion3_out1_s44=addSignal(symDemodQPSKScalar,'Data Type Conversion3_out1',pirTyp3,slRate1);
    DataTypeConversion4_out1_s45=addSignal(symDemodQPSKScalar,'Data Type Conversion4_out1',pirTyp3,slRate1);
    DataTypeConversion5_out1_s46=addSignal(symDemodQPSKScalar,'Data Type Conversion5_out1',pirTyp3,slRate1);
    DataTypeConversion6_out1_s47=addSignal(symDemodQPSKScalar,'Data Type Conversion6_out1',pirTyp3,slRate1);
    DataTypeConversion7_out1_s48=addSignal(symDemodQPSKScalar,'Data Type Conversion7_out1',pirTyp3,slRate1);
    DataTypeConversion8_out1_s49=addSignal(symDemodQPSKScalar,'Data Type Conversion8_out1',pirTyp3,slRate1);
    DataTypeConversion9_out1_s50=addSignal(symDemodQPSKScalar,'Data Type Conversion9_out1',pirTyp3,slRate1);
    Delay_out1_s51=addSignal(symDemodQPSKScalar,'Delay_out1',pirTyp4,slRate1);
    Delay1_out1_s52=addSignal(symDemodQPSKScalar,'Delay1_out1',pirTyp2,slRate1);
    Delay1_Initial_Val_out1_s53=addSignal(symDemodQPSKScalar,'Delay1_Initial_Val_out1',pirTyp2,slRate1);
    Delay1_ctrl_const_out1_s54=addSignal(symDemodQPSKScalar,'Delay1_ctrl_const_out1',pirTyp2,slRate1);
    Delay1_ctrl_delay_out1_s55=addSignal(symDemodQPSKScalar,'Delay1_ctrl_delay_out1',pirTyp2,slRate1);
    Delay1_switch_out1_s56=addSignal(symDemodQPSKScalar,'Delay1_switch_out1',pirTyp2,slRate1);
    Delay2_out1_s57=addSignal(symDemodQPSKScalar,'Delay2_out1',pirTyp3,slRate1);
    Delay2_enbsw_out1_s58=addSignal(symDemodQPSKScalar,'Delay2_enbsw_out1',pirTyp3,slRate1);
    Delay3_out1_s59=addSignal(symDemodQPSKScalar,'Delay3_out1',pirTyp7,slRate1);
    Delay3_Initial_Val_out1_s60=addSignal(symDemodQPSKScalar,'Delay3_Initial_Val_out1',pirTyp7,slRate1);
    Delay3_ctrl_const_out1_s61=addSignal(symDemodQPSKScalar,'Delay3_ctrl_const_out1',pirTyp2,slRate1);
    Delay3_ctrl_delay_out1_s62=addSignal(symDemodQPSKScalar,'Delay3_ctrl_delay_out1',pirTyp2,slRate1);
    Delay3_switch_out1_s63=addSignal(symDemodQPSKScalar,'Delay3_switch_out1',pirTyp7,slRate1);
    Delay4_out1_s64=addSignal(symDemodQPSKScalar,'Delay4_out1',pirTyp7,slRate1);
    Delay5_out1_s65=addSignal(symDemodQPSKScalar,'Delay5_out1',pirTyp3,slRate1);
    Delay5_enbsw_out1_s66=addSignal(symDemodQPSKScalar,'Delay5_enbsw_out1',pirTyp3,slRate1);
    Delay6_out1_s67=addSignal(symDemodQPSKScalar,'Delay6_out1',pirTyp4,slRate1);
    Delay7_out1_s68=addSignal(symDemodQPSKScalar,'Delay7_out1',pirTyp2,slRate1);
    Delay8_out1_s69=addSignal(symDemodQPSKScalar,'Delay8_out1',pirTyp2,slRate1);
    From_out1_s70=addSignal(symDemodQPSKScalar,'From_out1',pirTyp3,slRate1);
    From1_out1_s71=addSignal(symDemodQPSKScalar,'From1_out1',pirTyp7,slRate1);
    From11_out1_s72=addSignal(symDemodQPSKScalar,'From11_out1',pirTyp3,slRate1);
    From12_out1_s73=addSignal(symDemodQPSKScalar,'From12_out1',pirTyp3,slRate1);
    From13_out1_s74=addSignal(symDemodQPSKScalar,'From13_out1',pirTyp3,slRate1);
    From14_out1_s75=addSignal(symDemodQPSKScalar,'From14_out1',pirTyp3,slRate1);
    From15_out1_s76=addSignal(symDemodQPSKScalar,'From15_out1',pirTyp7,slRate1);
    From19_out1_s77=addSignal(symDemodQPSKScalar,'From19_out1',pirTyp3,slRate1);
    From2_out1_s78=addSignal(symDemodQPSKScalar,'From2_out1',pirTyp3,slRate1);
    From20_out1_s79=addSignal(symDemodQPSKScalar,'From20_out1',pirTyp7,slRate1);
    From21_out1_s80=addSignal(symDemodQPSKScalar,'From21_out1',pirTyp2,slRate1);
    From26_out1_s81=addSignal(symDemodQPSKScalar,'From26_out1',pirTyp2,slRate1);
    From27_out1_s82=addSignal(symDemodQPSKScalar,'From27_out1',pirTyp2,slRate1);
    From28_out1_s83=addSignal(symDemodQPSKScalar,'From28_out1',pirTyp7,slRate1);
    From3_out1_s84=addSignal(symDemodQPSKScalar,'From3_out1',pirTyp3,slRate1);
    From4_out1_s85=addSignal(symDemodQPSKScalar,'From4_out1',pirTyp7,slRate1);
    From5_out1_s86=addSignal(symDemodQPSKScalar,'From5_out1',pirTyp2,slRate1);
    From6_out1_s87=addSignal(symDemodQPSKScalar,'From6_out1',pirTyp2,slRate1);
    From7_out1_s88=addSignal(symDemodQPSKScalar,'From7_out1',pirTyp3,slRate1);
    From8_out1_s89=addSignal(symDemodQPSKScalar,'From8_out1',pirTyp7,slRate1);
    Goto11_out1_s90=addSignal(symDemodQPSKScalar,'Goto11_out1',pirTyp3,slRate1);
    Goto12_out1_s91=addSignal(symDemodQPSKScalar,'Goto12_out1',pirTyp3,slRate1);
    Goto13_out1_s92=addSignal(symDemodQPSKScalar,'Goto13_out1',pirTyp3,slRate1);
    Goto14_out1_s93=addSignal(symDemodQPSKScalar,'Goto14_out1',pirTyp3,slRate1);
    Goto15_out1_s94=addSignal(symDemodQPSKScalar,'Goto15_out1',pirTyp3,slRate1);
    Goto19_out1_s95=addSignal(symDemodQPSKScalar,'Goto19_out1',pirTyp2,slRate1);
    Goto2_out1_s96=addSignal(symDemodQPSKScalar,'Goto2_out1',pirTyp3,slRate1);
    Goto21_out1_s97=addSignal(symDemodQPSKScalar,'Goto21_out1',pirTyp7,slRate1);
    Goto26_out1_s98=addSignal(symDemodQPSKScalar,'Goto26_out1',pirTyp7,slRate1);
    Goto3_out1_s99=addSignal(symDemodQPSKScalar,'Goto3_out1',pirTyp3,slRate1);
    Goto4_out1_s100=addSignal(symDemodQPSKScalar,'Goto4_out1',pirTyp3,slRate1);
    Goto5_out1_s101=addSignal(symDemodQPSKScalar,'Goto5_out1',pirTyp2,slRate1);
    Goto6_out1_s102=addSignal(symDemodQPSKScalar,'Goto6_out1',pirTyp3,slRate1);
    Goto9_out1_s103=addSignal(symDemodQPSKScalar,'Goto9_out1',pirTyp2,slRate1);
    HwModeRegister_out1_s104=addSignal(symDemodQPSKScalar,'HwModeRegister_out1',pirTyp3,slRate1);
    HwModeRegister1_out1_s105=addSignal(symDemodQPSKScalar,'HwModeRegister1_out1',pirTyp3,slRate1);
    HwModeRegister10_out1_s106=addSignal(symDemodQPSKScalar,'HwModeRegister10_out1',pirTyp1,slRate1);
    HwModeRegister11_out1_s107=addSignal(symDemodQPSKScalar,'HwModeRegister11_out1',pirTyp8,slRate1);
    HwModeRegister12_out1_s108=addSignal(symDemodQPSKScalar,'HwModeRegister12_out1',pirTyp1,slRate1);
    HwModeRegister13_out1_s109=addSignal(symDemodQPSKScalar,'HwModeRegister13_out1',pirTyp8,slRate1);
    HwModeRegister14_out1_s110=addSignal(symDemodQPSKScalar,'HwModeRegister14_out1',pirTyp8,slRate1);
    HwModeRegister15_out1_s111=addSignal(symDemodQPSKScalar,'HwModeRegister15_out1',pirTyp1,slRate1);
    HwModeRegister2_out1_s112=addSignal(symDemodQPSKScalar,'HwModeRegister2_out1',pirTyp3,slRate1);
    HwModeRegister3_out1_s113=addSignal(symDemodQPSKScalar,'HwModeRegister3_out1',pirTyp3,slRate1);
    HwModeRegister4_out1_s114=addSignal(symDemodQPSKScalar,'HwModeRegister4_out1',pirTyp3,slRate1);
    HwModeRegister5_out1_s115=addSignal(symDemodQPSKScalar,'HwModeRegister5_out1',pirTyp3,slRate1);
    HwModeRegister6_out1_s116=addSignal(symDemodQPSKScalar,'HwModeRegister6_out1',pirTyp3,slRate1);
    HwModeRegister7_out1_s117=addSignal(symDemodQPSKScalar,'HwModeRegister7_out1',pirTyp3,slRate1);
    HwModeRegister8_out1_s118=addSignal(symDemodQPSKScalar,'HwModeRegister8_out1',pirTyp8,slRate1);
    HwModeRegister9_out1_s119=addSignal(symDemodQPSKScalar,'HwModeRegister9_out1',pirTyp1,slRate1);
    NOT_out1_s120=addSignal(symDemodQPSKScalar,'NOT_out1',pirTyp2,slRate1);
    OR1_out1_s122=addSignal(symDemodQPSKScalar,'OR1_out1',pirTyp2,slRate1);
    PSKSymbolConverterBlock_out1_s123=addSignal(symDemodQPSKScalar,'PSKSymbolConverterBlock_out1',pirTyp3,slRate1);
    PSKSymbolConverterBlock_out2_s124=addSignal(symDemodQPSKScalar,'PSKSymbolConverterBlock_out2',pirTyp3,slRate1);
    PSKSymbolConverterBlock_out3_s125=addSignal(symDemodQPSKScalar,'PSKSymbolConverterBlock_out3',pirTyp2,slRate1);
    PipelineRegister_out1_s126=addSignal(symDemodQPSKScalar,'PipelineRegister_out1',pirTyp9,slRate1);
    PipelineRegister1_out1_s127=addSignal(symDemodQPSKScalar,'PipelineRegister1_out1',pirTyp9,slRate1);
    PipelineRegister2_out1_s128=addSignal(symDemodQPSKScalar,'PipelineRegister2_out1',pirTyp9,slRate1);
    PipelineRegister3_out1_s129=addSignal(symDemodQPSKScalar,'PipelineRegister3_out1',pirTyp9,slRate1);
    PipelineRegister4_out1_s130=addSignal(symDemodQPSKScalar,'PipelineRegister4_out1',pirTyp10,slRate1);
    PipelineRegister5_out1_s131=addSignal(symDemodQPSKScalar,'PipelineRegister5_out1',pirTyp10,slRate1);
    PipelineRegister6_out1_s132=addSignal(symDemodQPSKScalar,'PipelineRegister6_out1',pirTyp10,slRate1);
    PipelineRegister7_out1_s133=addSignal(symDemodQPSKScalar,'PipelineRegister7_out1',pirTyp10,slRate1);
    Product_out1_s134=addSignal(symDemodQPSKScalar,'Product_out1',pirTyp9,slRate1);
    Product1_out1_s135=addSignal(symDemodQPSKScalar,'Product1_out1',pirTyp9,slRate1);
    Product2_out1_s136=addSignal(symDemodQPSKScalar,'Product2_out1',pirTyp9,slRate1);
    Product3_out1_s137=addSignal(symDemodQPSKScalar,'Product3_out1',pirTyp9,slRate1);
    Product4_out1_s138=addSignal(symDemodQPSKScalar,'Product4_out1',pirTyp10,slRate1);
    Product5_out1_s139=addSignal(symDemodQPSKScalar,'Product5_out1',pirTyp10,slRate1);
    Product6_out1_s140=addSignal(symDemodQPSKScalar,'Product6_out1',pirTyp10,slRate1);
    Product7_out1_s141=addSignal(symDemodQPSKScalar,'Product7_out1',pirTyp10,slRate1);
    RelationalOperator2_out1_s142=addSignal(symDemodQPSKScalar,'Relational Operator2_out1',pirTyp2,slRate1);
    RelationalOperator3_out1_s143=addSignal(symDemodQPSKScalar,'Relational Operator3_out1',pirTyp2,slRate1);
    Selector1_out1_s144=addSignal(symDemodQPSKScalar,'Selector1_out1',pirTyp2,slRate1);
    Selector10_out1_s145=addSignal(symDemodQPSKScalar,'Selector10_out1',pirTyp7,slRate1);
    Selector11_out1_s146=addSignal(symDemodQPSKScalar,'Selector11_out1',pirTyp8,slRate1);
    Selector12_out1_s147=addSignal(symDemodQPSKScalar,'Selector12_out1',pirTyp3,slRate1);
    Selector13_out1_s148=addSignal(symDemodQPSKScalar,'Selector13_out1',pirTyp7,slRate1);
    Selector2_out1_s149=addSignal(symDemodQPSKScalar,'Selector2_out1',pirTyp3,slRate1);
    Selector3_out1_s150=addSignal(symDemodQPSKScalar,'Selector3_out1',pirTyp8,slRate1);
    Selector4_out1_s151=addSignal(symDemodQPSKScalar,'Selector4_out1',pirTyp8,slRate1);
    Selector5_out1_s152=addSignal(symDemodQPSKScalar,'Selector5_out1',pirTyp3,slRate1);
    Selector6_out1_s153=addSignal(symDemodQPSKScalar,'Selector6_out1',pirTyp3,slRate1);
    Selector7_out1_s154=addSignal(symDemodQPSKScalar,'Selector7_out1',pirTyp7,slRate1);
    Selector8_out1_s155=addSignal(symDemodQPSKScalar,'Selector8_out1',pirTyp8,slRate1);
    Selector9_out1_s156=addSignal(symDemodQPSKScalar,'Selector9_out1',pirTyp7,slRate1);
    Subtract1_out1_s157=addSignal(symDemodQPSKScalar,'Subtract1_out1',pirTyp11,slRate1);
    Subtract2_out1_s158=addSignal(symDemodQPSKScalar,'Subtract2_out1',pirTyp11,slRate1);
    Subtract3_out1_s159=addSignal(symDemodQPSKScalar,'Subtract3_out1',pirTyp11,slRate1);
    Subtract4_out1_s160=addSignal(symDemodQPSKScalar,'Subtract4_out1',pirTyp4,slRate1);
    Subtract5_out1_s161=addSignal(symDemodQPSKScalar,'Subtract5_out1',pirTyp11,slRate1);
    Switch_out1_s162=addSignal(symDemodQPSKScalar,'Switch_out1',pirTyp7,slRate1);
    Switch1_out1_s163=addSignal(symDemodQPSKScalar,'Switch1_out1',pirTyp3,slRate1);
    Switch11_out1_s165=addSignal(symDemodQPSKScalar,'Switch11_out1',pirTyp7,slRate1);
    Switch12_out1_s166=addSignal(symDemodQPSKScalar,'Switch12_out1',pirTyp3,slRate1);
    Switch2_out1_s167=addSignal(symDemodQPSKScalar,'Switch2_out1',pirTyp3,slRate1);
    Switch3_out1_s168=addSignal(symDemodQPSKScalar,'Switch3_out1',pirTyp7,slRate1);
    Switch4_out1_s169=addSignal(symDemodQPSKScalar,'Switch4_out1',pirTyp7,slRate1);
    Switch5_out1_s170=addSignal(symDemodQPSKScalar,'Switch5_out1',pirTyp7,slRate1);
    Switch6_out1_s171=addSignal(symDemodQPSKScalar,'Switch6_out1',pirTyp7,slRate1);
    Switch7_out1_s172=addSignal(symDemodQPSKScalar,'Switch7_out1',pirTyp7,slRate1);
    Switch8_out1_s173=addSignal(symDemodQPSKScalar,'Switch8_out1',pirTyp7,slRate1);
    Switch9_out1_s174=addSignal(symDemodQPSKScalar,'Switch9_out1',pirTyp7,slRate1);
    UnaryMinus_out1_s175=addSignal(symDemodQPSKScalar,'Unary Minus_out1',pirTyp3,slRate1);
    concatenate_out1_s176=addSignal(symDemodQPSKScalar,'concatenate_out1',pirelab.createPirArrayType(pirTyp2,[2,0]),slRate1);
    cos4_out1_s177=addSignal(symDemodQPSKScalar,'cos4_out1',pirTyp8,slRate1);
    delayMatch_out1_s178=addSignal(symDemodQPSKScalar,'delayMatch_out1',pirTyp8,slRate1);
    delayMatch1_out1_s179=addSignal(symDemodQPSKScalar,'delayMatch1_out1',pirTyp8,slRate1);
    delayMatch10_out1_s180=addSignal(symDemodQPSKScalar,'delayMatch10_out1',pirTyp7,slRate1);
    delayMatch11_out1_s181=addSignal(symDemodQPSKScalar,'delayMatch11_out1',pirTyp2,slRate1);
    delayMatch12_out1_s182=addSignal(symDemodQPSKScalar,'delayMatch12_out1',pirTyp2,slRate1);
    delayMatch2_out1_s184=addSignal(symDemodQPSKScalar,'delayMatch2_out1',pirTyp7,slRate1);
    delayMatch3_out1_s185=addSignal(symDemodQPSKScalar,'delayMatch3_out1',pirTyp8,slRate1);
    delayMatch4_out1_s186=addSignal(symDemodQPSKScalar,'delayMatch4_out1',pirTyp7,slRate1);
    delayMatch5_out1_s187=addSignal(symDemodQPSKScalar,'delayMatch5_out1',pirTyp8,slRate1);
    delayMatch6_out1_s188=addSignal(symDemodQPSKScalar,'delayMatch6_out1',pirTyp2,slRate1);
    delayMatch7_out1_s189=addSignal(symDemodQPSKScalar,'delayMatch7_out1',pirTyp2,slRate1);
    delayMatch8_out1_s190=addSignal(symDemodQPSKScalar,'delayMatch8_out1',pirTyp2,slRate1);
    delayMatch9_out1_s191=addSignal(symDemodQPSKScalar,'delayMatch9_out1',pirTyp2,slRate1);
    lookUpTable4Im_out1_s192=addSignal(symDemodQPSKScalar,'lookUpTable4Im_out1',pirelab.createPirArrayType(pirTyp8,[3,0]),slRate1);
    lookUpTable4Re_out1_s193=addSignal(symDemodQPSKScalar,'lookUpTable4Re_out1',pirelab.createPirArrayType(pirTyp8,[3,0]),slRate1);
    sin4_out1_s194=addSignal(symDemodQPSKScalar,'sin4_out1',pirTyp8,slRate1);
    stateControl_out1_s195=addSignal(symDemodQPSKScalar,'stateControl_out1',pirTyp2,slRate1);
    stateControl1_out1_s196=addSignal(symDemodQPSKScalar,'stateControl1_out1',pirTyp2,slRate1);
    t_out1_s197=addSignal(symDemodQPSKScalar,'t_out1',pirTyp7,slRate1);
    t1_out1_s198=addSignal(symDemodQPSKScalar,'t1_out1',pirTyp7,slRate1);
    t2_out1_s199=addSignal(symDemodQPSKScalar,'t2_out1',pirTyp7,slRate1);
    t3_out1_s200=addSignal(symDemodQPSKScalar,'t3_out1',pirTyp7,slRate1);
    t4_out1_s201=addSignal(symDemodQPSKScalar,'t4_out1',pirTyp7,slRate1);
    t5_out1_s202=addSignal(symDemodQPSKScalar,'t5_out1',pirTyp7,slRate1);
    Abs_out1_s240=addSignal(symDemodQPSKScalar,'Abs_out1',pirTyp3,slRate1);
    Abs1_out1_s241=addSignal(symDemodQPSKScalar,'Abs1_out1',pirTyp3,slRate1);
    Delay2_out1_s242=addSignal(symDemodQPSKScalar,'Delay2_out1',pirTyp2,slRate1);
    Delay3_out1_s243=addSignal(symDemodQPSKScalar,'Delay3_out1',pirTyp3,slRate1);
    Delay4_out1_s244=addSignal(symDemodQPSKScalar,'Delay4_out1',pirTyp3,slRate1);
    Subsystem1_out1_s245=addSignal(symDemodQPSKScalar,'Subsystem1_out1',pirTyp2,slRate1);
    Switch_out1_s246=addSignal(symDemodQPSKScalar,'Switch_out1',pirTyp3,slRate1);
    Switch1_out1_s247=addSignal(symDemodQPSKScalar,'Switch1_out1',pirTyp2,slRate1);
    Switch2_out1_s248=addSignal(symDemodQPSKScalar,'Switch2_out1',pirTyp3,slRate1);
    delayMatch_out1_s249=addSignal(symDemodQPSKScalar,'delayMatch_out1',pirTyp2,slRate1);
    delayMatch1_out1_s250=addSignal(symDemodQPSKScalar,'delayMatch1_out1',pirTyp3,slRate1);
    delayMatch2_out1_s251=addSignal(symDemodQPSKScalar,'delayMatch2_out1',pirTyp2,slRate1);
    delayMatch3_out1_s252=addSignal(symDemodQPSKScalar,'delayMatch3_out1',pirTyp3,slRate1);
    AND_out1_s253=addSignal(symDemodQPSKScalar,'AND_out1',pirTyp2,slRate1);
    Add_out1_s254=addSignal(symDemodQPSKScalar,'Add_out1',pirTyp5,slRate1);
    CompareToConstant_out1_s255=addSignal(symDemodQPSKScalar,'Compare To Constant_out1',pirTyp2,slRate1);
    CompareToConstant1_out1_s256=addSignal(symDemodQPSKScalar,'Compare To Constant1_out1',pirTyp2,slRate1);
    CompareToConstant2_out1_s257=addSignal(symDemodQPSKScalar,'Compare To Constant2_out1',pirTyp2,slRate1);
    Constant_out1_s258=addSignal(symDemodQPSKScalar,'Constant_out1',pirTyp7,slRate1);
    Constant1_out1_s259=addSignal(symDemodQPSKScalar,'Constant1_out1',pirTyp7,slRate1);
    Constant4_out1_s260=addSignal(symDemodQPSKScalar,'Constant4_out1',pirTyp7,slRate1);
    Constant5_out1_s261=addSignal(symDemodQPSKScalar,'Constant5_out1',pirTyp7,slRate1);
    DataTypeConversion_out1_s262=addSignal(symDemodQPSKScalar,'Data Type Conversion_out1',pirTyp7,slRate1);
    Delay_out1_s263=addSignal(symDemodQPSKScalar,'Delay_out1',pirTyp7,slRate1);
    Delay1_out1_s264=addSignal(symDemodQPSKScalar,'Delay1_out1',pirTyp7,slRate1);
    From_out1_s265=addSignal(symDemodQPSKScalar,'From_out1',pirTyp7,slRate1);
    From1_out1_s266=addSignal(symDemodQPSKScalar,'From1_out1',pirTyp7,slRate1);
    From2_out1_s267=addSignal(symDemodQPSKScalar,'From2_out1',pirTyp7,slRate1);
    From3_out1_s268=addSignal(symDemodQPSKScalar,'From3_out1',pirTyp7,slRate1);
    From4_out1_s269=addSignal(symDemodQPSKScalar,'From4_out1',pirTyp7,slRate1);
    From5_out1_s270=addSignal(symDemodQPSKScalar,'From5_out1',pirTyp7,slRate1);
    Switch_out1_s271=addSignal(symDemodQPSKScalar,'Switch_out1',pirTyp7,slRate1);
    Switch1_out1_s272=addSignal(symDemodQPSKScalar,'Switch1_out1',pirTyp7,slRate1);
    Switch2_out1_s273=addSignal(symDemodQPSKScalar,'Switch2_out1',pirTyp7,slRate1);
    Switch3_out1_s274=addSignal(symDemodQPSKScalar,'Switch3_out1',pirTyp7,slRate1);
    Switch4_out1_s275=addSignal(symDemodQPSKScalar,'Switch4_out1',pirTyp7,slRate1);
    Switch5_out1_s276=addSignal(symDemodQPSKScalar,'Switch5_out1',pirTyp7,slRate1);
    CNT_s277=addSignal(symDemodQPSKScalar,'CNT',pirTyp7,slRate1);
    STOP_s278=addSignal(symDemodQPSKScalar,'STOP',pirTyp7,slRate1);
    count_s279=addSignal(symDemodQPSKScalar,'count',pirTyp7,slRate1);
    stateInternal_s280=addSignal(symDemodQPSKScalar,'stateInternal',pirTyp7,slRate1);


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant_out1_s258,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant1_out1_s259,...
    fi(0,nt1,fiMath1,'hex','00'),...
    'Constant1','on',1,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant4_out1_s260,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant4','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant5_out1_s261,...
    fi(0,nt1,fiMath1,'hex','00'),...
    'Constant5','on',1,'','','');


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch_out1_s271,...
    Delay_out1_s263,...
    1,'Delay',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch3_out1_s274,...
    Delay1_out1_s264,...
    1,'Delay1',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getWireComp(symDemodQPSKScalar,...
    CNT_s277,...
    From_out1_s265,...
    'From');


    pirelab.getWireComp(symDemodQPSKScalar,...
    STOP_s278,...
    From1_out1_s266,...
    'From1');


    pirelab.getWireComp(symDemodQPSKScalar,...
    count_s279,...
    From2_out1_s267,...
    'From2');


    pirelab.getWireComp(symDemodQPSKScalar,...
    STOP_s278,...
    From3_out1_s268,...
    'From3');


    pirelab.getWireComp(symDemodQPSKScalar,...
    CNT_s277,...
    From4_out1_s269,...
    'From4');


    pirelab.getWireComp(symDemodQPSKScalar,...
    stateInternal_s280,...
    From5_out1_s270,...
    'From5');


    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay_out1_s263,...
    stateInternal_s280,...
    'Goto');


    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay1_out1_s264,...
    count_s279,...
    'Goto1');


    pirelab.getWireComp(symDemodQPSKScalar,...
    Constant4_out1_s260,...
    CNT_s277,...
    'Goto2');


    pirelab.getWireComp(symDemodQPSKScalar,...
    Constant5_out1_s261,...
    STOP_s278,...
    'Goto3');


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch1_out1_s247,...
    Delay2_out1_s242,...
    1,'Delay2',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Abs_out1_s240,...
    Delay3_out1_s243,...
    1,'Delay3',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Abs1_out1_s241,...
    Delay4_out1_s244,...
    1,'Delay4',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    AND1_out1_s3,...
    delayMatch_out1_s249,...
    2,'delayMatch',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch_out1_s246,...
    delayMatch1_out1_s250,...
    1,'delayMatch1',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    AND1_out1_s3,...
    delayMatch2_out1_s251,...
    2,'delayMatch2',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch2_out1_s248,...
    delayMatch3_out1_s252,...
    1,'delayMatch3',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);

    pirelab.getWireComp(symDemodQPSKScalar,...
    AND_out1_s253,...
    Subsystem1_out1_s245,...
    'Subsystem1_out1');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant_out1_s16,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant1_out1_s17,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant1','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant10_out1_s18,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant10','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant11_out1_s19,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant11','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant12_out1_s20,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant12','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant13_out1_s21,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant13','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant14_out1_s22,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant14','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant15_out1_s23,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant15','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant16_out1_s24,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant16','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant17_out1_s25,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant17','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant18_out1_s26,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant18','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant19_out1_s27,...
    [fi(0,nt1,fiMath1,'hex','03'),fi(0,nt1,fiMath1,'hex','02')],...
    'Constant19','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant2_out1_s28,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant2','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant3_out1_s29,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant3','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant4_out1_s30,...
    [fi(0,nt1,fiMath1,'hex','03'),fi(0,nt1,fiMath1,'hex','02')],...
    'Constant4','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant5_out1_s31,...
    fi(0,nt2,fiMath1,'hex','00000'),...
    'Constant5','on',1,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant6_out1_s32,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant6','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant7_out1_s33,...
    fi(0,nt1,fiMath1,'hex','00'),...
    'Constant7','on',1,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant8_out1_s34,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Constant8','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Constant9_out1_s35,...
    fi(0,nt1,fiMath1,'hex','02'),...
    'Constant9','on',0,'','','');


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Add_out1_s4,...
    Delay_out1_s51,...
    1,'Delay',...
    fi(0,nt3,fiMath1,'hex','000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    OR_out1_s121,...
    Delay1_out1_s52,...
    1,'Delay1',...
    false,...
    0,0,[],0,0);


    pirelab.getConstComp(symDemodQPSKScalar,...
    Delay1_Initial_Val_out1_s53,...
    fi(0,nt4,fiMath1,'hex','1'),...
    'Delay1_Initial_Val','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Delay1_ctrl_const_out1_s54,...
    fi(0,nt4,fiMath1,'hex','1'),...
    'Delay1_ctrl_const','on',0,'','','');


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay1_ctrl_const_out1_s54,...
    Delay1_ctrl_delay_out1_s55,...
    1,'Delay1_ctrl_delay',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay2_enbsw_out1_s58,...
    Delay2_out1_s57,...
    1,'Delay2',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch5_out1_s170,...
    Delay3_out1_s59,...
    1,'Delay3',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getConstComp(symDemodQPSKScalar,...
    Delay3_Initial_Val_out1_s60,...
    fi(0,nt1,fiMath1,'hex','01'),...
    'Delay3_Initial_Val','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    Delay3_ctrl_const_out1_s61,...
    fi(0,nt4,fiMath1,'hex','1'),...
    'Delay3_ctrl_const','on',0,'','','');


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay3_ctrl_const_out1_s61,...
    Delay3_ctrl_delay_out1_s62,...
    1,'Delay3_ctrl_delay',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch6_out1_s171,...
    Delay4_out1_s64,...
    1,'Delay4',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay5_enbsw_out1_s66,...
    Delay5_out1_s65,...
    1,'Delay5',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Add1_out1_s5,...
    Delay6_out1_s67,...
    1,'Delay6',...
    fi(0,nt3,fiMath1,'hex','000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector1_out1_s144,...
    Delay7_out1_s68,...
    1,'Delay7',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From27_out1_s82,...
    Delay8_out1_s69,...
    1,'Delay8',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From11_out1_s72,...
    HwModeRegister_out1_s104,...
    1,'HwModeRegister',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From11_out1_s72,...
    HwModeRegister1_out1_s105,...
    1,'HwModeRegister1',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    ComplexToReal_Imag3_out2_s15,...
    HwModeRegister10_out1_s106,...
    1,'HwModeRegister10',...
    fi(0,nt5,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    sin4_out1_s194,...
    HwModeRegister11_out1_s107,...
    1,'HwModeRegister11',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    ComplexToReal_Imag3_out1_s14,...
    HwModeRegister12_out1_s108,...
    1,'HwModeRegister12',...
    fi(0,nt5,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    sin4_out1_s194,...
    HwModeRegister13_out1_s109,...
    1,'HwModeRegister13',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    cos4_out1_s177,...
    HwModeRegister14_out1_s110,...
    1,'HwModeRegister14',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    ComplexToReal_Imag3_out2_s15,...
    HwModeRegister15_out1_s111,...
    1,'HwModeRegister15',...
    fi(0,nt5,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From12_out1_s73,...
    HwModeRegister2_out1_s112,...
    1,'HwModeRegister2',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From12_out1_s73,...
    HwModeRegister3_out1_s113,...
    1,'HwModeRegister3',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From13_out1_s74,...
    HwModeRegister4_out1_s114,...
    1,'HwModeRegister4',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From13_out1_s74,...
    HwModeRegister5_out1_s115,...
    1,'HwModeRegister5',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From14_out1_s75,...
    HwModeRegister6_out1_s116,...
    1,'HwModeRegister6',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    From14_out1_s75,...
    HwModeRegister7_out1_s117,...
    1,'HwModeRegister7',...
    fi(0,nt2,fiMath1,'hex','00000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    cos4_out1_s177,...
    HwModeRegister8_out1_s118,...
    1,'HwModeRegister8',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    ComplexToReal_Imag3_out1_s14,...
    HwModeRegister9_out1_s119,...
    1,'HwModeRegister9',...
    fi(0,nt5,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product_out1_s134,...
    PipelineRegister_out1_s126,...
    2,'PipelineRegister',...
    fi(0,nt7,fiMath1,'hex','0000000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product1_out1_s135,...
    PipelineRegister1_out1_s127,...
    2,'PipelineRegister1',...
    fi(0,nt7,fiMath1,'hex','0000000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product2_out1_s136,...
    PipelineRegister2_out1_s128,...
    2,'PipelineRegister2',...
    fi(0,nt7,fiMath1,'hex','0000000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product3_out1_s137,...
    PipelineRegister3_out1_s129,...
    2,'PipelineRegister3',...
    fi(0,nt7,fiMath1,'hex','0000000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product4_out1_s138,...
    PipelineRegister4_out1_s130,...
    1,'PipelineRegister4',...
    fi(0,nt8,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product5_out1_s139,...
    PipelineRegister5_out1_s131,...
    1,'PipelineRegister5',...
    fi(0,nt8,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product6_out1_s140,...
    PipelineRegister6_out1_s132,...
    1,'PipelineRegister6',...
    fi(0,nt8,fiMath1,'hex','00000000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Product7_out1_s141,...
    PipelineRegister7_out1_s133,...
    1,'PipelineRegister7',...
    fi(0,nt8,fiMath1,'hex','00000000'),...
    0,0,[],0,0);






    pirelab.getConstComp(symDemodQPSKScalar,cos4_out1_s177,blockInfo.LUTvalueReal);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector4_out1_s151,...
    delayMatch_out1_s178,...
    2,'delayMatch',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector3_out1_s150,...
    delayMatch1_out1_s179,...
    2,'delayMatch1',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Switch_out1_s162,...
    delayMatch10_out1_s180,...
    2,'delayMatch10',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay7_out1_s68,...
    delayMatch11_out1_s181,...
    3,'delayMatch11',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay8_out1_s69,...
    delayMatch12_out1_s182,...
    5,'delayMatch12',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Delay8_out1_s69,...
    delayMatch13_out1_s183,...
    5,'delayMatch13',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector7_out1_s154,...
    delayMatch2_out1_s184,...
    2,'delayMatch2',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector8_out1_s155,...
    delayMatch3_out1_s185,...
    2,'delayMatch3',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector10_out1_s145,...
    delayMatch4_out1_s186,...
    2,'delayMatch4',...
    uint8(0),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    Selector11_out1_s146,...
    delayMatch5_out1_s187,...
    2,'delayMatch5',...
    fi(0,nt6,fiMath1,'hex','0000'),...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    AND1_out1_s3,...
    delayMatch6_out1_s188,...
    2,'delayMatch6',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    stateControl_out1_s195,...
    delayMatch7_out1_s189,...
    2,'delayMatch7',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    AND1_out1_s3,...
    delayMatch8_out1_s190,...
    2,'delayMatch8',...
    false,...
    0,0,[],0,0);


    pirelab.getIntDelayComp(symDemodQPSKScalar,...
    stateControl1_out1_s196,...
    delayMatch9_out1_s191,...
    2,'delayMatch9',...
    false,...
    0,0,[],0,0);


    pirelab.getConstComp(symDemodQPSKScalar,...
    lookUpTable4Im_out1_s192,...
    [fi(0,nt6,fiMath1,'hex','2d41'),fi(0,nt6,fiMath1,'hex','2d41'),fi(0,nt6,fiMath1,'hex','d2be')],...
    'lookUpTable4Im','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    lookUpTable4Re_out1_s193,...
    [fi(0,nt6,fiMath1,'hex','2d41'),fi(0,nt6,fiMath1,'hex','d2be'),fi(0,nt6,fiMath1,'hex','2d41')],...
    'lookUpTable4Re','on',0,'','','');






    pirelab.getConstComp(symDemodQPSKScalar,sin4_out1_s194,blockInfo.LUTvalueImag);


    pirelab.getConstComp(symDemodQPSKScalar,...
    stateControl_out1_s195,...
    fi(0,nt4,fiMath1,'hex','1'),...
    'stateControl','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    stateControl1_out1_s196,...
    fi(0,nt4,fiMath1,'hex','1'),...
    'stateControl1','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    t_out1_s197,...
    fi(0,nt1,fiMath1,'hex','01'),...
    't','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    t2_out1_s199,...
    fi(0,nt1,fiMath1,'hex','01'),...
    't2','on',0,'','','');


    pirelab.getConstComp(symDemodQPSKScalar,...
    t4_out1_s201,...
    fi(0,nt1,fiMath1,'hex','01'),...
    't4','on',0,'','','');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto2_out1_s96,...
    From_out1_s70,...
    'From_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto26_out1_s98,...
    From1_out1_s71,...
    'From1_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto11_out1_s90,...
    From11_out1_s72,...
    'From11_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto12_out1_s91,...
    From12_out1_s73,...
    'From12_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto13_out1_s92,...
    From13_out1_s74,...
    'From13_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto14_out1_s93,...
    From14_out1_s75,...
    'From14_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto26_out1_s98,...
    From15_out1_s76,...
    'From15_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto15_out1_s94,...
    From19_out1_s77,...
    'From19_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto3_out1_s99,...
    From2_out1_s78,...
    'From2_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto26_out1_s98,...
    From20_out1_s79,...
    'From20_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto19_out1_s95,...
    From21_out1_s80,...
    'From21_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto19_out1_s95,...
    From26_out1_s81,...
    'From26_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto5_out1_s101,...
    From27_out1_s82,...
    'From27_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto26_out1_s98,...
    From28_out1_s83,...
    'From28_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto4_out1_s100,...
    From3_out1_s84,...
    'From3_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto21_out1_s97,...
    From4_out1_s85,...
    'From4_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto5_out1_s101,...
    From5_out1_s86,...
    'From5_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto9_out1_s103,...
    From6_out1_s87,...
    'From6_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto6_out1_s102,...
    From7_out1_s88,...
    'From7_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Goto26_out1_s98,...
    From8_out1_s89,...
    'From8_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    DataTypeConversion7_out1_s48,...
    Goto11_out1_s90,...
    'Goto11_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    DataTypeConversion9_out1_s50,...
    Goto12_out1_s91,...
    'Goto12_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    DataTypeConversion8_out1_s49,...
    Goto13_out1_s92,...
    'Goto13_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    DataTypeConversion10_out1_s38,...
    Goto14_out1_s93,...
    'Goto14_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    DataTypeConversion6_out1_s47,...
    Goto15_out1_s94,...
    'Goto15_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay1_switch_out1_s56,...
    Goto19_out1_s95,...
    'Goto19_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay5_out1_s65,...
    Goto2_out1_s96,...
    'Goto2_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Switch6_out1_s171,...
    Goto21_out1_s97,...
    'Goto21_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay3_switch_out1_s63,...
    Goto26_out1_s98,...
    'Goto26_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay2_out1_s57,...
    Goto3_out1_s99,...
    'Goto3_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    PSKSymbolConverterBlock_out2_s124,...
    Goto4_out1_s100,...
    'Goto4_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    PSKSymbolConverterBlock_out3_s125,...
    Goto5_out1_s101,...
    'Goto5_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    PSKSymbolConverterBlock_out1_s123,...
    Goto6_out1_s102,...
    'Goto6_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    AND1_out1_s3,...
    Goto9_out1_s103,...
    'Goto9_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay3_out1_s243,...
    PSKSymbolConverterBlock_out1_s123,...
    'PSKSymbolConverterBlock_out1');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay4_out1_s244,...
    PSKSymbolConverterBlock_out2_s124,...
    'PSKSymbolConverterBlock_out2');

    pirelab.getWireComp(symDemodQPSKScalar,...
    Delay2_out1_s242,...
    PSKSymbolConverterBlock_out3_s125,...
    'PSKSymbolConverterBlock_out3');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    [CompareToConstant5_out1_s13,NOT_out1_s120],...
    AND_out1_s2,...
    'and','AND');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    [validIn_s1,From26_out1_s81],...
    AND1_out1_s3,...
    'and','AND1');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [DataTypeConversion_out1_s36,DataTypeConversion1_out1_s37],...
    Add_out1_s4,...
    'Floor','Wrap','Add',pirTyp4,'++');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [DataTypeConversion2_out1_s43,DataTypeConversion3_out1_s44],...
    Add1_out1_s5,...
    'Floor','Wrap','Add1',pirTyp4,'++');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Delay3_switch_out1_s63,Constant10_out1_s18],...
    Add2_out1_s6,...
    'Floor','Wrap','Add2',pirTyp5,'++');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Delay4_out1_s64,Constant8_out1_s34],...
    Add3_out1_s7,...
    'Floor','Wrap','Add3',pirTyp5,'++');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [PipelineRegister4_out1_s130,PipelineRegister5_out1_s131],...
    Add4_out1_s8,...
    'Floor','Wrap','Add4',pirTyp6,'+-');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [PipelineRegister7_out1_s133,PipelineRegister6_out1_s132],...
    Add5_out1_s9,...
    'Floor','Wrap','Add5',pirTyp6,'++');


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    From_out1_s70,...
    CompareToConstant_out1_s10,...
    '>',fi(0,nt2,fiMath1,'hex','00000'),...
    'Compare To Constant',1);


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    From2_out1_s78,...
    CompareToConstant1_out1_s11,...
    '>',fi(0,nt2,fiMath1,'hex','00000'),...
    'Compare To Constant1',1);


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    From4_out1_s85,...
    CompareToConstant2_out1_s12,...
    '==',fi(0,nt1,fiMath1,'hex','01'),...
    'Compare To Constant2',0);


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    From4_out1_s85,...
    CompareToConstant5_out1_s13,...
    '==',fi(0,nt1,fiMath1,'hex','00'),...
    'Compare To Constant5',1);


    pirelab.getComplex2RealImag(symDemodQPSKScalar,...
    dataIn_s0,...
    [ComplexToReal_Imag3_out1_s14,ComplexToReal_Imag3_out2_s15],...
    'Real and imag',...
    'Complex to Real-Imag3');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    PipelineRegister_out1_s126,...
    DataTypeConversion_out1_s36,...
    'Floor','Wrap','RWV','Data Type Conversion');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    PipelineRegister1_out1_s127,...
    DataTypeConversion1_out1_s37,...
    'Floor','Wrap','RWV','Data Type Conversion1');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Subtract2_out1_s158,...
    DataTypeConversion10_out1_s38,...
    'Floor','Wrap','RWV','Data Type Conversion10');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Add2_out1_s6,...
    DataTypeConversion11_out1_s39,...
    'Floor','Wrap','RWV','Data Type Conversion11');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Add3_out1_s7,...
    DataTypeConversion12_out1_s40,...
    'Floor','Wrap','RWV','Data Type Conversion12');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Add4_out1_s8,...
    DataTypeConversion13_out1_s41,...
    'Floor','Wrap','RWV','Data Type Conversion13');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Add5_out1_s9,...
    DataTypeConversion14_out1_s42,...
    'Floor','Wrap','RWV','Data Type Conversion14');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    PipelineRegister2_out1_s128,...
    DataTypeConversion2_out1_s43,...
    'Floor','Wrap','RWV','Data Type Conversion2');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    PipelineRegister3_out1_s129,...
    DataTypeConversion3_out1_s44,...
    'Floor','Wrap','RWV','Data Type Conversion3');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Delay_out1_s51,...
    DataTypeConversion4_out1_s45,...
    'Floor','Wrap','RWV','Data Type Conversion4');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Delay6_out1_s67,...
    DataTypeConversion5_out1_s46,...
    'Floor','Wrap','RWV','Data Type Conversion5');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Subtract4_out1_s160,...
    DataTypeConversion6_out1_s47,...
    'Floor','Wrap','RWV','Data Type Conversion6');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Subtract3_out1_s159,...
    DataTypeConversion7_out1_s48,...
    'Floor','Wrap','RWV','Data Type Conversion7');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Subtract1_out1_s157,...
    DataTypeConversion8_out1_s49,...
    'Floor','Wrap','RWV','Data Type Conversion8');


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Subtract5_out1_s161,...
    DataTypeConversion9_out1_s50,...
    'Floor','Wrap','RWV','Data Type Conversion9');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Delay1_out1_s52,Delay1_Initial_Val_out1_s53],...
    Delay1_switch_out1_s56,...
    Delay1_ctrl_delay_out1_s55,'Delay1_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch1_out1_s163,Delay2_out1_s57],...
    Delay2_enbsw_out1_s58,...
    delayMatch7_out1_s189,'Delay2_enbsw',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Delay3_out1_s59,Delay3_Initial_Val_out1_s60],...
    Delay3_switch_out1_s63,...
    Delay3_ctrl_delay_out1_s62,'Delay3_switch',...
    '~=',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch12_out1_s166,Delay5_out1_s65],...
    Delay5_enbsw_out1_s66,...
    delayMatch9_out1_s191,'Delay5_enbsw',...
    '~=',0,'Floor','Wrap');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    From6_out1_s87,...
    NOT_out1_s120,...
    'not','NOT');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    [CompareToConstant2_out1_s12,AND_out1_s2],...
    OR_out1_s121,...
    'or','OR');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    [From6_out1_s87,From21_out1_s80],...
    OR1_out1_s122,...
    'or','OR1');


    pirelab.getAbsComp(symDemodQPSKScalar,...
    Switch_out1_s246,...
    Abs_out1_s240,...
    'Floor','Wrap','Abs');


    pirelab.getAbsComp(symDemodQPSKScalar,...
    Switch2_out1_s248,...
    Abs1_out1_s241,...
    'Floor','Wrap','Abs1');


    pirelab.getLogicComp(symDemodQPSKScalar,...
    [CompareToConstant1_out1_s256,CompareToConstant2_out1_s257],...
    AND_out1_s253,...
    'and','AND');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Delay1_out1_s264,Constant_out1_s258],...
    Add_out1_s254,...
    'Floor','Wrap','Add',pirTyp5,'++');


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    From2_out1_s267,...
    CompareToConstant_out1_s255,...
    '==',fi(0,nt1,fiMath1,'hex','01'),...
    'Compare To Constant',0);


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    Delay1_out1_s264,...
    CompareToConstant1_out1_s256,...
    '<=',fi(0,nt1,fiMath1,'hex','01'),...
    'Compare To Constant1',0);


    pirelab.getCompareToValueComp(symDemodQPSKScalar,...
    Delay1_out1_s264,...
    CompareToConstant2_out1_s257,...
    '>=',fi(0,nt1,fiMath1,'hex','01'),...
    'Compare To Constant2',0);


    pirelab.getDTCComp(symDemodQPSKScalar,...
    Add_out1_s254,...
    DataTypeConversion_out1_s262,...
    'Floor','Wrap','RWV','Data Type Conversion');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch2_out1_s273,Switch1_out1_s272],...
    Switch_out1_s271,...
    Delay_out1_s263,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From_out1_s265,From1_out1_s266],...
    Switch1_out1_s272,...
    AND1_out1_s3,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From3_out1_s268,From4_out1_s269],...
    Switch2_out1_s273,...
    CompareToConstant_out1_s255,'Switch2',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch5_out1_s276,Switch4_out1_s275],...
    Switch3_out1_s274,...
    From5_out1_s270,'Switch3',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Constant_out1_s258,Constant1_out1_s259],...
    Switch4_out1_s275,...
    AND1_out1_s3,'Switch4',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Constant1_out1_s259,DataTypeConversion_out1_s262],...
    Switch5_out1_s276,...
    CompareToConstant_out1_s255,'Switch5',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion13_out1_s41,delayMatch1_out1_s250],...
    Switch_out1_s246,...
    delayMatch_out1_s249,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [AND1_out1_s3,Subsystem1_out1_s245],...
    Switch1_out1_s247,...
    AND1_out1_s3,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion14_out1_s42,delayMatch3_out1_s252],...
    Switch2_out1_s248,...
    delayMatch2_out1_s251,'Switch2',...
    '>',0,'Floor','Wrap');


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister_out1_s104,HwModeRegister1_out1_s105],...
    Product_out1_s134,...
    'Floor','Wrap','Product','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister2_out1_s112,HwModeRegister3_out1_s113],...
    Product1_out1_s135,...
    'Floor','Wrap','Product1','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister4_out1_s114,HwModeRegister5_out1_s115],...
    Product2_out1_s136,...
    'Floor','Wrap','Product2','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister6_out1_s116,HwModeRegister7_out1_s117],...
    Product3_out1_s137,...
    'Floor','Wrap','Product3','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister8_out1_s118,HwModeRegister9_out1_s119],...
    Product4_out1_s138,...
    'Floor','Wrap','Product4','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister10_out1_s106,HwModeRegister11_out1_s107],...
    Product5_out1_s139,...
    'Floor','Wrap','Product5','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister12_out1_s108,HwModeRegister13_out1_s109],...
    Product6_out1_s140,...
    'Floor','Wrap','Product6','**','',-1,0);


    pirelab.getMulComp(symDemodQPSKScalar,...
    [HwModeRegister14_out1_s110,HwModeRegister15_out1_s111],...
    Product7_out1_s141,...
    'Floor','Wrap','Product7','**','',-1,0);


    pirelab.getRelOpComp(symDemodQPSKScalar,...
    [Delay4_out1_s64,Constant6_out1_s32],...
    RelationalOperator2_out1_s142,...
    '<=',0,'Relational Operator2');


    pirelab.getRelOpComp(symDemodQPSKScalar,...
    [Delay3_switch_out1_s63,Constant9_out1_s35],...
    RelationalOperator3_out1_s143,...
    '<',0,'Relational Operator3');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [concatenate_out1_s176,t5_out1_s202],...
    Selector1_out1_s144,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector1');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [Constant17_out1_s25,Switch9_out1_s174],...
    Selector10_out1_s145,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector10');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [lookUpTable4Im_out1_s192,Selector13_out1_s148],...
    Selector11_out1_s146,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector11');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [From7_out1_s88,Constant_out1_s16],...
    Selector12_out1_s147,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector12');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [Constant19_out1_s27,Switch11_out1_s165],...
    Selector13_out1_s148,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector13');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [From3_out1_s84,Constant14_out1_s22],...
    Selector2_out1_s149,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector2');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [lookUpTable4Im_out1_s192,Constant15_out1_s23],...
    Selector3_out1_s150,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector3');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [lookUpTable4Re_out1_s193,Constant1_out1_s17],...
    Selector4_out1_s151,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector4');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [From3_out1_s84,t3_out1_s200],...
    Selector5_out1_s152,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector5');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [From7_out1_s88,t1_out1_s198],...
    Selector6_out1_s153,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector6');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [Constant2_out1_s28,Switch3_out1_s168],...
    Selector7_out1_s154,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector7');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [lookUpTable4Re_out1_s193,Selector9_out1_s156],...
    Selector8_out1_s155,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector8');


    indexParamArray={1:3};
    pirelab.getSelectorComp(symDemodQPSKScalar,...
    [Constant4_out1_s30,Switch8_out1_s173],...
    Selector9_out1_s156,...
    'One-based',{'Starting index (port)'},...
    indexParamArray,...
    {'1'},'1',...
    'Selector9');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Selector6_out1_s153,delayMatch3_out1_s185],...
    Subtract1_out1_s157,...
    'Floor','Wrap','Subtract1',pirTyp11,'+-');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Selector5_out1_s152,delayMatch5_out1_s187],...
    Subtract2_out1_s158,...
    'Floor','Wrap','Subtract2',pirTyp11,'+-');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Selector12_out1_s147,delayMatch_out1_s178],...
    Subtract3_out1_s159,...
    'Floor','Wrap','Subtract3',pirTyp11,'+-');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [DataTypeConversion4_out1_s45,DataTypeConversion5_out1_s46],...
    Subtract4_out1_s160,...
    'Floor','Wrap','Subtract4',pirTyp4,'+-');


    pirelab.getAddComp(symDemodQPSKScalar,...
    [Selector2_out1_s149,delayMatch1_out1_s179],...
    Subtract5_out1_s161,...
    'Floor','Wrap','Subtract5',pirTyp11,'+-');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From28_out1_s83,Constant13_out1_s21],...
    Switch_out1_s162,...
    From28_out1_s83,'Switch',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion14_out1_s42,Delay2_out1_s57],...
    Switch1_out1_s163,...
    delayMatch6_out1_s188,'Switch1',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch2_out1_s167,Constant5_out1_s31],...
    Switch10_out1_s164,...
    delayMatch12_out1_s182,'Switch10',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From15_out1_s76,Constant16_out1_s24],...
    Switch11_out1_s165,...
    From15_out1_s76,'Switch11',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion13_out1_s41,Delay5_out1_s65],...
    Switch12_out1_s166,...
    delayMatch8_out1_s190,'Switch12',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [UnaryMinus_out1_s175,From19_out1_s77],...
    Switch2_out1_s167,...
    delayMatch11_out1_s181,'Switch2',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From20_out1_s79,Constant3_out1_s29],...
    Switch3_out1_s168,...
    From20_out1_s79,'Switch3',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion11_out1_s39,Constant11_out1_s19],...
    Switch4_out1_s169,...
    RelationalOperator3_out1_s143,'Switch4',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Switch4_out1_s169,Constant11_out1_s19],...
    Switch5_out1_s170,...
    From5_out1_s86,'Switch5',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [Constant7_out1_s33,Switch7_out1_s172],...
    Switch6_out1_s171,...
    OR1_out1_s122,'Switch6',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [DataTypeConversion12_out1_s40,Constant7_out1_s33],...
    Switch7_out1_s172,...
    RelationalOperator2_out1_s142,'Switch7',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From8_out1_s89,Constant12_out1_s20],...
    Switch8_out1_s173,...
    From8_out1_s89,'Switch8',...
    '>',0,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [From1_out1_s71,Constant18_out1_s26],...
    Switch9_out1_s174,...
    From1_out1_s71,'Switch9',...
    '>',0,'Floor','Wrap');


    pirelab.getUnaryMinusComp(symDemodQPSKScalar,...
    From19_out1_s77,...
    UnaryMinus_out1_s175,...
    'Wrap','Unary Minus');


    pirelab.getMuxComp(symDemodQPSKScalar,...
    [CompareToConstant1_out1_s11,CompareToConstant_out1_s10],...
    concatenate_out1_s176,...
    'concatenate');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [delayMatch2_out1_s184,t_out1_s197],...
    t1_out1_s198,...
    delayMatch2_out1_s184,'t1',...
    '>=',1,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [delayMatch4_out1_s186,t2_out1_s199],...
    t3_out1_s200,...
    delayMatch4_out1_s186,'t3',...
    '>=',1,'Floor','Wrap');


    pirelab.getSwitchComp(symDemodQPSKScalar,...
    [delayMatch10_out1_s180,t4_out1_s201],...
    t5_out1_s202,...
    delayMatch10_out1_s180,'t5',...
    '>=',1,'Floor','Wrap');


    pirelab.getWireComp(symDemodQPSKScalar,Switch10_out1_s164,dataOut);
    pirelab.getWireComp(symDemodQPSKScalar,delayMatch13_out1_s183,validOut);
    pirelab.getWireComp(symDemodQPSKScalar,OR_out1_s121,readyOut);
end

function hS=addSignal(symDemodQPSKScalar,sigName,pirTyp,simulinkRate)
    hS=symDemodQPSKScalar.addSignal;
    hS.Name=sigName;
    hS.Type=pirTyp;
    hS.SimulinkHandle=0;
    hS.SimulinkRate=simulinkRate;
end
