function sl_postprocess(h)





    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Utilities/Custom Electrical Environment'),...
    sprintf('ee_lib/Utilities/Environment Parameters')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Controlled PWM Voltage'),...
    sprintf('ee_lib/Integrated Circuits/Controlled PWM Voltage')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/H-Bridge'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/H-Bridge')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/DC Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/DC Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Generic Rotary Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Generic Rotary Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Induction Motor'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Simplified Induction Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Piezo Rotary Motor'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Rotary Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Servomotor'),...
    sprintf('ee_lib/Electromechanical/Motor & Drive (System Level)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Shunt Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/Shunt Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Stepper Motor'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Universal Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/Universal Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Generic Linear Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Generic Linear Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Piezo Linear Motor'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Linear Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Piezo Stack'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Stack')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Solenoid'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Solenoid')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Utilities/SPICE Environment Parameters'),...
    sprintf('ee_lib/Utilities/Environment Parameters')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/Diode'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/NJFET'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NJFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/NMOS'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NMOS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/NPN'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NPN')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/PJFET'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PJFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/PMOS'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PMOS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/SPICE-Compatible Semiconductors/PNP'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PNP')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/DC Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/DC Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/DC Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/DC Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Exponential Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Exponential Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Exponential Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Exponential Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PCCCS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCCS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PCCCS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCCS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PCCVS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCVS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PCCVS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCVS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PVCCS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCCS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PVCCS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCCS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PVCVS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCVS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PVCVS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCVS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PWL Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Piecewise Linear Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/PWL Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Piecewise Linear Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Pulse Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Pulse Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Pulse Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Pulse Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/SFFM Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/SFFM Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/SFFM Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/SFFM Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Sinusoidal Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Sinusoidal Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/SPICE-Compatible Sources/Sinusoidal Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Sinusoidal Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Current-Controlled Switch'),...
    sprintf('ee_lib/Additional Components/SPICE Passives/Current-Controlled Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Voltage-Controlled Switch'),...
    sprintf('ee_lib/Additional Components/SPICE Passives/Voltage-Controlled Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Finite Gain Op-Amp'),...
    sprintf('ee_lib/Integrated Circuits/Finite-Gain Op-Amp')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Thermal Resistor'),...
    sprintf('fl_lib/Electrical/Electrical Elements/Thermal Resistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Generic Battery'),...
    sprintf('ee_lib/Sources/Battery')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Stepper Motor Driver'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/Stepper Motor Driver'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Passive Devices/Current-Controlled Switch'),...
    sprintf('ee_lib/Additional Components/SPICE Passives/Current-Controlled Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Passive Devices/SPICE Resistor'),...
    sprintf('ee_lib/Additional Components/SPICE Passives/SPICE Resistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Passive Devices/Voltage-Controlled Switch'),...
    sprintf('ee_lib/Additional Components/SPICE Passives/Voltage-Controlled Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/Controlled PWM Voltage'),...
    sprintf('ee_lib/Integrated Circuits/Controlled PWM Voltage')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/Gate Driver'),...
    sprintf('ee_lib/Semiconductors & Converters/Gate Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/H-Bridge'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/H-Bridge')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/Half-Bridge Driver'),...
    sprintf('ee_lib/Semiconductors & Converters/Half-Bridge Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Drivers/Unipolar Stepper Motor Driver'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Unipolar Stepper Motor Driver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Servomotor'),...
    sprintf('ee_lib/Electromechanical/Motor & Drive (System Level)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/DC Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/DC Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/FEM-Parameterized Rotary Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/FEM-Parameterized Rotary Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Generic Rotary Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Generic Rotary Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Induction Motor'),...
    sprintf('ee_lib/Electromechanical/Asynchronous/Simplified Induction Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Piezo Rotary Motor'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Rotary Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Stepper Motor'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Stepper Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/RC Servo'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/RC Servo')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Shunt Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/Shunt Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Switched Reluctance Motor'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Switched Reluctance Machine')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Unipolar Stepper Motor'),...
    sprintf('ee_lib/Electromechanical/Reluctance & Stepper/Unipolar Stepper Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/Universal Motor'),...
    sprintf('ee_lib/Electromechanical/Brushed Motors/Universal Motor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Rotational Actuators/FEM-Parameterized PMSM'),...
    sprintf('ee_lib/Electromechanical/Permanent Magnet/FEM-Parameterized PMSM')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Translational Actuators/FEM-Parameterized Linear Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/FEM-Parameterized Linear Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Translational Actuators/Generic Linear Actuator'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Generic Linear Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Translational Actuators/Piezo Linear Motor'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Linear Actuator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Translational Actuators/Piezo Stack'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Piezo Stack')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Actuators & Drivers/Translational Actuators/Solenoid'),...
    sprintf('ee_lib/Electromechanical/Mechatronic Actuators/Solenoid')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE Diode'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE NJFET'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NJFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE NMOS'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NMOS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE NPN'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE NPN')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE PJFET'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PJFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE PMOS'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PMOS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Semiconductor Devices/SPICE PNP'),...
    sprintf('ee_lib/Additional Components/SPICE Semiconductors/SPICE PNP')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PCCCS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCCS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PCCCS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCCS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PCCVS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCVS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PCCVS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PCCVS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/DC Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/DC Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Exponential Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Exponential Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Pulse Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Pulse Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PWL Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Piecewise Linear Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/SFFM Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/SFFM Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Sinusoidal Current Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Sinusoidal Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PVCCS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCCS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PVCCS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCCS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PVCVS'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCVS')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PVCVS2'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/PVCVS2')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/DC Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/DC Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Exponential Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Exponential Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Pulse Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Pulse Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/PWL Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Piecewise Linear Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/SFFM Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/SFFM Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Sources/Sinusoidal Voltage Source'),...
    sprintf('ee_lib/Additional Components/SPICE Sources/Sinusoidal Voltage Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Additional Components/SPICE-Compatible Components/Utilities/SPICE Environment Parameters'),...
    sprintf('ee_lib/Utilities/Environment Parameters')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Band-Limited Op-Amp'),...
    sprintf('ee_lib/Integrated Circuits/Band-Limited Op-Amp')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Comparator'),...
    sprintf('ee_lib/Integrated Circuits/Comparator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Fully Differential Op-Amp'),...
    sprintf('ee_lib/Integrated Circuits/Fully Differential Op-Amp')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Finite-Gain Op-Amp'),...
    sprintf('ee_lib/Integrated Circuits/Finite-Gain Op-Amp')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Multiplier'),...
    sprintf('ee_lib/Integrated Circuits/Multiplier')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Push-Pull Output'),...
    sprintf('ee_lib/Integrated Circuits/Push-Pull Output')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Timer'),...
    sprintf('ee_lib/Integrated Circuits/Timer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Operational Transconductance Amplifier'),...
    sprintf('ee_lib/Integrated Circuits/Operational Transconductance Amplifier')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Voltage-Controlled Oscillator'),...
    sprintf('ee_lib/Integrated Circuits/Voltage-Controlled Oscillator')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS AND'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS AND')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS Buffer'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS Buffer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS NAND'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS NAND')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS NOR'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS NOR')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS NOT'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS NOT')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS OR'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS OR')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/CMOS XOR'),...
    sprintf('ee_lib/Integrated Circuits/Logic/CMOS XOR')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/Schmitt Trigger'),...
    sprintf('ee_lib/Integrated Circuits/Logic/Schmitt Trigger')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Integrated Circuits/Logic/S-R Latch'),...
    sprintf('ee_lib/Integrated Circuits/Logic/S-R Latch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Capacitor'),...
    sprintf('ee_lib/Passive/Capacitor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Diffusion Resistor'),...
    sprintf('ee_lib/Passive/Diffusion Resistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Eddy Current'),...
    sprintf('ee_lib/Passive/Eddy Current')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Fault'),...
    sprintf('ee_lib/Utilities/Fault')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Fuse'),...
    sprintf('ee_lib/Switches & Breakers/Fuse')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Incandescent Lamp'),...
    sprintf('ee_lib/Passive/Incandescent Lamp')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Inductor'),...
    sprintf('ee_lib/Passive/Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Three-Winding Mutual Inductor'),...
    sprintf('ee_lib/Passive/Transformers/Three-Winding Mutual Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Mutual Inductor'),...
    sprintf('ee_lib/Passive/Transformers/Mutual Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Nonlinear Inductor'),...
    sprintf('ee_lib/Passive/Nonlinear Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Nonlinear Transformer'),...
    sprintf('ee_lib/Passive/Transformers/Nonlinear Transformer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Potentiometer'),...
    sprintf('ee_lib/Passive/Potentiometer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Relay'),...
    sprintf('ee_lib/Switches & Breakers/Relays/SPDT Relay')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Reluctance with Hysteresis'),...
    sprintf('ee_lib/Passive/Nonlinear Reluctance')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Resistor'),...
    sprintf('ee_lib/Passive/Resistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Transmission Line'),...
    sprintf('ee_lib/Passive/Lines/Transmission Line')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Variable Capacitor'),...
    sprintf('ee_lib/Passive/Variable Capacitor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Variable Inductor'),...
    sprintf('ee_lib/Passive/Variable Inductor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Varistor'),...
    sprintf('ee_lib/Passive/Varistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Crystal'),...
    sprintf('ee_lib/Passive/Crystal')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Switches/DPDT Switch'),...
    sprintf('ee_lib/Switches & Breakers/DPDT Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Switches/DPST Switch'),...
    sprintf('ee_lib/Switches & Breakers/DPST Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Switches/SPDT Switch'),...
    sprintf('ee_lib/Switches & Breakers/SPDT Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Passive Devices/Switches/SPST Switch'),...
    sprintf('ee_lib/Switches & Breakers/SPST Switch')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/NPN Bipolar Transistor'),...
    sprintf('ee_lib/Semiconductors & Converters/NPN Bipolar Transistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/PNP Bipolar Transistor'),...
    sprintf('ee_lib/Semiconductors & Converters/PNP Bipolar Transistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/Current Limiter'),...
    sprintf('ee_lib/Semiconductors & Converters/Current Limiter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/Diode'),...
    sprintf('ee_lib/Semiconductors & Converters/Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/N-Channel IGBT'),...
    sprintf('ee_lib/Semiconductors & Converters/N-Channel IGBT')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/N-Channel JFET'),...
    sprintf('ee_lib/Semiconductors & Converters/N-Channel JFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/N-Channel MOSFET'),...
    sprintf('ee_lib/Semiconductors & Converters/N-Channel MOSFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/Optocoupler'),...
    sprintf('ee_lib/Semiconductors & Converters/Optocoupler')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/P-Channel JFET'),...
    sprintf('ee_lib/Semiconductors & Converters/P-Channel JFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/P-Channel MOSFET'),...
    sprintf('ee_lib/Semiconductors & Converters/P-Channel MOSFET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/N-Channel LDMOS FET'),...
    sprintf('ee_lib/Semiconductors & Converters/N-Channel LDMOS FET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/P-Channel LDMOS FET'),...
    sprintf('ee_lib/Semiconductors & Converters/P-Channel LDMOS FET')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Semiconductor Devices/Thyristor'),...
    sprintf('ee_lib/Semiconductors & Converters/Thyristor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Accelerometer'),...
    sprintf('ee_lib/Sensors & Transducers/Accelerometer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Gyro'),...
    sprintf('ee_lib/Sensors & Transducers/Gyro')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Incremental Shaft Encoder'),...
    sprintf('ee_lib/Sensors & Transducers/Incremental Shaft Encoder')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Light-Emitting Diode'),...
    sprintf('ee_lib/Sensors & Transducers/Light-Emitting Diode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Photodiode'),...
    sprintf('ee_lib/Sensors & Transducers/Photodiode')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Power Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/Power Sensor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Pressure Transducer'),...
    sprintf('Pneumatic_lib/Pneumatic Sensors/Pressure Transducer')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Proximity Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/Proximity Sensor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/PS Sensor'),...
    sprintf('ee_lib/Sensors & Transducers/PS Sensor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/PTC Thermistor'),...
    sprintf('ee_lib/Sensors & Transducers/PTC Thermistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Resolver'),...
    sprintf('ee_lib/Sensors & Transducers/Resolver')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Strain Gauge'),...
    sprintf('ee_lib/Sensors & Transducers/Strain Gauge')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Thermistor'),...
    sprintf('ee_lib/Sensors & Transducers/Thermistor')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sensors/Thermocouple'),...
    sprintf('ee_lib/Sensors & Transducers/Thermocouple')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Battery'),...
    sprintf('ee_lib/Sources/Battery')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Current Source'),...
    sprintf('ee_lib/Sources/Current Source')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/DC-DC Converter'),...
    sprintf('ee_lib/Semiconductors & Converters/Converters/DC-DC Converter')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Peltier Device'),...
    sprintf('ee_lib/Sensors & Transducers/Peltier Device')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Negative Supply Rail'),...
    sprintf('ee_lib/Sources/Negative Supply Rail')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Positive Supply Rail'),...
    sprintf('ee_lib/Sources/Positive Supply Rail')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Solar Cell'),...
    sprintf('ee_lib/Sources/Solar Cell')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Battery (Table-Based)'),...
    sprintf('ee_lib/Sources/Battery (Table-Based)')});

    simscape.internal.blockforwarding.registerBlockUpdates(h,...
    {sprintf('elec_lib/Sources/Voltage Source'),...
    sprintf('ee_lib/Sources/Voltage Source')});

end
