function result=isComponentSynchronousMachine(componentPath)



    result=any(strcmp(componentPath,...
    {'ee.electromech.sync.round_rotor.abc',...
    'ee.electromech.sync.round_rotor.abc_thermal',...
    'ee.electromech.sync.salient_pole.abc',...
    'ee.electromech.sync.salient_pole.abc_thermal'}));
end

