function usSection=elabVectUpsampler(~,hTopN,blockInfo,slRate,combOut_re,combOut_im,c_vout,i_rstout,...
    usOut_re,usOut_im,us_vout)




    in1=combOut_re;
    in2=combOut_im;
    in3=c_vout;
    in4=i_rstout;

    out1=usOut_re;
    out2=usOut_im;
    out3=us_vout;


    usSection=pirelab.createNewNetwork(...
    'Network',hTopN,...
    'Name','usSection',...
    'InportNames',{'combOut_re','combOut_im','c_vout','i_rstout'},...
    'InportTypes',[in1.Type,in2.Type,in3.Type,in4.Type],...
    'Inportrates',[slRate,slRate,slRate,slRate],...
    'OutportNames',{'usOut_re','usOut_im','us_vout'},...
    'OutportTypes',[out1.Type,out2.Type,out3.Type]...
    );


    combOut_re=usSection.PirInputSignals(1);
    combOut_im=usSection.PirInputSignals(2);
    c_vout=usSection.PirInputSignals(3);
    i_rstout=usSection.PirInputSignals(4);

    usOut_re=usSection.PirOutputSignals(1);
    usOut_im=usSection.PirOutputSignals(2);
    us_vout=usSection.PirOutputSignals(3);

    dsOutSize=blockInfo.R1;
    residueVect=blockInfo.residueVect;
    vecsize=blockInfo.vecsize;
    interpFactor=blockInfo.InterpolationFactor;


    fid=fopen(fullfile(matlabroot,'toolbox','dsphdl','dsphdlutilities','+dsphdlsupport','+internal',...
    '@CICInterpolator','cgireml','upSamplerVect.m'),'r');
    upSamplerVect=fread(fid,Inf,'char=>char');
    fclose(fid);
    usSection.addComponent2(...
    'kind','cgireml',...
    'Name','upSamplerVect',...
    'InputSignals',[combOut_re,combOut_im,c_vout,i_rstout],...
    'OutputSignals',[usOut_re,usOut_im,us_vout],...
    'EMLFileName','upSamplerVect',...
    'EMLFileBody',upSamplerVect,...
    'EmlParams',{dsOutSize,residueVect,vecsize,interpFactor},...
    'EMLFlag_TreatInputIntsAsFixpt',true);
end
