function[out,dscr]=BuildConfiguration_entries(cs,~)



    dscr='BuildConfiguration''s enum option is dynamic generated by Toolchain';

    cs=cs.getConfigSet;
    adp=configset.internal.getConfigSetAdapter(cs);


    if isempty(adp.toolchainInfo)
        configset.internal.customwidget.ToolchainValues(cs,'Toolchain',0);
    end

    if~isfield(adp.toolchainInfo,'BcFound')
        configset.internal.customwidget.BuildConfigValues(cs,'BuildConfiguration',0);
    end

    buildConfigList=adp.toolchainInfo.BcList;
    bcFound=adp.toolchainInfo.BcFound;

    bcName=cs.get_param('BuildConfiguration');
    if isempty(bcName)
        bcName=coder.make.internal.getDefaultBuildConfigurationName;
    end

    if~bcFound
        buildConfigList=[buildConfigList;bcName];
    end

    out=struct('str',buildConfigList,'disp',buildConfigList);


