function runCmd=get_raccel_run_cmd(buildData)

    isLiveStreaming=slfeature('JetstreamRapidAccelStreaming')>0;

    if slfeature('MLSysBlockRaccelReval')==1||...
        slfeature('FMUBlockRaccelReval')==1
        reval_host_to_target=num2str(buildData.qidHost2target);
        reval_target_to_host=num2str(buildData.qidTarget2host);
        reval_service_port=num2str(buildData.dashServicePort);
    else
        reval_host_to_target='';
        reval_target_to_host='';
        reval_service_port='';
    end

    if ischar(buildData.toFileSuffix)
        toFileSuffix=buildData.toFileSuffix;
    else
        toFileSuffix='';
    end

    nTmpVar=length(buildData.tmpVarPrefix);
    runCmd=cell(1,nTmpVar);
    for i=1:nTmpVar
        runCmd{i}=slsim.internal.getRaccelRunCommand(...
        buildData.mdl,...
        buildData.buildDir,...
        buildData.tmpVarPrefix{i},...
        '',...
        toFileSuffix,...
        Simulink.sdi.getSource(),...
        isLiveStreaming,...
        Simulink.isRaccelDeployed,...
        buildData.runningInParallel,...
        false,...
        reval_host_to_target,...
        reval_target_to_host,...
        reval_service_port);

        sbruntestsSessionID=getenv('SBRUNTESTS_SESSION_ID');
        if~isempty(sbruntestsSessionID)
            runCmd{i}=[runCmd{i},' -ignore-arg ',sbruntestsSessionID];
        end


        if(~Simulink.isRaccelDeployed)&&~isempty(buildData.tgtConnMgr)
            exeActiveToken=fullfile(tempdir,['tp',buildData.tmpVarPrefix{i},'.info']);
            tgtconnActiveToken=fullfile(tempdir,['tgtconn',buildData.tmpVarPrefix{i},'.info']);
            runCmd{i}=[runCmd{i},...
            ' -server_info_file "',exeActiveToken,'"'...
            ,' -tgtconn_server_info_file "',tgtconnActiveToken,'"'...
            ,' -tgtconn_port 0'];
        end
    end
end