function confirm=createFixAndDeletePSUDialog(psuName,elemName)
    confirm=questdlg(...
    message('SystemArchitecture:PropertyInspector:ConfirmFixAndDeletePSU',elemName,psuName).string,...
    message('SystemArchitecture:PropertyInspector:ConfirmDeletePSU_Title').string,...
    message('SystemArchitecture:PropertyInspector:ConfirmFixAndDeletePSU_Yes').string,...
    message('SystemArchitecture:PropertyInspector:Cancel').string,...
    message('SystemArchitecture:PropertyInspector:Cancel').string);
end