function[status,reason,buildStatusMgr]=buildModelRefs(...
    iMdl,mdlRefNames,parMdlRefs,orderedMdlRefs,...
    iTopTflChecksum,...
    iBuildArgs,verbose,mdlrefUpdateCtrl,thisMdlUpdateCtrl,runningForExternalMode,targetType,...
    mdlRefSimModeMap,buildStatusMgr,libsToClose,updateMsg)




    nTotalMdls=length(mdlRefNames);
    status=repmat(Simulink.ModelReference.internal.ModelRefStatusHelper.getDefaultStatus(),nTotalMdls,1);
    reason=repmat({''},nTotalMdls,1);
    secTopLvlMdlRefNames=[];
    updateTopMdlRefTargetInSerial=false;


    startMsg=sl('construct_modelref_message',...
    'Simulink:slbuild:startingSerialCoderBuild',...
    'Simulink:slbuild:startingSerialSIMBuild',...
    targetType);
    slprivate('sl_disp_info',startMsg,true);

    [status,reason,buildStatusMgr]=...
    coder.serial.hBuildModelRefs(...
    iMdl,mdlRefNames,secTopLvlMdlRefNames,parMdlRefs,orderedMdlRefs,...
    iTopTflChecksum,updateTopMdlRefTargetInSerial,...
    iBuildArgs,verbose,mdlrefUpdateCtrl,thisMdlUpdateCtrl,runningForExternalMode,targetType,...
    mdlRefSimModeMap,buildStatusMgr,libsToClose,updateMsg,...
    status,reason);
end
