function setEnableForAddPreconditionAsConstraint(cbinfo,action)




    modelHandle=cbinfo.Context.Object.App.ModelHandle;
    vmStudioHandle=slvariants.internal.manager.core.getStudio(modelHandle);
    ddgComp=vmStudioHandle.getComponent('GLUE2:DDG Component',message('Simulink:VariantManagerUI:AutoGeneratedConfigsDDG').getString());
    if isempty(ddgComp)
        return;
    end

    dlg=ddgComp.getDialog;
    addBtnEnable=dlg.getSource().getGeneratedConfigsSource().canAddSelectedButtonEnabled();

    constraints=cbinfo.Context.Object.App.AutoGenConfigToolStripBroker.getConstraintsFromGeneratedVCD(modelHandle);


    action.enabled=addBtnEnable&&numel(constraints)>0;
end
