function tf=isNotAutogenerated(sfID)




    oIsa=sf('get',sfID.ID,'.isa');
    if oIsa==4||...
        oIsa==5||...
        oIsa==8||...
        oIsa==6
        tf=~sf('get',sfID.ID,'.autogen.isAutoCreated');
    else
        tf=true;
    end
