function btvComp=getBustoVectorComp(hN,hInSignals,hOutSignal,compName,slHandle)



    narginchk(5,5);

    btvComp=hN.addComponent2(...
    'kind','bustovector_comp',...
    'SimulinkHandle',slHandle,...
    'Name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignal);
end
