function dspbaComp=getDspbaComp(hN,name,inputSignals,outputSignals,...
    entityName,inportNames,outportNames,clkNames,ceNames,ceclrNames,busInputPortNames,busInputPortWidths,busReadEnablePortNames,...
    rates,baseRate,blackBoxAttributes,vhdlComponentLibrary,...
    slbh)



    assert(nargin>=15,'No enough arguments are given to create Dspba comp');

    if nargin<18
        slbh=-1;
    end

    if nargin<17
        vhdlComponentLibrary='';
    end

    if nargin<16
        blackBoxAttributes=false;
    end

    dspbaComp=hN.addComponent2(...
    'kind','dspba_comp',...
    'SimulinkHandle',slbh,...
    'name',name,...
    'InputSignals',inputSignals,...
    'OutputSignals',outputSignals,...
    'EntityName',entityName,...
    'InportNames',inportNames,...
    'OutportNames',outportNames,...
    'ClkNames',clkNames,...
    'CeNames',ceNames,...
    'ResetNames',ceclrNames,...
    'BusInputPortNames',busInputPortNames,...
    'BusInputPortWidths',busInputPortWidths,...
    'BusReadEnablePortNames',busReadEnablePortNames,...
    'Rates',rates,...
    'BaseRate',baseRate,...
    'BlackBoxAttributes',blackBoxAttributes,...
    'VhdlComponentLibrary',vhdlComponentLibrary);

end


