function hcComp=getHitCrossComp(hN,hInSignals,hOutSignals,hcOffset,hcDirectionMode,name)



    if(nargin<6)
        name='hitcross';
    end

    hcComp=hN.addComponent2(...
    'kind','hitcross_comp',...
    'Name',name,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'HcOffset',hcOffset,...
    'HcDirectionMode',hcDirectionMode);

end


