function relopComp=getRelOpComp(hN,hInSignals,hOutSignals,op,sameDT,compName,desc,slHandle,nfpOptions)


    if nargin<9
        nfpOptions.Latency=int8(0);
        nfpOptions.MantMul=int8(0);
        nfpOptions.Denormals=int8(0);
    end

    if~isfield(nfpOptions,'CustomLatency')
        nfpOptions.CustomLatency=int8(0);
    end

    relopComp=hN.addComponent2(...
    'kind','relop',...
    'SimulinkHandle',slHandle,...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'OpName',op,...
    'InputSameDT',sameDT,...
    'BlockComment',desc,...
    'NFPCustomLatency',nfpOptions.CustomLatency,...
    'NFPLatency',nfpOptions.Latency);

    relopComp.setSupportAlteraMegaFunctions(true);
    relopComp.setSupportXilinxCoreGen(true);
end
