function reshapeComp=getReshapeComp(hN,hInSignals,hOutSignals,outDimType,outDims,compName)



    narginchk(5,6);
    if nargin<6
        compName='Reshape';
    end

    reshapeComp=hN.addComponent2(...
    'kind','reshape_comp',...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'OutputDimensionality',outDimType,...
    'OutputDimensions',outDims);
end
