function subComp=getSubComp(hN,hInSignals,hOutSignals,...
    rndMode,satMode,compName,accType,slbh,desc)

    subComp=hN.addComponent2(...
    'kind','add',...
    'SimulinkHandle',slbh,...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'RoundingMode',rndMode,...
    'OverflowMode',satMode,...
    'AccumulatorType',accType,...
    'BlockComment',desc,...
    'inputsigns','+-');

end
