function sqrtComp=getSqrtComp(hN,hInSignals,hOutSignals,compName,slbh,fname,nfpOptions)


    if nargin<7
        nfpOptions.Latency=int8(0);
        nfpOptions.MantMul=int8(0);
        nfpOptions.Denormals=int8(0);
    end

    if~isfield(nfpOptions,'CustomLatency')
        nfpOptions.CustomLatency=int8(0);
    end

    sqrtComp=hN.addComponent2(...
    'kind','sqrt_comp',...
    'SimulinkHandle',slbh,...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'FunctionName',fname,...
    'NFPLatency',nfpOptions.Latency,...
    'NFPCustomLatency',nfpOptions.CustomLatency,...
    'NFPDenormals',nfpOptions.Denormals);

    sqrtComp.setSupportAlteraMegaFunctions(true);
    sqrtComp.setSupportXilinxCoreGen(true);
end
