function selComp=getSelectorComp(hN,hInSignals,hOutSignals,indexMode,...
    indexOptionArray,indexParamArray,...
    outputSizeArray,numDims,compName)


    if nargin<9
        compName='Selector';
    end

    selComp=hN.addComponent2(...
    'kind','selector_comp',...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'IndexMode',indexMode,...
    'IndexOptionArray',indexOptionArray,...
    'IndexParamArray',indexParamArray,...
    'OutputSizeArray',outputSizeArray,...
    'NumberOfDimensions',numDims);
end
