function recipComp=getSqrtNewtonComp(hN,hInSignals,hOutSignals,newtonInfo,slbh)


    narginchk(5,5);
    recipComp=hN.addComponent2(...
    'kind','sqrtnewton_comp',...
    'name',newtonInfo.networkName,...
    'SLBlockHandle',slbh,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'RoundingMode',newtonInfo.rndMode,...
    'OverflowMode',newtonInfo.satMode,...
    'IterNum',newtonInfo.iterNum,...
    'IntermDT',newtonInfo.intermDT,...
    'InternalRule',newtonInfo.internalRule);
end
