function switchComp=getSwitchComp(hN,inSignals,outSignals,selSignal,compName,...
    compareStr,compareVal,rndMode,ovMode,desc,slHandle)


    switchComp=hN.addComponent2(...
    'kind','switch_comp',...
    'InputSignals',[inSignals(1),selSignal,inSignals(2)],...
    'OutputSignals',outSignals,...
    'Name',compName,...
    'CompareStr',compareStr,...
    'Threshold',compareVal,...
    'RoundingMode',rndMode,...
    'OverflowMode',ovMode,...
    'BlockComment',desc,...
    'SimulinkHandle',slHandle);
end
