function tbTimeDelayComp=getTBTimeDelayComp(hN,hInSignal,hOutSignal,timeDelay,compName)


    narginchk(5,5);
    tbTimeDelayComp=hN.addComponent2(...
    'kind','tb_timedelay_comp',...
    'InputSignals',hInSignal,...
    'OutputSignals',hOutSignal,...
    'TimeDelay',timeDelay,...
    'Name',compName);
end

