function tbClockgenComp=getTBClockgenComp(hN,hInSignal,hClockSignal,highTime,lowTime)


    narginchk(5,5);
    tbClockgenComp=hN.addComponent2(...
    'kind','tb_clockgen_comp',...
    'InputSignals',hInSignal,...
    'OutputSignals',hClockSignal,...
    'ClockHighTime',highTime,...
    'ClockLowTime',lowTime);
end


