function hC=getTBStimulusSwitchComp(hN,hInSignals,hOutSignal,hSelSignal,compName)


    narginchk(5,5);
    hC=hN.addComponent2(...
    'kind','tb_stimulusswitch_comp',...
    'InputSignals',[hInSignals,hSelSignal],...
    'OutputSignals',hOutSignal,...
    'Name',compName);
end


