function tbResetgenComp=getTBResetgenComp(hN,hInSignal,hResetSignal,tResetHold)


    narginchk(4,4);
    tbResetgenComp=hN.addComponent2(...
    'kind','tb_resetgen_comp',...
    'InputSignals',hInSignal,...
    'OutputSignals',hResetSignal,...
    'ResetHoldTime',tResetHold);
end


