function delayComp=getUnitDelayEnabledComp(hN,hInSignals,...
    hOutSignals,hEnbSignal,compName,ic,resettype,desc,slbh,isSynchronousDelay)



    isReset=pircore.processDelayIC(ic);

    delayComp=hN.addComponent2(...
    'kind','UnitDelayEnabledResettable',...
    'SimulinkHandle',slbh,...
    'name',compName,...
    'InputSignals',hInSignals,...
    'OutputSignals',hOutSignals,...
    'ExternalEnableSignal',hEnbSignal,...
    'InitialValue',ic,...
    'ResetNone',resettype,...
    'ResetInitVal',isReset,...
    'Softreset',false,...
    'BlockComment',desc,...
    'IsSynchronousDelay',isSynchronousDelay);

end
