function categories=dataCategories()







    categories={'Inports',...
    'Outports',...
    'ModelParameters',...
    'LocalParameters',...
    'ExternalParameters',...
    'GlobalParameters',...
    'ExternalParameterObjects',...
    'SharedLocalDataStores',...
    'GlobalDataStores',...
    'InternalData',...
    'Constants'};

    categories=[categories(1:3),'ModelParameterArguments','ParameterArguments',categories(4:end)];

    if slfeature('EnableModelData')
        categories=[categories,'SelfDataStructure','ModelData'];
    end
