function dlgStruct=loop_getDialogSchema(this,name)




    if~builtin('license','checkout','SIMULINK_Report_Gen')
        dlgStruct=this.buildErrorMessage('panel',true);
        return;
    end

    oTypes={
'isAndOrStates'
'isBoxStates'
'isFcnStates'
'isTruthTables'
'isEMFunctions'
'isSLFunctions'
    };


    if this.LockType
        typeContents={};
        for i=length(oTypes):-1:1
            if get(this,oTypes{i})
                oProp=this.findprop(oTypes{i});
                typeContents={this.dlgText(oProp.Description)};
                break;
            end
        end
    else
        typeContents=cell(1,length(oTypes));
        for i=length(oTypes):-1:1
            typeContents{i}=this.dlgWidget(oTypes{i});
        end
    end

    dlgStruct={
    this.dlgContainer(typeContents,getString(message('RptgenSL:rsf_csf_state_loop:stateTypesLabel')))
    this.dlgContainer({
    this.dlgWidget('Depth',...
    'RowSpan',[1,1],...
    'ColSpan',[1,1])
    this.dlgWidget('SkipAutogenerated',...
    'RowSpan',[2,2],...
    'ColSpan',[1,1])
    RptgenML.twoColumnTable(this,'SFFilterTerms','isSFFilterList',...
    'RowSpan',[3,3],...
    'ColSpan',[1,1])
    },getString(message('RptgenSL:rsf_csf_state_loop:loopOptionsLabel')),'LayoutGrid',[3,1],'RowStretch',[0,0,1])
    };
