function schema





    pkg=findpackage('rptgen_sf');
    pkgRG=findpackage('rptgen');

    h=schema.class(pkg,'csf_state_loop',pkgRG.findclass('rpt_looper'));

    rptgen.prop(h,'isAndOrStates','bool',true,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeAndOrLabel')));
    rptgen.prop(h,'isBoxStates','bool',true,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeBoxLabel')));
    rptgen.prop(h,'isFcnStates','bool',true,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeFunctionsLabel')));
    rptgen.prop(h,'isTruthTables','bool',false,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeTruthTablesLabel')));
    rptgen.prop(h,'isEMFunctions','bool',false,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeMLFunctionsLabel')));
    rptgen.prop(h,'isSLFunctions','bool',false,...
    getString(message('RptgenSL:rsf_csf_state_loop:includeSLFunctionsLabel')));


    p=rptgen.prop(h,'LockType','bool',false,...
    '');
    p.AccessFlags.PublicSet='off';
    p.AccessFlags.PublicGet='off';
    p.Visible='off';










    rptgen.prop(h,'Depth',{
    'local',getString(message('RptgenSL:rsf_csf_state_loop:localChildrenOnlyLabel'))
    'deep',getString(message('RptgenSL:rsf_csf_state_loop:allObjectsLabel'))
    },'deep',getString(message('RptgenSL:rsf_csf_state_loop:reportDepthLabel')),1);


    rptgen.prop(h,'SkipAutogenerated','bool',true,...
    getString(message('RptgenSL:rsf_csf_state_loop:skipAutoGeneratedChartsLabel')));


    rptgen.prop(h,'isSFFilterList','bool',false,...
    getString(message('RptgenSL:rsf_csf_state_loop:searchStateflowLabel')));


    p=rptgen.prop(h,'SFFilterTerms','MATLAB array',{'Tag','MyTag'});
    p.Visible='off';


    rptgen.prop(h,'SortBy',{
    'breadthFirst','Breadth First'
    'depthFirst','Depth First'
    },'breadthFirst','Sort Order');




    rptgen.makeStaticMethods(h,{
    },{
'loop_getContextString'
'loop_getLoopObjects'
'loop_getObjectType'
'loop_getPropSrc'
'loop_restoreState'
'loop_saveState'
'loop_setState'
'setObjectType'
    });
