function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2Cxoka0AQVPCeFmGh0DvWZm/zYDaV7+bqmaeNzaZHJEUC/MPYtShGVY/DZ8'...
        ,'YD+2whj8lZEYaYq5huA5lU/c4una9ohfA7t7uhb0LMGlOMajd6Rinp0ifU54'...
        ,'9CnWAYiQKHdof4vb0KQuyE5/ETm4GhbUlQnRcvbtPBdylhd+NiXKKC2lJj+L'...
        ,'o5fEXm0Y0ZhKby2yujVjIQQhe/rZMA3EGApIi1mip7ypguvVuniL/Az7WdJC'...
        ,'GF23BbzaxwINFr99R/k8QRoCMDtibyGw56JmLxLXozXVx7sHo3sZv/uirTEC'...
        ,'KS8Q'];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end