function reqStruct=reqstruct(doc,id,description,keywords,linked,reqsys)



    reqStruct=struct('doc',doc,...
    'id',id,...
    'linked',linked,...
    'description',description,...
    'keywords',keywords,...
    'reqsys',reqsys);

