


classdef slmodules
    properties(Constant)
        ModuleMap=containers.Map({...
        'SlbeUnit1','SlbeUnit2','SlbeUnit3','SlbeUnit4','SlbeUnit5',...
        },learning.simulink.preferences.slmodules.getFundamentalModules());
    end

    methods(Static,Access=private)

        function moduleObjs=getFundamentalModules()
            fundamentalCourse=learning.simulink.preferences.slacademyprefs.CourseMap('slbe');
            fundamentalModule1Info=learning.simulink.preferences.ModuleInfo(...
            fundamentalCourse,'SlbeTitle1',...
            1,1,1,2,2,1);
            fundamentalModule2Info=learning.simulink.preferences.ModuleInfo(...
            fundamentalCourse,'SlbeTitle2',...
            3,1,1,2,2,2);
            fundamentalModule3Info=learning.simulink.preferences.ModuleInfo(...
            fundamentalCourse,'SlbeTitle3',...
            5,1,1,2,2.5,3);
            fundamentalModule4Info=learning.simulink.preferences.ModuleInfo(...
            fundamentalCourse,'SlbeTitle4',...
            7,1,1,2,2.5,4);
            fundamentalModule5Info=learning.simulink.preferences.ModuleInfo(...
            fundamentalCourse,'SlbeTitle5',...
            9,1,1,1,1,5);
            moduleObjs={...
            fundamentalModule1Info,...
            fundamentalModule2Info,...
            fundamentalModule3Info,...
            fundamentalModule4Info,...
            fundamentalModule5Info};
        end
    end
end