function result=openImpl(reporter,impl,varargin)
    if isempty(varargin)
        key=['E2Cxoka0AQVPCeFmGh0DvcY01O/YU+NBLtQJGSjUgHxIfiSHcA+Kin5Qt/He'...
        ,'FHj3MBNN2nq9hvqkU9/2nws6OfyrXJI7Cgcmtv7lPvM9wVBPLv9Q4GgcBplt'...
        ,'PYemPyic2LtTgwPWRaHoexez1MWV0Dqa4IGMdfbO2FVGM4iZ7uWaplC7cEqr'...
        ,'S/+51IbtTsReP6CBkGq9ZAjeC0cL5umS7GYIPB3Bzsn2djJZ0nfcDCc9rdGQ'...
        ,'UMHzvzk2XsPekchLo0tiZCYe5IloPx00tQOTftmWyFbVeNiHi/yWQDQLRit0'...
        ,'CuSNnOEf'];
    else
        key=varargin{1};
    end
    result=open(impl,key,reporter);
end